### ISSUE TITLE
Spark NLP Document Assembler()

### ISSUE THREAD

**Issue by gadhimoo** [JohnSnowLabs/spark-nlp#1000]
I am trying to create my own NLP pipeline, from the example posted by Johnsnowlabs in youtube. But, I am getting error in the document assembler() class.

My sparknlp.start() works fine and could create dataframe.

Then I use:
Document = DocumentAssembler().setInputCols('text').setOutputCol('document').setCleanupMode('shrink')

I get the following error:
Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
	at com.johnsnowlabs.nlp.AnnotatorModel.<init>(AnnotatorModel.scala:14)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.<init>(SentenceDetector.scala:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.util.MLWritable$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 13 more

* Spark NLP version:'2.5.0'
* Apache NLP version:3.0.0
* Java version (java -version):"1.8.0_261"
* Operating System and version: windows 10
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Is your PySpark version 3.0? 
```

Spark NLP version:'2.5.0'
Apache NLP version:3.0.0
```

**Comment by gadhimoo** [comment]
yes pyspark is 3.0

**Comment by maziyarpanahi** [comment]
We don't support that: https://github.com/JohnSnowLabs/spark-nlp#apache-spark-support

```
conda create -n sparknlp python=3.6 -y
conda activate sparknlp
pip install spark-nlp==2.5.5 pyspark==2.4.4
```

The best place for references is here: https://github.com/JohnSnowLabs/spark-nlp
