### ISSUE TITLE
UNRESOLVED DEPENDENCIES : com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5: not found

### ISSUE THREAD

**Issue by gadhimoo** [JohnSnowLabs/spark-nlp#1008]
I am trying to do
sparknlp.start()
But it shows server access error at all the repositories. I also tried to manually store the spark-nlp_2.11.jar file in the directory
C:\Users\GADHIMO\.ivy2\local\com.johnsnowlabs.nlp\spark-nlp_2.11\2.5.5\jars\

but, I noticed, if I am going to use that file location, I need a ivy.xml file. which I couldn't find to download. I am not able to create a .m2 folder. I have the spark-nlp_2.11-2.5.5.pom  file downloaded.

## Expected Behavior
sparknlp.start() should be working.

## Current Behavior
Ivy Default Cache set to: C:\Users\GADHIMO\.ivy2\cache
The jars for the packages stored in: C:\Users\GADHIMO\.ivy2\jars
:: loading settings :: url = jar:file:/C:/spark/spark-2.4.4-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.johnsnowlabs.nlp#spark-nlp_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-868b942d-b1a9-43b2-8edb-76cdd7d45116;1.0
        confs: [default]
:: resolution report :: resolve 84873ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5

        ==== local-m2-cache: tried

          file:/C:/Users/GADHIMO/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

          file:/C:/Users/GADHIMO/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

        ==== local-ivy-cache: tried

          C:\Users\GADHIMO\.ivy2\local\com.johnsnowlabs.nlp\spark-nlp_2.11\2.5.5\ivys\ivy.xml

          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

          C:\Users\GADHIMO\.ivy2\local\com.johnsnowlabs.nlp\spark-nlp_2.11\2.5.5\jars\spark-nlp_2.11.jar

        ==== central: tried

          https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

          https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

        ==== spark-packages: tried

          https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

          https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5: not found

                ::::::::::::::::::::::::::::::::::::::::::::::

:::: ERRORS
        Server access error at url https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom (java.net.ConnectException: Connection timed out: connect)

        Server access error at url https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar (java.net.ConnectException: Connection timed out: connect)

        Server access error at url https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom (java.net.ConnectException: Connection timed out: connect)

        Server access error at url https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar (java.net.ConnectException: Connection timed out: connect)

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1302)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:304)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:774)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "C:\spark\spark-2.4.4-bin-hadoop2.7\python\pyspark\shell.py", line 38, in <module>
    SparkContext._ensure_initialized()
  File "C:\spark\spark-2.4.4-bin-hadoop2.7\python\pyspark\context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "C:\spark\spark-2.4.4-bin-hadoop2.7\python\pyspark\java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "C:\spark\spark-2.4.4-bin-hadoop2.7\python\pyspark\java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

## Your Environment

* Spark NLP version: 2.5.5
* Apache spark version: 2.4.4
* Java version (java -version): 1.8
* Setup and installation (Pypi, Conda, Maven, etc.):  python 3.7.5
* Operating System and version: windows 10

**Comment by gadhimoo** [comment]
Hello,
I resolved
