### ISSUE TITLE
Exception: Java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by kswainsubrat** [JohnSnowLabs/spark-nlp#1011]
## Description
I'm trying to run a SparkNlp job, Sentiment Analysis, on a Linux server through a docker image the Dockerfile for which is given below. My code is:
```
import sparknlp
spark = sparknlp.start(gpu=True)

print("Spark NLP version")
sparknlp.version()
print("Apache Spark version")
spark.version
```
It is throwing the error:
```
Ivy Default Cache set to: /home/admin/.ivy2/cache
The jars for the packages stored in: /home/admin/.ivy2/jars
:: loading settings :: url = jar:file:/home/admin/.local/lib/python3.6/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.johnsnowlabs.nlp#spark-nlp_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-c8bf5c73-a569-4466-8f5a-d11a30e251d5;1.0
	confs: [default]
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
:: resolution report :: resolve 80319ms :: artifacts dl 0ms
	:: modules in use:
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

	Host dl.bintray.com not found. url=https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

	Host dl.bintray.com not found. url=https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

		module not found: com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5

	==== local-m2-cache: tried

	  file:/home/admin/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

	  file:/home/admin/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

	==== local-ivy-cache: tried

	  /home/admin/.ivy2/local/com.johnsnowlabs.nlp/spark-nlp_2.11/2.5.5/ivys/ivy.xml

	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

	  /home/admin/.ivy2/local/com.johnsnowlabs.nlp/spark-nlp_2.11/2.5.5/jars/spark-nlp_2.11.jar

	==== central: tried

	  https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

	  https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

	==== spark-packages: tried

	  https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.pom

	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5!spark-nlp_2.11.jar:

	  https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.11/2.5.5/spark-nlp_2.11-2.5.5.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.johnsnowlabs.nlp#spark-nlp_2.11;2.5.5: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1389)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:871)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/.local/lib/python3.6/site-packages/sparknlp/__init__.py", line 61, in start
    return builder.getOrCreate()
  File "/home/admin/.local/lib/python3.6/site-packages/pyspark/sql/session.py", line 186, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/admin/.local/lib/python3.6/site-packages/pyspark/context.py", line 371, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/admin/.local/lib/python3.6/site-packages/pyspark/context.py", line 128, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/admin/.local/lib/python3.6/site-packages/pyspark/context.py", line 320, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/admin/.local/lib/python3.6/site-packages/pyspark/java_gateway.py", line 105, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

```
## Steps to Reproduce
Mentioned in the description.

## Context
Not able to start any project

## Your Environment
I've built a docker image for it. The content of the docker file is:
```
#Download base image ubuntu 18.04
FROM ubuntu:18.04

ENV NB_USER admin
ENV NB_UID 1000
ENV HOME /home/${NB_USER}

ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

RUN apt-get update && apt-get install -y \
    tar \
    wget \
    bash \
    rsync \
    gcc \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libpng-dev \
    libzmq3-dev \
    python3 \ 
    python3-dev \
    python3-pip \
    unzip \
    pkg-config \
    software-properties-common \
    graphviz

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/" >> ~/.bashrc

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir mlflow Keras scikit-spark scikit-learn scipy matplotlib pydot tensorflow graphviz

USER root
RUN chown -R ${NB_UID} ${HOME}
USER ${NB_USER}

COPY requirements.txt /${HOME}/
WORKDIR ${HOME}
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["server.py"]
```
Requirements.txt:
```
Flask==1.1.2
numpy==1.18.3
pandas==1.1.0
kafka-python==2.0.1
pyspark==3.0.0
spark-nlp==2.5.5
```

**Comment by maziyarpanahi** [comment]
Hi,

We don't support Apache Spark/PySpark 3.0: https://github.com/JohnSnowLabs/spark-nlp#apache-spark-support

You need to use pyspark==2.4.6 or any version in 2.4.x releases.

**Comment by kswainsubrat** [comment]
Thanks, @maziyarpanahi!
It wasn't an internet issue. I was running it from inside a container. So, Docker DNS was not configured correctly. So, the issue was there. I'm closing the issue. Thanks for fast respond.

**Comment by xfonseca** [comment]
Hi @kswainsubrat 
I'm facing the same problem.
How did you fixed Docker DNS?

**Comment by c-iurlaro** [comment]
@kswainsubrat thanks for not even giving a clue about how you solved the problem. That really helped me and @xfonseca who have the same problem.

**Comment by maziyarpanahi** [comment]
@c-iurlaro Your comment is not useful nor helping anyone. At least give the person 24 hours to come back online and voluntarily share his/her solution.

Given the fact, the issue was caused by something outside this library the solution needs to be looked for somewhere else. This is not a place to learn how to set up DNS service correctly for Docker especially by force!
