### ISSUE TITLE
NerDLModel not support on window 10?

### ISSUE THREAD

**Issue by TiGaI** [JohnSnowLabs/spark-nlp#1021]
When will the NerDLModel be supported in window 10?

## Description

trying to run this.
![image](https://user-images.githubusercontent.com/22779825/91350870-520e7f00-e7b5-11ea-82eb-42976386d6a6.png)

## Current Behavior

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-3-52f50bd68fbf> in <module>
     33           .setPoolingLayer(-2)
     34 
---> 35 onto_ner_bert = NerDLModel.pretrained("ner_dl_bert", 'en') \
     36           .setInputCols(["document", "normalized", "embeddings"]) \
     37           .setOutputCol("ner")

~\Anaconda3\envs\nlp\lib\site-packages\sparknlp\annotator.py in pretrained(name, lang, remote_loc)
   1552     def pretrained(name="ner_dl", lang="en", remote_loc=None):
   1553         from sparknlp.pretrained import ResourceDownloader
-> 1554         return ResourceDownloader.downloadModel(NerDLModel, name, lang, remote_loc)
   1555 
   1556 

~\Anaconda3\envs\nlp\lib\site-packages\sparknlp\pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     39             t1.start()
     40             try:
---> 41                 j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     42             finally:
     43                 stop_threads = True

~\Anaconda3\envs\nlp\lib\site-packages\sparknlp\internal.py in __init__(self, reader, name, language, remote_loc, validator)
    174 class _DownloadModel(ExtendedJavaWrapper):
    175     def __init__(self, reader, name, language, remote_loc, validator):
--> 176         super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
    177 
    178 

~\Anaconda3\envs\nlp\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

~\Anaconda3\envs\nlp\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

C:\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

C:\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

C:\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

C:\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.UnsupportedOperationException: Spark NLP tried to load a TensorFlow Graph using Contrib module, but failed to load it on this system. If you are on Windows, this operation is not supported. Please try a noncontrib model. If not the case, please report this issue. Original error message:

Op type not registered 'BlockLSTM' in binary running on MSI. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(TensorflowWrapper.scala:212)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:252)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:97)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowModel(NerDLModel.scala:242)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$class.readNerGraph(NerDLModel.scala:219)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readNerGraph(NerDLModel.scala:242)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:226)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:226)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:360)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:354)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:465)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
## Your Environment

* Spark NLP version: 2.5.5
* Apache NLP version:  2.4.6
* Java version (java -version): 1.8.0_265
* Setup and installation (Pypi, Conda, Maven, etc.): Conda
* Operating System and version: Window 10

**Comment by maziyarpanahi** [comment]
Everything is supported in Windows 8 and 10 (the two versions that I've tested personally). You should follow the steps here, it should work fine: https://github.com/JohnSnowLabs/spark-nlp/issues/994

![image](https://user-images.githubusercontent.com/5762953/91357882-3a092080-e7f2-11ea-89eb-9c70840ff43a.png)

**Comment by TiGaI** [comment]
I follow the guide before. It works on my MacOS. I don't know why windows have so many issues with sparknlp.

I try a number of things: follow this guide, didn't work, since I am using sparknlp 2.5.5.
Seem like it is because I am not running the noncontrib model like this post states:
https://stackoverflow.com/questions/57610129/do-spark-nlp-pretrained-pipelines-only-work-on-linux-systems

Then I run anaconda prompt on admin and root directory, and that works. Maybe be a weird window bug with spaces. I also don't know why that error shows up when it has nothing to do with the problem.

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.UnsupportedOperationException: Spark NLP tried to load a TensorFlow Graph using Contrib module, but failed to load it on this system. If you are on Windows, this operation is not supported. Please try a noncontrib model. If not the case, please report this issue. Original error message:

**Comment by TiGaI** [comment]
Do you have to do that in window? I am trying to understand why I need to open jupyter notebook in root as well as running my prompt under admin? @maziyarpanahi

**Comment by maziyarpanahi** [comment]
The steps are for Windows and Windows only. The reason you need those steps is to setup Apache Spark (more than half of the steps) and the rest is for TensorFlow.

If you are using any Spark NLP version above 2.4 then you are using models which are cross-platform. What you see for noncontrib is for before. (If you look at the date)

Windows has been always the one OS that requires a few steps more or a few tricks here and there to run something that works easily in unix-based OSes.

Unfortunately, I cannot reproduce this issue on Windows is 10.
