### ISSUE TITLE
py4j.protocol.Py4JNetworkError: Error while receiving

### ISSUE THREAD

**Issue by swainsubrat** [JohnSnowLabs/spark-nlp#1044]
I'm getting this issue while running the running sparknlp models inside a Flask application which is wrapped in docker.

## Description
When I'm starting the application it's working fine and it's listing to the Kafka. But after some time, it's throwing this error:
An error occurred while trying to connect to the Java server (127.0.0.1:34663)

## Expected Behavior
It should work fine as while starting the application it's working fine and then it's failing.

## Possible Solution
As I'm running it inside a docker container, might be the issue with the network configuration of docker. Like, the address, (127.0.0.1:34663) might need to be changed. But where to change?

## Steps to Reproduce

```
import time
import logging
import requests
import sparknlp
import threading

from flask import Flask

from kafka_initializer import kafka_initializer
from load_models import load_model
from data_processor import processing

BROADCAST = "sparknlp"

app = Flask(__name__)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s %(levelname)s %(name)s %(threadName)s: %(message)s'
)


def kafka_consumer(genre, sentiment, vector, app, spark):
    for message in Consumer:
        app.logger.info("Consumed a Message!!!!")
        data = processing(message.value, genre, sentiment, vector, app, spark)
        app.logger.info("Processing Done!!!!")
        app.logger.info("Broadcasting.......")
        Producer.send(BROADCAST, data)
        app.logger.info("Broadcasting Done!!!!")
        app.logger.info("Waiting for new message......")


@app.route("/")
def hello():
    return "Hello, Welcome to Vachan-sparkNLP"


def start_runner(genre, sentiment, vector, app, spark):
    def start_loop():
        not_started = True
        while not_started:
            app.logger.info('In start loop')
            try:
                r = requests.get('http://167.86.321.101:5000/')
                if r.status_code == 200:
                    app.logger.info('Server started, quiting start_loop')
                    kafka_consumer(genre, sentiment, vector, app, spark)
                    not_started = False
                app.logger.info(r.status_code)
            except Exception as e:
                app.logger.info('Server not yet started {}'.format(e))
            time.sleep(2)

    app.logger.info('Started runner')
    thread = threading.Thread(target=start_loop)
    thread.start()


if __name__ == '__main__':
    app.logger.info("Starting the Application.......")
    app.logger.info("Creating SparkNLP Session......")
    spark = sparknlp.start()
    Consumer, Producer = kafka_initializer(app)
    genre, sentiment, vector = load_model(spark, app)
    start_runner(genre, sentiment, vector, app, spark)
    app.run(host="167.86.321.101", port=5000, debug=True)
```

## Your Environment
pyspark==2.4.6
spark-nlp==2.5.5
* Java version: jdk-8
* Setup and installation: Pypi
* Operating System and version: ubuntu 18.04(inside docker)

**Comment by maziyarpanahi** [comment]
Hi,

Thanks for a detailed step by step to reproduce this error.

Could you please attach the full stack of error? Also, making sure there is no other Java installed on the docker? (Sometimes this error is about using a different Java than 8, and sometimes is about the memory not being enough and it's failing)

I'll look deeper into what else can interrupt the Java connection on Docker.

**Comment by swainsubrat** [comment]
```
2020-09-12 16:02:08,379 INFO py4j.java_gateway Thread-3: Error while receiving.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
2020-09-12 16:02:08,380 ERROR root Thread-3: Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving

```

I'm giving you the Docker file source, where you can make sure that the version of java is 8.
```
#Download base image ubuntu 18.04
FROM ubuntu:18.04

ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3
ENV PYTHONIOENCODING=utf8

RUN apt-get update && apt-get install -y \
    tar \
    wget \
    bash \
    rsync \
    gcc \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libpng-dev \
    libzmq3-dev \
    python3 \ 
    python3-dev \
    python3-pip \
    unzip \
    pkg-config \
    software-properties-common \
    graphviz

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/" >> ~/.bashrc

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir mlflow Keras scikit-spark scikit-learn scipy matplotlib pydot tensorflow graphviz

COPY requirements.txt /app/
WORKDIR /app
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["server.py"]
```

**Comment by swainsubrat** [comment]
Thanks, @maziyarpanahi for the fast reply. My bad, I responded late.

**Comment by maziyarpanahi** [comment]
Thank you, this is helpful. I assume spark-nlp and pyspark==2.4.6 are in the requirements.txt?

**Comment by swainsubrat** [comment]
Yes, 
pyspark==2.4.6
spark-nlp==2.5.5
I also mentioned it in the description.

**Comment by maziyarpanahi** [comment]
Excellent, I'll look closer to the error logs to see what happens before that especially during sparknlp.start(), I am guessing that failed either due to network/internet issue or hostname/IP issue. I'll keep you updated.

**Comment by imsaravan** [comment]
Hello All, I am facing same kind of issue. I have installed pyspark 2.3.1 in my jenkins server. It works good when i run tests manually in the server but it fails when ran from jenkins build.
