### ISSUE TITLE
Unable to load files from S3 using spark-nlp

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [JohnSnowLabs/spark-nlp#1046]
## Description
There are classpath problems between spark-nlp dependencies and dependencies shipped with Spark.
In spark-nlp build files we depend on,

"org.apache.hadoop" % "hadoop-aws" %  "3.2.0"

which in turn depends on hadoop-commons-3.2.0, check,

https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.2.0

The version of hadoop-commons shipped with Spark 2.4.4 is,

spark-2.4.4-bin-hadoop2.7/jars/hadoop-common-2.7.3.jar

This causes the following exception when hadoop-aws tries to find latest hadoop common classes,

Py4JJavaError: An error occurred while calling o78.load.
: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/StreamCapabilities
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:45)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.StreamCapabilities
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 39 more
 

## Expected Behavior
Spark-nlp dependencies shoulnd't conflict with matchin spark dependencies.

## Possible Solution
Downgrade hadoop-aws to 2.7.2., or
Use shading(https://github.com/sbt/sbt-assembly#shading)

## Steps to Reproduce
Try to read anything from S3 while spark-nlp is in the classpath.

1. run the following code

```
builder = SparkSession.builder \
        .appName("Spark NLP") \
        .master("local[*]") \
        .config("spark.jars.packages", "org.apache.hadoop:hadoop-aws:2.7.3,com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.5")\
        .config("spark.driver.memory", "16G") \
        .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
        .config("spark.kryoserializer.buffer.max", "1000M") \
        .config("spark.driver.maxResultSize", "0")\
        .config('spark.hadoop.fs.s3a.access.key', "XXXXXXXXXXXXXXXXX" ) \
        .config('spark.hadoop.fs.s3a.secret.key', "XXXXXXXXXXXXXXXXXXXXX")
spark = builder.getOrCreate()

pdfs_path = "s3a://path-to-some-existing-bucket/and-folder/"
rdd = spark.sparkContext.binaryFiles(pdfs_path).collect()

```
2. It will fail.
3. Remove com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.5, and it will work.

## Your Environment

* Spark NLP version: 2.5.5
* Apache NLP version: ??
* Java version (java -version): 1.8 OpenJDK
* Setup and installation (Pypi, Conda, Maven, etc.): Conda.
* Operating System and version: Ubuntu 18.
* Link to your project (if any):

**Comment by Thijsvandepoll** [comment]
Hi! I am having the same issue. Did you find any temporary fix/workaround for this?

**Comment by amcquistan** [comment]
sam issues here

**Comment by maziyarpanahi** [comment]
Hi,
Could you also update the comments with a bit of info regarding the versions, your environment, which path/fileSystem is not accessible, etc.
This helps us to reproduce this issue in every possible scenarios and find a fix for it.
Thank you

**Comment by amcquistan** [comment]
Sorry I don't think my issue is related to spark-nlp but something else but I will still add more info since it is very similar to the error being seen for the OP.


General setup is.

```
from pyspark.sql import SparkSession
from pyspark.sql.functions import udf, desc, asc, sum as spark_sum
from pyspark.sql.types import StringType, IntegerType

import configparser

config = configparser.ConfigParser()
config.read('~/.aws/credentials')

accesskey_id = config.get('default', 'aws_access_key_id')
accesskey = config.get('default', 'aws_secret_access_key')

spark = SparkSession.builder.appName("Spark with S3")\
    .config("spark.jars.packages","org.apache.hadoop:hadoop-aws:3.2.0")\
    .getOrCreate()

hadoop_config = spark._jsc.hadoopConfiguration()
hadoop_config.set('fs.s3n.impl', 'org.apache.hadoop.fs.s3native.NativeS3FileSystem')
hadoop_config.set('fs.s3a.impl', 'org.apache.hadoop.fs.s3a.S3AFileSystem')
hadoop_config.set('fs.s3a.aws.credentials.provider', 'org.apache.hadoop.fs.s3a.BasicAWSCredentialsProvider')
hadoop_config.set('com.amazonaws.services.s3.enableV4', 'true')
hadoop_config.set('fs.s3n.awsAccessKeyId', accesskey_id)
hadoop_config.set('fs.s3n.awsSecretAccessKey', accesskey)
```

Then trying to read CSV from S3 I get very similar error to what is reported but I suspect it really is related to something spark / Hadoop / AWS 

```
df = spark.read.csv('s3a://udacity-dend/pagila/payment/payment.csv')

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-6-d16c0994225e> in <module>
----> 1 df = spark.read.csv('s3a://udacity-dend/pagila/payment/payment.csv')

~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/pyspark/sql/readwriter.py in csv(self, path, schema, sep, encoding, quote, escape, comment, header, inferSchema, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, nullValue, nanValue, positiveInf, negativeInf, dateFormat, timestampFormat, maxColumns, maxCharsPerColumn, maxMalformedLogPerPartition, mode, columnNameOfCorruptRecord, multiLine, charToEscapeQuoteEscaping, samplingRatio, enforceSchema, emptyValue, locale, lineSep, pathGlobFilter, recursiveFileLookup)
    533             path = [path]
    534         if type(path) == list:
--> 535             return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    536         elif isinstance(path, RDD):
    537             def func(iterator):

~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    126     def deco(*a, **kw):
    127         try:
--> 128             return f(*a, **kw)
    129         except py4j.protocol.Py4JJavaError as e:
    130             converted = convert_exception(e.java_exception)

~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o34.csv.
: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/StreamCapabilities
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:723)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.StreamCapabilities
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 40 more
```

**Comment by Thijsvandepoll** [comment]
Hi @maziyarpanahi I made some code to reproduce the errors. 

My set-up (local):
- macOS Catalina 10.15.7
- `pyspark` version 2.4.4 (installed using `pip install pyspark==2.4.4`)
- `spark-nlp` version 2.6.5 (installed using `pip install spark-nlp==2.6.5`)
- Java version 1.8.0_202
- I think the `pip` installed version of `pyspark` ships with `hadoop` version 2.7.3

My code to reproduce the errors, is a simple code that reads from an existing Postgres database, and then writes the output to a parquet file in S3. I excluded any Spark-NLP steps to make the code as easy as possible. The following code works fine:

```
import os
from pyspark.sql import SparkSession

# Get variable from environment
PG_HOST = os.environ.get("PG_HOST")
PG_PORT = os.environ.get("PG_PORT")
PG_DB = os.environ.get("PG_DB")
PG_USER = os.environ.get("PG_USER")
PG_PASS = os.environ.get("PG_PASS")

# Create SparkSession
spark = SparkSession.builder.\
    appName("family-embeddings").\
    config("spark.jars.packages", "org.postgresql:postgresql:42.1.1,org.apache.hadoop:hadoop-aws:2.7.3"). \
    config("spark.driver.memory", "16G"). \
    config("spark.driver.maxResultSize", "0"). \
    config("spark.kryoserializer.buffer.max", "1000M").\
    config("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem").\
    config("fs.s3a.access.key", aws_access_key_id).\
    config("fs.s3a.secret.key", aws_secret_access_key).\
    config("fs.s3a.endpoint", "s3.eu-central-1.amazonaws.com").\
    getOrCreate()

# Set property
spark.sparkContext.setSystemProperty('com.amazonaws.services.s3.enableV4', 'true')

# Load data from Postgres server
data = spark.read.format("jdbc").\
    option("url", "jdbc:postgresql://{}:{}/{}".format(PG_HOST, PG_PORT, PG_DB)).\
    option("dbtable", table).\
    option("user", PG_USER).\
    option("password", PG_PASS).\
    option("driver", "org.postgresql.Driver").\
    load()

# Write to parquet in S3
data.limit(10).write.format("parquet").mode("overwrite").save(s3_path)
```
Note that this does not include the Spark-NLP jars. However, as soon as I add the Spark-NLP jars to the SparkSession, the same code runs into problems. I used the following:

```
import os
from pyspark.sql import SparkSession

# Get variable from environment
PG_HOST = os.environ.get("PG_HOST")
PG_PORT = os.environ.get("PG_PORT")
PG_DB = os.environ.get("PG_DB")
PG_USER = os.environ.get("PG_USER")
PG_PASS = os.environ.get("PG_PASS")

# Create SparkSession
spark = SparkSession.builder.\
    appName("family-embeddings").\
    config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.6.5,org.postgresql:postgresql:42.1.1,org.apache.hadoop:hadoop-aws:2.7.3"). \
    config("spark.driver.memory", "16G"). \
    config("spark.driver.maxResultSize", "0"). \
    config("spark.kryoserializer.buffer.max", "1000M").\
    config("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem").\
    config("fs.s3a.access.key", aws_access_key_id).\
    config("fs.s3a.secret.key", aws_secret_access_key).\
    config("fs.s3a.endpoint", "s3.eu-central-1.amazonaws.com").\
    getOrCreate()

# Set property
spark.sparkContext.setSystemProperty('com.amazonaws.services.s3.enableV4', 'true')

# Load data from Postgres server
data = spark.read.format("jdbc").\
    option("url", "jdbc:postgresql://{}:{}/{}".format(PG_HOST, PG_PORT, PG_DB)).\
    option("dbtable", table).\
    option("user", PG_USER).\
    option("password", PG_PASS).\
    option("driver", "org.postgresql.Driver").\
    load()

# Write to parquet in S3
data.limit(10).write.format("parquet").mode("overwrite").save(s3_path)
```

This gives the following errors:

```
Traceback (most recent call last):
  File "<input>", line 8, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/thijsvandepoll/PycharmProjects/family-embeddings/applications/embedding-apps/examples/reproduce_error.py", line 44, in <module>
    data.limit(10).write.format("parquet").mode("overwrite").save(s3_path)
  File "/Users/thijsvandepoll/PycharmProjects/family-embeddings/venv/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 739, in save
    self._jwrite.save(path)
  File "/Users/thijsvandepoll/PycharmProjects/family-embeddings/venv/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/thijsvandepoll/PycharmProjects/family-embeddings/venv/lib/python3.7/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/Users/thijsvandepoll/PycharmProjects/family-embeddings/venv/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o90.save.
: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/StreamCapabilities
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:438)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:538)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:310)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.StreamCapabilities
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
```

Then another point that might be interesting is that I ran such scripts on an EMR cluster, in the following form (without the settings to read and write to S3, but with Spark-NLP jars included):

```
import os
from pyspark.sql import SparkSession

# Get variable from environment
PG_HOST = os.environ.get("PG_HOST")
PG_PORT = os.environ.get("PG_PORT")
PG_DB = os.environ.get("PG_DB")
PG_USER = os.environ.get("PG_USER")
PG_PASS = os.environ.get("PG_PASS")

# Create SparkSession
spark = SparkSession.builder.\
    appName("family-embeddings").\
    config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.6.5,org.postgresql:postgresql:42.1.1"). \
    config("spark.driver.memory", "16G"). \
    config("spark.driver.maxResultSize", "0"). \
    config("spark.kryoserializer.buffer.max", "1000M").\
    getOrCreate()

# Load data from Postgres server
data = spark.read.format("jdbc").\
    option("url", "jdbc:postgresql://{}:{}/{}".format(PG_HOST, PG_PORT, PG_DB)).\
    option("dbtable", table).\
    option("user", PG_USER).\
    option("password", PG_PASS).\
    option("driver", "org.postgresql.Driver").\
    load()

# Write to parquet in S3
data.limit(10).write.format("parquet").mode("overwrite").save(s3_path)
```
 
This works like a charm. The set-up of the EMR cluster includes:
- Spark version 2.4.7
- Hadoop version 2.10.1
- (I used her a `pip` installed version of `spark-nlp` version 2.6.5)

Any ideas?

**Comment by maziyarpanahi** [comment]
> Sorry I don't think my issue is related to spark-nlp but something else but I will still add more info since it is very similar to the error being seen for the OP.
> 
> 
> 
> Hadoop 3.2.0
> 
> Spark 3.0.1
> 
> 
> 
> 
> 
> General setup is.
> 
> 
> 
> ```
> 
> from pyspark.sql import SparkSession
> 
> from pyspark.sql.functions import udf, desc, asc, sum as spark_sum
> 
> from pyspark.sql.types import StringType, IntegerType
> 
> 
> 
> import configparser
> 
> 
> 
> config = configparser.ConfigParser()
> 
> config.read('~/.aws/credentials')
> 
> 
> 
> accesskey_id = config.get('default', 'aws_access_key_id')
> 
> accesskey = config.get('default', 'aws_secret_access_key')
> 
> 
> 
> spark = SparkSession.builder.appName("Spark with S3")\
> 
>     .config("spark.jars.packages","org.apache.hadoop:hadoop-aws:3.2.0")\
> 
>     .getOrCreate()
> 
> 
> 
> hadoop_config = spark._jsc.hadoopConfiguration()
> 
> hadoop_config.set('fs.s3n.impl', 'org.apache.hadoop.fs.s3native.NativeS3FileSystem')
> 
> hadoop_config.set('fs.s3a.impl', 'org.apache.hadoop.fs.s3a.S3AFileSystem')
> 
> hadoop_config.set('fs.s3a.aws.credentials.provider', 'org.apache.hadoop.fs.s3a.BasicAWSCredentialsProvider')
> 
> hadoop_config.set('com.amazonaws.services.s3.enableV4', 'true')
> 
> hadoop_config.set('fs.s3n.awsAccessKeyId', accesskey_id)
> 
> hadoop_config.set('fs.s3n.awsSecretAccessKey', accesskey)
> 
> ```
> 
> 
> 
> Then trying to read CSV from S3 I get very similar error to what is reported but I suspect it really is related to something spark / Hadoop / AWS 
> 
> 
> 
> ```
> 
> df = spark.read.csv('s3a://udacity-dend/pagila/payment/payment.csv')
> 
> 
> 
> ---------------------------------------------------------------------------
> 
> Py4JJavaError                             Traceback (most recent call last)
> 
> <ipython-input-6-d16c0994225e> in <module>
> 
> ----> 1 df = spark.read.csv('s3a://udacity-dend/pagila/payment/payment.csv')
> 
> 
> 
> ~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/pyspark/sql/readwriter.py in csv(self, path, schema, sep, encoding, quote, escape, comment, header, inferSchema, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, nullValue, nanValue, positiveInf, negativeInf, dateFormat, timestampFormat, maxColumns, maxCharsPerColumn, maxMalformedLogPerPartition, mode, columnNameOfCorruptRecord, multiLine, charToEscapeQuoteEscaping, samplingRatio, enforceSchema, emptyValue, locale, lineSep, pathGlobFilter, recursiveFileLookup)
> 
>     533             path = [path]
> 
>     534         if type(path) == list:
> 
> --> 535             return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
> 
>     536         elif isinstance(path, RDD):
> 
>     537             def func(iterator):
> 
> 
> 
> ~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
> 
>    1302 
> 
>    1303         answer = self.gateway_client.send_command(command)
> 
> -> 1304         return_value = get_return_value(
> 
>    1305             answer, self.gateway_client, self.target_id, self.name)
> 
>    1306 
> 
> 
> 
> ~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
> 
>     126     def deco(*a, **kw):
> 
>     127         try:
> 
> --> 128             return f(*a, **kw)
> 
>     129         except py4j.protocol.Py4JJavaError as e:
> 
>     130             converted = convert_exception(e.java_exception)
> 
> 
> 
> ~/code/udacity/dataengr/spark/venv/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
> 
>     324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
> 
>     325             if answer[1] == REFERENCE_TYPE:
> 
> --> 326                 raise Py4JJavaError(
> 
>     327                     "An error occurred while calling {0}{1}{2}.\n".
> 
>     328                     format(target_id, ".", name), value)
> 
> 
> 
> Py4JJavaError: An error occurred while calling o34.csv.
> 
> : java.lang.NoClassDefFoundError: org/apache/hadoop/fs/StreamCapabilities
> 
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
> 
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 
> 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
> 
> 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
> 
> 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
> 
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
> 
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> 
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 
> 	at java.base/java.lang.Class.forName0(Native Method)
> 
> 	at java.base/java.lang.Class.forName(Class.java:398)
> 
> 	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
> 
> 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
> 
> 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
> 
> 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
> 
> 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
> 
> 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
> 
> 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
> 
> 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
> 
> 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
> 
> 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
> 
> 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
> 
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
> 
> 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
> 
> 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
> 
> 	at scala.Option.getOrElse(Option.scala:189)
> 
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
> 
> 	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:723)
> 
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.StreamCapabilities
> 
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
> 
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> 
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 
> 	... 40 more
> 
> ```

Thanks, unfortunately, your issue is not related to spark-nlp. (We don't support Spark 3.x yet so I am sure you don't have this library included in the session)

**Comment by maziyarpanahi** [comment]
> Hi @maziyarpanahi I made some code to reproduce the errors. 


This is really helpful. I make sure we address this in the upcoming release. It seems sometimes (from outside AWS maybe) one of our dependencies either ignore or override the actual S3 dependency.

**Comment by Thijsvandepoll** [comment]
Great thanks!

**Comment by RodolpheCalvet** [comment]
Same msg on intellij spark shell (scala 2 11 12)
but ok with intellij scala 2 12 10

**Comment by maziyarpanahi** [comment]
Spark NLP is not compatible with Scala 2.12. I think you are not using Spark NLP in your project.

**Comment by captify-jrahman** [comment]
Does anyone know of a workaround until a fix is released?

**Comment by maziyarpanahi** [comment]
I would suggest changing `hadoop-aws` from 3.x to 2.7.3 and `aws-java-sdk` to 1.7.4, then make a fat JAR until the next release we fix this. (we need some testing to be sure we are not breaking anything that already works)
