### ISSUE TITLE
Loading saved DistilBertForSequenceClassification into SparkNLP throws saved_model/1/assets/vocab.txt not found error

### ISSUE THREAD

**Issue by randimah** [JohnSnowLabs/spark-nlp#10664]
### Description
I was following the example in https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/transformers/HuggingFace%20in%20Spark%20NLP%20-%20DistilBertForSequenceClassification.ipynb exactly step by step. It fails at the following step when it's trying to load the saved pre-trained model on Databricks.
```
from sparknlp.annotator import *
from sparknlp.base import *

sequenceClassifier = DistilBertForSequenceClassification.loadSavedModel(
     '{}/saved_model/1'.format(MODEL_NAME),
     spark
 )\
  .setInputCols(["document",'token'])\
  .setOutputCol("class")\
  .setCaseSensitive(True)\
  .setMaxSentenceLength(128)
```
### Current Behavior
`java.io.FileNotFoundException: file or folder: /databricks/driver/distilbert-base-uncased-finetuned-sst-2-english/saved_model/1/assets/vocab.txt not found`
But 
`!ls -al /databricks/driver/distilbert-base-uncased-finetuned-sst-2-english/saved_model/1/assets/` gives
```
total 12
drwxr-xr-x 2 root root 4096 Jul 20 16:20 .
drwxr-xr-x 4 root root 4096 Jul 20 15:57 ..
-rw-r--r-- 1 root root   17 Jul 20 16:06 labels.txt
-rw-r--r-- 1 root root    0 Jul 20 16:20 vocab.txt
```
So the file exists. Tried saving to other locations but didn't fix the issue.
### Environment
SparkNLP Version: spark-nlp==4.0.1
Databricks LTS: 10.4
Transformers: transformers==4.15.0
Java version: 
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)

### Full Stack Trace 
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-658370279830461> in <module>
      2 from sparknlp.base import *
      3 
----> 4 sequenceClassifier = DistilBertForSequenceClassification.loadSavedModel(
      5 #      '{}/saved_model/1'.format(MODEL_NAME),
      6     '/databricks/driver/distilbert-base-uncased-finetuned-sst-2-english/saved_model/1',

/databricks/python/lib/python3.8/site-packages/sparknlp/annotator/classifier_dl/distil_bert_for_sequence_classification.py in loadSavedModel(folder, spark_session)
    185         """
    186         from sparknlp.internal import _DistilBertSequenceClassifierLoader
--> 187         jModel = _DistilBertSequenceClassifierLoader(folder, spark_session._jsparkSession)._java_obj
    188         return DistilBertForSequenceClassification(java_model=jModel)
    189 

/databricks/python/lib/python3.8/site-packages/sparknlp/internal/__init__.py in __init__(self, path, jspark)
    120 class _DistilBertSequenceClassifierLoader(ExtendedJavaWrapper):
    121     def __init__(self, path, jspark):
--> 122         super(_DistilBertSequenceClassifierLoader, self).__init__(
    123             "com.johnsnowlabs.nlp.annotators.classifier.dl.DistilBertForSequenceClassification.loadSavedModel", path,
    124             jspark)

/databricks/python/lib/python3.8/site-packages/sparknlp/internal/extended_java_wrapper.py in __init__(self, java_obj, *args)
     24         super(ExtendedJavaWrapper, self).__init__(java_obj)
     25         self.sc = SparkContext._active_spark_context
---> 26         self._java_obj = self.new_java_obj(java_obj, *args)
     27         self.java_obj = self._java_obj
     28 

/databricks/python/lib/python3.8/site-packages/sparknlp/internal/extended_java_wrapper.py in new_java_obj(self, java_class, *args)
     34 
     35     def new_java_obj(self, java_class, *args):
---> 36         return self._new_java_obj(java_class, *args)
     37 
     38     def new_java_array(self, pylist, java_class):

/databricks/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.annotators.classifier.dl.DistilBertForSequenceClassification.loadSavedModel.
: java.io.FileNotFoundException: file or folder: /databricks/driver/distilbert-base-uncased-finetuned-sst-2-english/saved_model/1/assets/vocab.txt not found
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$SourceStream.<init>(ResourceHelper.scala:60)
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.parseLines(ResourceHelper.scala:278)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadDistilBertForSequenceTensorflowModel.loadSavedModel(DistilBertForSequenceClassification.scala:385)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadDistilBertForSequenceTensorflowModel.loadSavedModel$(DistilBertForSequenceClassification.scala:365)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.DistilBertForSequenceClassification$.loadSavedModel(DistilBertForSequenceClassification.scala:416)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.DistilBertForSequenceClassification.loadSavedModel(DistilBertForSequenceClassification.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maziyarpanahi** [comment]
The notebook(s) indicates clearly you cannot use loadSavedModel on the distributed file system. (any cluster mode Spark)

>NOTE: loadSavedModel only accepts local paths and not distributed file systems such as HDFS, S3, DBFS, etc. That is why we use write.save so we can use .load() from any file systems
