### ISSUE TITLE
 Unable to load Explain Clinical Document (license version) 

### ISSUE THREAD

**Issue by chandramohanreddyab** [JohnSnowLabs/spark-nlp#1069]
Trying to load pretrained model offline 

## Description

Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-8537561f4d52> in <module>
----> 1 explain_clinical_doc_era=PretrainedPipeline.from_disk("/dfs/is/home/m292915/spark_nlp/pretrained/license/explain_clinical_doc_era_en_2.5.5_2.4/")

~/.conda/envs/sparknlp26/lib/python3.7/site-packages/sparknlp/pretrained.py in from_disk(path, parse_embeddings)
     96     @staticmethod
     97     def from_disk(path, parse_embeddings=False):
---> 98         return PretrainedPipeline(None, None, None, parse_embeddings, path)
     99 
    100     def annotate(self, target, column=None):

~/.conda/envs/sparknlp26/lib/python3.7/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     91             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         else:
---> 93             self.model = PipelineModel.load(disk_location)
     94         self.light_model = LightPipeline(self.model, parse_embeddings)
     95 

~/.conda/envs/sparknlp26/lib/python3.6/site-packages/pyspark/ml/util.py in load(cls, path)
    309     def load(cls, path):
    310         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 311         return cls.read().load(path)
    312 
    313 

~/.conda/envs/sparknlp26/lib/python3.6/site-packages/pyspark/ml/pipeline.py in load(self, path)
    240         metadata = DefaultParamsReader.loadMetadata(path, self.sc)
    241         if 'language' not in metadata['paramMap'] or metadata['paramMap']['language'] != 'Python':
--> 242             return JavaMLReader(self.cls).load(path)
    243         else:
    244             uid, stages = PipelineSharedReadWrite.load(metadata, self.sc, path)

~/.conda/envs/sparknlp26/lib/python3.6/site-packages/pyspark/ml/util.py in load(self, path)
    247         if not isinstance(path, basestring):
    248             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 249         java_obj = self._jread.load(path)
    250         if not hasattr(self._clazz, "_from_java"):
    251             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

~/.conda/envs/sparknlp26/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1158         answer = self.gateway_client.send_command(command)
   1159         return_value = get_return_value(
-> 1160             answer, self.gateway_client, self.target_id, self.name)
   1161 
   1162         for temp_arg in temp_args:

~/.conda/envs/sparknlp26/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~/.conda/envs/sparknlp26/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    318                 raise Py4JJavaError(
    319                     "An error occurred while calling {0}{1}{2}.\n".
--> 320                     format(target_id, ".", name), value)
    321             else:
    322                 raise Py4JError(

Py4JJavaError: An error occurred while calling o189.load.
: java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.annotators.re.RelationExtractionModel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:235)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:452)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
## Expected Behavior

Pretrained models should be loaded successfully
## Current Behavior

No class RelationExtractionModel found exception and failed to load pretrained models
## Possible Solution

No Idea
## Steps to Reproduce

1. Initiate spark 2.3 session
2. Load explain_clinical_doc_carp licensed version
3. https://github.com/chandramohanreddyab/NLP/blob/master/explain_document_clinical.ipynb

## Your Environment

* Spark NLP version:2.6.0
* Apache NLP version:
* Java version (java -version):1.8
* Setup and installation (Pypi, Conda, Maven, etc.): Conda
* Operating System and version: Linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi @chandramohanreddyab 

This is only for issues related to the public and open-source library. We have no knowledge of the healthcare, you can reach out to them either via email (which you received your license) or via Slack channel (#healthcare).
