### ISSUE TITLE
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize. : com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied 

### ISSUE THREAD

**Issue by ajay9022** [JohnSnowLabs/spark-nlp#1082]
I want to run sparknlp on google colab and here's the code:

```spark = sparknlp.start()
clinical_ner = NerDLModel.pretrained("ner_posology", "en", "clinical/models") \
  .setInputCols(["sentence", "token", "embeddings"]) \
  .setOutputCol("ner")
```

but it shows this:
```
ner_posology download started this may take some time.

---------------------------------------------------------------------------

Py4JJavaError                             Traceback (most recent call last)

<ipython-input-20-cdd2d8bea7a6> in <module>()
----> 1 clinical_ner = NerDLModel.pretrained("ner_posology", "en", "clinical/models")   .setInputCols(["sentence", "token", "embeddings"])   .setOutputCol("ner")

8 frames

/usr/local/lib/python3.6/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: BG6Y4ZDTEH5JCG3P; S3 Extended Request ID: jazEEqsUBl87wRuerOLhHTHBRYJH43rIuzP/QwiZRM7849hZHXRIJ+FADybADSlO7ei8HlzVCUg=), S3 Extended Request ID: jazEEqsUBl87wRuerOLhHTHBRYJH43rIuzP/QwiZRM7849hZHXRIJ+FADybADSlO7ei8HlzVCUg=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1467)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1326)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:69)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:81)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:159)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:400)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:494)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)

`
```

**Comment by maziyarpanahi** [comment]
@ajay9022 
Sorry, this is only for open-source support, not the enterprise/healthcare. You have to either contact the person who gave you the license keys or join the Spark NLP Slack and ask in the #healthcare channel.

**Comment by ajay9022** [comment]
@maziyarpanahi  You mean all the pre-trained models on the healthcare domain are under some license? So, do I need to buy that?

**Comment by maziyarpanahi** [comment]
The answer to the first question is yes: https://github.com/JohnSnowLabs/spark-nlp-models#licensed-enterprise

For the second question, you can check this page (we really don't have any info, but you can ask any question from the chat in the main website): https://www.johnsnowlabs.com/spark-nlp-health/

**Comment by ajay9022** [comment]
@maziyarpanahi Actually, I wanted to capture duration, frequency in the medical prescriptions like `daily`, `weekly`, `3 months`. Is there any pre-trained model that you could recommend me? I desperately need it.

**Comment by maziyarpanahi** [comment]
We have onto_100 and onto_300 but they just extract Dates not durations. Those are domain specific and under healthcare license. It's best to ask for a trial from the company.
