### ISSUE TITLE
Request to upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.7

### ISSUE THREAD

**Issue by wangruinju** [JohnSnowLabs/spark-nlp#1091]
as title says

**Comment by maziyarpanahi** [comment]
Any specific reason? Motivation?

**Comment by wangruinju** [comment]
Hi @maziyarpanahi , I plan to use the latest version of spark-nlp for keyphrase extraction but it seems our internal system has this dependency blocker. Instead, if I use jar instead, do you have any suggestions of workaround?

**Comment by wangruinju** [comment]
To create the jar manually, `sbt -Dis_spark23=true assembly` will generate the following error: 
`Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:418)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at lombok.javac.JavacTreeMaker$SchroedingerType.getFieldCached(JavacTreeMaker.java:156)
	at lombok.javac.JavacTreeMaker$TypeTag.typeTag(JavacTreeMaker.java:244)
	at lombok.javac.Javac.<clinit>(Javac.java:154)
	at lombok.javac.handlers.HandleGetter.<clinit>(HandleGetter.java:298)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:170)
	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:155)
	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:86)
	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:702)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:830)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:926)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1270)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1384)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1263)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:935)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at sbt.compiler.javac.LocalJavaCompiler.run(LocalJava.scala:77)
	at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
	at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:59)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:927)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:918)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:916)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (compile:compileIncremental) java.lang.ExceptionInInitializerError
[error] Total time: 65 s, completed Oct 12, 2020, 4:55:52 PM`

**Comment by wangruinju** [comment]
+  "org.projectlombok" % "lombok" % "1.16.22",
-  "com.amazonaws" % "aws-java-sdk-core" % "1.11.603"
+  "com.amazonaws" % "aws-java-sdk-core" % "1.11.438"
-  "com.amazonaws" % "aws-java-sdk-s3" % "1.11.603",
+  "com.amazonaws" % "aws-java-sdk-s3" % "1.11.438",

**Comment by maziyarpanahi** [comment]
If you clone the repo and run that line it should generate a fat jar for Apache Spark 2.3.x as we do that for each release.
I am not sure if you have changed anything in the build.sbt or it's just you Java not being properly installed with all the required path. (I'll start with proper Java 8 on a machine that has everything)

**Comment by wangruinju** [comment]
After appending the `lombok 1.6.22` and downgrading `aws-java-sdk-core/s3 1.11.438`, I was able to build the jar manually.
