### ISSUE TITLE
SparkNLP LemmatizerModel.pretrained() error on Databricks Runtime 11.0 ML | Apache Spark 3.3.0

### ISSUE THREAD

**Issue by shringarsharan** [JohnSnowLabs/spark-nlp#11042]
I'm getting the following error while preprocessing text data and trying to run the `LemmatizerModel.pretrained().setInputCols(["normalized"]).setOutputCol("lemma")` 
code on Databricks Runtime 11.0 ML

### Environment

Databricks Runtime: 11.0 ML
SparkNLP version : 4.0.2
Apache Spark version: 3.3.0
Setup and installation (Maven, PyPi): Installed using Databricks libraries tab
Maven -> com.johnsnowlabs.nlp:spark-nlp_2.12:4.0.2
PyPi  -> spark-nlp==4.0.2

### Description of Error

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.ResourceDownloader$
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.$anonfun$getDownloadSize$1(ResourceDownloader.scala:722)
	at scala.Option.getOrElse(Option.scala:189)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:722)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:748)

### Expected Behavior

Pretrained model should load

**Comment by maziyarpanahi** [comment]
- Could you please share a screenshot from your Cluster tab and the Library tab? 
- Just to be sure this is not 1 annotator / 1 model, could you please try 'ner = NerDLModel.pretrained()'

If this fails too then there is an issue with your DBFS/S3 configs that it is not recognizing it, in that case I will ask further questions.

**Comment by shringarsharan** [comment]
I'm again getting the same error when I run `ner = NerDLModel.pretrained()`
<img width="982" alt="Screen Shot 2022-08-03 at 10 57 21 AM" src="https://user-images.githubusercontent.com/58893104/182677092-26b2e828-c473-4721-8a99-cd56fdf50094.png">

**Comment by maziyarpanahi** [comment]
So it's not the model, it's the configs. Could you please provide the screenshots from the cluster and libraries tabs?
