### ISSUE TITLE
unable to load any pretrained model after download

### ISSUE THREAD

**Issue by BingzhangZhu** [JohnSnowLabs/spark-nlp#11506]
## Description

I have successfully installed PySpark and SparkNLP on my linux box (see specifications below).

I launch pyspark with this command:
`pyspark --master yarn --deploy-mode client --queue default --num-executors=20 --executor-cores=4 --driver-memory=22g --executor-memory=16g --conf spark.scheduler.mode=FAIR --conf spark.driver.maxResultSize=8g --packages commons-configuration:commons-configuration:1.10,com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.6.5`

And I try to execute the following code:

```
import sparknlp
from sparknlp.annotator import *
from sparknlp.base import *

# we use BERT Tiny
bert_annotator = BertEmbeddings.pretrained('small_bert_L2_128', 'en') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
.setBatchSize(8)
```

## Expected Behavior

load the pretrained bert model for future use

## Current Behavior

During the execution, it seems the download is done, but when load the pretrained model, I get this error:

```
>>> import sparknlp
>>> from sparknlp.annotator import *
>>> from sparknlp.base import *
>>> # we use BERT Tiny
... bert_annotator = BertEmbeddings.pretrained('small_bert_L2_128', 'en') \
...  .setInputCols(["sentence",'token'])\
...  .setOutputCol("bert")\
... .setBatchSize(8)
small_bert_L2_128 download started this may take some time.
22/08/04 17:13:45 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
Approximate size to download 16.1 MB
[ | ]small_bert_L2_128 download started this may take some time.
Approximate size to download 16.1 MB
Download done! Loading the resource.
[ \ ]#                                                                          
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007ff24ad44da9, pid=20788, tid=0x00007ff45c5e3700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtensorflow_framework.so.1+0x744da9]  _GLOBAL__sub_I_loader.cc+0x99
#
# Core dump written. Default location: /home/ezhu/web_category/core or core.20788
#
# An error report file with more information is saved as:
# /home/ezhu/web_category/hs_err_pid20788.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
[OK!]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ezhu/.local/lib/python3.6/site-packages/sparknlp/annotator.py", line 1805, in pretrained
    return ResourceDownloader.downloadModel(BertEmbeddings, name, lang, remote_loc)
  File "/home/ezhu/.local/lib/python3.6/site-packages/sparknlp/pretrained.py", line 41, in downloadModel
    j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
  File "/home/ezhu/.local/lib/python3.6/site-packages/sparknlp/internal.py", line 176, in __init__
    super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
  File "/home/ezhu/.local/lib/python3.6/site-packages/sparknlp/internal.py", line 129, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/home/ezhu/.local/lib/python3.6/site-packages/sparknlp/internal.py", line 139, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 336, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel
```

## Your Environment

* Spark NLP version `sparknlp.version()`: 2.6.5
* Apache NLP version `spark.version`: 2.3.2
* Java version `java -version`: 1.8.0_144
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version: Ubuntu 14.04.5 LTS
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

Your operating system is not supported by the TensorFlow used in that Spark NLP version.

- You are using a very old and deprecated Ubuntu, I highly recommend at least using 16.04 (or 18.04/20.04)
- You are also using a very old Spark NLP version (2.6.5 is really old). If you need Spark 2.3.x support, Spark NLP 3.4.x (3.4.4) still supports Spark/PySpark 2.4.x/2.3.x - there is no need to use a 3-year-old release 

If you can have Ubuntu 18.04 with Spark NLP 3.4.x you can simply use the latest release (almost since 4.x is out) with your Spark 2.3
