### ISSUE TITLE
Crossvalidation for Normalizer and other Spark-NLP-Pipeline fails (e.g. "feature slangDict is not set" )

### ISSUE THREAD

**Issue by ahaas01** [JohnSnowLabs/spark-nlp#1158]
Hi guys,

my program fails, when I input a Pipeline with Spark-NLP-Elements in a Crossvalidator. But no error occurs, if i run the pipeline without the Crossvalidator.

I created a Colab Notebook, to easily reproduce the error:

https://colab.research.google.com/drive/1UgFtVMowOT_jC4gj5R-U3r3M3SmWa_HB?usp=sharing

The error message is "feature slangDict is not set", but running it without crossvalidation doesn't require this param. Even by setting "setSlangDictionary" at the Normalizer-Stage does not remove the Error.
Replacing the Normalizer with other NLP-Stages creates similar Error-Messages (feature * is not set).

## Stacktrace

org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 13.0 failed 1 times, most recent failure: Lost task 1.0 in stage 13.0 (TID 23, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)

....

Caused by: java.lang.Exception: feature slangDict is not set
	at com.johnsnowlabs.nlp.serialization.Feature$$anonfun$getOrDefault$1.apply(Feature.scala:80)
	at com.johnsnowlabs.nlp.serialization.Feature$$anonfun$getOrDefault$1.apply(Feature.scala:80)
	at scala.Option.getOrElse(Option.scala:121)

## Your Environment

* Spark NLP version: 2.6.3
* Spark (pyspark) version: 2.4.6  (fails in Java and PySpark)
* Java version (java -version): 8 (openjdk version "1.8.0_275")
* Setup and installation (Pypi, Conda, Maven, etc.): --- 
* Operating System and version: Example in Colab, ( reproducable in Windows w Java)
* Link to your project (if any): https://colab.research.google.com/drive/1UgFtVMowOT_jC4gj5R-U3r3M3SmWa_HB?usp=sharing#scrollTo=83HHcSoI0okm

**Comment by maziyarpanahi** [comment]
Thanks for reporting this. We will take a deeper look, however, regardless of this error, I would highly suggest separating the NLP pipeline from the ML functions affected by CV.

Meaning, in this case, you will have your first pipeline as follow:

```
documentAssembler,
regexTokenizer,
normalized,
...
finisher
```

You will .fit and .transform this pipeline and save it on disk (parquet is a good format, you can even just select the finisher column to save space on disk). Then load it back by `spark.read.parquet` and then feed it into the second pipeline which has `hashingTf` and `logreg`. The reason is that CV will repeat the stages based on a matrix given by you, so you will be processing the very same documents with the very same results over and over. If the dataset is very very small and your annotators are simple pre-processing you won't notice this but, if you have a real dataset with more complicated annotators such as word embeddings then all that time and computations will be wasted.

That's being said, we will definitely investigate this further as to why the `slangDict` param not serializable when it is used alongside `CrossValidator`.

**Comment by alexnb** [comment]
Unfortunately this is still broken with spark-nlp_2.12-3.0.1.jar, could you please have a look at the serialization problems?
(And thank you for your comment, @maziyarpanahi)

`Caused by: java.lang.Exception: feature rules is not set
	at com.johnsnowlabs.nlp.serialization.Feature.$anonfun$getOrDefault$1(Feature.scala:81) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at scala.Option.getOrElse(Option.scala:189) ~[scala-library-2.12.10.jar:?]
	at com.johnsnowlabs.nlp.serialization.Feature.getOrDefault(Feature.scala:81) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at com.johnsnowlabs.nlp.HasFeatures.$$(HasFeatures.scala:41) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at com.johnsnowlabs.nlp.HasFeatures.$$$(HasFeatures.scala:41) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at com.johnsnowlabs.nlp.AnnotatorModel.$$(AnnotatorModel.scala:14) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at com.johnsnowlabs.nlp.annotators.TokenizerModel.$anonfun$tag$7(TokenizerModel.scala:242) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:511) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator.foreach(Iterator.scala:941) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator.foreach$(Iterator.scala:941) ~[scala-library-2.12.10.jar:?]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429) ~[scala-library-2.12.10.jar:?]
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62) ~[scala-library-2.12.10.jar:?]
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313) ~[scala-library-2.12.10.jar:?]
	at scala.collection.AbstractIterator.to(Iterator.scala:1429) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307) ~[scala-library-2.12.10.jar:?]
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1429) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288) ~[scala-library-2.12.10.jar:?]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1429) ~[scala-library-2.12.10.jar:?]
	at com.johnsnowlabs.nlp.annotators.TokenizerModel.$anonfun$tag$2(TokenizerModel.scala:286) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableLike.map(TraversableLike.scala:238) ~[scala-library-2.12.10.jar:?]
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231) ~[scala-library-2.12.10.jar:?]
	at scala.collection.AbstractTraversable.map(Traversable.scala:108) ~[scala-library-2.12.10.jar:?]
	at com.johnsnowlabs.nlp.annotators.TokenizerModel.tag(TokenizerModel.scala:222) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at com.johnsnowlabs.nlp.annotators.TokenizerModel.annotate(TokenizerModel.scala:294) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at com.johnsnowlabs.nlp.HasSimpleAnnotate.$anonfun$dfAnnotate$1(HasSimpleAnnotate.scala:24) ~[spark-nlp_2.12-3.0.1.jar:3.0.1]
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.project_subExpr_0$(Unknown Source) ~[?:?]
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source) ~[?:?]
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43) ~[spark-sql_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755) ~[spark-sql_2.12-3.1.1.jar:3.1.1]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458) ~[scala-library-2.12.10.jar:?]
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458) ~[scala-library-2.12.10.jar:?]
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:192) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:131) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500) ~[spark-core_2.12-3.1.1.jar:3.1.1]
`

**Comment by maziyarpanahi** [comment]
@alexnb The issue is still open, not sure it will get fix since nothing in Spark ML CV will ever change anything in Spark NLP pipeline, my best advice is to follow my recommendation:
- Have a separate pipeline just for Spark NLP
- fit/transform and save the results on disk (so you don't end up keep recalculating the some stuff over and over again)
- read back the saved data from the disk and move on to your Spark ML pipeline with your CV

**Comment by alexnb** [comment]
@maziyarpanahi 
> since nothing in Spark ML CV will ever change anything in Spark NLP pipeline
But in my case this is exactly what is desired. I need to cross validate different NLP pipeline stage parameters and things like pipeline with normalizer and one without. With Spark ML we already implemented this and it works well. I thought since Spark NLP stages comply to Spark pipeline interfaces, CV would work exactly as for ML stages.

**Comment by maziyarpanahi** [comment]
This is an issue between CV in Spark ML and some annotators in Spark NLP. We have it on the list but we cannot get to it anytime soon as we need to finish other ongoing tasks first.

**Comment by JJorczik** [comment]
> This is an issue between CV in Spark ML and some annotators in Spark NLP. We have it on the list but we cannot get to it anytime soon as we need to finish other ongoing tasks first.

Any updates on this? I would find it quite helpful to use Spark ML CV in combination with Spark NLP annotators.

**Comment by maziyarpanahi** [comment]
Unfortunately, the CV in Spark ML is highly incompatible with the way Spark NLP works. We still haven't found any way to make them compatible. (it seems easier to implement our own CV, but that takes some time and needs some outside help)

**Comment by hilmar05** [comment]
Hello
Is there any news on this ? I would like to include parameters such as embedding size in hyperparameter tuning with pyspark CV.

If not, can you guide me how to include hyperparameter tuning for sparknlp modules?
