### ISSUE TITLE
Downloadable NerCrf sometimes fails on first attempt

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#126]
## Description

This can be reproduced in the ModelDownloaderExample on python notebooks.
The second time sometimes returns a 'Socket is closed' exception, and works only the third attempt.
This is a sporadic issue, some times it may not happen at all. Restart kernel and try again to reproduce it.
```
Caused by: org.rocksdb.RocksDBException: /tmp/spark-8d16b019-0b39-463a-b053-64f78a5cb79a/userFiles-4738a68b-a048-40d8-a4be-56546aea45e3/embeddings8aa1a103f941_idx5018497528102697011_work/MANIFEST-000008: No such file or directory
	at org.rocksdb.RocksDB.openROnly(Native Method)
	at org.rocksdb.RocksDB.openReadOnly(RocksDB.java:366)
	at org.rocksdb.RocksDB.openReadOnly(RocksDB.java:315)
	at com.johnsnowlabs.nlp.embeddings.WordEmbeddings.<init>(WordEmbeddings.scala:13)
	at com.johnsnowlabs.nlp.HasWordEmbeddings$$anonfun$embeddings$1.apply(HasWordEmbeddings.scala:35)
	at com.johnsnowlabs.nlp.HasWordEmbeddings$$anonfun$embeddings$1.apply(HasWordEmbeddings.scala:28)
	at scala.Option.map(Option.scala:146)
	at com.johnsnowlabs.nlp.HasWordEmbeddings$class.embeddings(HasWordEmbeddings.scala:28)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel.embeddings$lzycompute(NerCrfModel.scala:18)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel.embeddings(NerCrfModel.scala:18)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel.tag(NerCrfModel.scala:43)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel.annotate(NerCrfModel.scala:66)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:43)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:42)
	... 16 more
```
## Expected Behavior

Should work for the first time after it is downloaded

**Comment by aleksei-ai** [comment]
@saifjsl  can you try again with my branch deep_learning_ner?

**Comment by aleksei-ai** [comment]
As I understand this task is fixed. @saifjsl reopen it if there are still some problems
