### ISSUE TITLE
Intermittent problem in initialization in OCR

### ISSUE THREAD

**Issue by rvmey** [JohnSnowLabs/spark-nlp#12708]
## Description

We occasionally see this error in our OCR pipeline job.  If I re-run the same job with the same input data it works fine.  

## Stacktrace
```
22/09/08 09:50:55 ERROR Executor: Exception in task 10.0 in stage 0.0 (TID 10)
java.lang.ExceptionInInitializerError
	at org.apache.pdfbox.pdmodel.font.PDSimpleFont.<init>(PDSimpleFont.java:73)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java:122)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java:79)
	at com.johnsnowlabs.ocr.schema.Mapping.<init>(Mapping.scala:24)
	at com.johnsnowlabs.ocr.TesseractAcessPresets.$anonfun$doOCRWithConfidence$9(TesseractAccessPresets.scala:220)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at com.johnsnowlabs.ocr.TesseractAcessPresets.doOCRWithConfidence(TesseractAccessPresets.scala:212)
	at com.johnsnowlabs.ocr.TesseractAcessPresets.doOCR(TesseractAccessPresets.scala:262)
	at com.johnsnowlabs.ocr.transformers.ImageToText.$anonfun$transformUDF$2(ImageToText.scala:118)
	at scala.util.Try$.apply(Try.scala:213)
	at com.johnsnowlabs.ocr.transformers.ImageToText.$anonfun$transformUDF$1(ImageToText.scala:96)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.$anonfun$f$3(ScalaUDF.scala:169)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1127)
	at org.apache.spark.sql.catalyst.expressions.CreateArray.$anonfun$eval$1(complexTypeCreator.scala:73)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.expressions.CreateArray.eval(complexTypeCreator.scala:73)
	at org.apache.spark.sql.catalyst.expressions.ExplodeBase.eval(generators.scala:313)
	at org.apache.spark.sql.execution.GenerateExec.$anonfun$doExecute$3(GenerateExec.scala:95)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$ConcatIterator.hasNext(Iterator.scala:222)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2(ObjectHashAggregateExec.scala:109)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2$adapted(ObjectHashAggregateExec.scala:107)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:859)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:859)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.loadList(GlyphList.java:136)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.<init>(GlyphList.java:112)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.load(GlyphList.java:52)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.<clinit>(GlyphList.java:39)
	... 51 more
22/09/08 09:50:55 WARN TaskSetManager: Lost task 10.0 in stage 0.0 (TID 10, 6bb7b6f9a94f, executor driver): java.lang.ExceptionInInitializerError
	at org.apache.pdfbox.pdmodel.font.PDSimpleFont.<init>(PDSimpleFont.java:73)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java:122)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java:79)
	at com.johnsnowlabs.ocr.schema.Mapping.<init>(Mapping.scala:24)
	at com.johnsnowlabs.ocr.TesseractAcessPresets.$anonfun$doOCRWithConfidence$9(TesseractAccessPresets.scala:220)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at com.johnsnowlabs.ocr.TesseractAcessPresets.doOCRWithConfidence(TesseractAccessPresets.scala:212)
	at com.johnsnowlabs.ocr.TesseractAcessPresets.doOCR(TesseractAccessPresets.scala:262)
	at com.johnsnowlabs.ocr.transformers.ImageToText.$anonfun$transformUDF$2(ImageToText.scala:118)
	at scala.util.Try$.apply(Try.scala:213)
	at com.johnsnowlabs.ocr.transformers.ImageToText.$anonfun$transformUDF$1(ImageToText.scala:96)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.$anonfun$f$3(ScalaUDF.scala:169)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1127)
	at org.apache.spark.sql.catalyst.expressions.CreateArray.$anonfun$eval$1(complexTypeCreator.scala:73)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.expressions.CreateArray.eval(complexTypeCreator.scala:73)
	at org.apache.spark.sql.catalyst.expressions.ExplodeBase.eval(generators.scala:313)
	at org.apache.spark.sql.execution.GenerateExec.$anonfun$doExecute$3(GenerateExec.scala:95)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$ConcatIterator.hasNext(Iterator.scala:222)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2(ObjectHashAggregateExec.scala:109)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2$adapted(ObjectHashAggregateExec.scala:107)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:859)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:859)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.loadList(GlyphList.java:136)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.<init>(GlyphList.java:112)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.load(GlyphList.java:52)
	at org.apache.pdfbox.pdmodel.font.encoding.GlyphList.<clinit>(GlyphList.java:39)
	... 51 more

22/09/08 09:50:55 ERROR TaskSetManager: Task 10 in stage 0.0 failed 1 times; aborting job
22/09/08 09:50:56 WARN TaskSetManager: Lost task 16.0 in stage 0.0 (TID 16, 6bb7b6f9a94f, executor driver): TaskKilled (Stage cancelled)
```

## Expected Behavior
It should work consistently.

## Current Behavior
It fails intermittently.

## Possible Solution
It seems similar to this error, but we're not getting "java.lang.NoClassDefFoundError".
https://github.com/JohnSnowLabs/spark-nlp/issues/487

It seems similar to this error, but we're running java 1.8 so this should have been fixed:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7003462

## Steps to Reproduce
Run this code many times, and it will fail sometimes:
```
from pydoc import doc
import re
import os
import sys
import json
import shutil
import subprocess
from pprint import pprint
from zipfile import ZipFile

import uuid
import boto3
import pandas as pd
from datetime import datetime
from collections import Counter

import PIL
from PIL import Image
from PIL import ImageSequence
from PIL import TiffImagePlugin
from collections import Counter
from PyPDF2 import PdfFileMerger, PdfFileReader

import base64
import time
import requests
import jwt

...

spark = SparkSession.builder \
.appName("Spark NLP Enterprise") \
.master("local[*]") \
.config("spark.sql.legacy.allowUntypedScalaUDF","true") \
.config("spark.driver.memory","28G") \
.config("spark.driver.maxResultSize", "4096M") \
.config("spark.kryoserializer.buffer.max", "2000M")\
.config("spark.jars", "./spark-ocr-assembly-3.11.0-spark30.jar,./spark-nlp-assembly-3.4.1.jar") \
.getOrCreate()
spark
```

## Context
I'm trying to build an OCR job we can rely on.  At this point we have to watch for failures and re-run the jobs that fail.

## My Environment
* pyspark: 3.0.2
* spark-ocr: 3.11.0+spark30
* JSL_VERSION: 3.4.1
* PUBLIC_VERSION: 3.4.1
* OCR_VERSION: 3.11.0
* Java version: java-1.8.0-openjdk
* Setup and installation: pip3 install in Docker image
* Operating System and version: amazonlinux:latest docker image (2.0.20220805.0)

**Comment by maziyarpanahi** [comment]
Hi,

This repository only supports Spark NLP open-source library. For licensed products, you can either follow up in email or directly ask your question on Slack in `#ocr` channel: https://www.johnsnowlabs.com/slack-redirect/

**Comment by rvmey** [comment]
> Hi,
> 
> This repository only supports Spark NLP open-source library. For licensed products, you can either follow up in email or directly ask your question on Slack in `#ocr` channel: https://www.johnsnowlabs.com/slack-redirect/

Ok.  Thank you.
