### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling o136.load. : java.lang.NoClassDefFoundError: org/tensorflow/Tensor

### ISSUE THREAD

**Issue by dinesh1393** [JohnSnowLabs/spark-nlp#12749]
I am getting the above mentioned error while executing the below code in Aws ec2 machine using spark submit. The same code is working fine windows system. I am not sure what exactly the issue is.

spark-submit --master local[*] --jars '/home/ec2-user/jars/hadoop-aws-3.3.1.jar,/home/ec2-user/jars/aws-java-sdk-bundle-1.11.901.jar,/home/ec2-user/jars/spark-nlp_2.12-4.0.2.jar' --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version=2  /home/ec2-user/src/main/python/main/data_transformation.py  --spark_log_level 'ERROR' --temp_bucket_location 's3a://bs-bucket/flow_bucket'  --tmp_bucket_access_key 'XXXXXXXXXXXX' --tmp_bucket_secret_key 'YYYYYYYYYYYYYYY' --pipeline_name 'PIPELINE_TEXT_CSV' --src_node_number '1'  --functions_list '7'

`
from sparknlp.annotator import *
from sparknlp.base import *
from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from pyspark.sql.functions import udf, col, split,lit, concat
from pyspark.sql import functions as f
from pyspark.sql.types import StringType, ArrayType
import sparknlp
ffrom sparknlp.pretrained import PretrainedPipeline

def sentimentAnalysis(df, modelType):

	print(f"Processing Sentiment Analysis Pretrained Model {modelType}")
	print()
	sparknlp.start()
	
	#Remember that pretrained pipelines expect the input column to be named “text”.
	#analyze_sentimentdl_glove_imdb_en_3.0.0_3.0_1616544505213"
	sentiment_model = PretrainedPipeline.from_disk("/home/ec2-user/pretrained/").model    #offline

	finisher                    = Finisher().setInputCols(["sentiment"]) \
											.setOutputCols("result")

	#Include finisher in the Pipeline once testing is completed
	sentiment_pipeline          = Pipeline().setStages([sentiment_model, finisher])
	pipeline_model              = sentiment_pipeline.fit(df)
	df_sentimentResult          = pipeline_model.transform(df)
	df_sentimentResult.show(truncate=False)
`

`
2022-09-15 21:10:11,909 - DataTransformation - MainThread - ERROR - Exception in processing job: TEST_PIPELINE_TEXT_CSV_MYSQL_MONGO Exception: An error occurred while calling o136.load.
: java.lang.NoClassDefFoundError: org/tensorflow/Tensor
        at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:453)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowModel(TensorflowSerializeModel.scala:154)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowModel$(TensorflowSerializeModel.scala:123)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel$.readTensorflowModel(SentimentDLModel.scala:317)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.readTensorflow(SentimentDLModel.scala:304)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.readTensorflow$(SentimentDLModel.scala:302)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel$.readTensorflow(SentimentDLModel.scala:317)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.$anonfun$$init$$1(SentimentDLModel.scala:311)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.$anonfun$$init$$1$adapted(SentimentDLModel.scala:311)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:50)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:49)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:38)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$5(Pipeline.scala:277)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
        at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$4(Pipeline.scala:277)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$3(Pipeline.scala:274)
        at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:268)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$7(Pipeline.scala:356)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
        at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$6(Pipeline.scala:355)
        at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:355)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:349)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.tensorflow.Tensor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 58 more
Traceback (most recent call last):
  File "/home/ec2-user/src/main/python/main/data_transformation.py", line 179, in run
    transformed_df = data_clean_obj.sentimentAnalysis(extracted_df)
  File "/home/ec2-user/src/main/python/main/../trans_analytics/dataset_cleaning.py", line 291, in sentimentAnalysis
    sentiment_model = PretrainedPipeline.from_disk('/home/ec2-user/pretrained/').model
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sparknlp/pretrained/pretrained_pipeline.py", line 61, in from_disk
    return PretrainedPipeline(None, None, None, parse_embeddings, path)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/sparknlp/pretrained/pretrained_pipeline.py", line 56, in __init__
    self.model = PipelineModel.load(disk_location)
  File "/home/ec2-user/software/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/ml/util.py", line 332, in load
    return cls.read().load(path)
  File "/home/ec2-user/software/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/ml/pipeline.py", line 258, in load
    return JavaMLReader(self.cls).load(path)
  File "/home/ec2-user/software/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/ml/util.py", line 282, in load
    java_obj = self._jread.load(path)
  File "/home/ec2-user/software/spark-3.2.1-bin-hadoop3.2/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ec2-user/software/spark-3.2.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/ec2-user/software/spark-3.2.1-bin-hadoop3.2/python/lib/py4j-0.10.9.3-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o136.load.
: java.lang.NoClassDefFoundError: org/tensorflow/Tensor
        at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:453)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowModel(TensorflowSerializeModel.scala:154)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowModel$(TensorflowSerializeModel.scala:123)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel$.readTensorflowModel(SentimentDLModel.scala:317)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.readTensorflow(SentimentDLModel.scala:304)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.readTensorflow$(SentimentDLModel.scala:302)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel$.readTensorflow(SentimentDLModel.scala:317)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.$anonfun$$init$$1(SentimentDLModel.scala:311)
        at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel.$anonfun$$init$$1$adapted(SentimentDLModel.scala:311)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:50)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:49)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:38)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$5(Pipeline.scala:277)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
        at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$4(Pipeline.scala:277)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$3(Pipeline.scala:274)
        at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:268)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$7(Pipeline.scala:356)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
        at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
        at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$6(Pipeline.scala:355)
        at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:355)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:349)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.tensorflow.Tensor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 58 more

2022-09-15 21:10:11,913 - DataTransformation - MainThread - INFO - Spark Session is stopped
`

## Your Environment

* Spark NLP version `sparknlp.version()`:  spark-nlp_2.12-4.0.2
* Apache NLP version `spark.version`: spark 3.0
* Java version `java -version`: openjdk version "17.0.4.1" 2022-08-12 LTS
* Setup and installation (Pypi, Conda, Maven, etc.): pip install
* Operating System and version: linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

A couple of issues here:

- if you are using a JAR make sure it's a Fat JAR. Meaning it has everything included. I am not sure what `spark-nlp_2.12-4.0.2.jar` is, but it's not the Fat JAR we provide on S3. (the end of each release note you can see them listed: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/4.1.0)
- If you are using a Fat JAR from 4.0.2 please make sure you install `pip install spark-nlp==4.0.2` or else `sparknlp.start()` will pull whatever version spark-nlp PyPI you installed. (which may not work together)
- We don't support Java 17, it's only 8 or 11 being tested and officially supported
- You also mentioned `Linux`, if you can also be more specific about which distribution, what version, and the type of your EC2 instance, it would be more helpful.


Here is what I would do:
- remove Java 17, install Java 11 and make sure the JAVA_HOME and default Java is pointing to 11
- install `pip install --force-reinstall spark-nlp==4.0.2` to be sure 
- instead of ` --jars` pointing to those 2 JARs, let's use `--packages com.johnsnowlabs.nlp:spark-nlp_2.12:4.0.2`
- no need to include the other JAR or any jar, this is just a test
- Now instead of `spark-submit` let's use `spark-shell --master local[*] --dirver-memory 16G --packages com.johnsnowlabs.nlp:spark-nlp_2.12:4.0.2`
- Inside you can just do
```python
import sparknlp
from sparknlp.annotators import *

sparknlp.version()


nerModel = NerDLModel().pretrained
nerModel.getClasses()
```

This is just to test whether or not everything is compatible with PySpark and TensorFlow.
