### ISSUE TITLE
Issue with downloading LemmatizerModel.pretrained('lemma_antbnc')

### ISSUE THREAD

**Issue by lewisshkang** [JohnSnowLabs/spark-nlp#12880]
I am having issues with downloading '_lemma_antbnc_'. I had no issues beforehand, and suddenly I am unable to download it.

## Description

I run the following.
`lemmatizer = LemmatizerModel.pretrained()\
     .setInputCols(["cleanTokens"])\
     .setOutputCol("lemma")`

## Current Behavior

And I see the following error
`
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 3.0 failed 4 times, most recent failure: Lost task 6.3 in stage 3.0 (TID 36) (ap-main2022-w-2.europe-west2-c.c.main-cyclist-305608.internal executor 2): org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1200030671-10.154.0.31-1661648427805:blk_1073741873_1049 file=/user/root/cache_pretrained/lemma_antbnc_en_2.0.2_2.4_1556480454569/fields/lemmaDict/part-00006`

More specifically,
`
`

`
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [11], in <cell line: 2>()
      1 # Defining sentence detector 'lemma_antbnc'
----> 2 lemmatizer = LemmatizerModel.pretrained()\
      3      .setInputCols(["cleanTokens"])\
      4      .setOutputCol("lemma")

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/annotator/lemmatizer.py:241, in LemmatizerModel.pretrained(name, lang, remote_loc)
    223 """Downloads and loads a pretrained model.
    224 
    225 Parameters
   (...)
    238     The restored model
    239 """
    240 from sparknlp.pretrained import ResourceDownloader
--> 241 return ResourceDownloader.downloadModel(LemmatizerModel, name, lang, remote_loc)

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/pretrained/resource_downloader.py:43, in ResourceDownloader.downloadModel(reader, name, language, remote_loc, j_dwn)
     41 except Py4JJavaError as e:
     42     sys.stdout.write("\n" + str(e))
---> 43     raise e
     44 finally:
     45     stop_threads = True

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/pretrained/resource_downloader.py:40, in ResourceDownloader.downloadModel(reader, name, language, remote_loc, j_dwn)
     38 t1.start()
     39 try:
---> 40     j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     41 except Py4JJavaError as e:
     42     sys.stdout.write("\n" + str(e))

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/internal/__init__.py:317, in _DownloadModel.__init__(self, reader, name, language, remote_loc, validator)
    316 def __init__(self, reader, name, language, remote_loc, validator):
--> 317     super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained." + validator + ".downloadModel", reader,
    318                                          name, language, remote_loc)

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/internal/extended_java_wrapper.py:26, in ExtendedJavaWrapper.__init__(self, java_obj, *args)
     24 super(ExtendedJavaWrapper, self).__init__(java_obj)
     25 self.sc = SparkContext._active_spark_context
---> 26 self._java_obj = self.new_java_obj(java_obj, *args)
     27 self.java_obj = self._java_obj

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/internal/extended_java_wrapper.py:36, in ExtendedJavaWrapper.new_java_obj(self, java_class, *args)
     35 def new_java_obj(self, java_class, *args):
---> 36     return self._new_java_obj(java_class, *args)

File /usr/lib/spark/python/pyspark/ml/wrapper.py:66, in JavaWrapper._new_java_obj(java_class, *args)
     64     java_obj = getattr(java_obj, name)
     65 java_args = [_py2java(sc, arg) for arg in args]
---> 66 return java_obj(*java_args)

File /usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py:1304, in JavaMember.__call__(self, *args)
   1298 command = proto.CALL_COMMAND_NAME +\
   1299     self.command_header +\
   1300     args_command +\
   1301     proto.END_COMMAND_PART
   1303 answer = self.gateway_client.send_command(command)
-> 1304 return_value = get_return_value(
   1305     answer, self.gateway_client, self.target_id, self.name)
   1307 for temp_arg in temp_args:
   1308     temp_arg._detach()

File /usr/lib/spark/python/pyspark/sql/utils.py:111, in capture_sql_exception.<locals>.deco(*a, **kw)
    109 def deco(*a, **kw):
    110     try:
--> 111         return f(*a, **kw)
    112     except py4j.protocol.Py4JJavaError as e:
    113         converted = convert_exception(e.java_exception)

File /usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 3.0 failed 4 times, most recent failure: Lost task 6.3 in stage 3.0 (TID 36) (ap-main2022-w-2.europe-west2-c.c.main-cyclist-305608.internal executor 2): org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1200030671-10.154.0.31-1661648427805:blk_1073741873_1049 file=/user/root/cache_pretrained/lemma_antbnc_en_2.0.2_2.4_1556480454569/fields/lemmaDict/part-00006
	at org.apache.hadoop.hdfs.DFSInputStream.refetchLocations(DFSInputStream.java:971)
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:954)
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:933)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:656)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:849)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:921)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.apache.hadoop.io.SequenceFile$Reader.init(SequenceFile.java:1962)
	at org.apache.hadoop.io.SequenceFile$Reader.initialize(SequenceFile.java:1923)
	at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1872)
	at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1886)
	at org.apache.hadoop.mapred.SequenceFileRecordReader.<init>(SequenceFileRecordReader.java:49)
	at org.apache.hadoop.mapred.SequenceFileInputFormat.getRecordReader(SequenceFileInputFormat.java:64)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.liftedTree1$1(HadoopRDD.scala:286)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:285)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:243)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:96)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2304)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2253)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2252)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2252)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1124)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1124)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1124)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2491)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2433)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2422)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:902)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2204)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2225)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2244)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2269)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
	at com.johnsnowlabs.nlp.serialization.MapFeature.deserializeObject(Feature.scala:216)
	at com.johnsnowlabs.nlp.serialization.Feature.deserialize(Feature.scala:71)
	at com.johnsnowlabs.nlp.FeaturesReader.$anonfun$load$1(ParamsAndFeaturesReadable.scala:34)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:33)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:500)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:492)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:655)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1200030671-10.154.0.31-1661648427805:blk_1073741873_1049 file=/user/root/cache_pretrained/lemma_antbnc_en_2.0.2_2.4_1556480454569/fields/lemmaDict/part-00006
	at org.apache.hadoop.hdfs.DFSInputStream.refetchLocations(DFSInputStream.java:971)
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:954)
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:933)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:656)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:849)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:921)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.apache.hadoop.io.SequenceFile$Reader.init(SequenceFile.java:1962)
	at org.apache.hadoop.io.SequenceFile$Reader.initialize(SequenceFile.java:1923)
	at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1872)
	at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1886)
	at org.apache.hadoop.mapred.SequenceFileRecordReader.<init>(SequenceFileRecordReader.java:49)
	at org.apache.hadoop.mapred.SequenceFileInputFormat.getRecordReader(SequenceFileInputFormat.java:64)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.liftedTree1$1(HadoopRDD.scala:286)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:285)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:243)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:96)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
22/10/02 23:19:37 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 8.3 in stage 3.0 (TID 37) (ap-main2022-w-2.europe-west2-c.c.main-cyclist-305608.internal executor 3): TaskKilled (Stage cancelled)`

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.0.2
* Apache NLP version `spark.version`: 3.1.3
* Java version `java -version`: "1.8.0_332"
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Could you please answer the following questions:

- Operating System and version:
- How did you start your SparkSession?

**Comment by maziyarpanahi** [comment]
OK, this is definitely about your Operating System, file system, permissions on the `/user/root/` path. I am not sure whether you are in a cluster mode or single machine environment, but the actual error is about your file system:

```
file=/user/root/cache_pretrained/lemma_antbnc_en_2.0.2_2.4_1556480454569/fields/lemmaDict/part-00006
```

Also, the model with the exactm Spark NLP and PySpark versions works fine: https://colab.research.google.com/drive/1q_PS_IeDTVIEVabnbquk3cLXpoJgFwXy?usp=sharing
