### ISSUE TITLE
offline inference: org.apache.spark.SparkException: A master URL must be set in your configuration

### ISSUE THREAD

**Issue by mlcoop** [JohnSnowLabs/spark-nlp#13193]
I am trying to serve spark-nlp language detection model in spark cluster.
I have downloaded model and stored in our HDFS which is available for all pods.
Using sbt 
`scalaVersion: "2.12.13"`
`"com.johnsnowlabs.nlp" %% "spark-nlp" % "3.3.1"`

`import org.apache.spark.ml.PipelineModel`
`val pipe = PipelineModel.load(path="hdfs://PathToModel/language_detection_43")`

## Description

Trying to use languageDetection model for offline inference in spark cluster.
Which gives me an error: `org.apache.spark.SparkException: A master URL must be set in your configuration`
Also it works, only if I add config("spark.master", "local"), which i think is only option for local test not for production.

## Current Behavior

```scala> val pipe3 = PipelineModel.load(path="/Users/amalibayev/static_models/sparknlp/language_detection_43")
[ WARN] Another SparkContext is being constructed (or threw an exception in its constructor).  This may indicate an error, since only one SparkContext may be running in this JVM (see SPARK-2243). The other SparkContext was created at:
org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
org.apache.spark.ml.util.BaseReadWrite.sparkSession(ReadWrite.scala:76)
org.apache.spark.ml.util.BaseReadWrite.sparkSession$(ReadWrite.scala:74)
org.apache.spark.ml.util.MLReader.sparkSession(ReadWrite.scala:345)
org.apache.spark.ml.util.BaseReadWrite.sc(ReadWrite.scala:87)
org.apache.spark.ml.util.BaseReadWrite.sc$(ReadWrite.scala:87)
org.apache.spark.ml.util.MLReader.sc(ReadWrite.scala:345)
org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
org.apache.spark.ml.util.MLReadable.load(ReadWrite.scala:380)
org.apache.spark.ml.util.MLReadable.load$(ReadWrite.scala:380)
org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:332)
$line6.$read$$iw$$iw$.<init>(<console>:12)
$line6.$read$$iw$$iw$.<clinit>(<console>)
$line6.$eval$.$print$lzycompute(<console>:7)
$line6.$eval$.$print(<console>:6)
$line6.$eval.$print(<console>)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] Error initializing SparkContext.
org.apache.spark.SparkException: A master URL must be set in your configuration
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:368)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:930)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
	at org.apache.spark.ml.util.BaseReadWrite.sparkSession(ReadWrite.scala:76)
	at org.apache.spark.ml.util.BaseReadWrite.sparkSession$(ReadWrite.scala:74)
	at org.apache.spark.ml.util.MLReader.sparkSession(ReadWrite.scala:345)
	at org.apache.spark.ml.util.BaseReadWrite.sc(ReadWrite.scala:87)
	at org.apache.spark.ml.util.BaseReadWrite.sc$(ReadWrite.scala:87)
	at org.apache.spark.ml.util.MLReader.sc(ReadWrite.scala:345)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
	at org.apache.spark.ml.util.MLReadable.load(ReadWrite.scala:380)
	at org.apache.spark.ml.util.MLReadable.load$(ReadWrite.scala:380)
	at org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:332)
	at $line9.$read$$iw$$iw$.<init>(<console>:12)
	at $line9.$read$$iw$$iw$.<clinit>(<console>)
	at $line9.$eval$.$print$lzycompute(<console>:7)
	at $line9.$eval$.$print(<console>:6)
	at $line9.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:755)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1028)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:576)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:575)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:602)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:865)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:733)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:435)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:456)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:1048)
	at xsbt.ConsoleBridge.run(ConsoleBridge.scala:75)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:209)
	at sbt.Console.console0$1(Console.scala:64)
	at sbt.Console.$anonfun$apply$5(Console.scala:73)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.TrapExit$App.run(TrapExit.scala:258)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Uncaught exception in thread run-main-0
java.lang.NullPointerException
	at org.apache.spark.SparkContext.postApplicationEnd(SparkContext.scala:2416)
	at org.apache.spark.SparkContext.$anonfun$stop$2(SparkContext.scala:1931)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1340)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:1931)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:585)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:930)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
	at org.apache.spark.ml.util.BaseReadWrite.sparkSession(ReadWrite.scala:76)
	at org.apache.spark.ml.util.BaseReadWrite.sparkSession$(ReadWrite.scala:74)
	at org.apache.spark.ml.util.MLReader.sparkSession(ReadWrite.scala:345)
	at org.apache.spark.ml.util.BaseReadWrite.sc(ReadWrite.scala:87)
	at org.apache.spark.ml.util.BaseReadWrite.sc$(ReadWrite.scala:87)
	at org.apache.spark.ml.util.MLReader.sc(ReadWrite.scala:345)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
	at org.apache.spark.ml.util.MLReadable.load(ReadWrite.scala:380)
	at org.apache.spark.ml.util.MLReadable.load$(ReadWrite.scala:380)
	at org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:332)
	at $line9.$read$$iw$$iw$.<init>(<console>:12)
	at $line9.$read$$iw$$iw$.<clinit>(<console>)
	at $line9.$eval$.$print$lzycompute(<console>:7)
	at $line9.$eval$.$print(<console>:6)
	at $line9.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:755)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1028)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:576)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:575)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:602)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:865)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:733)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:435)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:456)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:1048)
	at xsbt.ConsoleBridge.run(ConsoleBridge.scala:75)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:209)
	at sbt.Console.console0$1(Console.scala:64)
	at sbt.Console.$anonfun$apply$5(Console.scala:73)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:17)
	at sbt.TrapExit$App.run(TrapExit.scala:258)
	at java.lang.Thread.run(Thread.java:748)
org.apache.spark.SparkException: A master URL must be set in your configuration
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:368)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
  at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:930)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
  at org.apache.spark.ml.util.BaseReadWrite.sparkSession(ReadWrite.scala:76)
  at org.apache.spark.ml.util.BaseReadWrite.sparkSession$(ReadWrite.scala:74)
  at org.apache.spark.ml.util.MLReader.sparkSession(ReadWrite.scala:345)
  at org.apache.spark.ml.util.BaseReadWrite.sc(ReadWrite.scala:87)
  at org.apache.spark.ml.util.BaseReadWrite.sc$(ReadWrite.scala:87)
  at org.apache.spark.ml.util.MLReader.sc(ReadWrite.scala:345)
  at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
  at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
  at org.apache.spark.ml.util.MLReadable.load(ReadWrite.scala:380)
  at org.apache.spark.ml.util.MLReadable.load$(ReadWrite.scala:380)
  at org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:332)
  ... 31 elided
```
## Your Environment

* Spark NLP version `2.4.6.0`:
* Apache NLP version `3.3.1`:
* Java version `1.8`:
* Setup and installation (Pypi, Conda, Maven, etc.): sbt
* Operating System and version:
* Link to your project (if any):
* spark-configs: `spark-configs {
      "spark.dynamicAllocation.enabled" = "true"
      "spark.dynamicAllocation.minExecutors" = "0"
      "spark.dynamicAllocation.maxExecutors" = "18"
      "spark.dynamicAllocation.initialExecutors" = "18"
      "spark.dynamicAllocation.executorIdleTimeout" = "1800s"
      "spark.dynamicAllocation.cachedExecutorIdleTimeout" = "1800s"
      "spark.dynamicAllocation.schedulerBacklogTimeout" = "300s"
      "spark.sql.streaming.minBatchesToRetain" = "20"
      "spark.sql.selfJoinAutoResolveAmbiguity" = "false"
    }`

**Comment by maziyarpanahi** [comment]
Hi,

There are some mismatches in the versions you mentioned. Here is a simple SBT project that should guide you regarding the Apache Spark version, Spark NLP version, and Scala version: https://github.com/maziyarpanahi/spark-nlp-starter

I will also advice you not to load `language_detection_43` manually like that. That is an old and deprecated pipeline with newer releases. I would suggest first looking at here which are the latest pipelines for language detection: https://nlp.johnsnowlabs.com/models?task=Language+Detection&type=pipeline

Those pipelines work without any issue if you have set up your project correctly as you can see here the tests pass (it may not be only Spark NLP related issue, it is complaining about master URL which has nothing to do with Spark NLP, but I hope this starter project helps): https://github.com/maziyarpanahi/spark-nlp-starter/blob/683914d8d925f9eba46aedb483d9808a3d58696d/src/main/scala/Main.scala#L99

**Comment by mlcoop** [comment]
@maziyarpanahi thank you for quick response. I made an error in my description.
here my versions:
`Spark Vesrion: 2.4.6`
`Spark NLP: 3.3.1`

examples that you gave are for local cases, right ? Seems like not passing `config("master", "local")` wont allow model to be downloaded. 
Or am i missing something ?

**Comment by maziyarpanahi** [comment]
The Spark NLP 4.x has dropped the support for Apache Spark 2.x so unless you can update the Apache Spark to 3.x we cannot use that with those pipelines.

It seems you already have something that works with Spark NLP 3.x and Apache Spark 2.4.x. The SparkSession requires `master`, it's not just Spark NLP, regardless of whether or not this is local[*] or `yarn` or `k8` or even another remote Spark, you still need the `master` in your config. 

Is there a reason you don't have a `master` set as a config? (I use an application.conf to have `local` for dev and `yarn` or others for cluster deployment)

**Comment by mlcoop** [comment]
@maziyarpanahi while trying to workaround I have faced another problem. 
Error: `Task not serializable: java.io.NotSerializableException`

`object LanguageDetection {

  val pipeline = PipelineModel.load("PathToModel/detect_language_43_xx_2.7.0_2.4_1607185195681")
   def batchDetection(data: sql.DataFrame):sql.DataFrame = {
      #do something
   }
}
`

**Comment by maziyarpanahi** [comment]
Could you please paste your entire error stack and the exact code that results that? (this is not a Spark NLP error. probably you have an object/class which is not serializable, like this `object LanguageDetection`)

**Comment by mlcoop** [comment]
@maziyarpanahi resolved.
