### ISSUE TITLE
loading pre-trained model is downloading the model on the driver and reading it from the executor

### ISSUE THREAD

**Issue by Hmr-ramzi** [JohnSnowLabs/spark-nlp#1327]
## Description

We have a sparknlp instance that works on sparkcontext that is triggered on kubernetes cluster. Whenever, we load the model using (for example: (BertEmbeddings.pretrained('bert_base_cased', 'en').setInputCols(["sentence",'token']).setOutputCol("bert").setCaseSensitive(False))) the model gets downloaded on the driver pod and the job fails as the executor (does not find the file) is expexcting the file to also be there.

## Expected Behavior
The executor should reach to the file

## Current Behavior
Executor complains about the file as it is not found

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
The downloading and loading models/pipelines depend on two setups:
- Local: where there is only 1 machine as both Driver/Executor which downloads on local fileSystem and loads it from the same path
- Cluster: In any setup that there is more than 1 machine (Driver and executors), Apache Spark requires a shared fileSystem (HDFS, S3, DBFS, etc.), which will download on that shared fileSystem and loads it from there. 
You have set up a cluster on KB but there is either no shared/distributed fileSystem or it's not correctly set up with Apache Spark. If you are going to use Apache Spark as a cluster you need a fileSystem that is accessible to all the nodes in the Apache Spark cluster (Driver/Executors). Spark NLP uses Apache Spark's underlying fileSystem.

**Comment by maziyarpanahi** [comment]
Just an FYI, a good architecture:

![image](https://user-images.githubusercontent.com/5762953/102603294-def19580-4122-11eb-96ff-b8da1b714d45.png)

If the shared/distributed storage is implemented and configured correctly on Apache Spark, Spark NLP automatically uses that without any code change.

**Comment by Hmr-ramzi** [comment]
Thanks! Very much appreciated!

**Comment by dvvj** [comment]
Hi @maziyarpanahi ,

I experienced similar issue when trying to load pretrained language detection model into a Spark cluster. The cluster is on AWS, and I put the pretrained model (I'm using **detect_language_43** model -- downloaded then **extracted** then saved) on S3:

Following the discussions in the thread, I wrote the code to load the model, which looks like:
```
        String modelPath = "s3a://..."; // s3 path where the **extracted** detect_language_43 is located
        Broadcast<PretrainedPipeline> brPipeline = sc.broadcast(PretrainedPipeline.fromDisk(modelPath));

        JavaRDD<String> tmp = textToDetectLang
            .map(text-> {
                val resultMap = brPipeline.value().annotate(text);
                ...
            });
        System.out.println("tmp #: " + tmp.count());
```

but it failed with the following execptions:
```
2021-04-19 08:34:55.587625: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARN  o.a.spark.scheduler.TaskSetManager - Lost task 15.0 in stage 13.0 (TID 848) (172.16.1.138 executor 5): java.io.IOException: com.esotericsoftware.kryo.KryoException: Error constructing instance of class: com.johnsnowlabs.nlp.annotators.ld.dl.LanguageDetectorDL
Serialization trace:
stages (org.apache.spark.ml.PipelineModel)
model (com.johnsnowlabs.nlp.pretrained.PretrainedPipeline)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1412)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:226)
	at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:103)
	at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
	at com.monocl.spark.sources.publications.DetectNonEnglishContent.lambda$process$ece8bdd2$1(DetectNonEnglishContent.java:102)
	at org.apache.spark.api.java.JavaPairRDD$.$anonfun$toScalaFunction$1(JavaPairRDD.scala:1070)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.esotericsoftware.kryo.KryoException: Error constructing instance of class: com.johnsnowlabs.nlp.annotators.ld.dl.LanguageDetectorDL
Serialization trace:
stages (org.apache.spark.ml.PipelineModel)
model (com.johnsnowlabs.nlp.pretrained.PretrainedPipeline)
	at com.twitter.chill.Instantiators$$anon$1.newInstance(KryoBase.scala:142)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1139)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:562)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:538)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:391)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:302)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:296)
	at org.apache.spark.broadcast.TorrentBroadcast$.$anonfun$unBlockifyObject$4(TorrentBroadcast.scala:336)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:338)
	at org.apache.spark.broadcast.TorrentBroadcast.$anonfun$readBroadcastBlock$4(TorrentBroadcast.scala:257)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.broadcast.TorrentBroadcast.$anonfun$readBroadcastBlock$2(TorrentBroadcast.scala:231)
	at org.apache.spark.util.KeyLock.withLock(KeyLock.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast.$anonfun$readBroadcastBlock$1(TorrentBroadcast.scala:226)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1405)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.twitter.chill.Instantiators$.$anonfun$normalJava$1(KryoBase.scala:174)
	at com.twitter.chill.Instantiators$$anon$1.newInstance(KryoBase.scala:139)
	... 45 more
Caused by: java.lang.IllegalStateException: SparkSession should only be created and accessed on the driver.
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$assertOnDriver(SparkSession.scala:1123)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:916)
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.$anonfun$getActiveSparkSession$1(ResourceHelper.scala:33)
	at scala.Option.getOrElse(Option.scala:189)
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.getActiveSparkSession(ResourceHelper.scala:34)
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.spark$lzycompute(ResourceHelper.scala:37)
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.spark(ResourceHelper.scala:37)
	at com.johnsnowlabs.nlp.serialization.Feature.<init>(Feature.scala:20)
	at com.johnsnowlabs.nlp.serialization.MapFeature.<init>(Feature.scala:145)
	at com.johnsnowlabs.nlp.annotators.ld.dl.LanguageDetectorDL.<init>(LanguageDetectorDL.scala:50)
	at com.johnsnowlabs.nlp.annotators.ld.dl.LanguageDetectorDL.<init>(LanguageDetectorDL.scala:44)
	... 51 more
```

I also tried to load the model in Spark `.map` functions (by which I suppose the slave machines will try to create its own copy of pretrained piplelines, but this fails with another exception:

```
WARN  o.a.spark.scheduler.TaskSetManager - Lost task 86.0 in stage 13.0 (TID 919) (172.16.1.144 executor 7): java.lang.IllegalStateException: SparkContext should only be created and accessed on the driver.
	at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$assertOnDriver(SparkContext.scala:2661)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:89)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:127)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2700)
	at org.apache.spark.ml.MLEvents.listenerBus(events.scala:116)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:159)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
	at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$6(Pipeline.scala:355)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:355)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:349)
	at org.apache.spark.ml.util.MLReadable.load(ReadWrite.scala:355)
	at org.apache.spark.ml.util.MLReadable.load$(ReadWrite.scala:355)
	at org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:337)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.<init>(PretrainedPipeline.scala:28)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline$.fromDisk(PretrainedPipeline.scala:48)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline$.fromDisk(PretrainedPipeline.scala:51)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.fromDisk(PretrainedPipeline.scala)
	at com.monocl.spark.utility.lang.LangDetectorHelper.getSparkNlpDetector(LangDetectorHelper.java:24)
	at com.monocl.spark.utility.lang.LangDetectorHelper.getLangDetectorsFromDisk(LangDetectorHelper.java:45)
	at com.monocl.spark.sources.publications.DetectNonEnglishContent.lambda$process$1ae37b5b$1(DetectNonEnglishContent.java:98)
	at org.apache.spark.api.java.JavaPairRDD$.$anonfun$toScalaFunction$1(JavaPairRDD.scala:1070)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.$anonfun$getOrCompute$1(RDD.scala:386)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Just wonder what I'm missing here, and can you perhaps elaborate a little bit on your 2nd bullet point, i.e. how to load models on `Cluster`?

Thanks in advance!

**Comment by maziyarpanahi** [comment]
Hi @dvvj 
This may be easier if I had all the required info (Spark version, Spark NLP version, since you are loading offline this means you have downloaded a model/pipeline so if there is a newer version of that which is compatible with a newer version of Spark NLP you don't have it and instead of loading an old model which may not be compatible, or vice versa, you are downloading something very new for an older version of Spark NLP)

That being said, `detect_language_43` is a pipeline: https://nlp.johnsnowlabs.com/2020/12/05/detect_language_43_xx.html

Using it online:

```scala
import com.johnsnowlabs.nlp.pretrained.PretrainedPipeline

val pipeline = new PretrainedPipeline("detect_language_43", lang = "xx")

pipeline.annotate("French author who helped pioneer the science-fiction genre.")
```

Using it offline, after downloading this pipeline from Models Hub, extracting it, you must have it on a FileSystem that is distributed and known to Apache Spark. (like HDFS or DBFS, something that all the executors can access)

```scala
val detectLangPipeline = PipelineModel.load("hdfs:///tmp/detect_language_43_xx_2.7.0_2.4_1607185195681/")
// To use the loaded Pipeline for prediction
detectLangPipeline.transform(predictionDF)
```

I am not sure why you are using broadcast etc. We are a native Spark ML library, so if you save the Spark ML model/pipeline on the distributed file system (or even locally) and you can simply load it back, you can do exactly the same with any Model/Pipeline in Spark NLP.

I do recommend first using the online version, making sure you have everything set up and they work fine (no mismatch of versions, etc.). Then you can use them offline. 

[IMPORTANT] If the issue persists, please create a **new issue** with a **full template**, all the information is required to reproduce.

**Comment by dvvj** [comment]
Hi @maziyarpanahi, many thanks for your quick response! I'll try again following your suggestions. And if it still doesn't working, will raise new issues using a full template!

**Comment by dvvj** [comment]
Hi @maziyarpanahi , just a quick follow-up:

The offline approach you suggested works well (though a bit tricky extracting the results):
```
           Dataset<Row> textRows = ... // load data
           PretrainedPipeline pipeline = PretrainedPipeline.fromDisk("s3a://...")
           Dataset<Row> detectResult = pipeline.annotate(textRows, textColumn);
           ...
```

On the other hand, the online approach doesn't seem to work, and I got exceptions which looks like:
```
java.io.FileNotFoundException: File file:/home/ec2-user/cache_pretrained/detect_language_43_xx_2.7.0_2.4_1607185195681/metadata/part-00000 does not exist
```
So I guess unless there's a way to configure the `cache_pretrained` folder to hdfs/s3, it would not work in a cluster environment?

Thanks again for your help -- really saved my day!

**Comment by maziyarpanahi** [comment]
I am sorry I have no idea where you are and what you are using. As I mentioned before, if you need any help you need to create a new issue, complete the template, all the steps to reproduce this issue, and report this behavior.
