### ISSUE TITLE
entityruler issue: char " not found

### ISSUE THREAD

**Issue by a-nematihayati** [JohnSnowLabs/spark-nlp#13317]
Trying to use entityruler with all three types csv, json and jsonl lead to this error.

## Description

Just like the notebooks, I expect to pass the json/csv/jsonl pattern file to the ruler at the end of the pipeline.

## Expected Behavior

Complete the pipeline and generate the entity column along with the chunk values

## Current Behavior

 rkException: Failed to execute user defined function (HasSimpleAnnotate$$Lambda$3534/0x000000084164a040: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.errors.QueryExecutionErrors$.failedExecuteUserDefinedFunctionError(QueryExecutionErrors.scala:190)
	at org.apache.spark.sql.errors.QueryExecutionErrors.failedExecuteUserDefinedFunctionError(QueryExecutionErrors.scala)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.project_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException: Char ” not found on alphabet. Please check alphabet
## Possible Solution

issue with pattern matching file .setPatternsResource or higher level EntityRulerApproach()

## Steps to Reproduce

1. build the python code pipeline as outlined in the notebook
2. use spark-submit to initiate the python runner
3.
4.

## Context

Unable to use entityruler module

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.2.4
* Apache NLP version `spark.version`: 3.3.1
* Java version `java -version`: 11.0.17
* Setup and installation (Pypi, Conda, Maven, etc.): pip virtual env, pypi
* Operating System and version: Ubuntu 20.04.3
* Link to your project (if any): NA

**Comment by maziyarpanahi** [comment]
You have all the examples here: https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/jupyter/training/english/entity-ruler

If you still have an issue, you need to complete this template with all the required sections or it's not possible to reproduce this on our side.

**Comment by a-nematihayati** [comment]
@maziyarpanahi Thanks for the quick response! I have actually tested both those codes you mentioned as well as the older versions which have tokens as part of the pipeline. All lead to this issue. 
The only difference I have is that it's not a notebook, but a python class and distributed run on a standalone spark cluster. 

Hope this helps.

Even if you could hint to what is potentially going run given the char " not found, that would be really helpful..

**Comment by maziyarpanahi** [comment]
Thanks for filling in the template. Could you please also provide the code/pipeline that results in this error? (a simple end-to-end example would be enough to reproduce this error)

**Comment by a-nematihayati** [comment]
This was resolved. The issue was not relevant to the source code. After passing the document to the documentnorm method, it all worked out. 
Now I have a question/suggestion: Would it be possible to use entity-ruler output for generating customized conll dataset? I see you have the nerconverter for IOB to IOB2, but not IOB2 to IOB.

**Comment by maziyarpanahi** [comment]
> This was resolved. The issue was not relevant to the source code. After passing the document to the documentnorm method, it all worked out.
> Now I have a question/suggestion: Would it be possible to use entity-ruler output for generating customized conll dataset for training? I see you have the nerconverter for IOB to IOB2, but not IOB2 to IOB.

Hi,

This is an interesting question (or feature request), could you please open a new issue so I can assign it to someone? This way we know better if it is already possible or we can add that feature.
