### ISSUE TITLE
SparkNLP does not work in Azure Synapse

### ISSUE THREAD

**Issue by xuezhizeng** [JohnSnowLabs/spark-nlp#13373]
## Description

I am trying to install and run a sample code for SparkNLP in Azure Synapse.

I am able to succesfully install SparkNLP 4.2.7 in Azure Synapse (its spark version is 3.2.2.5.1-75622951).

Then, I started sparkNLP manually as the code shown below, the start is succesful (as I can run spark.version, sparknlp.version(), and see spark UI where it tells me the master is Yarn).  

I downloaded a pretrained model manually and saved it in Azure data lake storage Gen2, as you can see its ABFSS Path below. I want to load this model by using `PipelineModel.load("abfss://<mypath>/recognize_entities_dl_en_3.0.0_3.0_1616473647254/"),` however it returns me the ` java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.DocumentAssembler` error.

![photo1](https://user-images.githubusercontent.com/35292840/213596296-7a30ec59-64f0-4936-8dcc-c76b0b18f2d6.PNG)

## Current Behavior

The detailed error messages are:

**Py4JJavaError: An error occurred while calling o1793.load.
: java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.DocumentAssembler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:216)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstanceReader(ReadWrite.scala:630)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$4(Pipeline.scala:276)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$3(Pipeline.scala:274)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:268)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$7(Pipeline.scala:356)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:160)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:155)
	at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$6(Pipeline.scala:355)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:355)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)**

## Steps to Reproduce

1. `from pyspark.sql import SparkSession
import sparknlp
from sparknlp.pretrained import PretrainedPipeline

spark = SparkSession.builder \
    .appName("Spark NLP")\
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.jars.packages","abfss://<mypath>/spark-nlp-assembly-4.2.7.jar")\
    .getOrCreate()`

2.  `from sparknlp.pretrained import PipelineModel
model = PipelineModel.load("abfss://<mypath>/recognize_entities_dl_en_3.0.0_3.0_1616473647254/")`

## Context

Looks like the config of  .config("spark.jars.packages","abfss://<mypath>/spark-nlp-assembly-4.2.7.jar") does not take effect in SparkSession, and hence SparkSession is not aware where this fat jar package is.

I also tried the following way to start SparkNLP, but got the same error when running `PipelineModel.load("abfss://<mypath>/recognize_entities_dl_en_3.0.0_3.0_1616473647254/")`
1. use default way to start
`spark = sparknlp.start()`

2.  use customized way to start by specifying 'spark.jars.packages' by 'com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.7'
`spark = SparkSession.builder \
    .appName("Spark NLP")\
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.7")\
    .getOrCreate()`

Instead of loading an pre-downloaded pre-trained model, if I use the below way to automatically download a model and load it, 

`from sparknlp.pretrained import PretrainedPipeline
model = PretrainedPipeline("recognize_entities_dl","en")`

then, I got the error: `TypeError: 'JavaPackage' object is not callable`

Can anyone point me how we can make SparkNLP work out in Azure Synapse environment?

Thanks.

## Your Environment

* Spark NLP version `sparknlp.version()`:    4.2.7
* Apache NLP version `spark.version`:   3.2.2.5.1-75622951
* Java version `java -version`:       openjdk version "11.0.17" 2022-10-18

**Comment by maziyarpanahi** [comment]
Hi @xuezhizeng 

The `TypeError: 'JavaPackage' object is not callable` error means the SparkSession does not have the JAR (Fat, Maven) in the current session. When you do `pip install spark-nlp` you only install the Python APIs, the actual library/logic is in the Maven package (or the Fat JAR)

Same as any Cloud provided service or managed Spark service (Databricks, EMR, Glue, etc.) there must be a way/place for users to add external/third-party Maven packages. (I say Maven package instead of Fat JAR because maybe the `abfss` is not supported in Spark Session)

This step must happen before SparkSession is created or else it will ignore `spark.jars` and `spark.jars.packages` when the session is already created. That's said, usually when you are in these services the SparkSession is either created or you add some configs and then it creates it for you. (meaning, `SparkSession.builder` won't really work, it will just created one for you based on the default parameters)


The steps should be pretty similar to Databricks: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

- have spark-nlp PyPI installed on the cluster (all the machine, so you add that python package in the settings)
- have Maven package of Spark NLP `com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.7` as external library to load during SparkSession creation

I see some tutorials of how to add external libs (from all languages) into the pool of resources and then use that inside for SparkSession:

- https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-manage-pool-packages
- https://learn.microsoft.com/en-us/answers/questions/1084703/adding-external-spark-packages-jars-to-spark-pool

Unfortunately, I never used `Azure Synapse` myself
