### ISSUE TITLE
Verify word embeddings under Windows OS

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#134]
## Description

```
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.pretrained.PythonResourceDownloader.downloadModel.
: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/Saif Addin/embeddings9ef4024dc3f6_idx6034142539355212329
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.apache.spark.SparkContext.addFile(SparkContext.scala:1525)
	at com.johnsnowlabs.nlp.embeddings.WordEmbeddingsClusterHelper$.copyIndexToCluster(ApproachWithWordEmbeddings.scala:128)
	at com.johnsnowlabs.nlp.HasWordEmbeddings$class.deserializeEmbeddings(HasWordEmbeddings.scala:65)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel.deserializeEmbeddings(NerCrfModel.scala:18)
	at com.johnsnowlabs.nlp.embeddings.EmbeddingsReadable$class.onRead(EmbeddingsReadable.scala:8)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel$.onRead(NerCrfModel.scala:78)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel$.onRead(NerCrfModel.scala:78)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:29)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:29)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:17)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:6)
	at com.johnsnowlabs.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:75)
	at com.johnsnowlabs.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:119)
	at com.johnsnowlabs.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by saifjsl** [comment]
Fixed in https://github.com/JohnSnowLabs/spark-nlp/pull/133
