### ISSUE TITLE
Couldn’t load spark nlp NER trained model on colab 

### ISSUE THREAD

**Issue by roy-souvik21** [JohnSnowLabs/spark-nlp#13516]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

I  am trying to do inference with Spark NLP NER model trained on the data on google colab. The nerDLModel.load couldn’t find the files it is looking for tensorflow files in this path.

```
new_path = "/content/NER_BERT_20221117"

loaded_ner_model = NerDLModel.load(new_path)\
            .setInputCols(["sentence", "token", "embeddings"])\
            .setOutputCol("ner")

converter = NerConverter()\
            .setInputCols(["document", "token", "ner"])\
            .setOutputCol("ner_span")

ner_prediction_pipeline = Pipeline(
    stages = [
        document,
        sentence,
        token,
        bert_embeddings,
        loaded_ner_model,
        converter
        ])
```

The file structure looks like this in colab

├─NER_BERT_20221117/
│ ├─tensorflow/
│ │ ├─variables.data-00000-of-00001
│ │ ├─variables.index
│ │ └─saved_model.pb
│ ├─metadata/
│ │ ├─part-00000
│ │ └─_SUCCESS
│ ├─fields/
│ │ └─datasetParams/
│ │   ├─part-00000
│ │   ├─part-00003
│ │   ├─_SUCCESS
│ │   ├─part-00002
│ │   └─part-00001
│ └─tensorflow.zip

### Current Behavior

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
[<ipython-input-17-d48aaba0abf3>](https://localhost:8080/#) in <module>
      7 #            .setOutputCol("ner")
      8 
----> 9 loaded_ner_model = NerDLModel.load(new_path)\
     10             .setInputCols(["sentence", "token", "embeddings"])\
     11             .setOutputCol("ner")

4 frames
[/usr/local/lib/python3.8/dist-packages/py4j/protocol.py](https://localhost:8080/#) in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o108.load.
: java.io.FileNotFoundException: /tmp/8ba96574c742_nerdl6067169658058207298/tensorflow (Is a directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1305)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at com.johnsnowlabs.util.ZipArchiveUtil$.unzip(ZipArchiveUtil.scala:112)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:464)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowModel(TensorflowSerializeModel.scala:154)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowModel$(TensorflowSerializeModel.scala:123)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowModel(NerDLModel.scala:401)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph.readNerGraph(NerDLModel.scala:369)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph.readNerGraph$(NerDLModel.scala:368)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readNerGraph(NerDLModel.scala:401)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph.$anonfun$$init$$1(NerDLModel.scala:376)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph.$anonfun$$init$$1$adapted(NerDLModel.scala:376)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:50)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:49)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:49)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:61)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:61)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:38)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Expected Behavior

The model should be able to load and no file missing issue

### Steps To Reproduce

new_path = "/content/NER_BERT_20221117"

loaded_ner_model = NerDLModel.load(new_path)\
            .setInputCols(["sentence", "token", "embeddings"])\
            .setOutputCol("ner")

converter = NerConverter()\
            .setInputCols(["document", "token", "ner"])\
            .setOutputCol("ner_span")

ner_prediction_pipeline = Pipeline(
    stages = [
        document,
        sentence,
        token,
        bert_embeddings,
        loaded_ner_model,
        converter
        ])

### Spark NLP version and Apache Spark

Spark NLP version:  4.0.2
Apache Spark version:  3.3.0

### Java Version

openjdk version "11.0.17" 2022-10-18 OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04) OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode)

### Setup and installation

!pip install -q pyspark==3.3.0  #spark-nlp==4.0.2

### Operating System and Version

google colab

**Comment by maziyarpanahi** [comment]
Hi,

Since we don't have access to that model, I am not sure how we are going to reproduce this. But I have some questions/suggestions:

- Please install `spark-nlp==4.3.0` and test this again
- If it is still failing, please provide information as how you are starting Spark NLP / Spark Session
- On which version of Spark NLP that model was trained? 

For now these would be enough to hopefully resolve this issue. Just in case, you can easily download/load any NER model in Colab: https://colab.research.google.com/drive/1_S78pbgEpH9jYUzUJfYwmK9_3OFt_cUl?usp=sharing

So this must be either a version of spark-nlp which you will update and test again, or the way you are starting SparkSession (sparknlp.start()), or something with that model and where it is coming from.
