### ISSUE TITLE
 requirement failed: The label column MultiClassifierDLApproach_1faf05ddfa95__labelColumn type is StringType and it's not compatible 

### ISSUE THREAD

**Issue by rajamed** [JohnSnowLabs/spark-nlp#13544]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Hello there, am training multilabel classifier using MultiClassifierDL, When I loaded my custom dataset it throws me the following error  @maziyarpanahi 

 requirement failed: The label column MultiClassifierDLApproach_1faf05ddfa95__labelColumn type is StringType and it's not compatible 

### What are you working on?

Am running  on my custom dataset with  universal sentence encoder as the initial pipeline.  

### Current Behavior

 requirement failed: The label column MultiClassifierDLApproach_1faf05ddfa95__labelColumn type is StringType and it's not compatible 

### Expected Behavior

When I tried to train a model with my custom dataset I get this error 

### Steps To Reproduce

https://colab.research.google.com/drive/1Whg0vGeqfh2yIkb2wtoS9gObJj47S4Ai?usp=sharing

### Spark NLP version and Apache Spark

4.3.0

**Comment by maziyarpanahi** [comment]
Just to be sure we are on the same page:

- ClassifierDLApproach : for multi-class text classification where you have 1 class/label per row. 
- MultiClassifierDLApproach : for multi-label text classification where you have multiple class/label per row. (requires list of labels)

To use `MultiClassifierDLApproach` you need to have a list of labels, you can just see the provided example dataset:

![image](https://user-images.githubusercontent.com/5762953/220067934-17a58a60-6e9c-4eb2-956a-d67ccb3caac1.png)
 
If you only have 1 label, you need ClassifierDLApproach for multi-class classification. You just need to make your input DataFrame the same schema depending on the annotator you need and you hve many examples here: https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/open-source-nlp/05.0.Text_Classification_with_ClassifierDL.ipynb

**Comment by rajamed** [comment]
@maziyarpa
![maziyar](https://user-images.githubusercontent.com/117824260/220122548-859903c0-d8ab-47bc-af95-094ac430da22.png)
nahi thanks for the reply, i have changed the dataset  into the format as you said , now am getting this error 
![mazi](https://user-images.githubusercontent.com/117824260/220122583-e3b762d5-a12f-4d45-a6d9-f99901d97b61.png)


```
Py4JJavaError                             Traceback (most recent call last)
[<ipython-input-114-b9b7d99b761e>](https://localhost:8080/#) in <module>
----> 1 pipelineModel = pipeline.fit(df2)

7 frames
[/usr/local/lib/python3.8/dist-packages/py4j/protocol.py](https://localhost:8080/#) in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o809.fit.
: java.lang.UnsupportedOperationException: empty.maxBy
	at scala.collection.TraversableOnce.maxBy(TraversableOnce.scala:282)
	at scala.collection.TraversableOnce.maxBy$(TraversableOnce.scala:280)
	at scala.collection.AbstractTraversable.maxBy(Traversable.scala:108)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ClassifierMetrics.aggregatedMetrics(ClassifierMetrics.scala:51)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ClassifierMetrics.aggregatedMetrics$(ClassifierMetrics.scala:35)
	at com.johnsnowlabs.ml.tensorflow.TensorflowMultiClassifier.aggregatedMetrics(TensorflowMultiClassifier.scala:28)
	at com.johnsnowlabs.ml.tensorflow.TensorflowMultiClassifier.measure(TensorflowMultiClassifier.scala:325)
	at com.johnsnowlabs.ml.tensorflow.TensorflowMultiClassifier.$anonfun$train$2(TensorflowMultiClassifier.scala:164)
	at com.johnsnowlabs.ml.tensorflow.TensorflowMultiClassifier.$anonfun$train$2$adapted(TensorflowMultiClassifier.scala:99)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at com.johnsnowlabs.ml.tensorflow.TensorflowMultiClassifier.train(TensorflowMultiClassifier.scala:99)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.MultiClassifierDLApproach.train(MultiClassifierDLApproach.scala:318)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.MultiClassifierDLApproach.train(MultiClassifierDLApproach.scala:191)
	at com.johnsnowlabs.nlp.AnnotatorApproach._fit(AnnotatorApproach.scala:69)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by maziyarpanahi** [comment]
Hi,
It seems you have empty list in your labels. Could you please filter empty `labels` column. I would say the best way to debug this is:
- First filter rows that have empty column `labels` (where the array length is 0) (ex: https://sparkbyexamples.com/spark/spark-get-size-length-of-array-map-column/)
- Use `.show()` to confirm those rows indeed have `labels` as an empty List
- Then do the opposite and filter all those rows out before going for `.fit()` / `.transform()`

**Comment by rajamed** [comment]
@maziyarpanahi hello mazi, thanks for the reply, above error has been resolved now am getting this error, 

IllegalArgumentException: requirement failed: The total unique number of classes must be more than 2 and less than 100. Currently is 4940 

Please help me out, why this is happening. @maziyarpanahi

**Comment by maziyarpanahi** [comment]
Yes, our classifiers only support up to 100 classes/labels, you have  4900+! That's way too many.
I would suggest either reducing the labels to 100 or using HuggingFace XXXForSequenceClassificarion (BERT, RoBERTa, etc.) and then you can bring that fine-tuned model into Spark NLP.

**Comment by maziyarpanahi** [comment]
The error is very clear, `classes must be more than 2 and less than 100. Currently is 4940`. The column `labels` for some reason has `4940` unique items, I would start from there and see where in your conversion of the schema something went wrong. (that part of the code, explodes the column, gets all the distinct labels, counts them and prepares them)
