### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.ResourceDownloader - pyspark

### ISSUE THREAD

**Issue by Swatisoni** [JohnSnowLabs/spark-nlp#13577]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Please help.

### What are you working on?

- databricks 10.3 ML machine cluster.
- spark 3.2.1
- spark-nlp - 2.7.5

Generating embeddings using pretrained model.

### Current Behavior

Erroring to retrieve the model, failing at pulling the resource's size[ I guess].
Please help.

### Expected Behavior

It should download the pre-trained model.

### Steps To Reproduce

```
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline
documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")
useEmbeddings = UniversalSentenceEncoder.pretrained() \
    .setInputCols(["document"]) \
    .setOutputCol("sentence_embeddings")

```
tfhub_use download started this may take some time.

### Spark NLP version and Apache Spark

- databricks, 
- spark - 3.2.1
- spark-nlp - 2.7.5

### Java Version

openjdk version "1.8.0_345" OpenJDK Runtime Environment (Zulu 8.64.0.19-CA-linux64) (build 1.8.0_345-b01) OpenJDK 64-Bit Server VM (Zulu 8.64.0.19-CA-linux64) (build 25.345-b01, mixed mode)

### Java Home Directory

/usr/bin/java

### Setup and installation

Maven - com.johnsnowlabs.nlp:spark-nlp-gpu_2.12:3.0.1, spark-nlp - latest.

### Additional Information

Stack Trace -

```
odule>
      6     .setInputCol("text") \
      7     .setOutputCol("document")
----> 8 useEmbeddings = UniversalSentenceEncoder.pretrained() \
      9     .setInputCols(["document"]) \
     10     .setOutputCol("sentence_embeddings")

/local_disk0/spark-d3954922-3d42-4eee-9260-0ad0fb28833b/userFiles-16ad91bb-ea01-440e-9eef-65b6e04925ce/addedFile7121790753955113154spark_nlp_2_7_5-fd923.jar/sparknlp/annotator.py in pretrained(name, lang, remote_loc)
   2188     def pretrained(name="tfhub_use", lang="en", remote_loc=None):
   2189         from sparknlp.pretrained import ResourceDownloader
-> 2190         return ResourceDownloader.downloadModel(UniversalSentenceEncoder, name, lang, remote_loc)
   2191 
   2192 

/local_disk0/spark-d3954922-3d42-4eee-9260-0ad0fb28833b/userFiles-16ad91bb-ea01-440e-9eef-65b6e04925ce/addedFile7121790753955113154spark_nlp_2_7_5-fd923.jar/sparknlp/pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     30     def downloadModel(reader, name, language, remote_loc=None, j_dwn='PythonResourceDownloader'):
     31         print(name + " download started this may take some time.")
---> 32         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     33         if file_size == "-1":
     34             print("Can not find the model to download please check the name!")

/local_disk0/spark-d3954922-3d42-4eee-9260-0ad0fb28833b/userFiles-16ad91bb-ea01-440e-9eef-65b6e04925ce/addedFile7121790753955113154spark_nlp_2_7_5-fd923.jar/sparknlp/internal.py in __init__(self, name, language, remote_loc)
    189 class _GetResourceSize(ExtendedJavaWrapper):
    190     def __init__(self, name, language, remote_loc):
--> 191         super(_GetResourceSize, self).__init__(
    192             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
    193 

/local_disk0/spark-d3954922-3d42-4eee-9260-0ad0fb28833b/userFiles-16ad91bb-ea01-440e-9eef-65b6e04925ce/addedFile7121790753955113154spark_nlp_2_7_5-fd923.jar/sparknlp/internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

/local_disk0/spark-d3954922-3d42-4eee-9260-0ad0fb28833b/userFiles-16ad91bb-ea01-440e-9eef-65b6e04925ce/addedFile7121790753955113154spark_nlp_2_7_5-fd923.jar/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

/databricks/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.ResourceDownloader$
 at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.$anonfun$getDownloadSize$1(ResourceDownloader.scala:771)
 at scala.Option.getOrElse(Option.scala:189)
 at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:771)
 at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
 at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
 at py4j.Gateway.invoke(Gateway.java:295)
 at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
 at py4j.commands.CallCommand.execute(CallCommand.java:79)
 at py4j.GatewayConnection.run(GatewayConnection.java:251)
 at java.lang.Thread.run(Thread.java:750)


Caused by: java.nio.file.AccessDeniedException: nvirginia-prod/2453194833633492/root/cache_pretrained/: PUT 0-byte object  on nvirginia-prod/2453194833633492/root/cache_pretrained/: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied; request: PUT https://dataeng-databricks-e2-prod.s3.us-east-1.amazonaws.com nvirginia-prod/2453194833633492/root/cache_pretrained/ {} Hadoop 3.3.1, aws-sdk-java/1.12.189 Linux/5.4.0-1094-aws OpenJDK_64-Bit_Server_VM/25.345-b01 java/1.8.0_345 scala/2.12.14 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.PutObjectRequest; Request ID: YSR446XXZVGWJMTC, Extended Request ID: X/7vy4OcBvrOniQsZU4YnSy9c+HDyIaxxiM8yo7YoWpKZSMnt8JHIlf6jjU8z3C1sUhcAcccxyE=, Cloud Provider: AWS, Instance ID: i-0691be04adf5fd0a3 (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: YSR446XXZVGWJMTC; S3 Extended Request ID: X/7vy4OcBvrOniQsZU4YnSy9c+HDyIaxxiM8yo7YoWpKZSMnt8JHIlf6jjU8z3C1sUhcAcccxyE=; Proxy: null), S3 Extended Request ID: X/7vy4OcBvrOniQsZU4YnSy9c+HDyIaxxiM8yo7YoWpKZSMnt8JHIlf6jjU8z3C1sUhcAcccxyE=:AccessDenied
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:248)
 at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:120)
 at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:274)
 at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:333)
 at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:270)
 at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:245)
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.createEmptyObject(S3AFileSystem.java:3895)
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.createFakeDirectory(S3AFileSystem.java:3867)
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.innerMkdirs(S3AFileSystem.java:3160)
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:3093)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$mkdirs$3(DatabricksFileSystemV2.scala:845)
 at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
 at com.databricks.s3a.S3AExceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:70)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$mkdirs$2(DatabricksFileSystemV2.scala:843)
 at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$withUserContextRecorded$2(DatabricksFileSystemV2.scala:1044)
 at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
 at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
 at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
 at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
 at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
 at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:510)
 at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
 at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:510)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withUserContextRecorded(DatabricksFileSystemV2.scala:1017)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$mkdirs$1(DatabricksFileSystemV2.scala:842)
 at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
 at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:330)
 at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:424)
 at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:444)
 at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
 at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
 at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
 at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
 at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
 at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:510)
 at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
 at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:510)
 at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:419)
 at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:339)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperationWithResultTags(DatabricksFileSystemV2.scala:510)
 at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:330)
 at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:302)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:510)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.mkdirs(DatabricksFileSystemV2.scala:842)
 at com.databricks.backend.daemon.data.client.DatabricksFileSystem.mkdirs(DatabricksFileSystem.scala:212)
 at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2388)
 at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.<init>(S3ResourceDownloader.scala:48)
 at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.<init>(ResourceDownloader.scala:114)
 at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.<clinit>(ResourceDownloader.scala)
 ... 15 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied; request: PUT https://dataeng-databricks-e2-prod.s3.us-east-1.amazonaws.com nvirginia-prod/2453194833633492/root/cache_pretrained/ {} Hadoop 3.3.1, aws-sdk-java/1.12.189 Linux/5.4.0-1094-aws OpenJDK_64-Bit_Server_VM/25.345-b01 java/1.8.0_345 scala/2.12.14 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.PutObjectRequest; Request ID: YSR446XXZVGWJMTC, Extended Request ID: X/7vy4OcBvrOniQsZU4YnSy9c+HDyIaxxiM8yo7YoWpKZSMnt8JHIlf6jjU8z3C1sUhcAcccxyE=, Cloud Provider: AWS, Instance ID: i-0691be04adf5fd0a3 (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: YSR446XXZVGWJMTC; S3 Extended Request ID: X/7vy4OcBvrOniQsZU4YnSy9c+HDyIaxxiM8yo7YoWpKZSMnt8JHIlf6jjU8z3C1sUhcAcccxyE=; Proxy: null), S3 Extended Request ID: X/7vy4OcBvrOniQsZU4YnSy9c+HDyIaxxiM8yo7YoWpKZSMnt8JHIlf6jjU8z3C1sUhcAcccxyE=
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
 at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
 at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
 at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
 at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6528)
 at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
 at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
 at shaded.databricks.org.apache.hadoop.fs.s3a.EnforcingDatabricksS3Client.putObject(EnforcingDatabricksS3Client.scala:69)
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.putObjectDirect(S3AFileSystem.java:2069)
 at shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$createEmptyObject$15(S3AFileSystem.java:3897)
 at shaded.databricks.org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:118)
 ... 67 more
```

**Comment by maziyarpanahi** [comment]
Hi,

You mentioned you have spark-nlp - 2.7.5, if that's true that version is ancient!

Could you please follow these steps and make sure you are using spark-nlp:4.3.1? https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

**Comment by Swatisoni** [comment]
Hi @maziyarpanahi ,

Thanks for pointing me in the direction of filestore. Unfortunately, I can not use DBFS as its blocked by admins. I tried using s3 location but that does not work either.

Any workarounds.

Below are the details. I tried downloading the model "explain_document_ml"

explain_document_ml download started this may take some time. 

Approximate size to download 9.2 MB Uploading model explain_document_ml_en_4.0.0_3.0_1656066222624 to external Cloud Storage URI: s3://blah/spark-nlp/pretrained 

Error 
```
IllegalArgumentException: requirement failed: Was not found appropriate resource to download for request: ResourceRequest(explain_document_ml,Some(en),public/models,4.2.8,3.3.0) with downloader: com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader@48b83ba2
at scala.Predef$.require(Predef.scala:281)
```

**Comment by danilojsl** [comment]
Hi @Swatisoni.

You need to add some configurations to spark session to setup S3 in `cache_folder`, please check [this notebook](https://github.com/JohnSnowLabs/spark-nlp/blob/master/examples/python/prediction/english/Load_Model_From_S3.ipynb) and make sure that to fulfill all the requirements.

**Comment by maziyarpanahi** [comment]
As @danilojsl mentioned, you have to follow that notebook and set the key, secret, session, etc. for S3 access from Spark NLP. We do not try to even attempt to see if we can access any private S3 bucket without credentials for security reason, it has to be explicitly set. (I use that actually myself all the time for AWS Glue 4/5 since it doesn't have any HDFS and in a cluster we need a distributed file system. So I use S3 for `cache_folder`)
