### ISSUE TITLE
Java - Errors - Apple Mac M1

### ISSUE THREAD

**Issue by mirozahorak** [JohnSnowLabs/spark-nlp#13758]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

trying to run colab locally
https://colab.research.google.com/drive/1-tBCvJO696sd6T63rBUD9prop_eiNF7G#scrollTo=t5CPqBTJzDnx

### Current Behavior

i am trying to run it localy on Mac M1 and get error below when running:
```python
import json
import pandas as pd
import numpy as np
import sparknlp
import pyspark.sql.functions as F

from pyspark.ml import Pipeline
from pyspark.sql import SparkSession
from sparknlp.annotator import *
from sparknlp.base import *
from sparknlp.pretrained import PretrainedPipeline
from pyspark.sql.types import StringType, IntegerType

spark = sparknlp.start()
text = """When things came up, and there was discussions, or were discussions, about various matters, they came together."

from sparknlp.pretrained import PretrainedPipeline 
pipeline = PretrainedPipeline("translate_en_sk", lang = "xx") 

```

```python
ConnectionRefusedError                    Traceback (most recent call last)
Cell In[10], line 2
      1 from sparknlp.pretrained import PretrainedPipeline 
----> 2 pipeline = PretrainedPipeline("translate_en_sk", lang = "xx") 

File [~/.conda/envs/sc/lib/python3.10/site-packages/sparknlp/pretrained/pretrained_pipeline.py:54](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/~/.conda/envs/sc/lib/python3.10/site-packages/sparknlp/pretrained/pretrained_pipeline.py:54), in PretrainedPipeline.__init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     52 def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     53     if not disk_location:
---> 54         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     55     else:
     56         self.model = PipelineModel.load(disk_location)

File [~/.conda/envs/sc/lib/python3.10/site-packages/sparknlp/pretrained/resource_downloader.py:56](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/~/.conda/envs/sc/lib/python3.10/site-packages/sparknlp/pretrained/resource_downloader.py:56), in ResourceDownloader.downloadPipeline(name, language, remote_loc)
     53 @staticmethod
     54 def downloadPipeline(name, language, remote_loc=None):
     55     print(name + " download started this may take some time.")
---> 56     file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     57     if file_size == "-1":
     58         print("Can not find the model to download please check the name!")

File [~/.conda/envs/sc/lib/python3.10/site-packages/sparknlp/internal/__init__.py:373](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/~/.conda/envs/sc/lib/python3.10/site-packages/sparknlp/internal/__init__.py:373), in _GetResourceSize.__init__(self, name, language, remote_loc)
    372 def __init__(self, name, language, remote_loc):
--> 373     super(_GetResourceSize, self).__init__(
    374         "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
...
--> 438 self.socket.connect((self.java_address, self.java_port))
    439 self.stream = self.socket.makefile("rb")
    440 self.is_connected = True

ConnectionRefusedError: [Errno 61] Connection refused

```

### Expected Behavior

return translated text, just like when running on Google Colab

### Steps To Reproduce

Run this on M1 Mac

```python
import json
import pandas as pd
import numpy as np
import sparknlp
import pyspark.sql.functions as F

from pyspark.ml import Pipeline
from pyspark.sql import SparkSession
from sparknlp.annotator import *
from sparknlp.base import *
from sparknlp.pretrained import PretrainedPipeline
from pyspark.sql.types import StringType, IntegerType

spark = sparknlp.start()
text = """When things came up, and there was discussions, or were discussions, about various matters, they came together."

from sparknlp.pretrained import PretrainedPipeline 
pipeline = PretrainedPipeline("translate_en_sk", lang = "xx") 

```

### Spark NLP version and Apache Spark

Spark NLP version 4.4.0
Apache Spark version: 3.1.2
Python version 3.9.13

### Type of Spark Application

Python Appliation

### Java Version

java version "1.8.0_321"

### Setup and installation

pip

### Operating System and Version

Mac OS Ventura 13.2.1 (22D68)

### Additional Information

```python
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000000151285575, pid=62831, tid=0x0000000000006eab
#
# JRE version: Java(TM) SE Runtime Environment (8.0_321-b07) (build 1.8.0_321-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.321-b07 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libtensorflow_framework.2.dylib+0x22575]  tensorflow::monitoring::MetricDef<(tensorflow::monitoring::MetricKind)1, long long, 2>::MetricDef<char [11], char [7]>(absl::lts_20210324::string_view, absl::lts_20210324::string_view, char const (&) [11], char const (&) [7])+0x125
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# [/Users/miro/pythons/TRANSLATION/hs_err_pid62831.log](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/hs_err_pid62831.log)
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py)", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py)", line 1033, in send_command
    response = connection.send_command(command)
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py)", line 1211, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while receiving
[OK!]
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?8df84d86-1e12-4ad7-98e4-f85547ec2d68)ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:51306)
Traceback (most recent call last):
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py)", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "[/var/folders/zw/py3dr_ks37ngxx0j_zhv8m1m0000gn/T/ipykernel_62769/71304026.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/zw/py3dr_ks37ngxx0j_zhv8m1m0000gn/T/ipykernel_62769/71304026.py)", line 2, in <cell line: 2>
    pipeline = PretrainedPipeline("translate_en_sk", lang = "xx")
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/pretrained_pipeline.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/pretrained_pipeline.py)", line 54, in __init__
    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/resource_downloader.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/resource_downloader.py)", line 147, in downloadPipeline
    j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/__init__.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/__init__.py)", line 344, in __init__
    super(_DownloadPipeline, self).__init__(
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/extended_java_wrapper.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/extended_java_wrapper.py)", line 27, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/extended_java_wrapper.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/extended_java_wrapper.py)", line 37, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/pyspark/ml/wrapper.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/pyspark/ml/wrapper.py)", line 66, in _new_java_obj
    return java_obj(*java_args)
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py)", line 1304, in __call__
    return_value = get_return_value(
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/pyspark/sql/utils.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/pyspark/sql/utils.py)", line 111, in deco
    return f(*a, **kw)
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/protocol.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/protocol.py)", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline
...
Traceback (most recent call last):
  File "[/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py](https://file+.vscode-resource.vscode-cdn.net/Users/miro/opt/anaconda3/lib/python3.9/site-packages/py4j/java_gateway.py)", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 61] Connection refused
```

```python
Py4JError                                 Traceback (most recent call last)
[/Users/miro/pythons/TRANSLATION/TRANSLATION_MARIAN.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/TRANSLATION_MARIAN.ipynb) Cell 5 in ()
      [1](vscode-notebook-cell:/Users/miro/pythons/TRANSLATION/TRANSLATION_MARIAN.ipynb#W5sZmlsZQ%3D%3D?line=0) from sparknlp.pretrained import PretrainedPipeline 
----> [2](vscode-notebook-cell:/Users/miro/pythons/TRANSLATION/TRANSLATION_MARIAN.ipynb#W5sZmlsZQ%3D%3D?line=1) pipeline = PretrainedPipeline("translate_en_sk", lang = "xx")

File [~/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/pretrained_pipeline.py:54](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/~/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/pretrained_pipeline.py:54), in PretrainedPipeline.__init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     52 def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     53     if not disk_location:
---> 54         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     55     else:
     56         self.model = PipelineModel.load(disk_location)

File [~/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/resource_downloader.py:147](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/~/opt/anaconda3/lib/python3.9/site-packages/sparknlp/pretrained/resource_downloader.py:147), in ResourceDownloader.downloadPipeline(name, language, remote_loc)
    145 t1.start()
    146 try:
--> 147     j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
    148     jmodel = PipelineModel._from_java(j_obj)
    149 finally:

File [~/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/__init__.py:344](https://file+.vscode-resource.vscode-cdn.net/Users/miro/pythons/TRANSLATION/~/opt/anaconda3/lib/python3.9/site-packages/sparknlp/internal/__init__.py:344), in _DownloadPipeline.__init__(self, name, language, remote_loc)
    343 def __init__(self, name, language, remote_loc):
--> 344     super(_DownloadPipeline, self).__init__(
    345         "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
...
    336             format(target_id, ".", name))
    337 else:
    338     type = answer[1]

Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline
```

**Comment by maziyarpanahi** [comment]
Hi,

The Apple Silicon support is still experimental so it may not work on some machines. (it never worked on mine that is M2 Max)
However, you can follow this instruction, it seems to be working for people with M1 (not Pro or Ultra): https://sparknlp.org/docs/en/install#installation-for-m1-macs
