### ISSUE TITLE
Typed Dependency Model Unavailable for download

### ISSUE THREAD

**Issue by Kraeze23** [JohnSnowLabs/spark-nlp#13766]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

The typed dependency model available on model hub cannot be downloaded. It produces an error.

### What are you working on?

A pipeline for graph extraction as documented here: [Graph Extraction](https://sparknlp.org/api/com/johnsnowlabs/nlp/annotators/GraphExtraction.html)

### Current Behavior

The following error is produced:
`
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>SFCJGCKN403SDY54</RequestId>
<HostId>6G21E6+wwoABVXPnvLUxeVzWv8qxmzwQpuMB20H2b6S5RF4nj5aMbGug9FE+ao1Np9S1dnHP+U4=</HostId>
</Error>`

### Expected Behavior

Ability to download the model.

### Steps To Reproduce

Go to spark model hub [model hub](https://sparknlp.org/2022/06/29/dependency_typed_conllu_en_3_0.html) and click download.

### Spark NLP version and Apache Spark

Spark nlp 4.4.0
Spark 3.2.1

**Comment by AayushSameerShah** [comment]
Hello, any update on this @danilojsl & @maziyarpanahi ? I am getting the same issue still.

## While downloading the model
For example downloading this: https://nlp.johnsnowlabs.com/2023/04/02/ner_jsl_limited_80p_for_benchmarks_en.html model.
![image](https://github.com/JohnSnowLabs/spark-nlp/assets/83115948/5d73a399-7037-4b46-b359-4bd6f0cdc1b4)

## Also while downloading from the code:
```python
documentAssembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")

sentenceDetector = SentenceDetectorDLModel.pretrained("sentence_detector_dl_healthcare","en","clinical/models") \
    .setInputCols(["document"]) \
    .setOutputCol("sentence") 

tokenizer = Tokenizer()\
    .setInputCols(["sentence"])\
    .setOutputCol("token")

word_embeddings = WordEmbeddingsModel.pretrained("embeddings_clinical", "en", "clinical/models")\
    .setInputCols(["sentence", "token"])\
    .setOutputCol("embeddings")

ner = MedicalNerModel.pretrained("ner_jsl_limited_80p_for_benchmarks", "en", "clinical/models")\
    .setInputCols(["sentence","token","embeddings"])\
    .setOutputCol("ner")
    
ner_converter = NerConverterInternal() \
    .setInputCols(["sentence", "token", "ner"]) \
    .setOutputCol("ner_chunk")

ner_pipeline = Pipeline(stages=[
    documentAssembler, 
    sentenceDetector,
    tokenizer,
    word_embeddings,
    ner,
    ner_converter])
```
Error:
```java
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: HRM39BMBH1F; S3 Extended Request ID: 4FTqiLf1Br4r3O2nqaRPIlep/vbDrTRLgmUk9YduxXAzVbgmUwVg+Y=; Proxy: null), S3 Extended Request ID: 4FTqiLf1Br4r3O2nqaRPIlep/vbDrTRLgmUk9YduxXAzVbgmUwVL388zug+Y=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1490)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1344)
	at com.johnsnowlabs.client.aws.AWSGateway.getMetadata(AWSGateway.scala:99)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:67)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:72)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:370)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:569)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:809)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Please help, thanks 🙏🏻

**Comment by maziyarpanahi** [comment]
Hi @AayushSameerShah 

Everything in `sparknlp.org` is free and open-source, including 18,000+ models/pipelines: https://sparknlp.org/models

There are two issues:
- There is an issue with your Graph Extraction code and this model that does exists but the URL to download is wrong https://sparknlp.org/2022/06/29/dependency_typed_conllu_en_3_0.html. @danilojsl will fix the URL for manual download, but it would be great if you can provide your code for Graph Extraction so he can check and be sure
- The second issue is your last post. You are trying to use a licensed model which those are not free and they are hosted some where else entirely (https://nlp.johnsnowlabs.com/) - you need to have a licensed for those and we don't have those information here 
![image](https://github.com/JohnSnowLabs/spark-nlp/assets/5762953/28126a67-3926-483f-a4b2-281bbc0759cb)

We will focus on the issue number one:
- find the right download URL and fix it in the model's card
- check your code for Graph Extraction and make sure everything works as expected

**Comment by maziyarpanahi** [comment]
Hi @narquette 
I would try to to post either on the Slack (#healthcare channel) or in JSL repo https://github.com/JohnSnowLabs/johnsnowlabs

We just don't have any knowledge of licensed products. (they are incredibly responsive on Slack if you wish to share your issue there)
