### ISSUE TITLE
no jnitensorflow error when using docker

### ISSUE THREAD

**Issue by alvarogracia** [JohnSnowLabs/spark-nlp#13799]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

I'm trying to use the pretrained model 'tfhub_use_multi' with UniversalSentenceEncoder inside a docker. 

### Current Behavior

When I run the code inside my M1 mac it works perfectly but when I run it in a docker i'm getting an error after downloading the model when it has to load it.

### Expected Behavior

To load the model without errors so I can use it.

### Steps To Reproduce

The code which is failing in the docker but not in my computer is the following minimal_example.py:
```
from sparknlp.annotator import UniversalSentenceEncoder
from pyspark.sql import SparkSession
from pyspark import SparkConf

conf = SparkConf() \
    .setAppName("Training functions testing session") \
    .setMaster("local[4]") \
    .set("spark.jars.packages",
         "com.johnsnowlabs.nlp:spark-nlp-m1_2.12:4.0.2")

spark_session = SparkSession.builder.config(conf=conf).getOrCreate()

use = UniversalSentenceEncoder \
    .pretrained("tfhub_use_multi", "xx") \
    .setInputCols("document") \
    .setOutputCol("use_embeddings")

```

The Dockerfile used is this:
```
FROM continuumio/miniconda3:latest

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get clean;

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-arm64

RUN conda create -n phishermans-wharf Python=3.8.13

# Make RUN commands use the new environment:
RUN echo "conda activate phishermans-wharf" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

RUN conda install -c conda-forge pyspark==3.2.1
RUN conda install -c johnsnowlabs spark-nlp==4.0.2

COPY minimal_example.py /
```

and when I build and run the image, when i try to run the minimal_example inside the docker it fails with the error:
```
Traceback (most recent call last):
  File "minimal_example.py", line 20, in <module>
    use = UniversalSentenceEncoder \
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/sparknlp/annotator/embeddings/universal_sentence_encoder.py", line 207, in pretrained
    return ResourceDownloader.downloadModel(UniversalSentenceEncoder, name, lang, remote_loc)
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/sparknlp/pretrained/resource_downloader.py", line 43, in downloadModel
    raise e
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/sparknlp/pretrained/resource_downloader.py", line 40, in downloadModel
    j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/sparknlp/internal/__init__.py", line 317, in __init__
    super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained." + validator + ".downloadModel", reader,
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/sparknlp/internal/extended_java_wrapper.py", line 26, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/sparknlp/internal/extended_java_wrapper.py", line 36, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/pyspark/ml/wrapper.py", line 66, in _new_java_obj
    return java_obj(*java_args)
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/opt/conda/envs/phishermans-wharf/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path: [/usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1738)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1345)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
        at org.tensorflow.internal.c_api.global.tensorflow.<clinit>(tensorflow.java:12)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1212)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1149)
        at org.tensorflow.NativeLibrary.load(NativeLibrary.java:64)
        at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:140)
        at com.johnsnowlabs.ml.tensorflow.sentencepiece.LoadSentencepiece$.loadSPToTensorflowLocally(LoadSentencepiece.scala:124)
        at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readWithSP(TensorflowWrapper.scala:530)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowWithSPModel(TensorflowSerializeModel.scala:195)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel.readTensorflowWithSPModel$(TensorflowSerializeModel.scala:162)
        at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder$.readTensorflowWithSPModel(UniversalSentenceEncoder.scala:373)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel.readTensorflow(UniversalSentenceEncoder.scala:338)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel.readTensorflow$(UniversalSentenceEncoder.scala:332)
        at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder$.readTensorflow(UniversalSentenceEncoder.scala:373)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel.$anonfun$$init$$1(UniversalSentenceEncoder.scala:342)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel.$anonfun$$init$$1$adapted(UniversalSentenceEncoder.scala:342)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:50)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:49)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:38)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:499)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:491)
        at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:664)
        at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jnitensorflow in class, module, and library paths.
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1705)
        ... 47 more
```

### Spark NLP version and Apache Spark

pyspark==3.2.1
spark-nlp==4.0.2

### Java Version

openjdk 11.0.19 2023-04-18

### Java Home Directory

usr/lib/jvm/java-11-openjdk-arm64

### Setup and installation

conda

### Operating System and Version

m1 macOS 12.5

**Comment by DevinTDHa** [comment]
@alvarogracia 
I looked into it and it does indeed seem like the issue is that the docker image is based on linux-aarch64.

Funnily enough, enabling support for that platform will then actually work inside docker. For example:

```python
import sparknlp
from sparknlp.annotator import UniversalSentenceEncoder

spark_session = sparknlp.start(aarch64=True)

use = UniversalSentenceEncoder \
    .pretrained("tfhub_use_multi", "xx") \
    .setInputCols("document") \
    .setOutputCol("use_embeddings")
```

Will work and if you build a bigger pipeline will also produce the right embeddings. (Note that aarch64 support was introduces after spark-nlp==4.0.2, so I recommend using the latest version.)

I will close this issue, feel free to reopen it if you have any other issues regarding this!

**Comment by maziyarpanahi** [comment]
@DevinTDHa shouldn't we use `sparknlp.start(apple_silicon=True)` in the start function? Or does the Docker on M1 turns into `aarch64`?

**Comment by DevinTDHa** [comment]
@maziyarpanahi 

This specific base image (so `FROM continuumio/miniconda3:latest`) will result in a Linux aarch64 container. That's why it couldn't find the libraries at first. A bit confusing but it's good to know that it will work on M1 :smile: 

Potentially, this could be an alternative for other MX silicon machines. I can't test it at the moment though as I only have an M1.

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi
> 
> This specific base image (so `FROM continuumio/miniconda3:latest`) will result in a Linux aarch64 container. That's why it couldn't find the libraries at first. A bit confusing but it's good to know that it will work on M1 😄
> 
> Potentially, this could be an alternative for other MX silicon machines. I can't test it at the moment though as I only have an M1.

That's what I suspected. Thanks for confirming it. If this is true, since the `apple_silicon` fails on M2 and my M2_Max, I am going to use this image to see if it works! (this way as you suggested, it can be a great workaround for other variations of Apple Silicon we don't yet support)
