### ISSUE TITLE
GPT 2 Transformer Serialization issue 

### ISSUE THREAD

**Issue by KhanjanD** [JohnSnowLabs/spark-nlp#13817]
When loading the models using GPT2Transformer.load(path); geeting this error:

Exception in thread "main" java.io.NotSerializableException: com.johnsnowlabs.nlp.annotators.tokenizer.bpe.Gpt2Tokenizer
Serialization stack:
	- object not serializable (class: com.johnsnowlabs.nlp.annotators.tokenizer.bpe.Gpt2Tokenizer, value: com.johnsnowlabs.nlp.annotators.tokenizer.bpe.Gpt2Tokenizer@20072ad1)
	- field (class: com.johnsnowlabs.ml.ai.GPT2, name: bpeTokenizer, type: class com.johnsnowlabs.nlp.annotators.tokenizer.bpe.Gpt2Tokenizer)
	- object (class com.johnsnowlabs.ml.ai.GPT2, com.johnsnowlabs.ml.ai.GPT2@6cb82168)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
	at org.apache.spark.broadcast.TorrentBroadcast$.$anonfun$blockifyObject$4(TorrentBroadcast.scala:311)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:313)
	at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:137)
	at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:91)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:35)
	at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:77)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1474)
	at com.johnsnowlabs.nlp.annotators.seq2seq.GPT2Transformer.setModelIfNotSet(GPT2Transformer.scala:410)
	at com.johnsnowlabs.nlp.annotators.seq2seq.ReadGPT2TransformerDLModel.readModel(GPT2Transformer.scala:521)
	at com.johnsnowlabs.nlp.annotators.seq2seq.ReadGPT2TransformerDLModel.readModel$(GPT2Transformer.scala:519)
	at com.johnsnowlabs.nlp.annotators.seq2seq.GPT2Transformer$.readModel(GPT2Transformer.scala:570)
	at com.johnsnowlabs.nlp.annotators.seq2seq.ReadGPT2TransformerDLModel.$anonfun$$init$$1(GPT2Transformer.scala:524)
	at com.johnsnowlabs.nlp.annotators.seq2seq.ReadGPT2TransformerDLModel.$anonfun$$init$$1$adapted(GPT2Transformer.scala:524)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:50)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:49)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:49)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:61)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:61)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:38)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
	at org.apache.spark.ml.util.MLReadable.load(ReadWrite.scala:355)
	at org.apache.spark.ml.util.MLReadable.load$(ReadWrite.scala:355)
	at com.johnsnowlabs.nlp.annotators.seq2seq.GPT2Transformer$.load(GPT2Transformer.scala:570)
	at com.johnsnowlabs.nlp.annotators.seq2seq.GPT2Transformer.load(GPT2Transformer.scala)
	at sparktimeserries.GPT2ModelSerializationExample.main(GPT2ModelSerializationExample.java:29)

**Comment by maziyarpanahi** [comment]
Could you please fill in the bug/issue report template? (we need all that data and also what is `path` and where is it coming from)
https://github.com/JohnSnowLabs/spark-nlp/issues/new?assignees=maziyarpanahi&labels=question&projects=&template=bug_report.yml
