### ISSUE TITLE
Quickstart guide is for an older version

### ISSUE THREAD

**Issue by AngledLuffa** [JohnSnowLabs/spark-nlp#13854]
### Link to the documentation pages (if available)

https://github.com/JohnSnowLabs/spark-nlp/blob/master/examples/python/quick_start.ipynb

### How could the documentation be improved?

When I run the initial suggestion, it throws an exception:

```
import sparknlp 

spark = sparknlp.start()

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)
```

I get the following version number:

```
Spark NLP version:  4.4.3
Apache Spark version:  3.4.0
```

I get the following error when trying to run the basic initialization:

```
>>> pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
recognize_entities_dl download started this may take some time.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/sparknlp/pretrained/pretrained_pipeline.py", line 54, in __init__

    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/sparknlp/pretrained/resource_downloader.py", line 142, in downloadPipeline
    file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/sparknlp/internal/__init__.py", line 380, in __init__
    "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/sparknlp/internal/extended_java_wrapper.py", line 27, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/sparknlp/internal/extended_java_wrapper.py", line 37, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/u/nlp/anaconda/main/anaconda3/envs/stanza-1.2/lib/python3.7/site-packages/pyspark/ml/wrapper.py", line 86, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable
>>>
```

This is on python 3.7.9 from the command line

**Comment by maziyarpanahi** [comment]
`TypeError: 'JavaPackage' object is not callable` This error means your SparkSession didn't start correctly with Spark NLP maven inside that session.

We need more information about your system and environment in order to help you. Here is an example of the same notebook working with the same versions you provided here: https://colab.research.google.com/drive/1PQIt1jq9-aHlQEuIfPhkl_-sL9BMi8Ak?usp=sharing

You chose `documentation` which is not a correct template for reporting a bug/issue. I suggest either creating an actual issue and providing the required information or following the README to make sure you have the requirement (Java 8 or 11, Python 3.7 and above, etc.):
- https://github.com/JohnSnowLabs/spark-nlp#requirements
- https://github.com/JohnSnowLabs/spark-nlp#quick-start
