### ISSUE TITLE
The summarization model(s) are not giving any result

### ISSUE THREAD

**Issue by AayushSameerShah** [JohnSnowLabs/spark-nlp#13898]
Hello,
Sorry for posting this under the "documentation" label, but I thought it is more appropriate than the "bug". The problem I am facing is currently of **two** types.

1️⃣ Model is **not downloading** at all
2️⃣ Model can be downloaded but **cannot do the inference**.

Let me brief you about them.
___

Before going through any of the problems, I would provide some code which I use as a starter to drive the context:
```python
# Using the colab for doing these testing
!wget http://setup.johnsnowlabs.com/colab.sh -O - | bash

# Start the server
import sparknlp
spark = sparknlp.start(gpu=True)

print("Spark NLP version: {}".format(sparknlp.version()))
print("Apache Spark version: {}".format(spark.version))
>>>Spark NLP version: 5.0.1
>>> Apache Spark version: 3.2.3

from sparknlp.pretrained import PretrainedPipeline
from sparknlp.base import *
from sparknlp.annotator import *
```

Now, let me show the error-prone code.

# 1️⃣ Model is not downloading at all
📝 The model page here: [Page](https://sparknlp.org/2023/05/09/bart_large_cnn_en.html)

**Model Name**: `bart_large_cnn`
```python
documentAssembler = DocumentAssembler() \
.setInputCol("text") \
.setOutputCol("documents")

bart = BartTransformer.pretrained("bart_large_cnn") \
            .setTask("summarize:") \
            .setMaxOutputLength(200) \
            .setInputCols(["documents"]) \
            .setOutputCol("summaries")

pipeline = Pipeline().setStages([documentAssembler, bart])
```

### **Throws** this error:
*(error in short)*
```
raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[OK!]
```
*(error in long)*
```
bart_large_cnn download started this may take some time.
Approximate size to download 1 GB
[ — ]----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 45808)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.10/dist-packages/pyspark/accumulators.py", line 262, in handle
    poll(accum_updates)
  File "/usr/local/lib/python3.10/dist-packages/pyspark/accumulators.py", line 235, in poll
    if func():
  File "/usr/local/lib/python3.10/dist-packages/pyspark/accumulators.py", line 239, in accum_updates
    num_updates = read_int(self.rfile)
  File "/usr/local/lib/python3.10/dist-packages/pyspark/serializers.py", line 564, in read_int
    raise EOFError
EOFError
----------------------------------------
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python3.10/dist-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[OK!]
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
[<ipython-input-12-6cb90d39d472>](https://localhost:8080/#) in <cell line: 1>()
----> 1 bart = BartTransformer.pretrained("bart_large_cnn") \
      2             .setTask("summarize:") \
      3             .setMaxOutputLength(200) \
      4             .setInputCols(["documents"]) \
      5             .setOutputCol("summaries")

8 frames
[/usr/local/lib/python3.10/dist-packages/py4j/protocol.py](https://localhost:8080/#) in get_return_value(answer, gateway_client, target_id, name)
    332                     format(target_id, ".", name, value))
    333         else:
--> 334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
    336                 format(target_id, ".", name))

Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel
```

# 2️⃣  Model is downloaded but can't run inference
I have seen this problem in **these two** models.
📝 **Model-1** page here: [Page-1](https://sparknlp.org/2023/04/09/distilbart_cnn_6_6_en.html)
📝 **Model-2** page here: [Page-2](https://sparknlp.org/2023/05/11/distilbart_xsum_12_6_en.html)

The code:
```python
documentAssembler = DocumentAssembler() \
.setInputCol("text") \
.setOutputCol("documents")


bart = BartTransformer.pretrained("distilbart_cnn_6_6") \
            .setTask("summarize:") \
            .setInputCols(["documents"]) \
            .setOutputCol("summaries") \
            .setMaxOutputLength(128) \
            .setTemperature(.2) \
            .setDoSample(True) 

pipeline = Pipeline().setStages([documentAssembler, bart])
```
***After the successful*** download I run the inference like below:
```python
data = spark.createDataFrame([["A LONG PARAGRAPH"]]).toDF("text")
result = pipeline.fit(data).transform(data)

summary = []
for row in result.select("summaries").collect():
    summary.append(row["summaries"][0]["result"])
```
And it gives this error:
```
Py4JJavaError                             Traceback (most recent call last)
[<ipython-input-11-c4bd6196dafa>](https://localhost:8080/#) in <cell line: 5>()
      3 result = pipeline.fit(data).transform(data)
      4 summary = []
----> 5 for row in result.select("summaries").collect():
      6     summary.append(row["summaries"][0]["result"])
      7 

3 frames
[/usr/local/lib/python3.10/dist-packages/py4j/protocol.py](https://localhost:8080/#) in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o313.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 8) (6fce83427708 executor driver): org.tensorflow.exceptions.TFInvalidArgumentException: 2 root error(s) found.
  (0) INVALID_ARGUMENT: required broadcastable shapes
	 [[{{function_node __inference_decoder_cached_serving_808693}}{{node decoder/layers.0/encoder_attn/add}}]]
	 [[StatefulPartitionedCall/_2389]]
  (1) INVALID_ARGUMENT: required broadcastable shapes
	 [[{{function_node __inference_decoder_cached_serving_808693}}{{node decoder/layers.0/encoder_attn/add}}]]
0 successful operations.
0 derived errors ignored.
```

It's a long error... but it will give the context. Seems like a problem in `.collect()` and also I tried using the `.select("summaries").first()` and still gives **some** other related error.

___
Thank you 🙏🏻

**Comment by DevinTDHa** [comment]
Hi, thanks for reporting! @prabod I think this might be related to your feature?

**Comment by AayushSameerShah** [comment]
Hie @prabod ! Any update on this?
I have found other models too which are causing this issue 😢 

Thanks!

**Comment by AayushSameerShah** [comment]
@maziyarpanahi Hope you were able to catch that error 🤗

**Comment by maziyarpanahi** [comment]
Hi @AayushSameerShah 
yes, your notebook was very helpful and we are debugging it currently.

**Comment by AayushSameerShah** [comment]
Hello! 
Thank you for addressing this issue... but I am unsure if I am able to run this properly. 
For example, I am still using the same colab as given above in the link. Trying to download the `bart_cnn` model but still shows the error.

Thanks.

**Comment by maziyarpanahi** [comment]
This code and model that was previously failing now works in 5.0.2: 
- https://colab.research.google.com/drive/1wSkD0R4yQszc0WKDUcPrKqyfG7zJolBi?usp=sharing

A few things to keep in mind:
- When the `temperature` and the `k` is too low it couldn't find anything. So we fixed this by falling back on more deterministic approach
- BART is heavy, so some of those models cannot fit in the free Colab. (the CNN, the Large, they just cannot fit in the memory so it crashes which is just different)

**Comment by maziyarpanahi** [comment]
Hi @AayushSameerShah 
The initial bug report was for BART annotator, this seems to be T5. (I also see `Java side is empty` which means you have issue with either starting your SparkSession or it was started and it was killed due to OOM)

In any case, if you have a notebook that can be reproduced (without loading an offline model), please create a new issue regarding T5 annotator.
