### ISSUE TITLE
BigTextMatcher fails when setStoragePath using HDFS

### ISSUE THREAD

**Issue by naydin2** [JohnSnowLabs/spark-nlp#13969]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

BigTextMatcher

### Current Behavior

my predefined phrases are inside hdfs, so I set setStoragePath as `hdfs:////tmp/test3.txt` 
but When initializing BigTextMatcher, it fails with 
```
Py4JJavaError: An error occurred while calling o5515.fit.
: java.io.FileNotFoundException: file or folder: /tmp/sparknlp_7540410410347557701.str not found
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$SourceStream.<init>(ResourceHelper.scala:112)
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.parseLinesIterator(ResourceHelper.scala:406)
	at com.johnsnowlabs.nlp.annotators.btm.BigTextMatcher.loadEntities(BigTextMatcher.scala:157)
	at com.johnsnowlabs.nlp.annotators.btm.BigTextMatcher.index(BigTextMatcher.scala:195)
	at com.johnsnowlabs.storage.HasStorage.indexDatabases(HasStorage.scala:95)
	at com.johnsnowlabs.storage.HasStorage.preload(HasStorage.scala:126)
	at com.johnsnowlabs.storage.HasStorage.indexStorage(HasStorage.scala:205)
	at com.johnsnowlabs.storage.HasStorage.indexStorage$(HasStorage.scala:201)
	at com.johnsnowlabs.nlp.annotators.btm.BigTextMatcher.indexStorage(BigTextMatcher.scala:105)
	at com.johnsnowlabs.nlp.AnnotatorApproach.indexIfStorage(AnnotatorApproach.scala:61)
	at com.johnsnowlabs.nlp.AnnotatorApproach._fit(AnnotatorApproach.scala:68)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:75)
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

(<class 'py4j.protocol.Py4JJavaError'>, Py4JJavaError('An error occurred while calling o5515.fit.\n', JavaObject id=o5636), <traceback object at 0x7f49dc4dbbe0>)
```

### Expected Behavior

It should create bigTextMatcher succesfully.

### Steps To Reproduce

```
%pyspark
news_df = spark.read \
            .option("header", True) \
            .csv("/tmp/news_category_train.csv")


documentAssembler = DocumentAssembler()\
    .setInputCol("description")\
    .setOutputCol("document")

tokenizer = Tokenizer() \
    .setInputCols(["document"]) \
    .setOutputCol("token")

financial_entity_extractor = BigTextMatcher() \
    .setInputCols(["document",'token'])\
    .setOutputCol("financial_entities")\
    .setStoragePath("hdfs:////tmp/test3.txt", ReadAs.TEXT)\
    .setCaseSensitive(False)

sport_entity_extractor = BigTextMatcher() \


nlpPipeline = Pipeline(
    stages=[
        documentAssembler,
        tokenizer,
        financial_entity_extractor
        ])

result = nlpPipeline.fit(news_df).transform(news_df)
```

### Spark NLP version and Apache Spark

spar version = '3.4.0-amzn-0'

spark nlp version = '5.1.0'

### Type of Spark Application

PYSPARK 
### Java Version

openjdk version "1.8.0_382"
OpenJDK Runtime Environment Corretto-8.382.05.1 (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM Corretto-8.382.05.1 (build 25.382-b05, mixed mode)

### Setup and installation

Zeppelin, maven 

### Operating System and Version

AMAZON AL2 LINUX 64

**Comment by naydin2** [comment]
I think the issue is, `BigTextMatcher` writes that file into `/tmp` but it's on master node, not in the executor's file system.

**Comment by maziyarpanahi** [comment]
Could you please provide the following `required` information:

### Type of Spark Application

_No response_

### Java Version

_No response_

### Setup and installation

_No response_

### Operating System and Version

_No response_

**Comment by naydin2** [comment]
HI @maziyarpanahi , I updated.
```
Spark NLP version and Apache Spark
spar version = '3.4.0-amzn-0'

spark nlp version = '5.1.0'

Type of Spark Application
PYSPARK

Java Version
openjdk version "1.8.0_382"
OpenJDK Runtime Environment Corretto-8.382.05.1 (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM Corretto-8.382.05.1 (build 25.382-b05, mixed mode)

Java Home Directory
No response

Setup and installation
Zeppelin, maven

Operating System and Version
AMAZON AL2 LINUX 64
```

**Comment by naydin2** [comment]
This is EMR cluster, 
```%pyspark
import sparknlp
from sparknlp.base import LightPipeline, Pipeline, ReadAs, Finisher
from sparknlp.annotator import SentenceDetector, Tokenizer, DocumentAssembler, TextMatcher, BigTextMatcher
from pyspark.sql import functions as F
import pandas as pd

spark = sparknlp.start()

sparknlp.version()
# spark.version
```

**Comment by naydin2** [comment]
TextMatcher works just fine if i give HDFS file path to read in, but as long as I switch to `BigTextMatcher` it fails with that above error msg in the question.

**Comment by naydin2** [comment]
@maziyarpanahi Here's the full code I'm using:
```
%pyspark
news_df = spark.read \
            .option("header", True) \
            .csv("/tmp/news_category_train.csv")


documentAssembler = DocumentAssembler()\
    .setInputCol("description")\
    .setOutputCol("document")

tokenizer = Tokenizer() \
    .setInputCols(["document"]) \
    .setOutputCol("token")

financial_entity_extractor = BigTextMatcher() \
    .setInputCols(["document",'token'])\
    .setOutputCol("financial_entities")\
    .setStoragePath("hdfs:////tmp/test3.txt", ReadAs.TEXT)\
    .setCaseSensitive(False)

sport_entity_extractor = BigTextMatcher() \


nlpPipeline = Pipeline(
    stages=[
        documentAssembler,
        tokenizer,
        financial_entity_extractor
        ])

result = nlpPipeline.fit(news_df).transform(news_df)
```
