### ISSUE TITLE
Failure to initialize configuration for storage account when trying to load model from Azure blob store

### ISSUE THREAD

**Issue by rphes** [JohnSnowLabs/spark-nlp#14019]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

I'm trying to load a fine-tuned model from an Azure blob storage account on Azure databricks on python using the following code:

```python
NerDLModel.load("abfss://...")
```

Spark has been configured with read access to this storage account and is able to read and write dataframes from and to it.

### Current Behavior

Calling load like shown above results in the following error:

```
Py4JJavaError: An error occurred while calling o904.load.
: Failure to initialize configuration for storage account ***.dfs.core.windows.net: Invalid configuration value detected for fs.azure.account.keyInvalid configuration value detected for fs.azure.account.key
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:52)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:666)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:2055)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:267)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:225)
	at com.databricks.common.filesystem.LokiFileSystem$.$anonfun$getLokiFS$1(LokiFileSystem.scala:63)
	at com.databricks.common.filesystem.Cache.getOrCompute(Cache.scala:38)
	at com.databricks.common.filesystem.LokiFileSystem$.getLokiFS(LokiFileSystem.scala:60)
	at com.databricks.common.filesystem.LokiFileSystem.initialize(LokiFileSystem.scala:86)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:537)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:275)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:244)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:332)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:216)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:333)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:57)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:333)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:329)
	at org.apache.spark.rdd.RDD.$anonfun$take$1(RDD.scala:1498)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:445)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1492)
	at org.apache.spark.rdd.RDD.$anonfun$first$1(RDD.scala:1533)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:445)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1533)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:593)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:471)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
Caused by: Invalid configuration value detected for fs.azure.account.key
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.diagnostics.ConfigurationBasicValidator.validate(ConfigurationBasicValidator.java:49)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.diagnostics.Base64StringConfigurationBasicValidator.validate(Base64StringConfigurationBasicValidator.java:40)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.validateStorageAccountKey(SimpleKeyProvider.java:71)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:49)
	... 49 more
```

To me this implies the existing spark configuration for Hadoop is not propagated to the spark-nlp loader, causing it to fall back to using an `fs.azure.account.key`, which is not set either, so it fails.

### Expected Behavior

I would expect authentication to succeed using the preset configuration values and the model to load correctly.

I'm not sure whether this is relevant, but perhaps [this line](https://github.com/JohnSnowLabs/spark-nlp/blob/6919f5e16b5928bf52c284927ecb8964a42e816e/src/main/scala/com/johnsnowlabs/storage/StorageLocator.scala#L25) should say 

```scala
FileSystem.get(spark.sessionState.newHadoopConf())
```

instead. See 

https://github.com/apache/spark/blob/ffc6994f46534dd955a387cea51afb9a67cb781e/sql/core/src/main/scala/org/apache/spark/sql/internal/SessionState.scala#L104

and e.g. 

https://github.com/apache/spark/blob/ffc6994f46534dd955a387cea51afb9a67cb781e/examples/src/main/scala/org/apache/spark/examples/DFSReadWriteTest.scala#L114

### Steps To Reproduce

It is difficult to provide a working set of steps due to the involvement of an Azure blob storage account. Roughly:

```python
spark.conf.set("fs.azure.account.auth.type", "OAuth")
spark.conf.set("fs.azure.account.oauth.provider.type", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.conf.set("fs.azure.account.oauth2.client.id", "...")
spark.conf.set("fs.azure.account.oauth2.client.secret", "...")
spark.conf.set("fs.azure.account.oauth2.client.endpoint", "https://login.microsoftonline.com/.../oauth2/token")

NerDLModel.load("abfss://...")
```

### Spark NLP version and Apache Spark

sparknlp==5.1.2
pyspark==3.3.2

### Type of Spark Application

Python Application

### Setup and installation

Set-up using Maven

### Additional Information

Databricks Runtime 12.2 LTS ML GPU

**Comment by danilojsl** [comment]
Hi @rphes 

The protocol (abfss) provided in the URI for loading NerDL is used in Azure Data Lake Storage Gen2. We currently do not support that configuration. We will add support for that configuration in coming releases (probably 5.2). In the meantime, you can use Amazon Blob Container protocol `wasbs` check [this notebook](https://colab.research.google.com/drive/1uJqJJsX8-1V93-UW6lXA42WcSBXX8fwx?usp=sharing) as an example

**Comment by rphes** [comment]
Thanks for your reply @danilojsl. I'll be looking out for that release! In the meantime I've worked around the issue by copying the model to the executors' file systems using `dbutils`.

**Comment by danilojsl** [comment]
Hi @rphes 

I configured an Azure container with Azure Data Lake Storage Gen2 and tested using `wasbs://` instead of `abfss` and it worked. Can you test in your environment using `wasbs`
