### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment  when I load model from hdfs

### ISSUE THREAD

**Issue by xueyuan1990** [JohnSnowLabs/spark-nlp#14272]
### Is there an existing issue for this?

I find it here(I'm not sure it's the same error) : https://github.com/JohnSnowLabs/spark-nlp/issues/5918

### Current Behavior
I got error below:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fa16bcb5260, pid=23030, tid=0x00007fa2af75b700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtensorflow_framework.so.2+0x16bc260]  nsync::nsync_mu_init(nsync::nsync_mu_s_*)+0x0
#
# Core dump written. Default location: /home/xueyuan.zhang/article_recom/core or core.23030
#
# An error report file with more information is saved as:
# /home/xueyuan.zhang/article_recom/hs_err_pid23030.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./test_spark_nlp.sh: line 20: 23030 Aborted                 (core dumped) /opt/spark3/bin/spark-submit --master yarn --name action_sequence_123 --deploy-mode client --files /opt/spark3/conf/hive-site.xml --class $class_name --jars hdfs:///apps/recommend/models/jars/xueyuan/mzreader/spark-nlp_2.12-5.3.3.jar,hdfs:///apps/recommend/models/jars/xueyuan/mzreader/aws-java-sdk-core-1.12.722.jar,hdfs:///apps/recommend/models/jars/xueyuan/mzreader/tensorflow-cpu_2.12-0.4.4.jar $jar_file $today
```
[hs_err_pid23030.log](https://github.com/JohnSnowLabs/spark-nlp/files/15383674/hs_err_pid23030.log)
### Steps To Reproduce
I load model from https://sparknlp.org/2022/04/11/bert_embeddings_chinese_roberta_wwm_ext_zh_3_0.html and put it onto  hdfs_path. But when I load it, the error comes.
```
import com.johnsnowlabs.nlp.embeddings.BertEmbeddings
val hdfs_path="...../bert_embeddings_chinese_roberta_wwm_ext_zh"
val embeddings = BertEmbeddings.load(hdfs_path)
```
spark-submit :
```
#!/bin/bash
today=$1
jar_file="./article_recommender_spark3-2.0-SNAPSHOT.jar"
class_name="com.algo.recom.article_recommender.v20240511.test_spark_nlp"
/opt/spark3/bin/spark-submit \
--master yarn \
--name action_sequence_123 \
--deploy-mode client \
--files /opt/spark3/conf/hive-site.xml \
--class $class_name \
--jars hdfs:///apps/recommend/models/jars/xueyuan/mzreader/spark-nlp_2.12-5.3.3.jar,hdfs:///apps/recommend/models/jars/xueyuan/mzreader/aws-java-sdk-core-1.12.722.jar,hdfs:///apps/recommend/models/jars/xueyuan/mzreader/tensorflow-cpu_2.12-0.4.4.jar \
$jar_file $today
```

### Spark NLP version and Apache Spark

<dependency>
    <groupId>com.johnsnowlabs.nlp</groupId>
    <artifactId>spark-nlp_2.12</artifactId>
    <version>5.3.3</version>
</dependency>

spark  version 3.3.2
Scala version 2.12.15
Java HotSpot(TM) 64-Bit Server VM, 1.8.0_144

**Comment by maziyarpanahi** [comment]
hi, could you please share some details regarding your:
- operating systems (in the cluster)
- the version of your OS
- processor type
- and, what is `spark-nlp_2.12-5.3.3.jar`? it doesn't look like a Fat JAR we provide in our release notes that comes all the dependencies

**Comment by xueyuan1990** [comment]
CentOS Linux 7
CPU
spark-nlp_2.12-5.3.3.jar is provided in your release notes in this link:https://sparknlp.org/docs/en/install#scala-and-java

**Comment by maziyarpanahi** [comment]
I suspect you are either missing some dependencies or your OS is too old. 

- The package will pull all the dependencies, but you went around and just included the thin jar which only has our code. That's not what we provide, you should either use the Maven package or our Fat JARs (at the bottom of the announcement) https://github.com/JohnSnowLabs/spark-nlp/releases/tag/5.3.3
- If using Fat JAR didn't work, there is an issue either with the model or the OS.

Please use the Fat JAR instead and try `BertEmbeddings.pretrained()` for this test.

**Comment by xueyuan1990** [comment]
I use the Fat JAR downloaded from https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/jars/spark-nlp-assembly-5.3.3.jar.  And try BertEmbeddings.pretrained("bert_embeddings_chinese_roberta_wwm_ext","zh").
But the error still comes.

**Comment by maziyarpanahi** [comment]
Thanks, but not to rule out the model's issue, I need you to just use `BertEmbeddings.pretrained()` no model inside. I just need to see if it's the model that has the problem or the OS. (from my experience, CentOS 7 is just way too old to support new TensorFlow/ONNX requirements, but let's see if the default model works)

please just run this code:

```
bert = BertEmbeddings.pretrained()
```

The default model is ONNX, so I want to see what happens when you use ONNX instead of TF.

**Comment by xueyuan1990** [comment]
When I run:
`bert = BertEmbeddings.pretrained()`
I got another error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java2266451697421274426/libonnxruntime.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/onnxruntime-java2266451697421274426/libonnxruntime.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:365)
        at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:156)
        at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:33)
        at com.johnsnowlabs.ml.onnx.OnnxSession.getSessionOptions(OnnxSession.scala:30)
        at com.johnsnowlabs.ml.onnx.OnnxWrapper$.read(OnnxWrapper.scala:125)
        at com.johnsnowlabs.ml.onnx.ReadOnnxModel.readOnnxModel(OnnxSerializeModel.scala:115)
        at com.johnsnowlabs.ml.onnx.ReadOnnxModel.readOnnxModel$(OnnxSerializeModel.scala:83)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.readOnnxModel(BertEmbeddings.scala:492)
        at com.johnsnowlabs.nlp.embeddings.ReadBertDLModel.readModel(BertEmbeddings.scala:436)
        at com.johnsnowlabs.nlp.embeddings.ReadBertDLModel.readModel$(BertEmbeddings.scala:427)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.readModel(BertEmbeddings.scala:492)
        at com.johnsnowlabs.nlp.embeddings.ReadBertDLModel.$anonfun$$init$$1(BertEmbeddings.scala:444)
        at com.johnsnowlabs.nlp.embeddings.ReadBertDLModel.$anonfun$$init$$1$adapted(BertEmbeddings.scala:444)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:50)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:49)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:49)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:61)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:38)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:515)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:507)
        at com.johnsnowlabs.nlp.HasPretrained.pretrained(HasPretrained.scala:44)
        at com.johnsnowlabs.nlp.HasPretrained.pretrained$(HasPretrained.scala:41)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.com$johnsnowlabs$nlp$embeddings$ReadablePretrainedBertModel$$super$pretrained(BertEmbeddings.scala:492)
        at com.johnsnowlabs.nlp.embeddings.ReadablePretrainedBertModel.pretrained(BertEmbeddings.scala:418)
        at com.johnsnowlabs.nlp.embeddings.ReadablePretrainedBertModel.pretrained$(BertEmbeddings.scala:417)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.pretrained(BertEmbeddings.scala:492)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.pretrained(BertEmbeddings.scala:492)
        at com.johnsnowlabs.nlp.HasPretrained.pretrained(HasPretrained.scala:52)
        at com.johnsnowlabs.nlp.HasPretrained.pretrained$(HasPretrained.scala:51)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.com$johnsnowlabs$nlp$embeddings$ReadablePretrainedBertModel$$super$pretrained(BertEmbeddings.scala:492)
        at com.johnsnowlabs.nlp.embeddings.ReadablePretrainedBertModel.pretrained(BertEmbeddings.scala:410)
        at com.johnsnowlabs.nlp.embeddings.ReadablePretrainedBertModel.pretrained$(BertEmbeddings.scala:410)
        at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.pretrained(BertEmbeddings.scala:492)
        at com.meizu.algo.recom.article_recommender.v20240511.test_spark_nlp$.main(test_spark_nlp.scala:7)
        at com.meizu.algo.recom.article_recommender.v20240511.test_spark_nlp.main(test_spark_nlp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by xueyuan1990** [comment]
I upgrade my OS to CentOS Linux release 7.9.2009 (Core) and gcc to gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3).
BertEmbeddings.pretrained() can load model successfully.
But BertEmbeddings.pretrained("bert_embeddings_chinese_roberta_wwm_ext","zh") still can not.

**Comment by maziyarpanahi** [comment]
Great, there is something wrong with the model.  suggest you either found another model with Chinese support, try to import the same model yourself with ONNX, or import another model yourself:


- choose another model: https://sparknlp.org/models?task=Embeddings&language=zh

Import new model(s):

- re-import this model https://huggingface.co/hfl/chinese-roberta-wwm-ext
- other candidate models to import: https://huggingface.co/models?pipeline_tag=fill-mask&language=zh&sort=trending&search=bert
- Notebooks to import any models from Hugging Face: https://github.com/JohnSnowLabs/spark-nlp/discussions/5669
