### ISSUE TITLE
Building a SearchTrie for entity extraction can sometimes throw java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by avenka11** [JohnSnowLabs/spark-nlp#151]
Building the `SearchTrie` for entity extraction can sometimes throw `java.lang.IndexOutOfBoundsException`

## Description
Building a trie for Entity extraction fails when datasets contain a word that is a part of many phrases  such that it appears first in the middle of a one phrase and subsequently appears as the first word of another phrase. For e.g. the word _ring_ in a dataset containing the following entires in the given order
```
the fellowship of the ring
ring of fire
```

## Expected Behavior
A SearchTrie should be successfully built.

## Current Behavior
An exception is thrown such as below:
```
[info]   java.lang.IndexOutOfBoundsException: 3
[info]   at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
[info]   at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
[info]   at com.johnsnowlabs.collections.SearchTrie$$anonfun$apply$4.apply$mcVI$sp(SearchTrie.scala:141)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at com.johnsnowlabs.collections.SearchTrie$.apply(SearchTrie.scala:134)
[info]   at com.johnsnowlabs.collections.SearchTrieSpec.<init>(SearchTrieSpec.scala:6)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

## Steps to Reproduce
Build a SearchTrie with the following test data:
```
 val trie = SearchTrie(
    Array(
      Array("a", "b", "a", "b"),
      Array("b", "a", "a")
    )
  )
```
In the test data, the string `b` appears first in the middle of the first phrase and then at the start of the second phrase

## Your Environment
* Version used: spark-nlp 1.4.2, apache spark 2.2.0

**Comment by avenka11** [comment]
@aleksei-ai Thanks for the fix
