### ISSUE TITLE
Failed to find a default value for corpus in 1.5

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#162]
## Description

After upgrading to 1.5 my pipeline fit crashes with: `Failed to find a default value for corpus` which it will go away by removing `PerceptronApproach` from the pipeline.
I can see in 1.5 `src/main/resources/anc-pos-corpus` has been removed.
## Expected Behavior

In documentation for annotation it should be more clear if the default has been removed and only pre-trained models exist.

## Your Environment

* Version used: 1.5
* Spark version: 2.2.0 and 2.2.1

Example code:

```scala
import com.johnsnowlabs.nlp.{DocumentAssembler, Finisher}
import com.johnsnowlabs.nlp.annotators.{Normalizer, Stemmer, Tokenizer}
import org.apache.spark.ml.Pipeline

val documentAssembler = new DocumentAssembler()
      .setInputCol(textColumnName)
      .setOutputCol("document")

    val sentenceDetector = new SentenceDetector()
      .setInputCols(Array("document"))
      .setOutputCol("sentence")

    val token = new Tokenizer()
      .setInputCols(Array("document"))
      .setOutputCol("token")

    val normalizer = new Normalizer()
      .setInputCols(Array("token"))
      .setOutputCol("normalized")

    val stemmer = new Stemmer()
      .setInputCols(Array("normalized"))
      .setOutputCol("stem")

    val posTagger = new PerceptronApproach()
      .setNIterations(5)
      .setInputCols(Array("sentence", "token"))
      .setOutputCol("pos")

    val token_finisher = new Finisher()
      .setInputCols("normalized")
      .setOutputCols("tokens_array")
      .setCleanAnnotations(false)
      .setOutputAsArray(true)

val pipeline = new Pipeline()
      .setStages(Array(
        documentAssembler,
        sentenceDetector,
        token,
        normalizer,
        stemmer,
        posTagger,
        token_finisher,
        filteredTokens
      ))

    val model = pipeline.fit(df)
    val pipeLineDF = model.transform(df)

````
Full error:
```
Exception in thread "main" java.util.NoSuchElementException: Failed to find a default value for corpus
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:652)
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:652)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getOrDefault(params.scala:651)
	at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:42)
	at org.apache.spark.ml.param.Params$class.$(params.scala:658)
	at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:42)
	at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronApproach.train(PerceptronApproach.scala:110)
	at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronApproach.train(PerceptronApproach.scala:20)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:33)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
	at Test_NLP_Libraries$.Test_English(Test_NLP_Libraries.scala:139)
	at Main$.main(Main.scala:18)
	at Main.main(Main.scala)
```

**Comment by saifjsl** [comment]
hi @maziyarpanahi !

Wow! thanks for updating so fast :). We are shifting the paradigm a little bit in 1.5, as we are not including corpus for training anymore (along with the issues that brings with).

Now you have two ways of using the library:

1. You can download a pretrained POS model with PerceptronModel.pretrained() call
2. You can use BasicPipeline which is a pretrained pipeline that includes POS.
3. If you still want to train your own POS model, we may provide some example data for training, but the idea is you use your own data for training from now on.

Thanks

**Comment by aleksei-ai** [comment]
@maziyarpanahi 
You can simple replace your posTagger training with code:
`posTagger = PerceptronModel.pretrained()`

Instead of training you simple download pretrained model.

**Comment by maziyarpanahi** [comment]
Hi @saifjsl,

Thanks for the explanation. I think some example datasets for different languages is a great idea.

**Comment by maziyarpanahi** [comment]
Hi @aleksei-ai 

I tried your snippet as you mentioned, I have this error which it means the download from S3 has failed. Is this only available to people on AWS or is it possible to use it without AWS credentials?

```
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: D5F13FE892091546; S3 Extended Request ID: Xoy1P+0CLXAvM4mFnW/XsEvMIwZ/KOwsRNiaPPfwagYcqQsUwoHAw2ltJwvnfxPxIjW+NLX+srQ=), S3 Extended Request ID: Xoy1P+0CLXAvM4mFnW/XsEvMIwZ/KOwsRNiaPPfwagYcqQsUwoHAw2ltJwvnfxPxIjW+NLX+srQ=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1410)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1271)
	at com.johnsnowlabs.nlp.pretrained.CloudResourceDownloader.downloadMetadataIfNeed(CloudResourceDownloader.scala:32)
	at com.johnsnowlabs.nlp.pretrained.CloudResourceDownloader.resolveLink(CloudResourceDownloader.scala:44)
	at com.johnsnowlabs.nlp.pretrained.CloudResourceDownloader.download(CloudResourceDownloader.scala:62)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:67)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:78)
	at com.johnsnowlabs.nlp.annotators.pos.perceptron.PretrainedPerceptronModel$class.pretrained(PerceptronModel.scala:73)
	at com.johnsnowlabs.nlp.annotator$PerceptronModel$.pretrained(annotator.scala:59)
```

**Comment by aleksei-ai** [comment]
hi @maziyarpanahi, 
* First exception raised because you set up AWS Key\Secret in config or via Environment Variables
* Second exception is more difficult. I think there are some troubles with dependencies. Can you create mininum project that reproduces this error and put it as gist https://gist.github.com/?

**Comment by aleksei-ai** [comment]
@maziyarpanahi  
I found that the problem is that Spark NLP 1.5.0 now depends on spark-core 2.3.0.
spark-core 2.3.0 has transitive dependencies on two version of google guava 16.0.1 and 11.0.2 and in guava 16 was a lot of breaking changes. 
So you have to choose 11.0.2 explicitly adding it as a dependency.
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>11.0.1</version>
    </dependency>

Here is my gist: https://gist.github.com/aleksei-ai/f18211d4530659176d55fda8dbf2381b
Please, let us know weather it works or not.

**Comment by maziyarpanahi** [comment]
@aleksei-ai 
* I added `"com.google.guava" % "guava" % "11.0.1"` to my build.sbt with Spark 2.2.1 and it gave me the same error.
* I changed my Spark version to 2.3 without `guava` and it gave me the same error
* I added `"com.google.guava" % "guava" % "11.0.1"` to my build with Spark 2.3 and still the same error

I can see the cache_pretrained has been downloaded.

Here is my build.sbt: https://github.com/multivacplatform/multivac-nlp/blob/master/build.sbt
Here is the code: https://github.com/multivacplatform/multivac-nlp/blob/master/src/main/scala/Test_NLP_Libraries.scala

**Comment by aleksei-ai** [comment]
@maziyarpanahi 

If you are using sbt than you can try exclude guava as transition dependency.
`"org.apache.spark" %%"spark-core" % sparkVer exclude("com.google.guava", "guava"),`
`"com.johnsnowlabs.nlp" %% "spark-nlp" % "1.5.0"  exclude("com.google.guava", "guava"),`

Can you try it?

**Comment by maziyarpanahi** [comment]
@aleksei-ai 
I did as you instructed, but still the same error.

```scala
"org.apache.spark" %%"spark-core" % sparkVer exclude("com.google.guava", "guava"),
"com.johnsnowlabs.nlp" %% "spark-nlp" % "1.5.0" exclude("com.google.guava", "guava"),
"com.google.guava" % "guava" % "11.0.1"
```

**Comment by saifjsl** [comment]
Hi @maziyarpanahi 

This thread became a little bit confusing and misleading.

Please open new issues with specific title. Also, feel free to join our SLACK channel mentioned in the website: nlp.johnsnowlabs.com
