### ISSUE TITLE
Unable to initialize DocumentAssembler in Python

### ISSUE THREAD

**Issue by Tredence-GitHub** [JohnSnowLabs/spark-nlp#178]
## Environment:

- Spark 2.3.0
- SBT 1.1.4
- Scala 2.12.5
- Windows 8.1

## Initial Issue:

Unable to compile spark-nlp on Windows due to ivy2 dependency issue.

sbt.ResolveException: unresolved dependency: org.apache.ivy#ivy;2.4.0: several p
roblems occurred while resolving dependency: org.apache.ivy#ivy;2.4.0 {compile=[
compile(*), master(compile)], runtime=[runtime(*)]}:

## Initial Issue Resolution:

Created Ubuntu VM and compiled it. Scala, Spark and SBT version were the same. Compilation was successful. I also ran 'sbt package' to obtain 'spark-nlp_2.11-1.5.0.jar'.

## The Issue:

'spark-nlp_2.11-1.5.0.jar' is in $SPARK_HOME/bin/. I started spark-shell using
> spark-shell --jars spark-nlp_2.11-1.5.0.jar

However, spark-submit --class com.johnsnowlabs.nlp ./spark-nlp_2.11-1.5.0.jar did not run. It gave the following error:
```
java.lang.ClassNotFoundException: com.johnsnowlabs.nlp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:235)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSub
mit$$runMain(SparkSubmit.scala:836)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:19
7)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2018-04-18 00:05:51 INFO  ShutdownHookManager:54 - Shutdown hook called
2018-04-18 00:05:51 INFO  ShutdownHookManager:54 - Deleting directory C:\Users\n
aveen.nathan\AppData\Local\Temp\spark-8b990d21-ec66-4527-9d84-998cd63191c3

```
After that I tried to initialize DocumentAssembler, but I got the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-7-ff7d4cab1d9b> in <module>()
----> 1 documentAssembler = DocumentAssembler().setInputCol("text").setOutputCol("document")
      2 
      3 sentenceDetector = SentenceDetector().setInputCols(["document"]).setOutputCol("sentence")
      4 
      5 tokenizer = Tokenizer().setInputCols(["document"]).setOutputCol("token")

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

~\Desktop\Code\TextMining\sparknlp\base.py in __init__(self)
    173     @keyword_only
    174     def __init__(self):
--> 175         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    176         self._setDefault(outputCol="document")
    177 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

~\Desktop\Code\TextMining\sparknlp\base.py in __init__(self, classname)
     18         self.setParams(**kwargs)
     19         self.__class__._java_class_name = classname
---> 20         self._java_obj = self._new_java_obj(classname, self.uid)
     21 
     22 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     61             java_obj = getattr(java_obj, name)
     62         java_args = [_py2java(sc, arg) for arg in args]
---> 63         return java_obj(*java_args)
     64 
     65     @staticmethod

TypeError: 'JavaPackage' object is not callable
```

**Comment by saifjsl** [comment]
Hi @Tredence-GitHub 

I am a little bit confused. Ivy is failing as a dependency, which is super strange.
Also, I'd suggest you use scala 2.11.12 instead of 2.12.x.

And finally, why don't you use --package from spark-packages as shown in the instructions? 
If you really need to compile it, --jars is the way to got, not --class. Spark-submit just with spark-nlp doesn't make much sense to me.

Let us know how it goes further
