### ISSUE TITLE
SentenceDetector Failed to find a default value for useCustomBoundsOnly

### ISSUE THREAD

**Issue by superman24-7** [JohnSnowLabs/spark-nlp#189]
## Description

In attempting to use the Named Entity Recognition Deep Learning annotator (NerDLApproach)  I get the exception 

```
Caused by: java.util.NoSuchElementException: Failed to find a default value for useCustomBoundsOnly
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getOrDefault(params.scala:779)
	at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:42)
	at org.apache.spark.ml.param.Params$class.$(params.scala:786)
	at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:42)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.model$lzycompute(SentenceDetector.scala:46)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.model(SentenceDetector.scala:45)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.tag(SentenceDetector.scala:54)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector$$anonfun$2.apply(SentenceDetector.scala:66)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector$$anonfun$2.apply(SentenceDetector.scala:66)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.annotate(SentenceDetector.scala:66)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:43)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:42)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:102)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:101)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1055)
	... 50 more
```
This stems from the SentenceDetector that I have included in my pipeline. I have also managed to replicate the issue using the below code:

[https://github.com/JohnSnowLabs/spark-nlp/blob/84d338d342485abba01e7aa1a94a7b5064c6bd4e/src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala](https://github.com/JohnSnowLabs/spark-nlp/blob/84d338d342485abba01e7aa1a94a7b5064c6bd4e/src/test/scala/com/johnsnowlabs/benchmarks/spark/NerDLCoNLL2003.scala)

I have attempted to manually set the value as below with the same exception still occuring:

```
    val sentenceDetector = new SentenceDetector()
      .setCustomBounds(Array("\n\n", "\r\n\r\n"))
      .setUseCustomBoundsOnly(false)
      .setInputCols(Array("document"))
      .setOutputCol("sentence")
```
This looks like a similar issue to:

[https://github.com/high-performance-spark/high-performance-spark-examples/issues/89](https://github.com/high-performance-spark/high-performance-spark-examples/issues/89)

Looking at the SentenceDetector.scala class default values seem to be set but not for the useCustomBoundsOnly value.

```
  setDefault(
    inputCols -> Array(DOCUMENT),
    useAbbrevations -> false,
    customBounds -> Array.empty[String]
  )
```
I would assume we need to modify this to the below:

```
  setDefault(
    inputCols -> Array(DOCUMENT),
    useAbbrevations -> false,
    useCustomBoundsOnly -> false,
    customBounds -> Array.empty[String]
  )
```

## Your Environment

* Version used: spark-nlp 1.5.1 apache spark 2.3.0 scala 2.11.12
* Operating System and version (desktop or mobile): macOS 10.13.4

**Comment by saifjsl** [comment]
Hello @superman24-7 

I am sorry I missed this! You are indeed right and this is not failing in our tests only because we test it in Python, and python has such default value.

Release 1.5.2 had some flaws so we'll be releasing a hotfix shortly and will very probably fix this.

**Comment by saifjsl** [comment]
I have tested and, even though the error is correct, for me it works if I call setUseCustomBoundsOnly(false) on the SentenceDetector.

**Comment by superman24-7** [comment]
Thanks @saifjsl. 

After further testing, calling setUseCustomBoundsOnly(false) on the SentenceDetector succeeds with:

```
import com.johnsnowlabs.nlp.RecursivePipeline

val pipeline = new RecursivePipeline()
      .setStages(stages)
```

but fails with the exception when declaring the pipeline as:

```
import org.apache.spark.ml.Pipeline  
  
val pipeline = new Pipeline()
      .setStages(stages)
```

**Comment by saifjsl** [comment]
We'll be shortly releasing 1.5.3 with the param default value fix. after this it should work fine.

**Comment by saifjsl** [comment]
Should be fixed now
