### ISSUE TITLE
Error while using 1.5.3 with python 2.7.11

### ISSUE THREAD

**Issue by surendralalwani** [JohnSnowLabs/spark-nlp#207]
## Description
```
from sparknlp.annotator import NerCrfModel, Lemmatizer, Tokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sparknlp/__init__.py", line 2, in <module>
    from sparknlp import annotator
  File "sparknlp/annotator.py", line 14, in <module>
    import com.johnsnowlabs.nlp
  File "com/johnsnowlabs/nlp/__init__.py", line 5, in <module>
    sys.modules['com.johnsnowlabs.nlp'] = sparknlp.annotator
AttributeError: 'module' object has no attribute 'annotator'
```

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/205

Thanks @surendralalwani
