### ISSUE TITLE
Using pretrained in PerceptronModel results in NoClassDefFoundError

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#212]
Hi,

I am following up on an issue I reported before: https://github.com/JohnSnowLabs/spark-nlp/issues/162

I am still experiencing the same issue in version 1.5.4 on local Spark:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AnonymousAWSCredentials
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.<init>(ResourceDownloader.scala:51)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.<clinit>(ResourceDownloader.scala)
	at com.johnsnowlabs.nlp.annotators.pos.perceptron.PretrainedPerceptronModel$class.pretrained$default$3(PerceptronModel.scala:72)
	at com.johnsnowlabs.nlp.annotator$PerceptronModel$.pretrained$default$3(annotator.scala:63)
	at Test_NLP_Libraries$.Test_English(Test_NLP_Libraries.scala:76)
	at Main$.main(Main.scala:18)
	at Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AnonymousAWSCredentials
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
Here is my sbt build: https://github.com/multivacplatform/multivac-nlp/blob/master/build.sbt

Many thanks,
Maziyar

**Comment by saifjsl** [comment]
Should be fixed
