### ISSUE TITLE
S3 access issue while using pretrained models 

### ISSUE THREAD

**Issue by psharma-cloudera** [JohnSnowLabs/spark-nlp#2180]
I am getting an AmazonS3Exception while trying to run some code that uses a pretrained model

## Description
When running this code in scala:

import com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel
val posModel = PerceptronModel.pretrained().
  setInputCols(Array("tokenized_content", "content_sentences")).
  setOutputCol("pos")

## Expected Behavior
I expect the model data to be downloaded

## Current Behavior
But, I am getting the following exception:

Name: com.amazonaws.services.s3.model.AmazonS3Exception
Message: All access to this object has been disabled (Service: Amazon S3; Status Code: 403; Error Code: AllAccessDisabled; Request ID: 1BF1226D4909F783)
StackTrace:   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168)
  at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1378)
  at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1255)
  at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:69)
  at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:81)
  at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:159)
  at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:399)
  at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:320)
  at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:360)
  at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:355)
  at com.johnsnowlabs.nlp.HasPretrained$class.pretrained(HasPretrained.scala:27)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel$.com$johnsnowlabs$nlp$annotators$pos$perceptron$ReadablePretrainedPerceptron$$super$pretrained(PerceptronModel.scala:108)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.ReadablePretrainedPerceptron$class.pretrained(PerceptronModel.scala:105)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel$.pretrained(PerceptronModel.scala:108)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel$.pretrained(PerceptronModel.scala:108)
  at com.johnsnowlabs.nlp.HasPretrained$class.pretrained(HasPretrained.scala:34)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel$.com$johnsnowlabs$nlp$annotators$pos$perceptron$ReadablePretrainedPerceptron$$super$pretrained(PerceptronModel.scala:108)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.ReadablePretrainedPerceptron$class.pretrained(PerceptronModel.scala:102)
  at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel$.pretrained(PerceptronModel.scala:108)

## Steps to Reproduce
Run the code above

## Your Environment

* Spark NLP version: com.johnsnowlabs.nlp:spark-nlp_2.11:2.6.5
* Setup and installation (Pypi, Conda, Maven, etc.): Scala
* Operating System and version: Linux

**Comment by C-K-Loan** [comment]
Hi @psharma-cloudera 

there was a small issue with our S3, but it is resolved now and you will not encounter this error if you try to download a model again :)

**Comment by Ldallison** [comment]
I had the same problem for approx the last 20 minutes, with several models. Same thing just downloading them from johnsnowlabs web site. Mine are working again now.
