### ISSUE TITLE
NER confidence score computation throwing exception

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [JohnSnowLabs/spark-nlp#2185]
## Description
It seems that when the NER receives a NaN from TF, the Java code to parse that value explodes.
Check stacktrace,

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
326 raise Py4JJavaError(
327 "An error occurred while calling {0}{1}{2}.\n".
--> 328 format(target_id, ".", name), value)
329 else:
330 raise Py4JError(

Py4JJavaError: An error occurred while calling o1214.fullAnnotateJava.
: java.lang.NumberFormatException
at java.math.BigDecimal.<init>(BigDecimal.java:497)
at java.math.BigDecimal.<init>(BigDecimal.java:827)
at scala.math.BigDecimal$.decimal(BigDecimal.scala:52)
at scala.math.BigDecimal$.apply(BigDecimal.scala:249)
at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2$$anonfun$7.apply(TensorflowNer.scala:80)
at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2$$anonfun$7.apply(TensorflowNer.scala:80)
at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
at scala.collection.immutable.Stream.drop(Stream.scala:858)
at scala.collection.immutable.Stream.drop(Stream.scala:202)
at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:64)
at scala.collection.immutable.Stream.apply(Stream.scala:202)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder$$anonfun$convertBatchTags$1$$anonfun$apply$8$$anonfun$apply$9.apply(NerDatasetEncoder.scala:143)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder$$anonfun$convertBatchTags$1$$anonfun$apply$8$$anonfun$apply$9.apply(NerDatasetEncoder.scala:143)
at scala.Option.map(Option.scala:146)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder$$anonfun$convertBatchTags$1$$anonfun$apply$8.apply(NerDatasetEncoder.scala:143)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder$$anonfun$convertBatchTags$1$$anonfun$apply$8.apply(NerDatasetEncoder.scala:141)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder$$anonfun$convertBatchTags$1.apply(NerDatasetEncoder.scala:141)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder$$anonfun$convertBatchTags$1.apply(NerDatasetEncoder.scala:140)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at com.johnsnowlabs.ml.tensorflow.NerDatasetEncoder.convertBatchTags(NerDatasetEncoder.scala:140)
at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2.apply(TensorflowNer.scala:91)
at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2.apply(TensorflowNer.scala:46)
at scala.collection.Iterator$class.foreach(Iterator.scala:891)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
at com.johnsnowlabs.ml.tensorflow.TensorflowNer.predict(TensorflowNer.scala:46)
at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel.tag(NerDLModel.scala:147)
at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel.annotate(NerDLModel.scala:200)
at com.johnsnowlabs.nlp.LightPipeline$$anonfun$fullAnnotate$1.apply(LightPipeline.scala:32)
at com.johnsnowlabs.nlp.LightPipeline$$anonfun$fullAnnotate$1.apply(LightPipeline.scala:20)
at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
at com.johnsnowlabs.nlp.LightPipeline.fullAnnotate(LightPipeline.scala:20)
at com.johnsnowlabs.nlp.LightPipeline.fullAnnotateJava(LightPipeline.scala:53)
at com.johnsnowlabs.nlp.LightPipeline$$anonfun$fullAnnotateJava$2.apply(LightPipeline.scala:59)
at com.johnsnowlabs.nlp.LightPipeline$$anonfun$fullAnnotateJava$2.apply(LightPipeline.scala:58)
at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

## Expected Behavior
The NaN shouldn't maket everyting explode. Not sure if we should ask instead why TF is returning Nan?

## Possible Solution
It seems that way to isolate and handle this is explained here,

https://stackoverflow.com/a/41582911/537068

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
This should be fixed in the latest releases
