### ISSUE TITLE
Py4JJavaError: An error occurred while calling 

### ISSUE THREAD

**Issue by Mushr0o0o0m** [JohnSnowLabs/spark-nlp#2188]
Hi, I'm trying to run a simple example using a pre-trained pipeline from the Spark NLP library. I get an error when I'm downloading the pipeline using:

pretrained_pipeline = PretrainedPipeline('recognize_entities_dl', lang='en')

Error: 
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)

Spark NLP version:  2.7.1
Apache Spark version:  3.0.1

**Comment by maziyarpanahi** [comment]
Hi,
We don’t support Apache Spark 3.0.x yet: https://github.com/JohnSnowLabs/spark-nlp#apache-spark-support
