### ISSUE TITLE
Provided Example works on explain_document_dl  , spell_check_ml gives the error

### ISSUE THREAD

**Issue by arun2dot0** [JohnSnowLabs/spark-nlp#2305]
Code
    SparkNLP.version()
    val spark = SparkSession.builder()
      .appName("nlp")
      .master("local[*]")
      .getOrCreate()

  val testData2 = spark.createDataFrame(Seq(
      (1, "Harry Potter is a great muvie"),
      (2, "Harry Potter is a great book")
    )).toDF("id", "text")

    val pipeline = PretrainedPipeline("spell_check_ml", lang="en")
    val annotation = pipeline.transform(testData2.select(col("text")))
    annotation.show()

Exception:
Download done! Loading the resource.
Exception in thread "main" java.util.NoSuchElementException: Param trimAndClearNewLines does not exist.
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)

Versions
scalaVersion := "2.11.12"
val sparkVersion = "2.4.7"

resolvers ++= Seq(
  "bintray-spark-packages" at "https://dl.bintray.com/spark-packages/maven",
  "Typesafe Simple Repository" at "https://repo.typesafe.com/typesafe/simple/maven-releases",
  "MavenRepository" at "https://mvnrepository.com"
)

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion,
  "org.apache.spark" %% "spark-sql" % sparkVersion,

  // streaming
  "org.apache.spark" %% "spark-streaming" % sparkVersion,

  //ml
  "org.apache.spark" %% "spark-mllib" % "2.4.7",

  //nlp
  "com.johnsnowlabs.nlp" % "spark-nlp_2.11" % "2.7.3"

)

**Comment by arun2dot0** [comment]
it belongs to spark ml
