### ISSUE TITLE
error loading CoNLL training dataset

### ISSUE THREAD

**Issue by ByronJames** [JohnSnowLabs/spark-nlp#2343]
Just reproducing the materials in a tutorial to familiarize myself with SparkNLP. Spark & Spark NLP seem to be running properly & can print version numbers to console. 

importing CoNLL works.

## Description
CoNLL().readDataset(spark, './eng.train') results in the following error:

## Expected Behavior
Should load and read the training dataset & output to console.

## Current Behavior
Error:
Traceback (most recent call last):
  File "sparky.py", line 15, in <module>
    training_data = CoNLL().readDataset(spark, './eng.train')
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\sparknlp\training.py", line 18, in __init__
    super(CoNLL, self).__init__("com.johnsnowlabs.nlp.training.CoNLL",
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\sparknlp\internal.py", line 129, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\sparknlp\internal.py", line 139, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\pyspark\ml\wrapper.py", line 69, in _new_java_obj
    return java_obj(*java_args)
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\py4j\java_gateway.py", line 1568, in __call__
    return_value = get_return_value(
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\pyspark\sql\utils.py", line 128, in deco
    return f(*a, **kw)
  File "D:\ProgramData\Anaconda3\envs\RnD\lib\site-packages\py4j\protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.training.CoNLL.
: java.lang.NoClassDefFoundError: scala/Product$class
        at com.johnsnowlabs.nlp.training.CoNLL.<init>(CoNLL.scala:17)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

## Possible Solution
Not sure

## Steps to Reproduce

1. from sparknlp.training import CoNLL
2. CoNLL().readDataset(spark, './eng.train')

## Context
Bug/error is preventing progress on tutorials & orientation on SparkNLP.

## Your Environment
Spark NLP version:  2.7.4
Apache Spark version:  3.0.2
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
Conda/Pip set up
Window s10 Pro

**Comment by maziyarpanahi** [comment]
Hi,
We don’t support Apache Spark version: 3.x, please use Apache Spark 2.4.x for both Spark and PySpark. (The requirements and compatibility are in the README)

**Comment by ByronJames** [comment]
Yep, that was it - I installed the v. 3.x of Spark - ah well, live & learn.
