### ISSUE TITLE
NerConverter IllegalArgumentException - chunk offsets are not within tokens

### ISSUE THREAD

**Issue by dkincaid** [JohnSnowLabs/spark-nlp#2399]
## Description
When using NerConverter we are getting an error on some medical notes that we're trying to process. 

## Current Behavior
When trying to view the results of an NLP pipeline which contains an NerConverter we are getting the following error. I can provide the file containing the document causing the error separately. I can't attach it here because it contains some personal information.

```
Caused by: java.lang.IllegalArgumentException: requirement failed: Failed to flush entities in NerConverter. Chunk offsets 103 - 121 are not within tokens:
HISTORY||:||Wt||:||8.8||pounds||,||T||:||not||obtained||,||P||:||144bpm||,||R||:||40rpm||Current||Medications||:||Prednisone||2.5mg||in||AM||&||1.25mg||in||PM||;||Clindamycin||was||discontinued
for sentence:
PRESENTING CONCERN:  PDVM update.
	at scala.Predef$.require(Predef.scala:224)
	at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$.com$johnsnowlabs$nlp$annotators$ner$NerTagsEncoding$$flushEntity$1(NerTagsEncoding.scala:31)
	at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$$anonfun$fromIOB$1.apply$mcVI$sp(NerTagsEncoding.scala:49)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$.fromIOB(NerTagsEncoding.scala:46)
	at com.johnsnowlabs.nlp.annotators.ner.NerConverter$$anonfun$2.apply(NerConverter.scala:76)
	at com.johnsnowlabs.nlp.annotators.ner.NerConverter$$anonfun$2.apply(NerConverter.scala:75)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.johnsnowlabs.nlp.annotators.ner.NerConverter.annotate(NerConverter.scala:75)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
	... 14 more
```

## Steps to Reproduce

1. Create a pipeline that includes document assembler, sentence detector DL (sentence_detector_dl_healthcare), tokenizer, word embeddings (embeddings_clinical), NerDL (ner_clinical_large), ner converter
2. Fit and transform the pipeline against a dataset containing certain documents
3. View the resulting data frame

## Your Environment
* Spark NLP version `sparknlp.version()`: 2.7.5 (happens with at least 2.7.3 as well)
* Apache NLP version `spark.version`: 2.4.5
* Java version `java -version`: openjdk version 1.8.0_282

**Comment by alinapetukhova** [comment]
Fixed in the new version of **sentence_detector_dl_healthcare** and released. @dkincaid  make sure you clear models cache before testing it.
