### ISSUE TITLE
Error while loading model files

### ISSUE THREAD

**Issue by ashu122** [JohnSnowLabs/spark-nlp#245]
I am unable to load model files from local and from s3 in my spark application which i trained using NerCrfModel.  

## Description

While trying to load the model files from local directory and from s3 this is what I am getting.

`Exception in thread "main" org.apache.spark.SparkException: addFile does not support local directories when not running local mode.
	at org.apache.spark.SparkContext.addFile(SparkContext.scala:1537)
	at com.johnsnowlabs.nlp.embeddings.SparkWordEmbeddings$.copyIndexToCluster(SparkWordEmbeddings.scala:86)
	at com.johnsnowlabs.nlp.embeddings.SparkWordEmbeddings$.apply(SparkWordEmbeddings.scala:111)
	at com.johnsnowlabs.nlp.HasWordEmbeddings$class.deserializeEmbeddings(HasWordEmbeddings.scala:57)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel.deserializeEmbeddings(NerCrfModel.scala:19)
	at com.johnsnowlabs.nlp.embeddings.EmbeddingsReadable$class.readEmbeddings(EmbeddingsReadable.scala:8)
	at com.johnsnowlabs.nlp.annotators.ner.crf.NerCrfModel$.readEmbeddings(NerCrfModel.scala:84)
	at com.johnsnowlabs.nlp.embeddings.EmbeddingsReadable$$anonfun$1.apply(EmbeddingsReadable.scala:11)
	at com.johnsnowlabs.nlp.embeddings.EmbeddingsReadable$$anonfun$1.apply(EmbeddingsReadable.scala:11)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
`

This is how i load the models  -

`val model = PipelineModel.read.load("/opt/model/")`

I have checked that the model files are present at this path on all the worker nodes. So it looks like the library is trying to call spark's addFile method which doesn't support local file directories in cluster or client mode.
Please let me know if you need more information.
Thanks.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ypandit** [comment]
Facing the same issue with External, Validation and Test dataset in `NerDLApproach`. The path from `pyspark.SparkFiles.get('train.txt')` is already available on all workers, however, I get the error `addFile does not support local directories when not running local mode.`

**Comment by saifjsl** [comment]
It is probable we include in next release, an override setting for shared path for internal embeddings in an S3 framework. We'll include instructions on the website and github

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/257

**Comment by saifjsl** [comment]
Hi, please try this solution on the new releases

https://github.com/JohnSnowLabs/spark-nlp#s3-cluster-with-no-hadoop-configuration
