### ISSUE TITLE
NerConverter IllegalArgumentException - chunk offsets are not within tokens

### ISSUE THREAD

**Issue by rahulraina7** [JohnSnowLabs/spark-nlp#2476]
## Description
NerConverter fails while trying to flush entities

## Current Behavior
StackTrace : 

```
Caused by: java.lang.IllegalArgumentException: requirement failed: Failed to flush entities in NerConverter. Chunk offsets 11 - 17 are not within tokens:
johndoe||texasfloria
for sentence:
.
	at scala.Predef$.require(Predef.scala:224)
	at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$.com$johnsnowlabs$nlp$annotators$ner$NerTagsEncoding$$flushEntity$1(NerTagsEncoding.scala:31)
	at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$$anonfun$fromIOB$1.apply$mcVI$sp(NerTagsEncoding.scala:49)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$.fromIOB(NerTagsEncoding.scala:46)
	at com.johnsnowlabs.nlp.annotators.ner.NerConverter$$anonfun$2.apply(NerConverter.scala:76)
	at com.johnsnowlabs.nlp.annotators.ner.NerConverter$$anonfun$2.apply(NerConverter.scala:75)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.johnsnowlabs.nlp.annotators.ner.NerConverter.annotate(NerConverter.scala:75)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:108)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:107)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1063)
	... 31 more

```

## Steps to Reproduce
```
sentences = [
    ["""word1 word2 word3 word4.word5 rahul-raina rahul,raina john,doe........... john.doe texas.floria, """]]

data = spark.createDataFrame(sentences).toDF("text")

document = (
    DocumentAssembler()
    .setInputCol("text")
    .setOutputCol("document")
    .setCleanupMode("inplace_full")
)

document_normalizer = (
    DocumentNormalizer()
    .setInputCols("document")
    .setOutputCol("document_normalized")
)

sentence = (
    SentenceDetector().setInputCols(['document_normalized']).setOutputCol('sentence')
)

token = (
    Tokenizer()
    .setInputCols(['sentence'])
    .setOutputCol('token')
    .setMinLength(2)
    .setSplitChars(['-', ','])
    .setContextChars(['(', ')', '?', '!'])
)

normalizer = (
    Normalizer()
    .setInputCols(["token"])
    .setOutputCol("token_normalized")
    .setSlangMatchCase(True)
)

lemmatizer = (
    LemmatizerModel.load(
        'file:///opt/workspace/data/models/current/lemma_antbnc_en/'
    )
    .setInputCols(["token_normalized"])
    .setOutputCol("lemma")
    .setLazyAnnotator(False)
)

stopwords = self.sc.textFile(
    "file:///opt/workspace/data/models/current/stopwords-en.txt"
).collect()

stop_words_cleaner = (
    StopWordsCleaner()
    .setInputCols(["lemma"])
    .setOutputCol("lemma")
    .setStopWords(stopwords)
    .setCaseSensitive(False)
)

bert_small_embeddings = (
    BertEmbeddings.load(
        'file:///opt/workspace/data/models/current/small_bert/'
    ) # small_bert_L2_128_en_2.6.0_2.4_1598344320681.zip
    .setInputCols(["document_normalized", "token_normalized"])
    .setOutputCol("embeddings")
)

onto_ner_bert_small = (
    NerDLModel.load(
        "file:///opt/workspace/data/models/current/onto_small_bert/"
    ) # onto_small_bert_L2_128_en_2.7.0_2.4_1607198998042.zip
    .setInputCols(["document_normalized", "token_normalized", "embeddings"])
    .setIncludeConfidence(True)
    .setOutputCol("ner")
)

ner_converter = (
    NerConverter()
    .setInputCols(["sentence", "token_normalized", "ner"])
    .setWhiteList(["PERSON", "LOC", "GPE"])
    .setOutputCol("ner_chunk")
    .setLazyAnnotator(False)
)

finisher = Finisher().setInputCols(["token_normalized"]).setCleanAnnotations(False)

prediction_pipeline = Pipeline(
    stages=[
        document,
        document_normalizer,
        sentence,
        token,
        normalizer,
        lemmatizer,
        stop_words_cleaner,
        bert_small_embeddings,
        onto_ner_bert_small,
        ner_converter,
        finisher,
    ]
)

target = prediction_pipeline.fit(data).transform(data)

target.limit(1).toPandas()

```

## Your Environment

* Spark NLP version `sparknlp.version()`: '2.7.4'
* Apache NLP version `spark.version`: 2.4.4
* Java version `java -version`: openjdk version "1.8.0_282"

**Comment by rahulraina7** [comment]
Hello @maziyarpanahi @alinapetukhova. I have done some investigation on this.

This happens when there are more ```documents ``` then ```sentences``` in 

https://github.com/JohnSnowLabs/spark-nlp/blob/aa7077f5746ce8ebdb0a5dece7c5171b519fb77b/src/main/scala/com/johnsnowlabs/nlp/annotators/ner/NerConverter.scala#L72-L78

the ```docs.zipWithIndex``` would essentially give wrong incorrect indexes.

I am not well versed with scala but filter ```docs``` based on the unpacked ```sentences``` like this should work.
These seem to work for the above-mentioned dataframe and the tests don't seem to break.


```
    val docs = annotations.filter(a => a.annotatorType == AnnotatorType.DOCUMENT && sentences.exists(
      b=> b.indexedTaggedWords.exists(c=> c.begin >= a.begin && c.end <= a.end)
    ))
```
This filters ```docs``` to check within ```sentences``` bounds

I might be wrong, thought might help

**Comment by maziyarpanahi** [comment]
Thanks @rahulraina7 
What you are doing is to make sure only sentences/documents being selected have any tokens. I will test this a few more times and will include it in the next release
