### ISSUE TITLE
Issue while loading a saved model into a different cluster

### ISSUE THREAD

**Issue by surendralalwani** [JohnSnowLabs/spark-nlp#250]
The below error occurred when I created and saved a custom model in CDH cluster and tried to load in AWS EMR.

Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-5073389282467574021.py", line 367, in <module>
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-5073389282467574021.py", line 360, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 1, in <module>
  File "/usr/lib/spark/python/pyspark/ml/util.py", line 257, in load
    return cls.read().load(path)
  File "/usr/lib/spark/python/pyspark/ml/util.py", line 197, in load
    java_obj = self._jread.load(path)
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
IllegalArgumentException: u'Wrong FS: s3://blah/model/ner_crf_custom_model/stages/4_NER_b3f45074bee5/embeddings, expected: hdfs://ip-.us-west-2.compute.internal:8020'

**Comment by surendralalwani** [comment]
It was 1.5.0

**Comment by saifjsl** [comment]
Hi, is it working on the current versions? Please try these instructions:

https://github.com/JohnSnowLabs/spark-nlp#s3-cluster-with-no-hadoop-configuration
