### ISSUE TITLE
Pretrained Lemmatization model fails to download for 1.6.0-1.6.2

### ISSUE THREAD

**Issue by danielchalef** [JohnSnowLabs/spark-nlp#265]
## Description

I'm unable to download the pretrained "lemma-fast" model for versions 1.6.0-1.6.2. Strangely, I was able to do so for version 1.6.0 in the recent past.

## Expected Behavior

Model downloads to cache directory and is available for use.

## Current Behavior

Download errors out. See stack trace below.

## Steps to Reproduce

This occurs with both Python 3.6.6 and 3.4.8 (stock on EMR).
```
> pyspark --packages JohnSnowLabs:spark-nlp:1.6.2
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.3.1
      /_/

Using Python version 3.4.8 (default, Apr 25 2018 23:50:36)
SparkSession available as 'spark'.
>>> from sparknlp.pretrained import ResourceDownloader
>>> downloader = ResourceDownloader()
>>> downloader.clearCache("lemma_fast", "en")
18/08/21 04:30:40 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/tmp/spark-5fd7d745-a44b-4cfd-adb0-be33eb401e4f/userFiles-d21e976b-97d1-4714-9589-8d4077695f64/JohnSnowLabs_spark-nlp-1.6.2.jar/sparknlp/pretrained/__init__.py", line 45, in clearCache
  File "/mnt/tmp/spark-5fd7d745-a44b-4cfd-adb0-be33eb401e4f/userFiles-d21e976b-97d1-4714-9589-8d4077695f64/JohnSnowLabs_spark-nlp-1.6.2.jar/sparknlp/internal.py", line 66, in __init__
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.clearCache.
: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
        at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:20)
        at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:50)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.parseJson(ResourceMetadata.scala:53)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$$anonfun$readResources$1.apply(ResourceMetadata.scala:82)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$$anonfun$readResources$1.apply(ResourceMetadata.scala:81)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at scala.collection.AbstractIterator.to(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
        at scala.collection.AbstractIterator.toList(Iterator.scala:1336)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.readResources(ResourceMetadata.scala:84)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.readResources(ResourceMetadata.scala:76)
        at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:67)
        at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.clearCache(S3ResourceDownloader.scala:146)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.clearCache(ResourceDownloader.scala:138)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.clearCache(ResourceDownloader.scala:134)
        at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.clearCache(ResourceDownloader.scala:189)
        at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.clearCache(ResourceDownloader.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
```

## Context

Unable to run NLP ETL pipeline.

## Your Environment

* Version used: 1.6.0-1.6.2
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by saifjsl** [comment]
hi @danielchalef can you confirm if it is working now? I have a last-minute type in pretrained metadata causing all pretrained models to fail.

**Comment by danielchalef** [comment]
That worked. Thanks!
