### ISSUE TITLE
 sparknlp_contrib_spar: cannot open shared object file

### ISSUE THREAD

**Issue by peili-uzh** [JohnSnowLabs/spark-nlp#2749]
When using NerDLApproach to train a Ner model, the following error pops up:
`An exception or error caused a run to abort: libtensorflow_framework.so: cannot open shared object file: No such file or directory 
java.lang.UnsatisfiedLinkError: libtensorflow_framework.so: cannot open shared object file: No such file or directory
	at org.tensorflow.TensorFlow.loadLibrary(TensorFlow.java:47)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.loadContribToTensorflow(LoadsContrib.scala:68)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLApproach.beforeTraining(NerDLApproach.scala:104)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:44)`

It points to `TensorFlow.loadLibrary(fp1)`, and the file `fp1` indeed exists in path:  `/tmp/spark-89f66167-45a0-413f-929b-5333a301db1e/userFiles-4ccf632e-c865-4d26-93a9-72346b266ad9/sparknlp_contrib_spar`

**Comment by peili-uzh** [comment]
Spark NLP version: 2.2.2.4

**Comment by maziyarpanahi** [comment]
@peili-uzh 
Sorry without filling in the issue template we cannot help. All that information needed. (the more the better to reproduce the issue)
