### ISSUE TITLE
Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.DocumentAssembler.

### ISSUE THREAD

**Issue by Nebraw** [JohnSnowLabs/spark-nlp#2750]
## Description
Hello, i'm on a NLP project and i would use spark-NLP to preprocess some documents, but when i try to use the Annotators
i got the error that follow:

## Expected Behavior
...
## Current Behavior
Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.DocumentAssembler.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V
	at com.johnsnowlabs.nlp.DocumentAssembler.<init>(DocumentAssembler.scala:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

## Possible Solution
No Idea

## Steps to Reproduce
import sparknlp 
from  pyspark.sql import SparkSession
from sparknlp.base import Finisher, DocumentAssembler
from sparknlp.annotator import (Tokenizer, Normalizer, LemmatizerModel)

spark = sparknlp.start()
document_assembler =  DocumentAssembler().setInputCol(value='text').setOutputCol('document')
## Context
I try to create a pipeline with spark-nlp, to preprocess some documents.
## Annotators affected by this bug
-DocumentAssembler()
-Tokenizer()
-Normalizer()
-Lemmatizer()

## Your Environment
* Spark NLP version: 2.7.5
* Apache Spark version: 2.4.3
* Pyspark version: 2.4.3
* Java version:
                     openjdk version "1.8.0_265"
                    OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
                    OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
* Setup and installation (Pypi, Conda, Maven, etc.): spark-nlp and spark was installed with pip
* Operating System and version: Linux

**Comment by maziyarpanahi** [comment]
You have a mismatch between spark-nlp and spark. Please read this discussion:
https://github.com/JohnSnowLabs/spark-nlp/discussions/2562

Make sure you are really on those versions via:
sparknlp.version() and spark.version to be sure

**Comment by Nebraw** [comment]
Hello, 
I checked the version of spark-nlp and spark:
spark-nlp=2.7.5
spark = 2.4.3
![Spark_NLP version](https://user-images.githubusercontent.com/11179240/114687622-dba29b00-9d0b-11eb-9b1a-4a4904aa35c6.PNG)

**Comment by Nebraw** [comment]
hmmm,  ok sorry, the error is gone.

I sorry for the trouble, i work on a server and i don't have the control of my environnement.

**Comment by maziyarpanahi** [comment]
No worries, probably it was an environment with `pyspark==3.x` which is compatible with `spark-nlp=3.0.0`

Don't hesitate to create new issues if you face any problems.
