### ISSUE TITLE
sentenceDetector fails when bound is between two words that contain apostrophes

### ISSUE THREAD

**Issue by haimco10** [JohnSnowLabs/spark-nlp#276]
## Description

`SentenceDetector` annotator fails to detect bounds when bound is between two words that contain apostrophes.

## Expected Behavior
In such case, it should split such text based on the given bounds.
For example: 
> "We don't want to ignore this period. Isn't it right?"

Should become:
> "We don't want to ignore this period."
    "Isn't it right?"

## Current Behavior
It doesn't split text on such cases.
For example, the sentence: 
> "We don't want to ignore this period. Isn't it right?"

Stays the same.

## Possible Solution
The reason that it fails, is because it tries to protect everything within single quotes from being splitted. 
My (simple) suggestion is to consider two apostrophes as single quotes  only if the first one is coming at the beginning of the word. 

Practically I suggest to replace the following line of code from

https://github.com/JohnSnowLabs/spark-nlp/blob/c2371f58f7d91221bbfa9265debd3afd10588c90/src/main/scala/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/PragmaticContentFormatter.scala#L326

to:
`.addRule(new RegexRule("(?<=\\s|^)'(?:[^']|'\\w)+'", "betweenPunctuations-singleQuot"))`

**Comment by haimco10** [comment]
@saifjsl , Can you please confirm if it's indeed a bug?

**Comment by saifjsl** [comment]
Hi @haimco10 not sure why I missed this issue. Thanks for reporting this.

It is not necessarily a bug, it's a product decision. The best way would be to have an option to be capable of breaking blocks (quotes, parenthesis content, etc).

I'll take a look into this or feel free to propose a way that makes different use-cases happy.

**Comment by haimco10** [comment]
Thanks @saifjsl. It is possible to have the option to break or protect single quotes, but once we decide to protect them, we need to make sure it  behaves correctly. This is why I think it's a bug.

My suggestion, as I suggested above, is:
To replace the current regex: `'[\\w\\s?!\\.,']+'` with  `(?<=\\s|^)'(?:[^']|'\\w)+'`

I created an example here:
- With the current regex: http://rubular.com/r/QKzU17kFWN
- With suggested regex: http://rubular.com/r/pX7vBTUbMO

**Comment by saifjsl** [comment]
Hello @haimco10 

We were reviewing your Pull request (and actually merged). But after further testing, before release. We found it caused a several issue when training a NerCrf model with sentence detector after this change.

If you are willing to try (and sorry for long delayed responses), this is the text that causes a 

```
: java.lang.StackOverflowError
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3779)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4787)
```
With the following target text:
```
Israel plays down fears of war with Syria .

Colleen Siegel

JERUSALEM 1996-08-22

Israel 's outgoing peace negotiator with Syria said on Thursday current tensions between the two countries appeared to be a storm in a teacup .

Itamar Rabinovich , who as Israel 's ambassador to Washington conducted unfruitful negotiations with Syria , told Israel Radio it looked like Damascus wanted to talk rather than fight .

" It appears to me the Syrian priority is still to negotiate .

The Syrians are confused , they are definitely tense , but the general assessment here in Washington is that this is essentially a storm in a teacup , " he said .

Rabinovich is winding up his term as ambassador .

He will be replaced by Eliahu Ben-Elissar , a former Israeli envoy to Egypt and right-wing Likud party politician .

Israel on Wednesday sent Syria a message , via Washington , saying it was committed to peace and wanted to open negotiations without preconditions .

But it slammed Damascus for creating what it called a dangerous atmosphere .

Syria accused Israel on Wednesday of launching a hysterical campaign against it after Israeli television reported that Damascus had recently test fired a missile .

It said its arms purchases were for defensive purposes .

" The message that we sent to ( Syrian President Hafez al- ) Assad is that Israel is ready at any time without preconditions to enter peace negotiations , " Israeli Foreign Minister David Levy told Israel Radio in an interview .

Tension has mounted since Israeli Prime Minister Benjamin Netanyahu took office in June vowing to retain the Golan Heights Israel captured from Syria in the 1967 Middle East war .

Israeli-Syrian peace talks have been deadlocked over the Golan since 1991 despite the previous government 's willingness to make Golan concessions .

Peace talks between the two sides were last held in February .

" The voices coming out of Damascus are bad , not good .

The media ...

are full of expressions and declarations that must be worrying ...

this artificial atmosphere is very dangerous because those who spread it could become its prisoners , " Levy said .

" We expect from Syria , if its face is to peace , that it will answer Israel 's message to enter peace negotiations because that is our goal , " he said . "

We do not want a war , God forbid .

No one benefits from wars . "

Israel 's Channel Two television said Damascus had sent a " calming signal " to Israel .

It gave no source for the report .

Netanyahu and Levy 's spokesmen said they could not confirm it .

The television also said that Netanyahu had sent messages to reassure Syria via Cairo , the United States and Moscow .
```

Also, you can reproduce it with this block of code in the unit tests:

```
val tAns = Array("Israel plays down fears of war with Syria .\n\nColleen Siegel\n\nJERUSALEM 1996-08-22\n\nIsrael 's outgoing peace negotiator with Syria said on Thursday current tensions between the two countries appeared to be a storm in a teacup .\n\nItamar Rabinovich , who as Israel 's ambassador to Washington conducted unfruitful negotiations with Syria , told Israel Radio it looked like Damascus wanted to talk rather than fight .\n\n\" It appears to me the Syrian priority is still to negotiate .\n\nThe Syrians are confused , they are definitely tense , but the general assessment here in Washington is that this is essentially a storm in a teacup , \" he said .\n\nRabinovich is winding up his term as ambassador .\n\nHe will be replaced by Eliahu Ben-Elissar , a former Israeli envoy to Egypt and right-wing Likud party politician .\n\nIsrael on Wednesday sent Syria a message , via Washington , saying it was committed to peace and wanted to open negotiations without preconditions .\n\nBut it slammed Damascus for creating what it called a dangerous atmosphere .\n\nSyria accused Israel on Wednesday of launching a hysterical campaign against it after Israeli television reported that Damascus had recently test fired a missile .\n\nIt said its arms purchases were for defensive purposes .\n\n\" The message that we sent to ( Syrian President Hafez al- ) Assad is that Israel is ready at any time without preconditions to enter peace negotiations , \" Israeli Foreign Minister David Levy told Israel Radio in an interview .\n\nTension has mounted since Israeli Prime Minister Benjamin Netanyahu took office in June vowing to retain the Golan Heights Israel captured from Syria in the 1967 Middle East war .\n\nIsraeli-Syrian peace talks have been deadlocked over the Golan since 1991 despite the previous government 's willingness to make Golan concessions .\n\nPeace talks between the two sides were last held in February .\n\n\" The voices coming out of Damascus are bad , not good .\n\nThe media ...\n\nare full of expressions and declarations that must be worrying ...\n\nthis artificial atmosphere is very dangerous because those who spread it could become its prisoners , \" Levy said .\n\n\" We expect from Syria , if its face is to peace , that it will answer Israel 's message to enter peace negotiations because that is our goal , \" he said . \"\n\nWe do not want a war , God forbid .\n\nNo one benefits from wars . \"\n\nIsrael 's Channel Two television said Damascus had sent a \" calming signal \" to Israel .\n\nIt gave no source for the report .\n\nNetanyahu and Levy 's spokesmen said they could not confirm it .\n\nThe television also said that Netanyahu had sent messages to reassure Syria via Cairo , the United States and Moscow .")
  val t = "Israel plays down fears of war with Syria .\n\nColleen Siegel\n\nJERUSALEM 1996-08-22\n\nIsrael 's outgoing peace negotiator with Syria said on Thursday current tensions between the two countries appeared to be a storm in a teacup .\n\nItamar Rabinovich , who as Israel 's ambassador to Washington conducted unfruitful negotiations with Syria , told Israel Radio it looked like Damascus wanted to talk rather than fight .\n\n\" It appears to me the Syrian priority is still to negotiate .\n\nThe Syrians are confused , they are definitely tense , but the general assessment here in Washington is that this is essentially a storm in a teacup , \" he said .\n\nRabinovich is winding up his term as ambassador .\n\nHe will be replaced by Eliahu Ben-Elissar , a former Israeli envoy to Egypt and right-wing Likud party politician .\n\nIsrael on Wednesday sent Syria a message , via Washington , saying it was committed to peace and wanted to open negotiations without preconditions .\n\nBut it slammed Damascus for creating what it called a dangerous atmosphere .\n\nSyria accused Israel on Wednesday of launching a hysterical campaign against it after Israeli television reported that Damascus had recently test fired a missile .\n\nIt said its arms purchases were for defensive purposes .\n\n\" The message that we sent to ( Syrian President Hafez al- ) Assad is that Israel is ready at any time without preconditions to enter peace negotiations , \" Israeli Foreign Minister David Levy told Israel Radio in an interview .\n\nTension has mounted since Israeli Prime Minister Benjamin Netanyahu took office in June vowing to retain the Golan Heights Israel captured from Syria in the 1967 Middle East war .\n\nIsraeli-Syrian peace talks have been deadlocked over the Golan since 1991 despite the previous government 's willingness to make Golan concessions .\n\nPeace talks between the two sides were last held in February .\n\n\" The voices coming out of Damascus are bad , not good .\n\nThe media ...\n\nare full of expressions and declarations that must be worrying ...\n\nthis artificial atmosphere is very dangerous because those who spread it could become its prisoners , \" Levy said .\n\n\" We expect from Syria , if its face is to peace , that it will answer Israel 's message to enter peace negotiations because that is our goal , \" he said . \"\n\nWe do not want a war , God forbid .\n\nNo one benefits from wars . \"\n\nIsrael 's Channel Two television said Damascus had sent a \" calming signal \" to Israel .\n\nIt gave no source for the report .\n\nNetanyahu and Levy 's spokesmen said they could not confirm it .\n\nThe television also said that Netanyahu had sent messages to reassure Syria via Cairo , the United States and Moscow ."
  "an isolated pragmatic detector" should behave like isolatedPDReadAndMatchResult(t, tAns)
```

**Comment by haimco10** [comment]
@saifjsl , I see,. It's an issue caused by a [long string Regex](https://stackoverflow.com/questions/7509905/java-lang-stackoverflowerror-while-using-a-regex-to-parse-big-strings). I will try to find a better Regex.

**Comment by saifjsl** [comment]
Thanks!!
