### ISSUE TITLE
ContextSpellCheckerModel:  ClassNotFoundException: it.unimi.dsi.fastutil.chars.Char2ObjectSortedMap

### ISSUE THREAD

**Issue by franckjay** [JohnSnowLabs/spark-nlp#2793]
## Expected Behavior
We are hoping to validate this tutorial on our Spark system: https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/SPELL_CHECKER_EN.ipynb#scrollTo=9zHSiB0skP83

## Current Behavior
This is our full stack trace:
```
spellcheck_dl download started this may take some time.
Approximate size to download 112.2 MB

[ | ]

[OK!]
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-1405345296431633783.py", line 326, in <module>
    exec(code)
  File "<stdin>", line 10, in <module>
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/annotator.py", line 2739, in pretrained
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/pretrained.py", line 41, in downloadModel
    j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/internal.py", line 176, in __init__
    super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/internal.py", line 129, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/internal.py", line 139, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/chars/Char2ObjectSortedMap
	at com.github.liblevenshtein.serialization.PlainTextSerializer.<init>(PlainTextSerializer.java:90)
	at com.johnsnowlabs.nlp.serialization.TransducerFeature.deserializeObject(Feature.scala:276)
	at com.johnsnowlabs.nlp.serialization.Feature.deserialize(Feature.scala:47)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:15)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:14)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:14)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:379)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:373)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:494)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.chars.Char2ObjectSortedMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-1405345296431633783.py", line 333, in <module>
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-1405345296431633783.py", line 326, in <module>
    exec(code)
  File "<stdin>", line 10, in <module>
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/annotator.py", line 2739, in pretrained
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/pretrained.py", line 41, in downloadModel
    j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/internal.py", line 176, in __init__
    super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/internal.py", line 129, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/usr/lib/envs/env-38-ver-29-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/sparknlp/internal.py", line 139, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/chars/Char2ObjectSortedMap
	at com.github.liblevenshtein.serialization.PlainTextSerializer.<init>(PlainTextSerializer.java:90)
	at com.johnsnowlabs.nlp.serialization.TransducerFeature.deserializeObject(Feature.scala:276)
	at com.johnsnowlabs.nlp.serialization.Feature.deserialize(Feature.scala:47)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:15)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:14)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:14)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:379)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:373)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:494)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.chars.Char2ObjectSortedMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

## Possible Solution
Absolutely no clue.

## Steps to Reproduce

1. We are following this example, step by step: https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/SPELL_CHECKER_EN.ipynb#scrollTo=9zHSiB0skP83, but in a Zeppelin notebook.

## Context
We are trying to validate the spell checker.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.2 (Also tried 2.7.5)
* Apache NLP version `spark.version`: 2.3.2
* Java version `java -version`: 1.8.0_201 (Oracle Corporation)
* Setup and installation (Pypi, Conda, Maven, etc.):Zeppelin-based solution
```
# From https://stackoverflow.com/questions/12332975/installing-python-module-within-code
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

def list_packages():
    # Now you can check to ensure that your package exists in the current pip
    subprocess.check_call([sys.executable, "-m", "pip", "list"])
    
install("spark-nlp==3.0.2")# Spark NLP for Spark 3+
```
* Operating System and version: Linux 4.14.154-99.181.amzn1.x86_64
* Link to your project (if any): https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/SPELL_CHECKER_EN.ipynb#scrollTo=9zHSiB0skP83

**Comment by maziyarpanahi** [comment]
Hi,
- Is spark.version: 2.3.2 a correct info? 
- since Zeppelin starts with SparkSession you cannot use sparknlp.start() like Jupyter, could you please share how you start SparkSession and include Spark NLP Maven/or JAR?

**Comment by franckjay** [comment]
Hi @maziyarpanahi , thanks for the quick reply! 

1. Yes, that is the correct info on Spark.
2. We have been using `spark = sparknlp.start(gpu=False, spark23=True)`, which seems to work for most pretrained models (BERT embeddings, NER, etc.)
3. In my interpreter, I have included: `artifact : com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:3.0.2`

Thanks and have a good day!

**Comment by maziyarpanahi** [comment]
Thank you, could you please let me know:
- the version of your Zeppelin
- is everything else works? Other annotators and models?

**Comment by franckjay** [comment]
@maziyarpanahi , I think my Zeppelin version is 0.6.2 based on the path I found on the UI: 
/usr/lib/zeppelin/interpreter/spark/zeppelin-spark_2.10-0.6.2.jar:/usr/lib/spark/conf . 

Yes, most other packages work except for this one and the UniversalSentenceEncoder (I raised a separate issue for that here: https://github.com/JohnSnowLabs/spark-nlp/issues/2792) .

I realize I am on an old version of Spark + Zeppelin, but unfortunately have no control over that. 

Thank you for your attention!

**Comment by maziyarpanahi** [comment]
Great this is very helpful, I will answer for USE, it’s a pretty easy fix (you are missing some configs in your SparkSession)
My best guess is that ContextSpellChecker is not compatible with Spark 2.3, however, I ask a member who developed it for better insight

**Comment by franckjay** [comment]
Thans @maziyarpanahi
