### ISSUE TITLE
UniversalSentenceEncoder-->ClassifierDLApproach pipelin Error

### ISSUE THREAD

**Issue by franklydog** [JohnSnowLabs/spark-nlp#2811]
Spark 2.4 and spark-nlp.3.0.2. the error is following:

Exception in thread "main" org.tensorflow.exceptions.TensorFlowException: Op type not registered 'SentencepieceEncodeSparse' in binary running on xxx. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
        at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:101)
        at org.tensorflow.Graph.importGraphDef(Graph.java:590)
        at org.tensorflow.Graph.importGraphDef(Graph.java:184)
        at org.tensorflow.Graph.importGraphDef(Graph.java:168)
        at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(TensorflowWrapper.scala:271)
        at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readWithSP(TensorflowWrapper.scala:383)
        at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowWithSPModel(TensorflowSerializeModel.scala:161)
        at com.johnsnowlabs.nlp.annotator.package$UniversalSentenceEncoder$.readTensorflowWithSPModel(annotator.scala:157)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel$class.readTensorflow(UniversalSentenceEncoder.scala:188)
        at com.johnsnowlabs.nlp.annotator.package$UniversalSentenceEncoder$.readTensorflow(annotator.scala:157)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel$$anonfun$2.apply(UniversalSentenceEncoder.scala:192)
        at com.johnsnowlabs.nlp.embeddings.ReadUSETensorflowModel$$anonfun$2.apply(UniversalSentenceEncoder.scala:192)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
        at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
        at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
        at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:380)
        at com.johnsnowlabs.nlp.annotator.package$UniversalSentenceEncoder$.load(annotator.scala:157)
        at com.facebac.NLP.ClassTrainEngine$$anonfun$main$2.apply(ClassTrainEngine.scala:222)
        at com.facebac.NLP.ClassTrainEngine$$anonfun$main$2.apply(ClassTrainEngine.scala:182)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.facebac.NLP.ClassTrainEngine$.main(ClassTrainEngine.scala:182)
        at com.facebac.NLP.ClassTrainEngine.main(ClassTrainEngine.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)

**Comment by maziyarpanahi** [comment]
Please use the issue template, complete all the steps, example code and required information. (Without all of the info, we have to spend a lot of time chasing those items one by one. Please use the issue template)
