### ISSUE TITLE
 Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize. : java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by ZbynekAfiala** [JohnSnowLabs/spark-nlp#2866]
## Description

I found similiar bug report(https://github.com/JohnSnowLabs/spark-nlp/issues/846) with solution but it just didn't work for me. My problem is:
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$
At this point I've tried to reproduce it on different desktop but ran into same issue. I don't know what could be the reason. I've also tried to download model and load it via BertEmbeddings.load() but same issue once again.

## Steps to Reproduce

I've followed this guide:
https://github.com/JohnSnowLabs/spark-nlp/discussions/1022

## Your Environment

Spark NLP version:  3.0.3
Apache spark version:  2.4.7
* Java version `java -version`:
* C:\Users\zbyne>java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
* Operating System and version: Windows 10
* Deployment: Jupyter python3
## Code generating error
```
import sys

from pyspark.sql import SparkSession
from pyspark.ml import PipelineModel

import sparknlp
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *
from sparknlp.pretrained import ResourceDownloader

lemmatizer = LemmatizerModel.pretrained("lemma", "cs") \
        .setInputCols(["token"]) \
        .setOutputCol("lemma")
nlp_pipeline = Pipeline(stages=[document_assembler, tokenizer, lemmatizer])
light_pipeline = LightPipeline(nlp_pipeline.fit(spark.createDataFrame([['']]).toDF("text")))
results = light_pipeline.fullAnnotate("Kromě toho, že je králem severu, je John Snow anglickým lékařem a lídrem ve vývoji anestezie a lékařské hygieny.")
```

## error 
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-6-25a5461b5173> in <module>
     10 from sparknlp.pretrained import ResourceDownloader
     11 
---> 12 lemmatizer = LemmatizerModel.pretrained("lemma", "cs") \
     13         .setInputCols(["token"]) \
     14         .setOutputCol("lemma")

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\annotator.py in pretrained(name, lang, remote_loc)
    686     def pretrained(name="lemma_antbnc", lang="en", remote_loc=None):
    687         from sparknlp.pretrained import ResourceDownloader
--> 688         return ResourceDownloader.downloadModel(LemmatizerModel, name, lang, remote_loc)
    689 
    690 

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     45     def downloadModel(reader, name, language, remote_loc=None, j_dwn='PythonResourceDownloader'):
     46         print(name + " download started this may take some time.")
---> 47         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     48         if file_size == "-1":
     49             print("Can not find the model to download please check the name!")

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in __init__(self, name, language, remote_loc)
    205     def __init__(self, name, language, remote_loc):
    206         super(_GetResourceSize, self).__init__(
--> 207             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
    208 
    209 

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    142         super(ExtendedJavaWrapper, self).__init__(java_obj)
    143         self.sc = SparkContext._active_spark_context
--> 144         self._java_obj = self.new_java_obj(java_obj, *args)
    145         self.java_obj = self._java_obj
    146 

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    152 
    153     def new_java_obj(self, java_class, *args):
--> 154         return self._new_java_obj(java_class, *args)
    155 
    156     def new_java_array(self, pylist, java_class):

C:\spark\python\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

C:\spark\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

C:\spark\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

C:\spark\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

## Code for loading offline

```
bert = BertEmbeddings.load(r'C:\Users\zbyne\Downloads\bert_base_cased_en_2.4.0_2.4_1580579557778')\
.setInputCols(["sentence",'token'])\
.setOutputCol("bert")\
.setCaseSensitive(False)\
.setPoolingLayer(0)

```
```
## Respective error
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-10-32133a97f9a1> in <module>
----> 1 bert = BertEmbeddings.load(r'C:\Users\zbyne\Downloads\bert_base_cased_en_2.4.0_2.4_1580579557778')\
      2 .setInputCols(["sentence",'token'])\
      3 .setOutputCol("bert")\
      4 .setCaseSensitive(False)\
      5 .setPoolingLayer(0)

C:\spark\python\pyspark\ml\util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in read(cls)
     64     def read(cls):
     65         """Returns an MLReader instance for this class."""
---> 66         return AnnotatorJavaMLReader(cls())
     67 
     68 

C:\spark\python\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    108             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    109         self._input_kwargs = kwargs
--> 110         return func(self, **kwargs)
    111     return wrapper
    112 

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\annotator.py in __init__(self, classname, java_model)
   1920         super(BertEmbeddings, self).__init__(
   1921             classname=classname,
-> 1922             java_model=java_model
   1923         )
   1924         self._setDefault(

C:\spark\python\pyspark\__init__.py in wrapper(self, *args, **kwargs)
    108             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    109         self._input_kwargs = kwargs
--> 110         return func(self, **kwargs)
    111     return wrapper
    112 

~\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\common.py in __init__(self, classname, java_model)
     72         if classname and not java_model:
     73             self.__class__._java_class_name = classname
---> 74             self._java_obj = self._new_java_obj(classname, self.uid)
     75         if java_model is not None:
     76             self._transfer_params_from_java()

C:\spark\python\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

C:\spark\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1523         answer = self._gateway_client.send_command(command)
   1524         return_value = get_return_value(
-> 1525             answer, self._gateway_client, None, self._fqn)
   1526 
   1527         for temp_arg in temp_args:

C:\spark\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

C:\spark\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.embeddings.BertEmbeddings.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V
	at com.johnsnowlabs.nlp.AnnotatorModel.<init>(AnnotatorModel.scala:15)
	at com.johnsnowlabs.nlp.embeddings.BertEmbeddings.<init>(BertEmbeddings.scala:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

I Never had to submit new issue so if I made some significant error on the road excuse me and point it out so it won't happen next time.
Any meaningful feedback is appreciated.

**Comment by ZbynekAfiala** [comment]
Hello, first of all thank you for your quick response, you were right when I've updated Pyspark version to 3.0.3 This error was eliminated. So this issue can be closed :).

Thank you a lot !
