### ISSUE TITLE
ConfigException$Parse with --properties-file flag

### ISSUE THREAD

**Issue by bairathirahul** [JohnSnowLabs/spark-nlp#292]
Receiving `com.typesafe.config.ConfigException$Parse` when a custom properties-file is provided to the `spark-submit` command with the `--properties-file` flag.

## Description

I am providing a custom .conf file to the spark-submit command, and I think it is being read in the ConfigLoader.scala. The format for Spark's configuration file is key value pair separated by whitespace. This format is not supported by Lightbend's config reader.

## Expected Behavior

I am not sure why the config file is read there. Those properties are available via spark.conf

## Current Behavior

The config file is read again by the library and ConfigException$Parse is thrown. Here is the full stacktrace:
`py4j.protocol.Py4JJavaError: An error occurred while calling o96.fit.
: com.typesafe.config.ConfigException$Parse: ./application.conf: 5: Key 'spark.global.tmp_path          /tmp' may not be followed by token: 'spark.es.nodes' (if you intended 'spark.es.nodes' to be part of a key or string value, try enclosing the key or value in double quotes)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:408)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:595)
        at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:734)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:748)
        at com.johnsnowlabs.util.ConfigLoader$.retrieve(ConfigLoader.scala:17)
        at com.johnsnowlabs.nlp.serialization.Feature.<init>(Feature.scala:17)
        at com.johnsnowlabs.nlp.serialization.StructFeature.<init>(Feature.scala:105)
        at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel.<init>(PerceptronModel.scala:22)
        at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel.<init>(PerceptronModel.scala:57)
        at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronApproach.train(PerceptronApproach.scala:163)
        at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronApproach.train(PerceptronApproach.scala:20)
        at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)`

## Possible Solution

I am not sure about the side-affects of removing it.

## Steps to Reproduce

1. Prepare a conf file with the same format as spark-defaults.conf.template
2. Provide the location of this file in the `--properties-file` command line argument

## Context

I am using a custom config file with configurations used by my project. Spark-NLP library is throwing error when that file is provided.

## Your Environment

* Version used: Spark 2.3.2 and Spark-NLP 1.7.2
* Operating System and version (desktop or mobile): MacOS

**Comment by saifjsl** [comment]
Hm this is interesting, would be great to know what makes Spark-NLP (actually that is Spark's responsibility) read application.conf in such format. @albertoandreottiATgmail any thoughts?
