### ISSUE TITLE
Using Pretrained model from GCS path throws unreadable exception

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#2944]
I've download the **entity_recognizer_lg** model from here:
https://nlp.johnsnowlabs.com/2021/03/23/entity_recognizer_lg_de.html

and uploaded it into a GCS bucket at:
'gs://MyProject/SparkNLP/models/entity_recognizer_lg/entity_recognizer_lg_de_3.0.0_3.0_1616491780964'

## Description

```
modelPath = 'gs://MyProject/SparkNLP/models/entity_recognizer_lg/entity_recognizer_lg_de_3.0.0_3.0_1616491780964'
/explain_document_dl_en_2.4.3_2.4_1584626657780'

!gsutil list {modelPath}
```

shows:
```
gs://MyProject/SparkNLP/models/entity_recognizer_lg/entity_recognizer_lg_de_3.0.0_3.0_1616491780964/metadata/
gs://MyProject/SparkNLP/models/entity_recognizer_lg/entity_recognizer_lg_de_3.0.0_3.0_1616491780964/stages/
```

## Expected Behavior

I've found the demo code [here](https://nlp.johnsnowlabs.com/2021/03/23/entity_recognizer_lg_de.html) and wish to executed it in an airtight environment. So, I downloaded the model from the Download button and upload it into a GCS Bucket in the GCP.

```
from sparknlp.pretrained import PretrainedPipelinein
pipeline = PretrainedPipeline('entity_recognizer_lg', lang = 'de')
annotations =  pipeline.fullAnnotate(""Hallo aus John Snow Labs! "")[0]
annotations.keys()
```

## Current Behavior

So I am trying to execute the demo code from the referenced page but with a local copy instead of the downloadable version. But 

## Issue 1
```
from sparknlp.pretrained import PretrainedPipeline

pipeline = PretrainedPipeline.from_disk(modelPath, lang = 'de')
```
Results in an error:
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-3fa4cb516ee6> in <module>
      1 from sparknlp.pretrained import PretrainedPipeline
      2 
----> 3 pipeline = PretrainedPipeline.from_disk(modelPath, lang = 'de')

TypeError: from_disk() got an unexpected keyword argument 'lang'
```

## Issue 2
Now I remove the lang parameter even though it should have worked according to the demo code in [this page](https://nlp.johnsnowlabs.com/2021/03/23/entity_recognizer_lg_de.html).

```
from sparknlp.pretrained import PretrainedPipeline

pipeline = PretrainedPipeline.from_disk(modelPath)
```
Results in a long unreadable stacktrace and I have no idea whats wrong here. I am sure the location is correct and the model is uncompressed correctly as I am using the same mechanism for the explain_document_dl model and this works fine for me.

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-10-5a9c485bc8fb> in <module>
      1 from sparknlp.pretrained import PretrainedPipeline
      2 
----> 3 pipeline = PretrainedPipeline.from_disk(modelPath)

/opt/conda/anaconda/lib/python3.6/site-packages/sparknlp/pretrained.py in from_disk(path, parse_embeddings)
    110     @staticmethod
    111     def from_disk(path, parse_embeddings=False):
--> 112         return PretrainedPipeline(None, None, None, parse_embeddings, path)
    113 
    114     def annotate(self, target, column=None):

/opt/conda/anaconda/lib/python3.6/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
    105             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
    106         else:
--> 107             self.model = PipelineModel.load(disk_location)
    108         self.light_model = LightPipeline(self.model, parse_embeddings)
    109 

/usr/lib/spark/python/pyspark/ml/util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

/usr/lib/spark/python/pyspark/ml/pipeline.py in load(self, path)
    240         metadata = DefaultParamsReader.loadMetadata(path, self.sc)
    241         if 'language' not in metadata['paramMap'] or metadata['paramMap']['language'] != 'Python':
--> 242             return JavaMLReader(self.cls).load(path)
    243         else:
    244             uid, stages = PipelineSharedReadWrite.load(metadata, self.sc, path)

/usr/lib/spark/python/pyspark/ml/util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o337.load.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 10 in stage 43.0 failed 4 times, most recent failure: Lost task 10.3 in stage 43.0 (TID 111, vf-de-dbahle-test-w-1.c.vf-de-ca-lab.internal, executor 1): java.io.InvalidClassException: com.johnsnowlabs.nlp.util.regex.RuleFactory; local class incompatible: stream classdesc serialVersionUID = 3820943135112344102, local class serialVersionUID = 3504449169794985547
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1964)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1830)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2121)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2054)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1635)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at org.apache.spark.util.Utils$.deserialize(Utils.scala:169)
	at org.apache.spark.SparkContext$$anonfun$objectFile$1$$anonfun$apply$16.apply(SparkContext.scala:1305)
	at org.apache.spark.SparkContext$$anonfun$objectFile$1$$anonfun$apply$16.apply(SparkContext.scala:1305)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:390)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1334)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$31.apply(RDD.scala:1409)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$31.apply(RDD.scala:1409)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1892)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1880)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1879)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2113)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2062)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2051)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1409)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1382)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1423)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1422)
	at com.johnsnowlabs.nlp.serialization.StructFeature.deserializeObject(Feature.scala:120)
	at com.johnsnowlabs.nlp.serialization.Feature.deserialize(Feature.scala:47)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:15)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:14)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:14)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:652)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.InvalidClassException: com.johnsnowlabs.nlp.util.regex.RuleFactory; local class incompatible: stream classdesc serialVersionUID = 3820943135112344102, local class serialVersionUID = 3504449169794985547
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1964)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1830)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2121)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1647)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2054)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1635)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:441)
	at org.apache.spark.util.Utils$.deserialize(Utils.scala:169)
	at org.apache.spark.SparkContext$$anonfun$objectFile$1$$anonfun$apply$16.apply(SparkContext.scala:1305)
	at org.apache.spark.SparkContext$$anonfun$objectFile$1$$anonfun$apply$16.apply(SparkContext.scala:1305)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:390)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1334)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$31.apply(RDD.scala:1409)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$31.apply(RDD.scala:1409)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

## Possible Solution

I've tried everything I could but this problem does not go away...

## Steps to Reproduce

1. Download the model from the Download button and put the uncompressed archiv into a GCP Bucket
2. Execute the listed code with the correct path

## Context

Can't get started with a simple hello world type of code sample :-(

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.3
* Apache NLP version `spark.version`: 2.4.6
* Java version `java -version`: n/a
* Setup and installation (Pypi, Conda, Maven, etc.): n/a
* Operating System and version: n/a
* Link to your project (if any): n/a

**Comment by maziyarpanahi** [comment]
Hi,

When you are loading something offline then you don't need the `lang`, in fact, it doesn't really matter since you have an explicit path to the model or the pipeline. The `lang` is to look online and make sure it downloads the one for that language if there is more than 1 model/pipeline with the same name. So `lang` param is not for offline and it's correct to get an exception, you can remove it.

Your second error is actually already documented:

```
Caused by: java.io.InvalidClassException: com.johnsnowlabs.nlp.util.regex.RuleFactory; local class incompatible: stream classdesc serialVersionUID = 3820943135112344102, local class serialVersionUID = 3504449169794985547
```

Java error trace can be long but it always gets to the point which here is `serialVersionUID`. You need to follow this discussion: https://github.com/JohnSnowLabs/spark-nlp/discussions/2562 (your Spark NLP and Apache Spark / PySpark are not matched)

Spark NLP version sparknlp.version(): 3.0.3
Apache NLP version spark.version: 2.4.6

You can see there are different packages for Spark `2.4.x` if you are using Spark NLP `3.x`, it is mentioned here: https://github.com/JohnSnowLabs/spark-nlp#usage and in the release notes at the bottom.

**Comment by Dirkster99** [comment]
Just tried

```
from sparknlp.pretrained import PipelineModel

pipeline = PipelineModel.load(modelPath)
```

but this also throws the long winded stack trace exception shown above

**Comment by Dirkster99** [comment]
Sorry but I am lost here:

This [page](https://github.com/JohnSnowLabs/spark-nlp#usage) says:

**Spark NLP 3.0.3 has been built on top of Apache Spark 3.x while fully supports Apache Spark 2.3.x and Apache Spark 2.4.x**

So, this means SparkNLP 3.0.3 should work with 2.4.6 right?

If not what is the correct version to be used with Spark 2.4.6?

**Comment by maziyarpanahi** [comment]
It supports all 3 major versions of Spark but for each has its own package, it's pretty clear in the link I shared:

- If you are spark 3.x then spark-nlp
- If you are spark 2.4.x then it should be spark-nlp-spark24
- If you are spark 2.3.x then it should be spark-nlp-spark23

You need to change the package/jar that you are using right now in your GC setup to match it with your spark version.

**Comment by maziyarpanahi** [comment]
Sorry I forgot to mention, in any case you can share your setup scripts and I can point which part should be changed and to what. 😊

**Comment by Dirkster99** [comment]
Is it possible to find an equivalent setup for CoLab? I am currently using the versions below but I am not sure whether an alternative version (other than 3.0.3) can be installed via pip-install?

```
import os

# Install java
! apt-get update -qq
! apt-get install -y openjdk-8-jdk-headless -qq > /dev/null

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
! java -version

# Install pyspark
! pip install --ignore-installed pyspark==2.4.6

# Install Spark NLP
! pip install --ignore-installed spark-nlp==3.0.3
```

**Comment by maziyarpanahi** [comment]
Only the Maven or the JAR is based on each Spark version. The PyPI is only one package and works with all them, so it is always 'spark-nlp'.

PS: We have extensive docs, there is even a section for Colab with instructions/script/demo/easy to use if you read the parts that says use other pyspark versions.

Good luck!
