### ISSUE TITLE
Unable to download ner_bionlp : ClasscastException MedicalNerModel cannot be cast to NerDLModel 

### ISSUE THREAD

**Issue by kaniska** [JohnSnowLabs/spark-nlp#2979]
## Description
Unable to download pretrained bio_nlp due to ClassCastException: com.johnsnowlabs.nlp.annotators.ner.MedicalNerModel cannot be cast to com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel

## Expected Behavior
ner_bionlp should get downloaded sucessfully

## Current Behavior
ClasscastException MedicalNerModel cannot be cast to NerDLModel 

## Possible Solution
Is the specified approach of using NerMLModel incompatible with latest version of sparknlp ?

## Steps to Reproduce
Follow the steps in https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/enterprise/healthcare/EntityResolution_ICDO_SNOMED.ipynb

spark = sparknlp_jsl.start(secret, gpu=False, spark23=(spark_version[:3]=="2.3"))

#sparknlp_jsl.version = 3.0.3
#spark.version = 3.0.2

docAssembler = DocumentAssembler().setInputCol("note_txt").setOutputCol("document")
sentenceDetector = SentenceDetector().setInputCols("document").setOutputCol("sentence")
tokenizer = Tokenizer().setInputCols("sentence").setOutputCol("token")
word_embeddings = WordEmbeddingsModel.pretrained("embeddings_clinical", "en", "clinical/models")\
    .setInputCols("sentence", "token")\
    .setOutputCol("word_embeddings")

#embeddings_clinical download started this may take some time.
#Approximate size to download 1.6 GB
#[OK!]

icdo_ner = NerDLModel.pretrained("ner_bionlp", "en", "clinical/models")\
    .setInputCols("sentence", "token", "word_embeddings")\
    .setOutputCol("icdo_ner")

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: **java.lang.ClassCastException: com.johnsnowlabs.nlp.annotators.ner.MedicalNerModel cannot be cast to com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel**
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$onRead$1$adapted(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable.$anonfun$read$1$adapted(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:379)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:373)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:494)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

## Context
I want to extract ICD / SNOMED Codes from sample Clinical Notes
I need to also try Named Entity Resolution and Clinical Assertion on the dataset.

## Your Environment

#sparknlp_jsl.version = 3.0.3
#spark.version = 3.0.2
* Spark NLP version : 3.0.3
* Java version : 1.8.0_144
* Python version: 3.7.0
* Setup and installation (Pypi, Conda, Maven, etc.): conda jupyter
* Operating System and version: Red Hat 7.7
* Link to your project (if any): https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/enterprise/healthcare/EntityResolution_ICDO_SNOMED.ipynb

**Comment by maziyarpanahi** [comment]
Hi,

We don't have any access or knowledge of licensed products/models.
Please either ask via email or in Slack (#healthcare channel). 
They sort you out pretty quick.
