### ISSUE TITLE
Error loading AdvancedPipeline: AmazonS3Exception: Forbidden

### ISSUE THREAD

**Issue by gsindholt** [JohnSnowLabs/spark-nlp#305]
## Description
Loading pretrained pipeline: `AdvancedPipeline().pretrained`, I get the following AWS exception:

`Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: CE4C334E140CF087), S3 Extended Request ID: H6TN70nAEPU6YlG3uriBXo31m0w+DbkFi7hrK1ABzcti5NkndmGK053yfXRQ4zcYjE3TJnHrzao=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3790)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1012)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:987)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$S3ClientWrapper.doesObjectExist(S3ResourceDownloader.scala:183)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$download$1.apply(S3ResourceDownloader.scala:94)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$download$1.apply(S3ResourceDownloader.scala:91)
	at scala.Option.flatMap(Option.scala:171)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.download(S3ResourceDownloader.scala:90)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:91)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:123)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:118)
	at com.johnsnowlabs.nlp.pretrained.pipelines.PretrainedPipeline.modelCache$lzycompute(PretrainedPipeline.scala:11)
	at com.johnsnowlabs.nlp.pretrained.pipelines.PretrainedPipeline.modelCache(PretrainedPipeline.scala:10)
	at com.johnsnowlabs.nlp.pretrained.pipelines.PretrainedPipeline.pretrained(PretrainedPipeline.scala:22)
`

## Expected Behavior
I would expect the pipeline to load :) I tried loading both `BasicPipeline().pretrained()` and `SentimentPipeline().pretrained()` and they both work fine.

## Current Behavior
Getting exception:
`com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: CE4C334E140CF087), S3 Extended Request ID: H6TN70nAEPU6YlG3uriBXo31m0w+DbkFi7hrK1ABzcti5NkndmGK053yfXRQ4zcYjE3TJnHrzao=`

## Steps to Reproduce
Simple Scala app:
``` 
def main(implicit args: Array[String]): Unit = {
  import spark.implicits._
  val sparkConfig = new SparkConf().setAppName("Test").setMaster("local[*]").set("spark.executor.memory", "8g")

  val spark = SparkSession.builder.config(sparkConfig).getOrCreate()
  val df = Seq("Going to USA to visit John Doe").toDF("mainColumn")
  val finisher = new Finisher()
    .setInputCols("token", "normal", "ner")

  val nerPipeline = AdvancedPipeline().pretrained()

  val pipeline = new Pipeline().
    setStages(Array(
      nerPipeline,
      finisher
    ))

  pipeline.
    fit(spark.emptyDataFrame).
    transform(df.withColumnRenamed("mainColumn", "text")).
    show()
}
```

## Your Environment

* Version used: spark-nlp 1.7.3, spark version 2.2.0
* Operating System and version (desktop or mobile): MacOS

**Comment by saifjsl** [comment]
Thanks for reporting this. I'll take  a look shortly

**Comment by saifjsl** [comment]
There is a problem on our server, mismatching model version and number. Going to re-train and re-upload as soon as possible and will let you know!

**Comment by saifjsl** [comment]
hi @gsindholt this is supposed to be fixed. Could you confirm?

**Comment by gsindholt** [comment]
Yes, I can confirm that it now works 👍

**Comment by tonydspaniard** [comment]
@saif-ellafi I have the same issue with latest release: 

```
 File "/usr/local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: D294CBCCF1F85B2A; S3 Extended Request ID: M3WO2yupb9KOvxbo2DUMObstGqPSXUPfqQkwhUgdfFbrPmwMUQUlBqyP9zAetdjXIsFzaU6oX0g=), S3 Extended Request ID: M3WO2yupb9KOvxbo2DUMObstGqPSXUPfqQkwhUgdfFbrPmwMUQUlBqyP9zAetdjXIsFzaU6oX0g=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1320)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1294)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$getDownloadSize$1.apply(S3ResourceDownloader.scala:164)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$getDownloadSize$1.apply(S3ResourceDownloader.scala:161)
	at scala.Option.flatMap(Option.scala:171)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:160)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:395)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:483)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
