### ISSUE TITLE
java.lang.NullPointerException issue while calling PerceptronApproach().setCorpus()

### ISSUE THREAD

**Issue by munaAchyuta** [JohnSnowLabs/spark-nlp#306]
Hi,

can anyone tell me why this issue is coming ? 

while setting corpus after done with pos-tag this issue is coming.  specifically in this line.
`.setCorpus("file:///" + os.getcwd() + "/../../../src/test/resources/anc-pos-corpus-small/","|")`

is it permission issue ? i don't think so, bcs other files are able to be created.

python - 2.7
spark - 2.4.0
spark-nlp - latest version

more on issue details : 

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-53-d0ecfbd07161> in <module>()
      2 #import pdb;pdb.set_trace()
      3 print("Start fitting")
----> 4 model = pipeline.fit(data)
      5 print("Fitting is ended")
      6 print (time.time() - start)

/spark/python/pyspark/ml/base.pyc in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/spark/python/pyspark/ml/pipeline.pyc in _fit(self, dataset)
    107                     dataset = stage.transform(dataset)
    108                 else:  # must be an Estimator
--> 109                     model = stage.fit(dataset)
    110                     transformers.append(model)
    111                     if i < indexOfLastEstimator:

/spark/python/pyspark/ml/base.pyc in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/spark/python/pyspark/ml/wrapper.pyc in _fit(self, dataset)
    293 
    294     def _fit(self, dataset):
--> 295         java_model = self._fit_java(dataset)
    296         model = self._create_model(java_model)
    297         return self._copyValues(model)

/spark/python/pyspark/ml/wrapper.pyc in _fit_java(self, dataset)
    290         """
    291         self._transfer_params_to_java()
--> 292         return self._java_obj.fit(dataset._jdf)
    293 
    294     def _fit(self, dataset):

/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1085.fit.
: java.lang.NullPointerException
	at com.johnsnowlabs.nlp.util.io.ResourceHelper$.parseTupleSentences(ResourceHelper.scala:229)
	at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronApproach.train(PerceptronApproach.scala:110)
	at com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronApproach.train(PerceptronApproach.scala:20)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks.

**Comment by albertoandreottiATgmail** [comment]
hi @munaAchyuta, I don't understand how that line could have triggered the exception you pasted. It seems like you're trying to fit the POS model without a dataset or an external file.
Is this your code?,

      2 #import pdb;pdb.set_trace()
      3 print("Start fitting")
----> 4 model = pipeline.fit(data)
      5 print("Fitting is ended")
      6 print (time.time() - start)

In case it's not, please paste the complete code, at least the part where you set up the pipeline.

thanks!

**Comment by munaAchyuta** [comment]
Hi @albertoandreottiATgmail  , thanks for quick reply. FYI, i am using some code samples from spark-nlp repo. more concretely crf-ner code , which is available in **spark-nlp-->python-->example-->crf-ner-->ner.ipynb**

i was just exploring features through given example test script.

as mentioned above , i'm also using same given dataset (spark-nlp-->src-->test-->resources-->anc-pos-corpus-small).

please find pipeline code . 

```
documentAssembler = DocumentAssembler()\
  .setInputCol("text")\
  .setOutputCol("document")

sentenceDetector = SentenceDetector()\
  .setInputCols(["document"])\
  .setOutputCol("sentence")

tokenizer = Tokenizer()\
  .setInputCols(["document"])\
  .setOutputCol("token")

posTagger = PerceptronApproach()\
  .setIterations(3)\
  .setInputCols(["token", "document"])\
  .setOutputCol("pos")\
  .setCorpus("file:///" + os.getcwd() + "/../../../src/test/resources/anc-pos-corpus-small/","|")
#.setCorpus("/home/ice-ner-dev/spark_nlp/spark-nlp/src/test/resources/anc-pos-corpus-small/", "/")

nerTagger = NerCrfApproach()\
  .setInputCols(["sentence", "token", "pos"])\
  .setLabelColumn("label")\
  .setOutputCol("ner")\
  .setMinEpochs(1)\
  .setMaxEpochs(1)\
  .setLossEps(1e-3)\
  .setEmbeddingsSource("./glove.6B.100d.txt", 100, 2)\
  .setExternalDataset("./eng_small.train")\
  .setL2(1)\
  .setC0(1250000)\
  .setRandomSeed(0)\
  .setVerbose(2)\
  .setIncludeEmbeddings(False)\
  .setEmbeddingsRef("glove100")

finisher = Finisher() \
    .setInputCols(["ner"]) \
    .setIncludeMetadata(True)

pipeline = Pipeline(
    stages = [
    documentAssembler,
    sentenceDetector,
    tokenizer,
    posTagger,
    #nerTagger,
    #finisher
  ])
```



Thanks.

**Comment by saifjsl** [comment]
Thank you, indeed the fault it is **Spark 2.4.x**.

So, we're officially not yet supporting it.

**Comment by maziyarpanahi** [comment]
I just tested my Scala code that uses already trained POS model by `spark-nlp` against **Spark 2.4.0** and it worked. Is this only for Python? 
I'll see if I can test more annotators to see if they all pass in Scala at least.

**Comment by saifjsl** [comment]
Indeed, the problems seems to come mostly from python. But since Spark 2.4.x changes were noticeable, we can't say we support it until we explicitly tested everything with it. It is safer for now to work with Spark 2.3.2.

**Comment by maziyarpanahi** [comment]
This has been fixed in new releases of `spark-nlp` against Spark `2.4.0`.
