### ISSUE TITLE
python example sentiment.ipynb - issues with Lemmatizer

### ISSUE THREAD

**Issue by nilichen** [JohnSnowLabs/spark-nlp#48]
## Description

1. git clone the repository
2. export PYSPARK_DRIVER_PYTHON=jupyter
    export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
3. pyspark --packages JohnSnowLabs:spark-nlp:1.2.3
4. had issues with Lemmatizer when running the sentiment notebook in python example

## Error message
Py4JJavaError: An error occurred while calling o40.setLemmaDict.
: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable
	at com.johnsnowlabs.nlp.annotators.Lemmatizer$.<init>(Lemmatizer.scala:62)
	at com.johnsnowlabs.nlp.annotators.Lemmatizer$.<clinit>(Lemmatizer.scala)
	at com.johnsnowlabs.nlp.annotators.Lemmatizer.setLemmaDict(Lemmatizer.scala:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigMergeable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

## Environment

* Version used: JohnSnowLabs:spark-nlp:1.2.3
* Browser Name and version: Google Chrome version 61.0.3163.100 (64-bit)
* Operating System and version (desktop or mobile): macOS Sierra Version 10.12.6

**Comment by nilichen** [comment]
Tried with JohnSnowLabs:spark-nlp:1.2.2 and it works!

**Comment by saifjsl** [comment]
Thank you @nilichen . I've tried both 1.2.3 and 1.2.2 and could not reproduce it either way, what do you think it could be? Looks like typesafe config not properly setup in your classpath but certainly there is no difference between 1.2.3 and 1.2.2, actually there is only minimal change in those versions.

**Comment by nilichen** [comment]
@saifjsl My bad. I tried with 1.1.0 locally and it worked, neither 1.2.2 nor 1.2.3 works. I think it is indeed a problem of my local setting because I tried 1.2.3 on my school cluster and it works. Thank you so much!

**Comment by saifjsl** [comment]
thank you

**Comment by snape6666** [comment]
I have the same problem with 1.6.0,
what kind of settings do i need?
