### ISSUE TITLE
Error using PretrainedPipeline: AmazonS3Exception: AccessDenied

### ISSUE THREAD

**Issue by ciliop** [JohnSnowLabs/spark-nlp#480]
## Description
Hello, I'm trying the example "running pre-trained models" from spark-nlp workshop but looks like I don't have access to the pre-trained models.

I'm using PretrainedPipeline("pipeline_basic") to annotate a String, but i get the following exception:

Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 2CD94D6F322010B4, AWS Error Code: AccessDenied, AWS Error Message: Access Denied, S3 Extended Request ID: 5QJUS9/TG7MW8YBtzLnbNTP/lKjbQp5LW85K9w60OiNNYFHh0mREPdJsurpomDNnmreS5LDWTHk=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:798)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1111)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:984)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:66)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:77)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.download(S3ResourceDownloader.scala:89)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:101)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:133)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:128)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.model$lzycompute(PretrainedPipeline.scala:14)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.model(PretrainedPipeline.scala:13)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.annotate(PretrainedPipeline.scala:19)
	at App.getPretrainedModels(App.java:65)
	at App.main(App.java:37)

## Possible Solution
Do I have to provide the AWS API keys? if yes how do I do that?
I'm using scala.

## Your Environment
Maven dependencies:

<dependency>
    <groupId>com.johnsnowlabs.nlp</groupId>
    <artifactId>spark-nlp_2.11</artifactId>
    <version>2.0.1</version>
</dependency>

<dependency>
    <groupId>com.johnsnowlabs.nlp</groupId>
    <artifactId>spark-nlp-ocr_2.11</artifactId>
    <version>2.0.1</version>
</dependency>

**Comment by maziyarpanahi** [comment]
Hi @ciliop,
Could you please create this issue in the appropriate repo for others if they might face the same problem?

Many thanks,
