### ISSUE TITLE
spark-nlp 1.8.2 trying dl-ner example

### ISSUE THREAD

**Issue by nehadave78** [JohnSnowLabs/spark-nlp#534]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by nehadave78** [comment]
Hi Everyone, I have pyspark + spark-nlp (1.8.2) I am trying this example:
https://github.com/JohnSnowLabs/spark-nlp/blob/182-release-candidate/python/example/dl-ner/ner.ipynb

I am getting the following error: (didn't find any solution) 

Py4JJavaError: An error occurred while calling o53.getParam.
: java.util.NoSuchElementException: Param caseSensitiveEmbeddings does not exist.
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getParam(params.scala:728)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:42)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
