### ISSUE TITLE
spark-nlp(2.0.7) + pyspark dl-ner example

### ISSUE THREAD

**Issue by nehadave78** [JohnSnowLabs/spark-nlp#536]
Hi @maziyarpanahi  @saifjsl , I am trying :
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/english/dl-ner/ner.ipynb
at

****ner_model = ner_pipeline.fit(training_data)**
print("Fitting is ended")
print (time.time() - start)**
**_with spark-nlp 2.0.7 and I am getting following error_** 

Py4JJavaError: An error occurred while calling o57.getParam.
: java.util.NoSuchElementException: Param useContrib does not exist.
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getParam(params.scala:728)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:42)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by maziyarpanahi** [comment]
Hi,

That is an old example that only works with 1.8.2 for the users who are still using 1.8.x release.
I will release some new notebooks just for `2.x.x` release.

**Comment by nehadave78** [comment]
Thanks that will be super helpful

**Comment by nehadave78** [comment]
@maziyarpanahi Did you get a chance to release new notebooks for 2.x.x ?

**Comment by maziyarpanahi** [comment]
This is a new notebook, we will review it again and make the changes for 2.10 and upcoming release. But it’s based on 2.x release.
