### ISSUE TITLE
S3 model PythonResourceDownloader:  not able to find Java class definition for s3 models

### ISSUE THREAD

**Issue by karthik-nair** [JohnSnowLabs/spark-nlp#568]
## Code
import os
os.environ["SPARK_HOME"] = '/usr/local/spark-2.4.3-bin-hadoop2.7'
from pyspark import SparkContext,SparkConf

conf = SparkConf().setAppName("basic")
sc = SparkContext(conf=conf)

import sparknlp
sparknlp.start()

from sparknlp.pretrained import PretrainedPipeline

pipeline = PretrainedPipeline('entity_recognizer_dl', 'en')
result = pipeline.annotate('Harry Potter is a great movie')
print(result['ner'])

## Description

It gives me an error : 
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.NoClassDefFoundError: com/amazonaws/services/s3/model/S3ObjectInputStream
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.<init>(ResourceDownloader.scala:75)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.<clinit>(ResourceDownloader.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$$anonfun$7.apply(ResourceDownloader.scala:198)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$$anonfun$7.apply(ResourceDownloader.scala:198)
	at scala.Option.getOrElse(Option.scala:121)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:198)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.s3.model.S3ObjectInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

## System 
Java: openjdk 1.8.0_212
Scala: 2.11.12
pyspark=2.4.1
spark-nlp 2.0.1

**Comment by maziyarpanahi** [comment]
Hi,

Could you please try to install pyspark==2.4.3 and spark-nlp==2.0.9?

There are lots of enhancements in the latest versions of Apache Spark and Spark NLP.
