### ISSUE TITLE
Param pooling Layer doesn't not exist 

### ISSUE THREAD

**Issue by ShubhamPal7** [JohnSnowLabs/spark-nlp#5813]
Hi I am trying to use BERT embedding in my Databricks and this is the error I am getting 

Spark NLP version 3.1.2
Apache Spark version: 3.1.1

My Code : 

bert_embeddings = BertEmbeddings.load('dbfs:/FileStore/shared_uploads/sp261c@att.com/bert_large_cased_en_2.4.0_2.4_1580580251298')\
    .setInputCols(['document',"cleanTokens"])\
    .setOutputCol('bert')\
    .setCaseSensitive(False)

Error : 

 An error occurred while calling o690.load.
: java.util.NoSuchElementException: Param poolingLayer does not exist.
	at org.apache.spark.ml.param.Params.$anonfun$getParam$2(params.scala:705)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.ml.param.Params.getParam(params.scala:705)
	at org.apache.spark.ml.param.Params.getParam$(params.scala:703)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:41)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.$anonfun$setParams$1(ReadWrite.scala:563)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.setParams(ReadWrite.scala:561)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.getAndSetParams(ReadWrite.scala:549)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:469)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

Thanks for the help!

**Comment by maziyarpanahi** [comment]
Hi,
You are trying to load a very old BERT model when it used to have poolingLayer param. You can either use pretrained() to automatically download the most recent and compatible model or download the compatible one manually:

https://nlp.johnsnowlabs.com/2020/08/25/bert_large_cased.html
