### ISSUE TITLE
Error while using Spark NLP pretrained pipelines "explain_document_dl"  - Py4JJavaError 

### ISSUE THREAD

**Issue by snowyan** [JohnSnowLabs/spark-nlp#5881]
## Description
I am getting error when I use Spark NLP pretrained pipelines on databricks notebook.

When I try to run the cell :
pipeline = PretrainedPipeline('explain_document_dl', lang='en')

I get error like this:
java.util.NoSuchElementException: Param includeAllConfidenceScores does not exist.
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.util.NoSuchElementException: Param includeAllConfidenceScores does not exist.

## Expected Behavior
Download a pre-trained pipeline.

## Current Behavior
explain_document_dl download started this may take some time.
Approx size to download 168 MB
[OK!]
java.util.NoSuchElementException: Param includeAllConfidenceScores does not exist.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-594536443691438> in <module>
      7 
      8 
----> 9 pipeline = PretrainedPipeline('explain_document_dl', 'en')

/databricks/python/lib/python3.8/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
    107     def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
    108         if not disk_location:
--> 109             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
    110         else:
    111             self.model = PipelineModel.load(disk_location)

/databricks/python/lib/python3.8/site-packages/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     77             t1.start()
     78             try:
---> 79                 j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     80                 jmodel = PipelineModel._from_java(j_obj)
     81             finally:
/databricks/python/lib/python3.8/site-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
    194 class _DownloadPipeline(ExtendedJavaWrapper):
    195     def __init__(self, name, language, remote_loc):
--> 196         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
    197 
    198 

/databricks/python/lib/python3.8/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
    142         super(ExtendedJavaWrapper, self).__init__(java_obj)
    143         self.sc = SparkContext._active_spark_context
--> 144         self._java_obj = self.new_java_obj(java_obj, *args)
    145         self.java_obj = self._java_obj
    146 

/databricks/python/lib/python3.8/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    152 
    153     def new_java_obj(self, java_class, *args):
--> 154         return self._new_java_obj(java_class, *args)
    155 
    156     def new_java_array(self, pylist, java_class):

/databricks/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.util.NoSuchElementException: Param includeAllConfidenceScores does not exist.
	at org.apache.spark.ml.param.Params.$anonfun$getParam$2(params.scala:705)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.ml.param.Params.getParam(params.scala:705)
	at org.apache.spark.ml.param.Params.getParam$(params.scala:703)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:41)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.$anonfun$setParams$1(ReadWrite.scala:563)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.setParams(ReadWrite.scala:561)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.getAndSetParams(ReadWrite.scala:549)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:469)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:12)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$5(Pipeline.scala:277)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:161)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:156)
	at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:43)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$4(Pipeline.scala:277)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.$anonfun$load$3(Pipeline.scala:274)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:284)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:284)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:268)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$7(Pipeline.scala:356)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent(events.scala:161)
	at org.apache.spark.ml.MLEvents.withLoadInstanceEvent$(events.scala:156)
	at org.apache.spark.ml.util.Instrumentation.withLoadInstanceEvent(Instrumentation.scala:43)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.$anonfun$load$6(Pipeline.scala:355)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:284)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:284)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:355)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:349)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:397)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:391)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:504)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

## Your Environment
* Databricks : DBR8.3ML
* Spark:3.1.1
* Java version (java -version): 8
Setup and installation (Pypi, Maven, etc.):
spark-nlp==3.1.1
Maven: com.johnsnowlabs.nlp:spark-nlp_2.12:3.1.1

* Spark NLP version `sparknlp.version()`: 3.1.1
* Apache NLP version `spark.version`: 3.1.0

 Any clue to fix this.Thanks!

**Comment by maziyarpanahi** [comment]
Hi @snowyan 

This is a typical situation in Databricks. Unfortunately, the Maven/JAR of Spark NLP is locked on a specific version while the PyPI is being installed as `spark-nlp`. So every time you start the cluster it will pull the exact version for Maven/JAR, but downloads and installs the latest version of `spark-nlp` for Python. (Python has a param called `includeAllConfidenceScores`, but Maven/JAR doesn't)

Please make sure you have the latest for both Maven and PyPI on the same version by using:

- Maven: `com.johnsnowlabs.nlp:spark-nlp_2.12:3.1.3` assuming you are on CPU/Apache Spark 3.x
- PyPI: `spark-nlp==3.1.3`

Reference: https://github.com/JohnSnowLabs/spark-nlp/blob/master/README.md#databricks-cluster

**Comment by snowyan** [comment]
Thanks for help.  I updated Maven and PyPI to 3.1.3 and it works well.

**Comment by maziyarpanahi** [comment]
Fantastic! Thanks for the update.
