### ISSUE TITLE
Question: Is it possible to train a SentenceDetector() to ignore abbreviations? 

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#5898]
**Link to doc page in question (if any):**
I am using Spark NLP for a German NER Pipeline but am having trouble detecting items that have an abbreviation.
Eg.:  Given a sentence like 'Ich lebe in 89192 München Bavariastr. 34 und bin hier gern zu Hause.' (address is invented)

I would like to extract a zip-code-city-street style address like this '89192 München Bavariastr. 34' but the `SentenceDetector()` breaks this into 2 sentences:
'Ich lebe in 89192 München Bavariastr.'
 '34 und bin hier gern zu Hause.'

 which (most likely) makes it rather hard to detect the intended string as an address.

**Name of the Spark NLP feature whose docs need improvement:**
`SentenceDetector()`

**What you think the docs should say:**
It would be great if there was something similar along the lines as I found it for [NLTK PunktTrainer](https://stackoverflow.com/questions/52150000/how-to-train-nltk-punktsentencetokenizer-batchwise) or [OpenNLP](https://www.tutorialkart.com/opennlp/train-model-sentence-detection-java/). Even if there was no way of training and applying a custom `SentenceDetector()` (which would surprise me) it would be good if there was a statement on that limitation.

**Comment by maziyarpanahi** [comment]
Hi @Dirkster99 

Could you please share your full pipeline so we know what are you using?

**Comment by Dirkster99** [comment]
The annotaded CONLL data in 1) was created manually. So end of sentence items are marked as given in [eng.train](https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp/master/src/test/resources/conll2003/eng.train):

```
. . B-NP O

```
All other abbreviations are kept as is. eg:

```
Bavariastr. NNP B-NP I-ADDRESS
34 NNP B-NP I-ADDRESS
```

The results are really cool in terms of KPIs I am reaching 0.99 in F1 score and others after 5 epochs:

```
label                 tp       fp  fn     prec               rec            f1
B-ADDRESS      599    1    0      0.99833333   1.0             0.99916595
I-ADDRESS       2664  1    8      0.9996248      0.997006  0.99831367
```

However, I can see that a lot of the marked address items are not being recognized because the `SentenceDetector` in 3) seems to split at the abbreviation of `Bavariastr` (see question above). So, I am thinking that the `SentenceDetector` should be trained with the custom abbreviations I am seeing (?).

### 1) My pipeline/code sequence for training is the following (based on [workshop notebook](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/blogposts/3.NER_with_BERT.ipynb))

```py
from sparknlp.training import CoNLL

# read training data from annotaded CONLL file
training_data = CoNLL().readDataset(spark, TrainCONLL)

# Training using pretrained BERT
bert_annotator = BertEmbeddings.load('gs://..../SparkNLP/NER/bert_multi_cased_xx_2.6.0_2.4_1598341875191/') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
.setBatchSize(32)

# Prepare test data from annotaded CONLL file
test_data = CoNLL().readDataset(spark, TestCONLL)
test_data = bert_annotator.transform(test_data)
test_data.write.parquet("test_withEmbeds.parquet")

nerTagger = NerDLApproach()\
  .setInputCols(["sentence", "token", "bert"])\
  .setLabelColumn("label")\
  .setOutputCol("ner")\
  .setMaxEpochs(7)\
  .setLr(0.001)\
  .setPo(0.005)\
  .setBatchSize(32)\
  .setEvaluationLogExtended(True) \
  .setEnableOutputLogs(True)\
  .setTestDataset("test_withEmbeds.parquet")

pipeline = Pipeline(
    stages = [
    bert_annotator,
    nerTagger
  ])

ner_model = pipeline.fit(training_data)
```

### 2 Save NER model after training

```py
ner_model.stages[1].write().overwrite().save('./NER_bert_20200219')
```

### 3 My Pipeline for later prediction (evaluation with independent data)

```py
document = DocumentAssembler().setInputCol("text") \
                              .setOutputCol("document")

sentence = SentenceDetector().setInputCols("document") \
                              .setOutputCol("sentence")

token = Tokenizer().setInputCols("sentence") \
                   .setOutputCol("token")

bert_annotator = BertEmbeddings.load('gs://..../SparkNLP/NER/bert_multi_cased_xx_2.6.0_2.4_1598341875191/') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
.setBatchSize(8)

#and then load back later on using NerDLModel annotator.
loaded_ner_model = NerDLModel.load("./NER_bert_20200219")\
   .setInputCols(["sentence", "token", "bert"])\
   .setOutputCol("ner")

converter = NerConverter().setInputCols(["document", "token", "ner"]) \
                          .setOutputCol("ner_span")

custom_ner_pipeline = Pipeline(stages=[document, sentence, token, bert_annotator, loaded_ner_model, converter])


# Read text data for independent prediction (evaluation or test after training)
EvalText = remotePath + 'eval.csv'

eval_data = spark.read.format('com.databricks.spark.csv')                              \
           .options( delimiter='|', header='true', inferschema='true', encoding="utf-8") \
           .load(EvalText)

prediction_data = eval_data.select('id','text')

prediction_model = custom_ner_pipeline.fit(prediction_data)
preds = prediction_model.transform(prediction_data)
```

**Comment by maziyarpanahi** [comment]
So the issue seems to be detecting sentence boundaries. I would suggest using a better Sentence Detector especially the one that has a multi-lingual model:

https://nlp.johnsnowlabs.com/2021/01/02/sentence_detector_dl_xx.html

```python
sentencerDL = SentenceDetectorDLModel\
  .pretrained("sentence_detector_dl", "xx") \
  .setInputCols(["document"]) \
  .setOutputCol("sentences")
```

This annotator and the multi-lingual may help to avoid simple rule-based detection such as `.`. In case it didn't, you can train your own sentence detector, perhaps by using the same CoNLL data to teach it (should be pretty simple):

example: https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/test/scala/com/johnsnowlabs/nlp/annotators/sentence_detector_dl/SentenceDetectorDLSpec.scala
doc: https://nlp.johnsnowlabs.com/docs/en/annotators#sentencedetectordl

**Comment by Dirkster99** [comment]
So I am trying to use the Multi-Lingual model you specified above via its load method (in my airtight env) but it throws an exception: `java.lang.IllegalArgumentException: requirement failed: TF model not setup.` on a Pipeline that works otherwise just fine (works great without the load() method call). What am I doning wrong here (using Spark 2.4.6 with SparkNLP 3.0.3)?

```py
modelSD_Path = "..../SparkNLP/NER/sentence_detector_dl_xx_2.7.0_2.4_1609610616998/"

document = DocumentAssembler().setInputCol("text") \
                              .setOutputCol("document")

sentence = SentenceDetector().load(modelSD_Path) \
                             .setInputCols("document") \
                             .setOutputCol("sentence")

finisher = Finisher() \
    .setInputCols(["sentence"]) \
    .setOutputCols(["sentence_features"]) \
    .setOutputAsArray(False) \
    .setCleanAnnotations(False)

custom_ner_pipeline = Pipeline(stages=[document, sentence, finisher])

prediction_data = eval_data.select('id','text') \

prediction_model = custom_ner_pipeline.fit(prediction_data)
preds = prediction_model.transform(prediction_data)
preds.show()

```

```
Full Execption Stack Trace:
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-9-481ad2f8ec9d> in <module>
      1 prediction_model = custom_ner_pipeline.fit(prediction_data)
      2 preds = prediction_model.transform(prediction_data)
----> 3 preds.show()

/usr/lib/spark/python/pyspark/sql/dataframe.py in show(self, n, truncate, vertical)
    379         """
    380         if isinstance(truncate, bool) and truncate:
--> 381             print(self._jdf.showString(n, 20, vertical))
    382         else:
    383             print(self._jdf.showString(n, int(truncate), vertical))

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o193.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 7, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: requirement failed: TF model not setup.
	at scala.Predef$.require(Predef.scala:224)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel.getTFClassifier(SentenceDetectorDLModel.scala:142)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$1.apply(SentenceDetectorDLModel.scala:219)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$1.apply(SentenceDetectorDLModel.scala:217)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$JoinIterator.hasNext(Iterator.scala:212)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.Iterator$JoinIterator.foreach(Iterator.scala:207)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$annotate$1.apply(SentenceDetectorDLModel.scala:254)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$annotate$1.apply(SentenceDetectorDLModel.scala:252)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel.annotate(SentenceDetectorDLModel.scala:252)
	at com.johnsnowlabs.nlp.HasSimpleAnnotate$$anonfun$dfAnnotate$1.apply(HasSimpleAnnotate.scala:24)
	at com.johnsnowlabs.nlp.HasSimpleAnnotate$$anonfun$dfAnnotate$1.apply(HasSimpleAnnotate.scala:23)
	... 21 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1892)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1880)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1879)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2113)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2062)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2051)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:365)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3389)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2550)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2764)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:254)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalArgumentException: requirement failed: TF model not setup.
	at scala.Predef$.require(Predef.scala:224)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel.getTFClassifier(SentenceDetectorDLModel.scala:142)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$1.apply(SentenceDetectorDLModel.scala:219)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$1.apply(SentenceDetectorDLModel.scala:217)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$JoinIterator.hasNext(Iterator.scala:212)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.Iterator$JoinIterator.foreach(Iterator.scala:207)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$annotate$1.apply(SentenceDetectorDLModel.scala:254)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel$$anonfun$annotate$1.apply(SentenceDetectorDLModel.scala:252)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.annotators.sentence_detector_dl.SentenceDetectorDLModel.annotate(SentenceDetectorDLModel.scala:252)
	at com.johnsnowlabs.nlp.HasSimpleAnnotate$$anonfun$dfAnnotate$1.apply(HasSimpleAnnotate.scala:24)
	at com.johnsnowlabs.nlp.HasSimpleAnnotate$$anonfun$dfAnnotate$1.apply(HasSimpleAnnotate.scala:23)
	... 21 more

```

**Comment by maziyarpanahi** [comment]
- `SentenceDetector` is a rule-based annotator for sentence detection
- `SentenceDetectorDL` is a DL-based annotator that has pretrained models, can be trained, etc.

You cannot load one into another, the example I gave you and the link to the model has a snippet code:

```python
# SentenceDetectorDLModel.pretrained() or SentenceDetectorDLModel.load() not SentenceDetector

sentencerDL = SentenceDetectorDLModel\
  .pretrained("sentence_detector_dl", "xx") \
  .setInputCols(["document"]) \
  .setOutputCol("sentences")
```

This annotator and its multi-lingual model should help for those sentences with `.` to split smarter, and in case it didn't it's pretty easy to train one using SentenceDetectorDLApproach based on your CoNLL dataset so it learns the sentence boundaries. https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/9.SentenceDetectorDL.ipynb

Feel free to open another issue if you face a bug regarding SentenceDetectorDL (SentenceDetectorDLModel and SentenceDetectorDLApproach)

**Comment by Dirkster99** [comment]
Just for completness sake: I found my error. My last code snippet has a typo because I am using the `SentenceDetector` class to load model for the `SentenceDetectorDLModel` class from disk (now that I've seen the error I understand what you meant by the rather generic phrase:
'You cannot load one into another'.

The sentence splitting problem was not resolved with the application of the model :-( (as I downloaded it from the models hub). But I'll try to train it and see if this could resolve my problem :-)

Thanx a lot for your quick support and this great library :-)

**Comment by Dirkster99** [comment]
Just to circle back on this for one last time:

Training the `SentenceDetectorDLModel` on those special abbreviations as explained above has improved the efficiency of my NER pipeline. The percentage of correctly extracted entries jumped from 93,5% to 99,6% - so I am able to extract text almost error free :-)

Its amazing to see how easy this works once you know how its done :-) I cannot share the actual data results but I'll be looking for a public German text to maybe write an article on this since I can imagine that many others face similar issues ...anyways, thanks for your quick feedbacks it realy is very helpful 👍🏽  🥇

**Comment by maziyarpanahi** [comment]
@Dirkster99 Thank you for updating this thread! That's a very good result and I am glad it helped you in your project.

Looking forward to reading your article! 🚀 (we will feature it on the Website under the `Learn` section)

**Comment by Dirkster99** [comment]
Here is the article (at last) on German legal text data since I could not find any other public sample text containing useful abbreviations:
https://medium.com/@Dirk_Bahle/customizing-the-sentencedetector-in-spark-nlp-2f6ef336a149

Please let me know what you think and tell me if you see any errors that I should correct :-)
