### ISSUE TITLE
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.

### ISSUE THREAD

**Issue by arjunsingla** [JohnSnowLabs/spark-nlp#590]
## Description
 I am trying to use JohnSnowLab's pretrained models, but to no avail.
 Using python 3, spark-nlp 2.1.0, and pyspark 2.4.3 in Jupyter notebook. Here is my code (it is very very simple, and yet still does not work). Ran on Mac OS Mojave

<img width="1061" alt="Screen Shot 2019-08-13 at 2 13 13 PM" src="https://user-images.githubusercontent.com/6709889/62977780-8b579500-bdd4-11e9-9ae5-4577ecb9b3e6.png">

## Error
Here is the error. Something to do with a java.io thing??
```---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-12-d759b18b57fc> in <module>
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

/usr/local/lib/python3.7/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc)
     44 
     45     def __init__(self, name, lang='en', remote_loc=None):
---> 46         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     47         self.light_model = LightPipeline(self.model)
     48 

/usr/local/lib/python3.7/site-packages/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     15     @staticmethod
     16     def downloadPipeline(name, language, remote_loc=None):
---> 17         j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     18         jmodel = JavaModel(j_obj)
     19         return jmodel

/usr/local/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
     58     def __init__(self, name, language, remote_loc):
     59         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline")
---> 60         self._java_obj = self._new_java_obj(self._java_obj, name, language, remote_loc)
     61 
     62 

/usr/local/lib/python3.7/site-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.io.IOException: Cannot run program "chmod": error=17, File exists
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:523)
	at org.apache.hadoop.util.Shell.run(Shell.java:479)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:866)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:849)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:733)
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:225)
	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:209)
	at org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:307)
	at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:296)
	at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:328)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:398)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:461)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:778)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$download$1.apply(S3ResourceDownloader.scala:125)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$download$1.apply(S3ResourceDownloader.scala:95)
	at scala.Option.flatMap(Option.scala:171)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.download(S3ResourceDownloader.scala:94)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:286)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:318)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:313)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:389)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: error=17, File exists
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 39 more
```

**Comment by maziyarpanahi** [comment]
Hi, 
We download models and pipelines into ~/cached_pretrained directory.

Could you please run this in terminal and paste the results here:

ls -l ~/chached_pretrianed

**Comment by arjunsingla** [comment]
For some reason, the problem fixed itself. Thanks!
Arjun

**Comment by SyedShahzaib790** [comment]
Hi @maziyarpanahi,
I am having the same issue. I ran the command you have written above. It has the following output (even if I run it as sudo): ls: cannot access /home/cloud_user/chached_pretrianed: No such file or directory
Kindly guide me why I am not being able to run SparkSession properly.

Error:
IndexError                                Traceback (most recent call last)
~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in _get_connection(self)
    928         try:
--> 929             connection = self.deque.pop()
    930         except IndexError:

IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

ConnectionRefusedError                    Traceback (most recent call last)
~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in start(self)
   1066         try:
-> 1067             self.socket.connect((self.address, self.port))
   1068             self.stream = self.socket.makefile("rb")

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Py4JNetworkError                          Traceback (most recent call last)
<ipython-input-5-e83fac3bf565> in <module>
      6     .config("spark.driver.maxResultSize", "2G") \
      7     .config("spark.jars.packages", "JohnSnowLabs:spark-nlp:2.2.1")\
----> 8     .config("spark.kryoserializer.buffer.max", "500m")\
      9     .getOrCreate()

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/pyspark/sql/session.py in getOrCreate(self)
    181                     session = SparkSession(sc)
    182                 for key, value in self._options.items():
--> 183                     session._jsparkSession.sessionState().conf().setConfString(key, value)
    184                 for key, value in self._options.items():
    185                     session.sparkContext._conf.set(key, value)

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1253             proto.END_COMMAND_PART
   1254 
-> 1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
   1257             answer, self.gateway_client, self.target_id, self.name)

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in send_command(self, command, retry, binary)
    981          if `binary` is `True`.
    982         """
--> 983         connection = self._get_connection()
    984         try:
    985             response = connection.send_command(command)

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in _get_connection(self)
    929             connection = self.deque.pop()
    930         except IndexError:
--> 931             connection = self._create_connection()
    932         return connection
    933 

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in _create_connection(self)
    935         connection = GatewayConnection(
    936             self.gateway_parameters, self.gateway_property)
--> 937         connection.start()
    938         return connection
    939 

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in start(self)
   1077                 "server ({0}:{1})".format(self.address, self.port)
   1078             logger.exception(msg)
-> 1079             raise Py4JNetworkError(msg, e)
   1080 
   1081     def _authenticate_connection(self):

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:40503)

**Comment by SyedShahzaib790** [comment]
@maziyarpanahi Thanks for the quick reply.
I have tried loading the model manually but faced another error. Can you kindly guide me? I have the following versions installed as per the guidelines:
Spark NLP version:  2.4.2
Apache Spark version:  2.4.0

Error:
Py4JError                                 Traceback (most recent call last)
<ipython-input-3-264abd7243c5> in <module>
----> 1 NerDLModel.load('/home/cloud_user/shahzaib/engine/CTL/spark_models/ner_dl_model')

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/pyspark/ml/util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/pyspark/ml/util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~/anaconda3/envs/allennlp/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
--> 336                 format(target_id, ".", name))
    337     else:
    338         type = answer[1]

Py4JError: An error occurred while calling o55.load

**Comment by maziyarpanahi** [comment]
@SyedShahzaib790 This is a new error and I need the full complete issue template to debug it. Could you please create a new issue, fill the template, explain the steps for installations, how you start your SparkSession, and full code to reproduce it?

**Comment by SyedShahzaib790** [comment]
@maziyarpanahi Sure, will do that.
