### ISSUE TITLE
ERROR LicenseValidator$: Wrong symbol in license key

### ISSUE THREAD

**Issue by tschaffter** [JohnSnowLabs/spark-nlp#5915]
## Description

I'm trying to use the python class `MedicalNerModel`. I get the following error, which seems to be related to my trial license. Below I have masked part of the license with `****************`.

```
phi-annotator  | Picked up JAVA_TOOL_OPTIONS: -Xmx4G -Dorg.bytedeco.javacpp.maxBytes=0
phi-annotator  | Picked up JAVA_TOOL_OPTIONS: -Xmx4G -Dorg.bytedeco.javacpp.maxBytes=0
phi-annotator  | 21/08/04 17:24:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
phi-annotator  | Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
phi-annotator  | Setting default log level to "WARN".
phi-annotator  | To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
phi-annotator  | 21/08/04 17:24:32 ERROR LicenseValidator$: Wrong symbol in license key: 3.1.1-****************.
phi-annotator  | java.lang.IllegalArgumentException: Input byte[] should at least have 2 bytes for base64 bytes
phi-annotator  |        at java.util.Base64$Decoder.outLength(Base64.java:659)
phi-annotator  |        at java.util.Base64$Decoder.decode(Base64.java:525)
phi-annotator  |        at pdi.jwt.JwtBase64$.decode(JwtBase64.scala:9)
phi-annotator  |        at pdi.jwt.JwtBase64$.decodeString(JwtBase64.scala:17)
phi-annotator  |        at pdi.jwt.JwtBase64$.decodeString(JwtBase64.scala:20)
phi-annotator  |        at pdi.jwt.JwtCore.splitToken(Jwt.scala:193)
phi-annotator  |        at pdi.jwt.JwtCore.$anonfun$decodeAll$5(Jwt.scala:451)
phi-annotator  |        at scala.util.Try$.apply(Try.scala:213)
phi-annotator  |        at pdi.jwt.JwtCore.decodeAll(Jwt.scala:450)
phi-annotator  |        at pdi.jwt.JwtCore.decodeAll$(Jwt.scala:450)
phi-annotator  |        at pdi.jwt.Jwt$.decodeAll(JwtPureScala.scala:19)
phi-annotator  |        at pdi.jwt.JwtCore.decode(Jwt.scala:538)
phi-annotator  |        at pdi.jwt.JwtCore.decode$(Jwt.scala:537)
phi-annotator  |        at pdi.jwt.Jwt$.decode(JwtPureScala.scala:19)
phi-annotator  |        at pdi.jwt.JwtCore.decode(Jwt.scala:541)
phi-annotator  |        at pdi.jwt.JwtCore.decode$(Jwt.scala:540)
phi-annotator  |        at pdi.jwt.Jwt$.decode(JwtPureScala.scala:19)
phi-annotator  |        at com.johnsnowlabs.license.LicenseValidator$.$anonfun$isValidLicence$2(LicenseValidator.scala:33)
phi-annotator  |        at scala.util.Try$.apply(Try.scala:213)
phi-annotator  |        at com.johnsnowlabs.license.LicenseValidator$.<init>(LicenseValidator.scala:35)
phi-annotator  |        at com.johnsnowlabs.license.LicenseValidator$.<clinit>(LicenseValidator.scala)
phi-annotator  |        at com.johnsnowlabs.license.Licensed.$init$(Licensed.scala:5)
phi-annotator  |        at com.johnsnowlabs.nlp.annotators.ner.MedicalNerModel.<init>(MedicalNerModel.scala:18)
phi-annotator  |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
phi-annotator  |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
phi-annotator  |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
phi-annotator  |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
phi-annotator  |        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
phi-annotator  |        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
phi-annotator  |        at py4j.Gateway.invoke(Gateway.java:238)
phi-annotator  |        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
phi-annotator  |        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
phi-annotator  |        at py4j.GatewayConnection.run(GatewayConnection.java:238)
phi-annotator  |        at java.lang.Thread.run(Thread.java:748)
phi-annotator  | An error occurred while calling None.com.johnsnowlabs.nlp.annotators.ner.MedicalNerModel.
phi-annotator  | : java.lang.Exception: Licence not configured or invalid licence key! Please contact support!!
phi-annotator  |        at com.johnsnowlabs.license.Licensed.$init$(Licensed.scala:6)
phi-annotator  |        at com.johnsnowlabs.nlp.annotators.ner.MedicalNerModel.<init>(MedicalNerModel.scala:18)
phi-annotator  |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
phi-annotator  |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
phi-annotator  |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
phi-annotator  |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
phi-annotator  |        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
phi-annotator  |        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
phi-annotator  |        at py4j.Gateway.invoke(Gateway.java:238)
phi-annotator  |        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
phi-annotator  |        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
phi-annotator  |        at py4j.GatewayConnection.run(GatewayConnection.java:238)
phi-annotator  |        at java.lang.Thread.run(Thread.java:748)
```

## Expected Behavior

Not have this message if my license key is valid.

To clarify, my license is `3.1.1-***********` where `***********` is a string of 40 characters. The license is specified as the environment variable "SPARK_NLP_LICENSE" as a previous error message suggested me to do. My main question is: Is the format of the license I described in this paragraph correct. If yes, why is the error `java.lang.IllegalArgumentException: Input byte[] should at least have 2 bytes for base64 bytes` thrown?

## Current Behavior

I get the error message `Wrong symbol in license key: 3.1.1-****************.` and `java.lang.IllegalArgumentException: Input byte[] should at least have 2 bytes for base64 bytes`.

## Possible Solution

What confused me at some point is that a release version number of NLP Spark is included in the license. My understanding is that this version number is part of the license. I tried without and I got the error `Wrong length of license key: ***********.` and `Expected token [***********.] to be composed of 2 or 3 parts separated by dots.`.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.1
* Apache NLP version `spark.version`: 3,1,1
* Java version `java -version`: 1.8.0_292
* Setup and installation (Pypi, Conda, Maven, etc.): Python 3.9.6
* Operating System and version: Debian 10
* Link to your project (if any):

Thanks

**Comment by maziyarpanahi** [comment]
Hi @tschaffter 

This is an open-source library, we don't have any knowledge of licensed products. You can either:
- contact the person who gave you the license key
- or ask the question on Slack under #healthcare channel
