### ISSUE TITLE
Problem with Spark NLP, This error occurs while loading a pretrained model

### ISSUE THREAD

**Issue by shubbham37** [JohnSnowLabs/spark-nlp#5937]
## Description

The Fatal Error occurs while loading the pre-trained model. Spark Session gets started and model gets downloaded successfully but while loading the pre-trained model fatal error occurs.

My code:
from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from sparknlp.annotator import *
from sparknlp.common import *

from sparknlp.base import *
import sparknlp
spark = sparknlp.start()

bert = BertEmbeddings.pretrained('bert_base_cased', 'en')\
.setInputCols(["sentence",'token'])\
.setOutputCol("bert")\
.setCaseSensitive(False)\
.setPoolingLayer(0) # default 0

## Expected Behavior

The model Should have loaded without any fatal error

## Current Behavior

error on the terminal:

Download done! Loading the resource.
```
 A fatal error has been detected by the Java Runtime Environment:

  SIGILL (0x4) at pc=0x00007fbb92742210, pid=20478, tid=0x00007fbbb1c44700

 JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
 Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libtensorflow_framework.so.2+0x1550210]  nsync::nsync_mu_init(nsync::nsync_mu_s_*)+0x0

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /datadrive/users/shubhamkd/hs_err_pid20478.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.
```
Error on the notebook:
```
bert_base_cased download started this may take some time.
Approximate size to download 389.1 MB
[ \ ]
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/shubhamkd/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shubhamkd/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/home/shubhamkd/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1212, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
[OK!]
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-8-9152bd939383> in <module>
      8 spark = sparknlp.start()
      9 
---> 10 bert = BertEmbeddings.pretrained('bert_base_cased', 'en')\
     11 .setInputCols(["sentence",'token'])\
     12 .setOutputCol("bert")\

~/.local/lib/python3.6/site-packages/sparknlp/annotator.py in pretrained(name, lang, remote_loc)
   5213     def pretrained(name="small_bert_L2_768", lang="en", remote_loc=None):
   5214         from sparknlp.pretrained import ResourceDownloader
-> 5215         return ResourceDownloader.downloadModel(BertEmbeddings, name, lang, remote_loc)
   5216 
   5217 

~/.local/lib/python3.6/site-packages/sparknlp/pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     58             t1.start()
     59             try:
---> 60                 j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     61             except Py4JJavaError as e:
     62                 sys.stdout.write("\n" + str(e))

~/.local/lib/python3.6/site-packages/sparknlp/internal.py in __init__(self, reader, name, language, remote_loc, validator)
    192 class _DownloadModel(ExtendedJavaWrapper):
    193     def __init__(self, reader, name, language, remote_loc, validator):
--> 194         super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
    195 
    196 

~/.local/lib/python3.6/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
    145         super(ExtendedJavaWrapper, self).__init__(java_obj)
    146         self.sc = SparkContext._active_spark_context
--> 147         self._java_obj = self.new_java_obj(java_obj, *args)
    148         self.java_obj = self._java_obj
    149 

~/.local/lib/python3.6/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    155 
    156     def new_java_obj(self, java_class, *args):
--> 157         return self._new_java_obj(java_class, *args)
    158 
    159     def new_java_array(self, pylist, java_class):

~/spark-3.0.3-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     67             java_obj = getattr(java_obj, name)
     68         java_args = [_py2java(sc, arg) for arg in args]
---> 69         return java_obj(*java_args)
     70 
     71     @staticmethod

~/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

~/spark-3.0.3-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
    126     def deco(*a, **kw):
    127         try:
--> 128             return f(*a, **kw)
    129         except py4j.protocol.Py4JJavaError as e:
    130             converted = convert_exception(e.java_exception)

~/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
--> 336                 format(target_id, ".", name))
    337     else:
    338         type = answer[1]

Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel
## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
```
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

Spark NLP version sparknlp.version():3.1.1
Apache NLP version spark.version:3.0.3
Java version java -version:1.8.0_292
Setup and installation (Pypi, Conda, Maven, etc.):Pypi
Operating System and version:Ubuntu 18.04.5 LTS
Link to your project (if any):

**Comment by maziyarpanahi** [comment]
@albertoandreottiATgmail You have more experience with Ubuntu 18.04.5 LTS and TensorFlow C/GCC. If you can help here would be great.

@shubbham37 Could you please provide system info about your `Ubuntu 18.04.5 LTS`? The hardware? (laptop, server, VM, etc.) The type of CPU?

**Comment by shubbham37** [comment]
Server
