### ISSUE TITLE
LongformerEmbedding, BertForTokenClassification, and DistilBertForTokenClassification Models not loading in Python

### ISSUE THREAD

**Issue by DevinTDHa** [JohnSnowLabs/spark-nlp#5947]
## Description

There are some issues with loading and using some Longformer models. 

The model can't be loaded with the error `Unsupported Model: LONGFORMER_EMBEDDINGS`.  This was observed in Colab as well as Databricks.

Both models `longformer_base_4096` and `longformer_large_4096` throw the same error.

The error does not happen in the Scala version.

## Expected Behavior

The annotator should load the pretrained model.

## Current Behavior

The annotator throws the error.

### Colab
1. Run the setup script `https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/colab_setup.sh`
2. Update spark nlp to latest version ` pip install --upgrade spark-nlp`
3. Run this example pipeline:
```python
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline

# First extract the prerequisites for the NerDLModel
documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")

tokenizer = Tokenizer() \
    .setInputCols(["document"]) \
    .setOutputCol("token")

# Use the transformer embeddings
embeddings = LongformerEmbeddings \
      .pretrained("longformer_base_4096")\
      .setInputCols(['document', 'token'])\
      .setOutputCol("embeddings")\
      .setCaseSensitive(True)\
      .setMaxSentenceLength(4096)

# This pretrained model requires those specific transformer embeddings
ner_model = NerDLModel.pretrained('ner_conll_longformer_base_4096', 'en') \
    .setInputCols(['document', 'token', 'embeddings']) \
    .setOutputCol('ner')

pipeline = Pipeline().setStages([
    documentAssembler,
    sentence,
    tokenizer,
    embeddings,
    ner_model
])

data = spark.createDataFrame([["U.N. official Ekeus heads for Baghdad."]]).toDF("text")
result = pipeline.fit(data).transform(data)

result.select("ner.result").show(truncate=False)
```
### Databricks
Same as colab, but Spark NLP is installed without the script.

## Stack Trace
```
longformer_base_4096 download started this may take some time.
Approximate size to download 343.3 MB
[ | ]
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.RuntimeException: Unsupported Model: LONGFORMER_EMBEDDINGS
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.$anonfun$downloadModel$1(ResourceDownloader.scala:453)
	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
	at scala.collection.AbstractMap.getOrElse(Map.scala:63)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:453)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
[OK!]

---------------------------------------------------------------------------

Py4JJavaError                             Traceback (most recent call last)

<ipython-input-6-1ad04ff4b3f2> in <module>()
     10 
     11 # Use the transformer embeddings
---> 12 embeddings = LongformerEmbeddings       .pretrained("longformer_base_4096")      .setInputCols(['document', 'token'])      .setOutputCol("embeddings")      .setCaseSensitive(True)      .setMaxSentenceLength(4096)
     13 
     14 # This pretrained model requires those specific transformer embeddings

9 frames

/usr/local/lib/python3.7/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.RuntimeException: Unsupported Model: LONGFORMER_EMBEDDINGS
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.$anonfun$downloadModel$1(ResourceDownloader.scala:453)
	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
	at scala.collection.AbstractMap.getOrElse(Map.scala:63)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:453)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
## Your Environment

* Spark NLP version `sparknlp.version()`: 3.2.0
* Apache NLP version `spark.version`: 3.0.2 (Colab), 3.1.0 (Databricks)
* Java version `java -version`: openjdk version "1.8.0_292" (Colab), openjdk version "1.8.0_282" (Databricks
* Setup and installation (Pypi, Conda, Maven, etc.): Colab, Databricks

**Comment by maziyarpanahi** [comment]
Thanks @DevinTDHa 
I'll do a patch release tomorrow.
