### ISSUE TITLE
Loading Pre-trained German Bert Model results in No Operation named [save/restore_all] in the Graph

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#5950]
I am running Spark and Spark NLP in the Google Cloud using the following code to start the session:

```py
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *

import argparse
import os
import time

from datetime import datetime
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import desc, col, isnan, when, count, stddev
from pyspark.sql import Row
from pyspark.sql.functions import udf

spark = SparkSession.builder \
.master('local[*]') \
.appName('NLP Test') \
.config("spark.driver.memory", "6g") \
.config("spark.executor.memory", "6g") \
.config("spark.jars", "gs://..../external_jars/spark-nlp-spark24_2.11-3.0.3.jar") \
.config("spark.jars", "gs://..../SparkNLP/init/version_3_3/spark-nlp-assembly-3.0.3.jar") \
.getOrCreate()

sc = spark.sparkContext

print("    Spark version:", spark.version)
print("Spark NLP version:", sparknlp.version())
!scala -version
```

Output:
    Spark version: 3.1.1
Spark NLP version: 3.1.1
Scala code runner version 2.12.13 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.

```py
# Process fails with same exception on both German Bert models
# Uncased model: https://nlp.johnsnowlabs.com/2021/05/20/bert_base_german_uncased_de.html
# Cased model: https://nlp.johnsnowlabs.com/2021/05/20/bert_base_german_cased_de.html
bert_annotator = BertEmbeddings.load('gs://..../SparkNLP/NER/bert_base_german_cased_de_3.1.0_3.0_1621502949396/') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
.setBatchSize(8)
```

Output:
```
---------------------------------------------------------------------------
IllegalArgumentException                  Traceback (most recent call last)
<ipython-input-13-f8bf53f38603> in <module>
      6 
----> 7 bert_annotator = BertEmbeddings.load('gs://..../SparkNLP/NER/bert_base_german_cased_de_3.1.0_3.0_1621502949396/') \
      8  .setInputCols(["sentence",'token'])\
      9  .setOutputCol("bert")\

/usr/lib/spark/python/pyspark/ml/util.py in load(cls, path)
    330     def load(cls, path):
    331         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 332         return cls.read().load(path)
    333 
    334 

/usr/lib/spark/python/pyspark/ml/util.py in load(self, path)
    280         if not isinstance(path, str):
    281             raise TypeError("path should be a string, got type %s" % type(path))
--> 282         java_obj = self._jread.load(path)
    283         if not hasattr(self._clazz, "_from_java"):
    284             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

/opt/conda/miniconda3/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115                 # Hide where the exception came from that shows a non-Pythonic
    116                 # JVM exception message.
--> 117                 raise converted from None
    118             else:
    119                 raise

IllegalArgumentException: No Operation named [save/restore_all] in the Graph

```
## Description

The session starts fine and I was able to use a different [POS model](https://nlp.johnsnowlabs.com/2021/03/08/pos_ud_hdt_de.html) using the same setup. So, I am thinking this could be a bug rather than me using a wrong setup(?). If you require more information please let me know how to query it in python since the setup was done by a different person (I am not sure how to determine things like loaded jars, OS etc.)

## Expected Behavior

The model should be loaded and available as other embeddings are.

## Current Behavior

See output listed above.

## Steps to Reproduce

See above description

## Context

I am trying to optimize a NER pipeline that works in version 2.4 but requires a large multilangual pre-trained Bert model - I was hoping to be more effective and efficient by using Spark/NLP version 3.1 with the german pre-trained model.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.1
* Apache NLP version `spark.version`: 3.1.1
* Java version `java -version`:
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

I am very confused here:

```
.config("spark.jars", "gs://..../external_jars/spark-nlp-spark24_2.11-3.0.3.jar") \
.config("spark.jars", "gs://..../SparkNLP/init/version_3_3/spark-nlp-assembly-3.0.3.jar") \
```
- Why do you have two entirely different Fat JARs in your SparkSession? If you are on pyspark 2.4, you should use `spark-nlp-spark24_2.11` and if you are on pyspark 3. (as you mentioned) you should use `spark-nlp-assembly`. But both at the same time?
- Why are they 3.0.3 when you said 3.1.1 (your PyPI might be 3.1.1, but your Fat Jar must be the same version)
- And finally, why is it an issue if the model that says it is compatible with Spark NLP 3.1.x, crashes on Spark NLP 3.0.3? (it is supposed to crash)

![image](https://user-images.githubusercontent.com/5762953/129180074-4b33ed11-7816-4ccf-8422-244866d73f80.png)

**Comment by Dirkster99** [comment]
Cool. I've loaded the above jar file **only** in the shown config section and got this work with the German cased and uncased embeddings. So, just to be crystal clear and sure:

- Using Spark 3.1.1. I can use any FATJar with version >= 3.1.1 and use corresponding models, right?

**Comment by Dirkster99** [comment]
I guess I was too quick with my confirmation :-( I use the above German uncased Bert model in a NER pipeline and the Bert model appears to be loading fine but the pipeline is now producing a stacktrace. Could this be because something else required is missing?

```py
nerTagger = NerDLApproach()\
  .setInputCols(["sentence", "token", "bert"])\
  .setLabelColumn("label")\
  .setOutputCol("ner")\
  .setMaxEpochs(5)\
  .setLr(0.001)\
  .setPo(0.005)\
  .setBatchSize(8)\
  .setEvaluationLogExtended(True) \
  .setEnableOutputLogs(True)\
  .setTestDataset("test_withEmbeds.parquet")

pipeline = Pipeline(
    stages = [
    bert_annotator,
    nerTagger
  ])

ner_model = pipeline.fit(training_data)

```

Output:
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<timed exec> in <module>

/usr/lib/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/usr/lib/spark/python/pyspark/ml/pipeline.py in _fit(self, dataset)
    112                     dataset = stage.transform(dataset)
    113                 else:  # must be an Estimator
--> 114                     model = stage.fit(dataset)
    115                     transformers.append(model)
    116                     if i < indexOfLastEstimator:

/usr/lib/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/usr/lib/spark/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    333 
    334     def _fit(self, dataset):
--> 335         java_model = self._fit_java(dataset)
    336         model = self._create_model(java_model)
    337         return self._copyValues(model)

/usr/lib/spark/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    329             fitted Java model
    330         """
--> 331         self._transfer_params_to_java()
    332         return self._java_obj.fit(dataset._jdf)
    333 

/usr/lib/spark/python/pyspark/ml/wrapper.py in _transfer_params_to_java(self)
    144                 self._java_obj.set(pair)
    145             if self.hasDefault(param):
--> 146                 pair = self._make_java_param_pair(param, self._defaultParamMap[param])
    147                 pair_defaults.append(pair)
    148         if len(pair_defaults) > 0:

/usr/lib/spark/python/pyspark/ml/wrapper.py in _make_java_param_pair(self, param, value)
    130         sc = SparkContext._active_spark_context
    131         param = self._resolveParam(param)
--> 132         java_param = self._java_obj.getParam(param.name)
    133         java_value = _py2java(sc, value)
    134         return java_param.w(java_value)

/opt/conda/miniconda3/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

/opt/conda/miniconda3/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o138.getParam.
: java.util.NoSuchElementException: Param includeAllConfidenceScores does not exist.
	at org.apache.spark.ml.param.Params.$anonfun$getParam$2(params.scala:705)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.ml.param.Params.getParam(params.scala:705)
	at org.apache.spark.ml.param.Params.getParam$(params.scala:703)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:41)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Dirkster99** [comment]
I got it to work in the end I was using the wrong whl file :-( So, I think the correct setup for Spark 3.1.1/NLP 3.1.1 is to use these files:

spark-nlp-assembly-3.1.1.jar (https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.1.1)
spark_nlp-3.1.1-py2.py3-none-any.whl (https://pypi.org/project/spark-nlp/3.1.1/#modal-close)

with the seesion start-up method via spark:

```py
spark = SparkSession.builder \
.master('local[*]') \
.appName('NLP Test') \
.config("spark.driver.memory", "6g") \
.config("spark.executor.memory", "6g") \
.config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
   .config("spark.kryoserializer.buffer.max", "2000M") \
.config("spark.jars", "gs://vf-de-ca-lab-dev/notebooks/jupyter/DirkB_test/SparkNLP/init/SparkNLP_version_3_1_1/spark-nlp-assembly-3.1.1.jar") \
.getOrCreate()
```

I guess the setup could be improved since it requires using multiple file from different sources and there no warnings when one uses one file of a certain version that requires another file of a certain version but is not present :-( Anyways, my mistake, sorry about that.
