### ISSUE TITLE
GraphExtraction not working with LightPipeline

### ISSUE THREAD

**Issue by JoaoBone** [JohnSnowLabs/spark-nlp#6091]
GraphExtraction is returning an ArrayIndexOutOfBoundsException when used with LightPipeline. Works fine otherwise.

## Description
I tried implementing GraphExtraction with a previously trained NER model, and used a LightPipeline. 
Although it fits the pipeline, when trying to annotate an example with any RelationshipTypes set, it returns a java.lang.ArrayIndexOutOfBoundsException.
@danilojsl has managed to replicate this issue, and indicated that it seems to be a bug when using LightPipeline with GraphExtraction.

## Expected Behavior

When annotating a string, the following output would be expected:

```
{   'dependency': [   'fell',
                      'Ms',
                      'fell',
                      'ROOT',
                      'overdose',
                      'overdose',
                      'overdose',
                      'fell',
                      'paracetamol',
                      'overdose'],
    'dependency_type': [   'nsubj',
                           'punct',
                           'nsubj',
                           'root',
                           'amod',
                           'mark',
                           'nsubj',
                           'nsubj',
                           'det',
                           'flat'],
    'documents': ['Ms. Stewart fell due to an overdose of paracetamol'],
    'embeddings': [   'Ms',
                      '.',
                      'Stewart',
                      'fell',
                      'due',
                      'to',
                      'an',
                      'overdose',
                      'of',
                      'paracetamol'],
    'ner': [   'O',
               'O',
               'O',
               'I-Diagnosis',
               'O',
               'O',
               'O',
               'O',
               'O',
               'I-Medication'],
    'pos': ['NNP', '.', 'NNP', 'VBD', 'JJ', 'TO', 'DT', 'NN', 'IN', 'NN'],
    'raw_graph': [],
    'sentences': ['Ms. Stewart fell due to an overdose of paracetamol'],
    'token': [   'Ms',
                 '.',
                 'Stewart',
                 'fell',
                 'due',
                 'to',
                 'an',
                 'overdose',
                 'of',
                 'paracetamol']}
```

## Current Behavior

```
Py4JJavaError: An error occurred while calling o11442.annotateJava.
: java.lang.ArrayIndexOutOfBoundsException: 5
	at com.johnsnowlabs.nlp.util.GraphBuilder.$anonfun$findPath$2(GraphBuilder.scala:66)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at com.johnsnowlabs.nlp.util.GraphBuilder.findPath(GraphBuilder.scala:62)
	at com.johnsnowlabs.nlp.annotators.GraphExtraction.buildPath(GraphExtraction.scala:465)
	at com.johnsnowlabs.nlp.annotators.GraphExtraction.$anonfun$extractGraphsFromRelationships$7(GraphExtraction.scala:448)
```

## Possible Solution
--

## Steps to Reproduce

1. Create a pipeline like this:

```
documenter = DocumentAssembler() \
             .setInputCol("text") \
             .setOutputCol("documents")

sentence_detector = SentenceDetector() \
                    .setInputCols("documents") \
                    .setOutputCol("sentences")

tokenizer = Tokenizer() \
            .setInputCols("sentences") \
            .setOutputCol("token")

embedder = BertEmbeddings.pretrained('biobert_clinical_base_cased', 'en') \
           .setInputCols(["sentences", "token"]) \
           .setOutputCol("embeddings")

ner = MedicalNerModel.load('custom_NER_Diag&Med_ALabTagTog_biobert_clinical_base_cased_IO_part6') \
      .setInputCols(['sentence', 'token', "embeddings"]) \
      .setOutputCol("ner")


posTagger = PerceptronModel.pretrained() \
            .setInputCols(["sentences", "token"]) \
            .setOutputCol("pos")

dependencyParser = DependencyParserModel.pretrained() \
                   .setInputCols(["sentences", "pos", "token"]) \
                   .setOutputCol("dependency")

typedDependencyParser = TypedDependencyParserModel.pretrained() \
                        .setInputCols(["dependency", "pos", "token"]) \
                        .setOutputCol("dependency_type")

graph_extractor = GraphExtraction() \
                  .setInputCols(["sentences", "token", "ner"]) \
                  .setOutputCol("raw_graph") \
                  .setRelationshipTypes(["due-Medication"])

graph_finisher = GraphFinisher() \
                 .setInputCol("raw_graph") \
                 .setOutputCol("graph")\
                 .setOutputAsArray(False)

pipeline = Pipeline().setStages(
    [
        documenter,
        sentence_detector,
        tokenizer,
        embedder,
        ner,
        posTagger,
        dependencyParser,
        typedDependencyParser,
        graph_extractor,
        graph_finisher
    ])

light_pipeline = LightPipeline(pipeline.fit(spark.createDataFrame([['']]).toDF("text")))
```

2. Try to annotate something, like this:

```
test_phrase = "Ms. Stewart fell due to an overdose of paracetamol"
print(light_pipeline.annotate(test_phrase ))
```

3. Clear the RelationshipTypes:

```
...
.setRelationshipTypes([""])
...

```

4. Try to annotate the same string again.

## Context
I've been trying to extract relationships between extracted entities in a medical report style of text.

## Your Environment

* Spark NLP version `sparknlp.version()`: SparkNLP 3.2.1, SparkNLP for Healthcare 3.2.0
* Apache NLP version `spark.version`: Pyspark 3.1.2
* Java version `java -version`: 8
* Setup and installation (Pypi, Conda, Maven, etc.): Conda
* Operating System and version: Ubuntu 20.04

**Comment by maziyarpanahi** [comment]
@JoaoBone Thanks for reporting this.

@danilojsl I think GraphFinisher is not added to LightPipeline support, could you please have a look so we can fix this by next release?

**Comment by danilojsl** [comment]
Hi @maziyarpanahi sure I will work on the solution.
Thanks for creating the issue @JoaoBone

**Comment by JoaoBone** [comment]
Thank you both for taking care of it so quickly!
