### ISSUE TITLE
java.lang.IllegalArgumentException: No Operation named [test_cids] in the Graph

### ISSUE THREAD

**Issue by karolisjan** [JohnSnowLabs/spark-nlp#618]
## Description

Unable to run a simple example using `explain_document_dl_en_2.1.0_2.4_1562946191575`. However, `recognize_entities_dl_en_2.1.0_2.4_1562946909722` works.

```bash
Py4JJavaError: An error occurred while calling o648.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 69.0 failed 1 times, most recent failure: Lost task 2.0 in stage 69.0 (TID 212, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.project_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No Operation named [test_cids] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:372)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:381)
	at org.tensorflow.Session$Runner.feed(Session.java:131)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSpell$$anonfun$predict_$1.apply(TensorflowSpell.scala:60)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSpell$$anonfun$predict_$1.apply(TensorflowSpell.scala:54)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSpell.predict_(TensorflowSpell.scala:54)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$decodeViterbi$1.apply$mcVI$sp(ContextSpellCheckerModel.scala:152)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel.decodeViterbi(ContextSpellCheckerModel.scala:131)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20$$anonfun$24.apply(ContextSpellCheckerModel.scala:242)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20$$anonfun$24.apply(ContextSpellCheckerModel.scala:242)
	at scala.Option.getOrElse(Option.scala:121)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20.apply(ContextSpellCheckerModel.scala:242)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20.apply(ContextSpellCheckerModel.scala:233)
	at scala.collection.MapLike$MappedValues$$anonfun$iterator$3.apply(MapLike.scala:246)
	at scala.collection.MapLike$MappedValues$$anonfun$iterator$3.apply(MapLike.scala:246)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.MapLike$$anon$2.next(MapLike.scala:216)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at scala.collection.generic.GenericTraversableTemplate$class.flatten(GenericTraversableTemplate.scala:171)
	at scala.collection.AbstractTraversable.flatten(Traversable.scala:104)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel.annotate(ContextSpellCheckerModel.scala:247)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
	... 22 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:365)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3383)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2544)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2544)
	at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3364)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3363)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2544)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2758)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:254)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.project_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalArgumentException: No Operation named [test_cids] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:372)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:381)
	at org.tensorflow.Session$Runner.feed(Session.java:131)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSpell$$anonfun$predict_$1.apply(TensorflowSpell.scala:60)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSpell$$anonfun$predict_$1.apply(TensorflowSpell.scala:54)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at com.johnsnowlabs.ml.tensorflow.TensorflowSpell.predict_(TensorflowSpell.scala:54)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$decodeViterbi$1.apply$mcVI$sp(ContextSpellCheckerModel.scala:152)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel.decodeViterbi(ContextSpellCheckerModel.scala:131)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20$$anonfun$24.apply(ContextSpellCheckerModel.scala:242)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20$$anonfun$24.apply(ContextSpellCheckerModel.scala:242)
	at scala.Option.getOrElse(Option.scala:121)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20.apply(ContextSpellCheckerModel.scala:242)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel$$anonfun$20.apply(ContextSpellCheckerModel.scala:233)
	at scala.collection.MapLike$MappedValues$$anonfun$iterator$3.apply(MapLike.scala:246)
	at scala.collection.MapLike$MappedValues$$anonfun$iterator$3.apply(MapLike.scala:246)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.MapLike$$anon$2.next(MapLike.scala:216)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at scala.collection.generic.GenericTraversableTemplate$class.flatten(GenericTraversableTemplate.scala:171)
	at scala.collection.AbstractTraversable.flatten(Traversable.scala:104)
	at com.johnsnowlabs.nlp.annotators.spell.context.ContextSpellCheckerModel.annotate(ContextSpellCheckerModel.scala:247)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
	... 22 more
```

## Steps to Reproduce

```python
import pyspark
import pandas as pd

ss = pyspark.sql.SparkSession.builder\
    .master('local[4]')\
    .config('spark.app.name', 'spark-nlp-demo') \
    .config('spark.driver.memory','8G') \
    .config('spark.jars', '~/spark-nlp/target/scala-2.11/spark-nlp-assembly-2.2.1.jar') \
    .getOrCreate()
    
# Replacing explain_document_dl_en_2.1.0_2.4_1562946191575 with recognize_entities_dl_en_2.1.0_2.4_1562946909722 works
pipeline = PipelineModel.load('~/spark-nlp/explain_document_dl_en_2.1.0_2.4_1562946191575')

spark_df = ss.createDataFrame(pd.DataFrame(['Harry Potter is a great movie'], columns=['text']))
result = pipeline .transform(spark_df)
result.show()
```

## Environment

* `pyspark==2.4.3` installed with `pip`
* `spark-nlp==2.2.1` installed with `pip`
* `spark-nlp-assembly-2.2.1.jar` built locally with `sbt v0.13.18`

**Comment by maziyarpanahi** [comment]
There was a problem with the exact pipeline you are using. Be careful when you are loading pipelines offline you won’t be downloading the new, fixed, and improved pipelines. To have the latest pipeline use this please: 

pipeline = PretrainedPipeline("explain_document_dl", lang="en")

**Comment by karolisjan** [comment]
@maziyarpanahi thanks. I was loading the pipeline offline because was running into the following error with `pipeline = PretrainedPipeline("explain_document_dl", lang="en")`. FYI, I'm working behind a proxy.

```bash
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NullPointerException
	at com.amazonaws.ClientConfiguration.getProxyUsernameEnvironment(ClientConfiguration.java:874)
	at com.amazonaws.ClientConfiguration.getProxyUsername(ClientConfiguration.java:902)
	at com.amazonaws.http.settings.HttpClientSettings.getProxyUsername(HttpClientSettings.java:90)
	at com.amazonaws.http.settings.HttpClientSettings.isAuthenticatedProxy(HttpClientSettings.java:182)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.addProxyConfig(ApacheHttpClientFactory.java:96)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:75)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:324)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:308)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:229)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:181)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:617)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:597)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:575)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:542)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.client$lzycompute(S3ResourceDownloader.scala:45)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.client(S3ResourceDownloader.scala:36)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:69)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:81)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:159)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:382)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:468)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maziyarpanahi** [comment]
That must be the proxy. No worries, I’ll update the links to offline pipelines tomorrow so at least you use the latest and fixed pipelines while you are loading them.

**Comment by maziyarpanahi** [comment]
I have updated the links to `explain_document_dl` to use the new pipelines. 
https://nlp.johnsnowlabs.com/docs/en/pipelines

**Comment by karolisjan** [comment]
Great. Thanks!
