### ISSUE TITLE
java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable

### ISSUE THREAD

**Issue by karolisjan** [JohnSnowLabs/spark-nlp#628]
## Description

Getting this error while loading the pipeline or model.

```bash
recognize_entities_dl_en_pipeline = PipelineModel.load('recognize_entities_dl_en_2.1.0_2.4_1562946909722')
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-12-cf62a6d8e33d> in <module>
----> 1 recognize_entities_dl_en_pipeline = PipelineModel.load(path_to_model)
~/pyspark/lib/python3.7/site-packages/pyspark/ml/util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 
~/pyspark/lib/python3.7/site-packages/pyspark/ml/pipeline.py in load(self, path)
    240         metadata = DefaultParamsReader.loadMetadata(path, self.sc)
    241         if 'language' not in metadata['paramMap'] or metadata['paramMap']['language'] != 'Python':
--> 242             return JavaMLReader(self.cls).load(path)
    243         else:
    244             uid, stages = PipelineSharedReadWrite.load(metadata, self.sc, path)
~/pyspark/lib/python3.7/site-packages/pyspark/ml/util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"
~/pyspark/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:
~/pyspark/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()
~/pyspark/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o294.load.
: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable
    at com.johnsnowlabs.nlp.serialization.Feature.<init>(Feature.scala:19)
    at com.johnsnowlabs.nlp.serialization.StructFeature.<init>(Feature.scala:107)
    at com.johnsnowlabs.nlp.annotators.TokenizerModel.<init>(TokenizerModel.scala:25)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:496)
    at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:12)
    at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
    at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:652)
    at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
    at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
    at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
    at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:282)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:238)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigMergeable
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 32 more
```

## Steps to Reproduce
I've tested different pipelines and models - all return the same error. Also tested using a locally built `jar` vs pulling it online - same result too:

**Option 1 - using a locally built `jar`**
```python
import pyspark
from sparknlp.base import PipelineModel

ss = pyspark.sql.SparkSession.builder\
    .master('local[4]')\
    .config('spark.app.name', 'spark-nlp-demo') \
    .config('spark.driver.memory','8G') \
    .config('spark.jars', 'spark-nlp/target/scala-2.11/spark-nlp-assembly-2.2.1.jar') \
    .getOrCreate()
    
recognize_entities_dl_en_pipeline = PipelineModel.load('recognize_entities_dl_en_2.1.0_2.4_1562946909722')
```

**Option 2 - importing the `jar` from `spark.jars.packages`**
```python
import pyspark
from sparknlp.base import PipelineModel

proxy_host = ''
proxy_port = ''
username = ''
password = ''

ss = pyspark.sql.SparkSession.builder\
    .master('local[4]')\
    .config('spark.app.name', 'spark-nlp-demo') \
    .config('spark.driver.memory','8G') \
    .config(
        'spark.driver.extraJavaOptions', 
        f'-Dhttp.proxyHost={proxy_host} -Dhttp.proxyPort={proxy_port} -Dhttp.proxyUser={username} -Dhttp.proxyPassword={password}' + \
        f' -Dhttps.proxyHost={proxy_host} -Dhttps.proxyPort={proxy_port} -Dhttps.proxyUser={username} -Dhttps.proxyPassword={password}'
    ) \
    .config('spark.jars.packages', 'JohnSnowLabs:spark-nlp:2.2.1') \
    .getOrCreate()
    
recognize_entities_dl_en_pipeline = PipelineModel.load('recognize_entities_dl_en_2.1.0_2.4_1562946909722')
```

## Environment

* `pyspark==2.4.3` installed with `pip`
* `spark-nlp==2.2.1` installed with `pip`

**Comment by maziyarpanahi** [comment]
I think this is still related to the proxy! Somehow still checks the configs instead of bypassing it for an offline load.
All the mentioned pipelines work perfectly without proxy in both online and offline situations. I'll let the team know about the proxy, but I am afraid this issue seems the same as your other issue.

**Comment by maziyarpanahi** [comment]
If you agree this is the result of proxies, could you please add you issue as a comment to your existing issue for more evidence and extra info for reproducing and removing this one?

**Comment by karolisjan** [comment]
So to give a bit more context, I'm posting on behalf of my college who was getting this error. We have identical setup, the PySpark environments are identical (based on the Spark UI output), `/usr/bin/env` output is identical, she was also able to build the `jar` herself (step that requires proxy auth). For some reason she is getting this error...

Also, with the **Option 2**, `JohnSnowLabs:spark-nlp:2.2.1` gets pulled successfully and I can see `typesafe` dependency is present in `$HOME/.ivy2/jars/com.typesafe_config-1.3.0.jar`.

**Comment by maziyarpanahi** [comment]
The proxy issue blocking the download for pretrained is something we should look at. Which might be the same issue for Option 2. But Option 1, I have always had the issue with `spark.jars`. If you don't have `spark-nlp` installed via `pip` or `conda` the very first line `from sparknlp.base` will give you an error. So if you have, then loading the JAR might have some conflicts. 

Could you make sure there is no Spark NLP is installed in your Python env? Also, if this is a PySpark, how are you starting it? Is this a pyspark-shell? Keep in mind in some situations Spark Session is being created beforehand like in spark-shell and it's best to pass --jars config.

**Comment by maziyarpanahi** [comment]
And one more thing, make sure the JAR is a Fat jar. The size should be around `120MB`. When you clone:

```bash
git checkout 2.2.1
sbt clean && sbt assembly
```
And use that JAR, otherwise, the package will be few megabytes and ot won't be having any dependencies.

**Comment by karolisjan** [comment]
The problem turned out to be caused by the fact that driver and worker Python had different versions. Even though the `PYSPARK_PYTHON` and `PYSPARK_DRIVER_PYTHON` environment variables were set correctly and PySpark was running fine in local mode. After setting up both `PYSPARK_PYTHON` and `PYSPARK_DRIVER_PYTHON` have the same versions, the error was fixed.

**More context:**
PySpark is launched in the local mode from a notebook. The driver is jupyter which is running in a separate virtual environment. The worker is from another virtual environment where `pyspark` and `spark-nlp` are installed.
