### ISSUE TITLE
SentimentDLModel expects column with ref.  tfhub_use

### ISSUE THREAD

**Issue by kgoderis** [JohnSnowLabs/spark-nlp#6313]
## Description
When building a Pipeline with a SentimentDLModel, and feeding that annotator with sentence embeddings coming from a  SentenceEmbeddings stage, the runtime throws a IllegalArgumentException:

2021-10-18 08:27:23.461 ERROR 66773 --- [nTaskExecutor-1] o.apache.spark.ml.util.Instrumentation   : java.lang.IllegalArgumentException: requirement failed: Found input column with storage metadata. But such ref does not match to the ref this annotator requires. Make sure you are loading the annotator with ref: **tfhub_use**
	at scala.Predef$.require(Predef.scala:281)
	at com.johnsnowlabs.storage.HasStorageRef.validateStorageRef(HasStorageRef.scala:32)
	at com.johnsnowlabs.storage.HasStorageRef.validateStorageRef$(HasStorageRef.scala:28)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel.validateStorageRef(SentimentDLModel.scala:95)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel.beforeAnnotate(SentimentDLModel.scala:212)
	at com.johnsnowlabs.nlp.AnnotatorModel._transform(AnnotatorModel.scala:50)
	at com.johnsnowlabs.nlp.AnnotatorModel.transform(AnnotatorModel.scala:96)
	at org.apache.spark.ml.PipelineModel.$anonfun$transform$4(Pipeline.scala:311)
	at org.apache.spark.ml.MLEvents.withTransformEvent(events.scala:146)
	at org.apache.spark.ml.MLEvents.withTransformEvent$(events.scala:139)
	at org.apache.spark.ml.util.Instrumentation.withTransformEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.PipelineModel.$anonfun$transform$3(Pipeline.scala:311)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:198)
	at org.apache.spark.ml.PipelineModel.$anonfun$transform$2(Pipeline.scala:310)
	at org.apache.spark.ml.MLEvents.withTransformEvent(events.scala:146)
	at org.apache.spark.ml.MLEvents.withTransformEvent$(events.scala:139)
	at org.apache.spark.ml.util.Instrumentation.withTransformEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.PipelineModel.$anonfun$transform$1(Pipeline.scala:308)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
	at org.apache.spark.ml.PipelineModel.transform(Pipeline.scala:307)

I have no clue where this tfhub_use reference is coming from, AFAIK it is only used as a reference when getting some pre-trained annotators

## Expected Behavior
The model should be fitted as SentenceEmbeddings outputs a column of type SENTENCE_EMBEDDINGS and SentimentDLModel takes one of type SENTENCE_EMBEDDINGS as input

https://github.com/JohnSnowLabs/spark-nlp/blob/340fe8068fae9a83130871f31633109f5fda8e70/src/main/scala/com/johnsnowlabs/nlp/embeddings/SentenceEmbeddings.scala#L115

https://github.com/JohnSnowLabs/spark-nlp/blob/340fe8068fae9a83130871f31633109f5fda8e70/src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/SentimentDLModel.scala#L122

## Possible Solution

The same pipeline implemented in python does not have that problem, but in python there is no runtime complaint if the SentimentDLModel has more than one input column, e.g. I feed it the "document" and "sentence embeddings"

## Steps to Reproduce
1. Build a pipeline with at least the following stages

```
	protected Pipeline buildPipeline() {
		return new Pipeline().setStages(new PipelineStage[] { getDocumentAssembler(), getTokenizer(), getEncoder(),
				getEmbedder(), getClassifier() });
	}

....
	 return ((SentenceEmbeddings) ((SentenceEmbeddings) new SentenceEmbeddings()
				.setInputCols(new String[] { "document", "embeddings" })).setOutputCol("sentence_embeddings"))
						.setPoolingStrategy("AVERAGE");
....

      return ((SentimentDLModel) ((SentimentDLModel) SentimentDLModel.pretrained(
                    "sentimentdl_use_twitter", "en").setInputCols( new String[] {"sentence_embeddings"})).setOutputCol("category"));	
```

I omitted the other stages

2. Fit the model using an empty Dataset (it does not matter as the model is pretrained anyways)

`model = buildPipeline().fit(spark.emptyDataFrame().withColumn("text", lit("dummy")));`

3. call transform() on a Dataset that has a "text" column

## Your Environment
spark.jars.packages : com.johnsnowlabs.nlp:spark-nlp_2.12:3.2.1

**Comment by maziyarpanahi** [comment]
Hi @kgoderis 

If a model was trained by a specific embeddings model (word or sentence), the storageRef of that model is connected to that specific embeddings model. It means you cannot use `sentimentdl_use_twitter` which is trained by UniversalSentenceEncoder with other embeddings. (this is a rule for all the models that require embeddings)

To avoid such issues, you can just have a look at the model's card on Models Hun for examples: https://nlp.johnsnowlabs.com/2021/01/18/sentimentdl_use_twitter_en.html (we always use the correct embeddings in the examples, you can also do a getStorageRef on your variable that holds SentimentDLModel (or any other annotator) and it tells you the exact name of the embeddings model's name you need to use it)
