### ISSUE TITLE
Error while using pretrained Sentiment Analysis in Java

### ISSUE THREAD

**Issue by ayushbnk** [JohnSnowLabs/spark-nlp#641]
## Description
I want to use SparkNLP for doing sentiment analysis on a spark dataset on column column1 using the default trained model. I downloaded the pretrained ViveknSentimentModel and extracted it and trying to use it in my code. This is my code:

```
DocumentAssembler docAssembler = (DocumentAssembler) new DocumentAssembler().setInputCol("column1")
                .setOutputCol("document");

Tokenizer tokenizer = (Tokenizer) ((Tokenizer) new Tokenizer().setInputCols(new String[] { "document" }))
                .setOutputCol("token");
String[] inputCols = new String[] { "token", "document" };

SentimentDetector sentiment =((SentimentDetector) ((SentimentDetector) ((SentimentDetector) ViveknSentimentModel
	.load("C:\\Users\\Ayush\\Downloads\\sentiment_vivekn_en_2.0.2_2.4_1556663184035\\"))
						.setInputCols(inputCols)).setOutputCol("sentiment"));
Pipeline pipeline = new Pipeline().setStages(new PipelineStage[] { docAssembler, tokenizer, sentiment });

// Fit the pipeline to training documents.
PipelineModel pipelineFit = pipeline.fit(ds);
ds = pipelineFit.transform(ds);
ds.show();`
```

I am getting the following error
`Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsedMillis()J
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:245)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:313)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1343)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1337)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1378)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1377)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:615)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:493)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:12)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:380)
	at com.johnsnowlabs.nlp.annotators.sda.vivekn.ViveknSentimentModel$.load(ViveknSentimentModel.scala:107)
	at com.johnsnowlabs.nlp.annotators.sda.vivekn.ViveknSentimentModel.load(ViveknSentimentModel.scala)
	at com.zscore.links.models.recipes.ZSCSentimentAnalysis.zscexecute(ZSCSentimentAnalysis.java:45)
	at com.zscore.donut.ZSCWorkflowExecution.zscexecuteRecipe(ZSCWorkflowExecution.java:98)`

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Spark NLP 2.11
* Browser Name and version:
* Operating System and version (desktop or mobile): Windows
* Link to your project:
Spark running in my local machine as standalone.

**Comment by maziyarpanahi** [comment]
Please complete the environment correctly including your setup. (ex: there is no `2.11` version in Spark NLP).

**Comment by willprice76** [comment]
This method is removed in Guava 16.0+ (see https://stackoverflow.com/a/31034594/1386714)
Fixing the guava dependency at version 15.0 will sort it:

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>15.0</version>
    </dependency>
