### ISSUE TITLE
RocksDB fails in earlier macOS versions

### ISSUE THREAD

**Issue by sabarishs** [JohnSnowLabs/spark-nlp#652]
I see the following issue  when I run the recognize_entities_dl pretrained model

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
Referenced from: /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/tensorflow_native_libraries-1569934535911-0//libtensorflow_framework.so (which was built for Mac OS X 10.12)
Expected in: /usr/lib/libSystem.B.dylib
```

## Expected Behavior
Entity recognition should work normally on a mac

## Current Behavior
Get the following error
```
18:25:35,683 [task-result-getter-0] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Finished task 0.0 in stage 16.0 (TID 29) in 12 ms on localhost (executor driver) (7/8)
18:25:35,684 [task-result-getter-1] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Finished task 6.0 in stage 16.0 (TID 35) in 12 ms on localhost (executor driver) (8/8)
18:25:35,684 [task-result-getter-1] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Removed TaskSet 16.0, whose tasks have all completed, from pool 
18:25:35,684 [dag-scheduler-event-loop] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - ResultStage 16 (first at Feature.scala:121) finished in 0.016 s
18:25:35,685 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Job 16 finished: first at Feature.scala:121, took 0.018724 s
18:25:35,686 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Block broadcast_31 stored as values in memory (estimated size 8.4 KB, free 2003.5 MB)
18:25:35,687 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Block broadcast_31_piece0 stored as bytes in memory (estimated size 895.0 B, free 2003.5 MB)
18:25:35,688 [dispatcher-event-loop-4] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Added broadcast_31_piece0 in memory on 192.168.0.100:49930 (size: 895.0 B, free: 2004.5 MB)
18:25:35,688 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Created broadcast 31 from broadcast at Feature.scala:88
18:25:35,698 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Added file /var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/sparknlp_contrib_spar at file:/private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/sparknlp_contrib_spar with timestamp 1569934535697
18:25:35,698 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Copying /var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/sparknlp_contrib_spar to /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/spark-30c7ec5a-3650-40a3-96fa-97d8c191c4b8/userFiles-3b712c2c-f1c2-4c77-9ac5-775a423fee12/sparknlp_contrib_spar
18:25:35,719 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Added file /var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/sparknlp_contrib_lstm at file:/private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/sparknlp_contrib_lstm with timestamp 1569934535719
18:25:35,719 [main] INFO  org.apache.spark.internal.Logging$class::logInfo()::54 - Copying /var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/sparknlp_contrib_lstm to /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/spark-30c7ec5a-3650-40a3-96fa-97d8c191c4b8/userFiles-3b712c2c-f1c2-4c77-9ac5-775a423fee12/sparknlp_contrib_lstm
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/tensorflow_native_libraries-1569934535911-0//libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/tensorflow_native_libraries-1569934535911-0//libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

## Steps to Reproduce
The code I used
```
        Dataset<Row> ds = spark.createDataFrame(
                Arrays.asList(new StringIdPair(1,
                        "Google has announced the release of a beta version of the popular TensorFlow machine learning library")),
                StringIdPair.class);
        PretrainedPipeline pl = new PretrainedPipeline("recognize_entities_dl", "en", "public/models");
        Dataset<Row> result = pl.transform(ds);
        result.select("entities.result").show();
```
Run with local master

## Context
Not able to run entity recognition

## Your Environment
Spark nlp: spark-nlp_2.11:2.2.2
Spark: spark-core_2.11:2.4.3, spark-mllib_2.11:2.4.3, spark-sql_2.11:2.4.3
Desktop: Mac OS X El Capitan 10.11.6

**Comment by sabarishs** [comment]
Thanks @maziyarpanahi for spraying enough hints. After a few tense moments upgrading to Sierra, I was able to make progress but failed with following error

```
java.lang.UnsatisfiedLinkError: /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/librocksdbjni8726785939966486594.jnilib: dlopen(/private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/librocksdbjni8726785939966486594.jnilib, 1): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/librocksdbjni8726785939966486594.jnilib
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/folders/zm/5y62__2n301059kxyg7_xym40000gp/T/librocksdbjni8726785939966486594.jnilib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.johnsnowlabs.nlp.embeddings.WordEmbeddingsRetriever.db(WordEmbeddingsRetriever.scala:18)
```

**Comment by maziyarpanahi** [comment]
Thanks this really helps. It’s actually about RockDB in our WordEmbeddings. I’ll look around to see any incompatibility with earlier macOS versions.

**Comment by sabarishs** [comment]
Thanks @maziyarpanahi  
Do we have an update on this? Btw, I tried rocksdb 5.15.10 (which we are using in other components) and that too failed with similar error. Do you have a suggestion for a rocksdb version I can try with?

**Comment by sabarishs** [comment]
Btw, my team confirmed it works with Mojave 10.14.6 and we were facing issues with rocksdb in other projects as well.
