### ISSUE TITLE
Model downloading every time & errors initializing session and downloading model

### ISSUE THREAD

**Issue by ghnp5** [JohnSnowLabs/spark-nlp#6565]
I read somewhere that this project doesn't download the model every time, on the same machine.
I'm running this on a Docker container ([my Dockerfile is here](https://github.com/JohnSnowLabs/spark-nlp/issues/6563)), but while it's running (without rebuilding or restarting or anything), it appears to me it's downloading multiple times, especially if I restart `python3`, and I'm also getting errors when initializing the session:

```
$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparknlp
>>> from sparknlp.pretrained import PretrainedPipeline
>>> spark = sparknlp.start()
:: loading settings :: url = jar:file:/usr/local/lib/python3.6/dist-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/yuefeng/.ivy2/cache
The jars for the packages stored in: /home/yuefeng/.ivy2/jars
com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-5a7da207-9721-4eef-9a0e-e433db968584;1.0
        confs: [default]
        found com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.4 in central
        found com.typesafe#config;1.4.1 in central
        found org.rocksdb#rocksdbjni;6.5.3 in central
        found com.amazonaws#aws-java-sdk-bundle;1.11.603 in central
        found com.github.universal-automata#liblevenshtein;3.0.0 in central
        found com.google.code.findbugs#annotations;3.0.1 in central
        found net.jcip#jcip-annotations;1.0 in central
        found com.google.code.findbugs#jsr305;3.0.1 in central
        found com.google.protobuf#protobuf-java-util;3.0.0-beta-3 in central
        found com.google.protobuf#protobuf-java;3.0.0-beta-3 in central
        found com.google.code.gson#gson;2.3 in central
        found it.unimi.dsi#fastutil;7.0.12 in central
        found org.projectlombok#lombok;1.16.8 in central
        found org.slf4j#slf4j-api;1.7.21 in central
        found com.navigamez#greex;1.0 in central
        found dk.brics.automaton#automaton;1.11-8 in central
        found org.json4s#json4s-ext_2.12;3.5.3 in central
        found joda-time#joda-time;2.9.5 in central
        found org.joda#joda-convert;1.8.1 in central
        found com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3 in central
        found net.sf.trove4j#trove4j;3.0.3 in central
:: resolution report :: resolve 1671ms :: artifacts dl 329ms
        :: modules in use:
        com.amazonaws#aws-java-sdk-bundle;1.11.603 from central in [default]
        com.github.universal-automata#liblevenshtein;3.0.0 from central in [default]
        com.google.code.findbugs#annotations;3.0.1 from central in [default]
        com.google.code.findbugs#jsr305;3.0.1 from central in [default]
        com.google.code.gson#gson;2.3 from central in [default]
        com.google.protobuf#protobuf-java;3.0.0-beta-3 from central in [default]
        com.google.protobuf#protobuf-java-util;3.0.0-beta-3 from central in [default]
        com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.4 from central in [default]
        com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3 from central in [default]
        com.navigamez#greex;1.0 from central in [default]
        com.typesafe#config;1.4.1 from central in [default]
        dk.brics.automaton#automaton;1.11-8 from central in [default]
        it.unimi.dsi#fastutil;7.0.12 from central in [default]
        joda-time#joda-time;2.9.5 from central in [default]
        net.jcip#jcip-annotations;1.0 from central in [default]
        net.sf.trove4j#trove4j;3.0.3 from central in [default]
        org.joda#joda-convert;1.8.1 from central in [default]
        org.json4s#json4s-ext_2.12;3.5.3 from central in [default]
        org.projectlombok#lombok;1.16.8 from central in [default]
        org.rocksdb#rocksdbjni;6.5.3 from central in [default]
        org.slf4j#slf4j-api;1.7.21 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   21  |   0   |   0   |   0   ||   21  |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-5a7da207-9721-4eef-9a0e-e433db968584
        confs: [default]
        0 artifacts copied, 21 already retrieved (0kB/166ms)
21/12/04 17:30:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/12/04 17:31:10 ERROR Inbox: Ignoring error
java.lang.NullPointerException
        at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:524)
        at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:116)
        at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
        at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21/12/04 17:31:10 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:103)
        at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:87)
        at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:78)
        at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:589)
        at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1000)
        at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:212)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1996)
        at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:524)
        at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:116)
        at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
        at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
>>>
```
--

```
>>> language_detector_pipeline = PretrainedPipeline('detect_language_21', lang='xx')
detect_language_21 download started this may take some time.
Approx size to download 7.7 MB
[ | ]detect_language_21 download started this may take some time.
Approximate size to download 7.7 MB
Download done! Loading the resource.
[ / ]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sparknlp/pretrained.py", line 32, in printProgress
    sys.stdout.write('\r[{}]'.format(states[nextc]))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 3: ordinal not in range(128)

2021-12-04 17:33:09.466234: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-04 17:33:09.687832: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2807995000 Hz
>>> language_detector_pipeline.annotate("Harry Potter is a great movie")
{'document': ['Harry Potter is a great movie'], 'sentence': ['Harry Potter is a great movie'], 'language': ['en']}
>>>
```

I get errors above, but the detection still worked.

--

Within the same `python3` session, it does take some time and says "download started", but doesn't seem to actually download (but it would be nice if it was faster, though!)

```
>>> language_detector_pipeline = PretrainedPipeline('detect_language_21', lang='xx')
detect_language_21 download started this may take some time.
Approx size to download 7.7 MB
[OK!]
>>> language_detector_pipeline.annotate("Harry Potter is a great movie")
{'document': ['Harry Potter is a great movie'], 'sentence': ['Harry Potter is a great movie'], 'language': ['en']}
```

--

If I start a new `python3`, initialize a new session, then it seems to download again:

```
>>> language_detector_pipeline = PretrainedPipeline('detect_language_21', lang='xx')
detect_language_21 download started this may take some time.
Approx size to download 7.7 MB
[ | ]detect_language_21 download started this may take some time.
Approximate size to download 7.7 MB
Download done! Loading the resource.
[ / ]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sparknlp/pretrained.py", line 32, in printProgress
    sys.stdout.write('\r[{}]'.format(states[nextc]))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 3: ordinal not in range(128)

2021-12-04 17:36:02.604939: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-04 17:36:02.834789: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2807995000 Hz
>>>
```

**Comment by maziyarpanahi** [comment]
- This `UnicodeEncodeError` error is your Python bash environment, we use some `ascii` characters to show the loading progress bar so your terminal/bash doesn't support that. (it's not really a big deal as you observed, it's just an environment error and you may be able to Google it "how to set PYTHONIOENCODING in your terminal")

- Spark NLP never downloads a model/pipeline twice. It downloads everything inside `~/cache_pretrained` by default, but you will always see these:
```
detect_language_21 download started this may take some time.
Approx size to download 7.7 MB
```
The difference is that it checks if the model/pipeline already exists it will just load it so you will see the next message immediately:
```
Download done! Loading the resource.
```

- The speed of downloading models/pipelines is really up to your network (loading depends on your system resources - disk speed - etc.) You can just easily check this in Google Colab and time it to compare it with your own setup. (we have pipelines or models with more than 2G size, this one is less than 8MB, so if you are waiting then there is something going on in your setup. I would suggest using Google Colab just to %%time it so you can be sure)
