### ISSUE TITLE
java.lang.NoSuchMethodError   spark nlp jsl

### ISSUE THREAD

**Issue by IsraelAbebe** [JohnSnowLabs/spark-nlp#6568]
While trying to create 
```
spark = SparkSession.builder \
    .master('local[*]') \
    .appName('Spark NLP') \
    .config("spark.driver.memory", "20g") \
    .config("spark.executor.memory", "20g") \
    .config("spark.driver.maxResultSize", "2000MB") \
    .config('spark.debug.maxToStringFields', "2000MB") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:" + spark_version) \
    .config("spark.jars", "https://pypi.johnsnowlabs.com/"+spark_nlp_secret+"/spark-nlp-jsl-"+jsl_version+".jar") \
    .getOrCreate()
```

I got the following error

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/tmp/ipykernel_10226/4044756739.py in <module>
      7     .config('spark.debug.maxToStringFields', "2000MB") \
      8     .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:" + spark_version) \
----> 9     .config("spark.jars", "https://pypi.johnsnowlabs.com/"+spark_nlp_secret+"/spark-nlp-jsl-"+jsl_version+".jar") \
     10     .getOrCreate()

~/.local/lib/python3.7/site-packages/pyspark/sql/session.py in getOrCreate(self)
    231                     session = SparkSession(sc)
    232                 for key, value in self._options.items():
--> 233                     session._jsparkSession.sessionState().conf().setConfString(key, value)
    234                 return session
    235 

~/.local/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

~/.local/lib/python3.7/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

~/.local/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o37.sessionState.
: java.lang.NoSuchMethodError: org.apache.spark.ContextCleaner.registerSparkListenerForCleanup(Ljava/lang/Object;Lorg/apache/spark/scheduler/SparkListener;)V
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$new$1(QueryExecutionListener.scala:82)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$new$1$adapted(QueryExecutionListener.scala:81)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.util.ExecutionListenerManager.<init>(QueryExecutionListener.scala:81)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.$anonfun$listenerManager$2(BaseSessionStateBuilder.scala:319)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.listenerManager(BaseSessionStateBuilder.scala:319)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:346)
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1145)
	at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:159)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:155)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

and 

```

print (sparknlp.version())
print (sparknlp_jsl.version())
```

gives 

```
3.1.1
3.1.2
```

installation of spark is as following 

```

spark_version='3.1.2'
jsl_version='3.1.2'

!python -m pip install findspark

!python -m pip install --ignore-installed -q pyspark==$spark_version

!python -m pip install --ignore-installed --no-cache-dir spark-nlp-jsl==$jsl_version --extra-index-url https://pypi.johnsnowlabs.com/$spark_nlp_secret
!python -m pip install --ignore-installed --no-cache-dir spark-nlp==3.1.2

```

**Comment by maziyarpanahi** [comment]
Hi,

Unfortunately, we don't have any way to test anything that is licensed (even if it's related to open source). You can use direct email or Slack (#healthcare channel) for your questions regarding licensed products. (they are very quick and sort this out for you immediately via those channels)
