### ISSUE TITLE
sparknlp_contrib_spar: cannot open shared object file

### ISSUE THREAD

**Issue by vasudhajain0** [JohnSnowLabs/spark-nlp#659]
```
Py4JJavaError: An error occurred while calling 
z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.UnsatisfiedLinkError: /tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/sparknlp_contrib_spar: cannot open shared object file: No such file or directory
```

## Description
```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-d759b18b57fc> in <module>()
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

/tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc)
     89 
     90     def __init__(self, name, lang='en', remote_loc=None):
---> 91         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         self.light_model = LightPipeline(self.model)
     93 

/tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     59             t1.start()
     60             try:
---> 61                 j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     62                 jmodel = JavaModel(j_obj)
     63             finally:

/tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/internal.py in __init__(self, name, language, remote_loc)
     57 class _DownloadPipeline(ExtendedJavaWrapper):
     58     def __init__(self, name, language, remote_loc):
---> 59         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
     60 
     61 

/tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/internal.py in __init__(self, java_obj, *args)
      9         super(ExtendedJavaWrapper, self).__init__(java_obj)
     10         self.sc = SparkContext._active_spark_context
---> 11         self._java_obj = self.new_java_obj(java_obj, *args)
     12         self.java_obj = self._java_obj
     13 

/tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/internal.py in new_java_obj(self, java_class, *args)
     19 
     20     def new_java_obj(self, java_class, *args):
---> 21         return self._new_java_obj(java_class, *args)
     22 
     23     def new_java_array(self, pylist, java_class):

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

/opt/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.UnsatisfiedLinkError: /tmp/spark-6bd784e5-2863-4cb3-87ad-c6cd6f2e20e7/userFiles-53628481-f2d0-47dd-9f58-0400e4e5fcbb/sparknlp_contrib_spar: cannot open shared object file: No such file or directory
	at org.tensorflow.TensorFlow.loadLibrary(TensorFlow.java:47)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.loadContribToTensorflow(LoadsContrib.scala:65)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:191)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:73)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowModel(NerDLModel.scala:139)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$class.readNerGraph(NerDLModel.scala:117)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readNerGraph(NerDLModel.scala:139)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:121)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:121)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:652)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:360)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:354)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:446)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

## Steps to Reproduce
1.
2.
3.
4.

## Your Environment
Spark NLP version
2.2.1
Apache Spark version
'2.4.3'
working on jupyter notebook
centos

**Comment by maziyarpanahi** [comment]
@vasudhajain0 Could you please also share the code that results in this error? We would like to reproduce this and see if this is an error on `Centos`.

**Comment by maziyarpanahi** [comment]
Thank you, we’ll try to find centos and test it. Meanwhile, could please test this pipeline instead: 
recognize_entities_dl_noncontrib

**Comment by vasudhajain0** [comment]
> Thank you, we’ll try to find centos and test it. Meanwhile, could you please test this pipeline instead:
> recognize_entities_dl_noncontrib

 recognize_entities_dl_noncontrib this pipeline works fine.

**Comment by maziyarpanahi** [comment]
That's great news. The `_noncontrib` models and pipelines are for Operating Systems which are not compatible with TensorFlow contrib.
