### ISSUE TITLE
Error downloading pretrained models

### ISSUE THREAD

**Issue by ericbugin** [JohnSnowLabs/spark-nlp#6863]
Hello, wondering if someone has seen this error before. Spark NLP used to work locally for me no problem, then suddenly started getting this error when trying to download BERT models. My code works fine in production in EMR and GCP, so my local env must not be correct, specifically for tensorflow models being used by Spark NLP. Spark NLP/Spark works totally fine for all other operations and pretrained models (sentence detector, parts-of-speech etc.)

Im using:
tensorflow 2.7.0
spark 2.4
scala 2.11
spark = SparkSession.builder\
    .appName("Spark NLP")\
    .config("spark.driver.memory","16G")\
    .master("local[*]")\
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp-spark24_2.11:3.4.0")\
    .getOrCreate()

Running this fails with error log:
`bert = BertSentenceEmbeddings.pretrained().setInputCols("document").setOutputCol("embeddings")`

```
sent_small_bert_L2_768 download started this may take some time.
Approximate size to download 139.6 MB
[ / ]
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.io.FileNotFoundException: File file:/Users/eric.bugin/cache_pretrained/sent_small_bert_L2_768_en_2.6.0_2.4_1598350960245/bert_sentence_tensorflow does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:289)
	at org.apache.hadoop.fs.LocalFileSystem.copyToLocalFile(LocalFileSystem.java:88)
	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:1979)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:141)
	at com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings$.readTensorflowModel(BertSentenceEmbeddings.scala:439)
	at com.johnsnowlabs.nlp.embeddings.ReadBertSentenceTensorflowModel$class.readTensorflow(BertSentenceEmbeddings.scala:395)
	at com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings$.readTensorflow(BertSentenceEmbeddings.scala:439)
	at com.johnsnowlabs.nlp.embeddings.ReadBertSentenceTensorflowModel$$anonfun$7.apply(BertSentenceEmbeddings.scala:399)
	at com.johnsnowlabs.nlp.embeddings.ReadBertSentenceTensorflowModel$$anonfun$7.apply(BertSentenceEmbeddings.scala:399)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:47)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:46)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:46)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:57)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:57)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:35)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:24)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:406)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:400)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:545)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maziyarpanahi** [comment]
Hi,

It is possible that the previously downloaded model(s) has been corrupted. Could you please remove everything inside this directory, exist your Spark application and try again?

```
# if you are on macOS or Linux - on Windows you can select all and remove everything inside here
rm -rf /Users/eric.bugin/cache_pretrained/*
```

**Comment by ericbugin** [comment]
@maziyarpanahi thanks for the quick fix! that seemed to do the trick. much appreciated

**Comment by maziyarpanahi** [comment]
You are welcome @ericbugin 

There are some functions you can use internally in Python, like `clearCache` which will remove everything downloaded for you as well: https://nlp.johnsnowlabs.com/api/com/johnsnowlabs/nlp/pretrained/PythonResourceDownloader$.html

**Comment by maziyarpanahi** [comment]
```python
from sparknlp.pretrained import *

# display and filter all available pretrained pipelines
ResourceDownloader.showPublicPipelines()
ResourceDownloader.showPublicPipelines(lang="en")
ResourceDownloader.showPublicPipelines(lang="en", version="3.2.0")

# display and filter all available pretrained pipelines
ResourceDownloader.showPublicModels()
ResourceDownloader.showPublicModels("NerDLModel", "3.2.0")
ResourceDownloader.showPublicModels("NerDLModel", "en")
ResourceDownloader.showPublicModels("XlmRoBertaEmbeddings", "xx")
+--------------------------+------+---------+
| Model                    | lang | version |
+--------------------------+------+---------+
| xlm_roberta_base         |  xx  | 3.1.0   |
| twitter_xlm_roberta_base |  xx  | 3.1.0   |
| xlm_roberta_xtreme_base  |  xx  | 3.1.3   |
| xlm_roberta_large        |  xx  | 3.3.0   |
+--------------------------+------+---------+

# remove all the downloaded models & pipelines to free up storage
ResourceDownloader.clearCache()

# display all available annotators that can be saved as a Model
ResourceDownloader.showAvailableAnnotators()
```

**Comment by ericbugin** [comment]
Super helpful. thanks again!
