### ISSUE TITLE
Unable to load models on zeppelin-EMR setup

### ISSUE THREAD

**Issue by surajkrayon** [JohnSnowLabs/spark-nlp#7343]
## Description
 We are trying to setup the sparkNLP on EMR cluster. We did not have any problems importing the necessary libraries but got this error while trying to load any model.
Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLReadable.$init$(Lorg/apache/spark/ml/util/MLReadable;)

## Error Message
 "while using pretrained()

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLReadable.$init$(Lorg/apache/spark/ml/util/MLReadable;)V
	at com.johnsnowlabs.nlp.DocumentAssembler$.<init>(DocumentAssembler.scala:325)
	at com.johnsnowlabs.nlp.DocumentAssembler$.<clinit>(DocumentAssembler.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<init>(ResourceDownloader.scala:481)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<clinit>(ResourceDownloader.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

(<class 'py4j.protocol.Py4JJavaError'>, Py4JJavaError('An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.\n', JavaObject id=o100), <traceback object at 0x7f1d3897ba08>)Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLReadable.$init$(Lorg/apache/spark/ml/util/MLReadable;)V
	at com.johnsnowlabs.nlp.DocumentAssembler$.<init>(DocumentAssembler.scala:325)
	at com.johnsnowlabs.nlp.DocumentAssembler$.<clinit>(DocumentAssembler.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<init>(ResourceDownloader.scala:481)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<clinit>(ResourceDownloader.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

(<class 'py4j.protocol.Py4JJavaError'>, Py4JJavaError('An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.\n', JavaObject id=o100), <traceback object at 0x7f1d3897ba08>)

while using load()

Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V
	at com.johnsnowlabs.nlp.AnnotatorModel.<init>(AnnotatorModel.scala:30)
	at com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings.<init>(BertSentenceEmbeddings.scala:136)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

(<class 'py4j.protocol.Py4JJavaError'>, Py4JJavaError('An error occurred while calling None.com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings.\n', JavaObject id=o119), <traceback object at 0x7f1d3737e188>)Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V
	at com.johnsnowlabs.nlp.AnnotatorModel.<init>(AnnotatorModel.scala:30)
	at com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings.<init>(BertSentenceEmbeddings.scala:136)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748) "

## Current Behavior
 Able to import the libraries from sparknlp but while loading the model or while using the pretrained() methods an error is thrown

## Possible Solution
 we tried the solution steps given in this issue #846 

## Steps to Reproduce
%pyspark
import sparknlp
spark = sparknlp.start()

%pyspark
from sparknlp.base import *
from sparknlp.annotator import *

%pyspark
BertSentenceEmbeddings.pretrained()

%pyspark
BertSentenceEmbeddings.load("s3://**/**/spark_nlp_models/bert_l2768/sent_small_bert_L2_768_en_2.6.0_2.4_1598350960245/")

## Context
We re trying to use the sentence embeddings to for calculating the text similarity

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.4.2
* Apache NLP version `spark.version`: 2.4.0
* Java version `java -version`: 8
* Setup and installation (Pypi, Conda, Maven, etc.): Maven
* Operating System and version: emr-5.20.0, Amazon 2.8.5, Hive 2.3.4, Livy 0.5.0, Zeppelin 0.8.0
* Link to your project (if any):

**Comment by surajkrayon** [comment]
We have tried the things given in issue #846[https://github.com/JohnSnowLabs/spark-nlp/issues/846](url)

**Comment by maziyarpanahi** [comment]
Hi @surajkrayon 

You are using Apache Spark 2.4.x, therefore, you need to choose an appropriate Maven package (`spark-nlp-spark24`).

- you can find the right package from this simple chart: https://github.com/JohnSnowLabs/spark-nlp#packages-cheatsheet
- and following the instructions just in case: https://github.com/JohnSnowLabs/spark-nlp#emr-cluster
