### ISSUE TITLE
Error when using pretrained model

### ISSUE THREAD

**Issue by Bassie1** [JohnSnowLabs/spark-nlp#7357]
### Description:
I am trying to run code in python to preprocess data. I am using a few spark-nlp pretrained models. The notebook runs without issue on an AWS EMR cluster. When I try to run the notebook locally, in visual studio code, I run into an error. 

### Steps to Reproduce: 
This is the code block that I am trying to run:
```python
documentAssembler = DocumentAssembler().setInputCol('text_col').setOutputCol('document')
tokenizer = Tokenizer().setInputCols(['document']).setOutputCol('tokenized')
normalizer = Normalizer().setInputCols(['tokenized']).setOutputCol('normalized').setLowercase(True)
spell_chk = NorvigSweetingModel().pretrained().setInputCols(['normalized']).setOutputCol('checked')
lemmatizer = LemmatizerModel.pretrained().setInputCols(['checked']).setOutputCol('lemmatized')
stopwords_cleaner = StopWordsCleaner.pretrained('stopwords_en','en').setInputCols(['lemmatized']).setOutputCol('unigrams')
ngrammer = NGramGenerator().setInputCols(['lemmatized']).setOutputCol('ngrams').setN(3).setEnableCumulative(True).setDelimiter('_')
pos_tagger = PerceptronModel.pretrained('pos_anc').setInputCols(['document', 'lemmatized']).setOutputCol('pos')
finisher = Finisher().setInputCols(['unigrams', 'ngrams','pos'])
sqlTrans = SQLTransformer(statement="SELECT *, CONCAT(finished_ngrams, finished_unigrams) AS final FROM __THIS__")
tfizer= HashingTF(inputCol='final',outputCol='tf_features')
idfizer = IDF(inputCol='tf_features', outputCol='tf_idf_features')
va = VectorAssembler(inputCols =['tf_idf_features','previous_target'], outputCol= 'features')
pipeline = Pipeline().setStages([documentAssembler,
                                tokenizer,
                                normalizer,
                                spell_chk,
                                lemmatizer, stopwords_cleaner,
                                pos_tagger,
                                ngrammer,
                                finisher,
                                sqlTrans,
                                tfizer,
                                idfizer,
                                va])
pipelineModel = pipeline.fit(trainingData)`
```

###Expected Behavior:
As mentioned above, the code runs without error on the EMR cluster.

### Current Behavior: 
This is the error that I get. The NorvingSweetingModel() is returning the following error:
```
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: com.amazonaws.util.StringUtils.trim(Ljava/lang/String;)Ljava/lang/String;
	at com.amazonaws.auth.profile.internal.AwsProfileNameLoader.getEnvProfileName(AwsProfileNameLoader.java:72)
	at com.amazonaws.auth.profile.internal.AwsProfileNameLoader.loadProfileName(AwsProfileNameLoader.java:54)
	at com.amazonaws.regions.AwsProfileRegionProvider.<init>(AwsProfileRegionProvider.java:40)
	at com.amazonaws.regions.DefaultAwsRegionProviderChain.<init>(DefaultAwsRegionProviderChain.java:23)
	at com.amazonaws.client.builder.AwsClientBuilder.<clinit>(AwsClientBuilder.java:60)
	at com.johnsnowlabs.client.aws.AWSGateway.getAmazonS3Client(AWSGateway.scala:60)
	at com.johnsnowlabs.client.aws.AWSGateway.client$lzycompute(AWSGateway.scala:50)
	at com.johnsnowlabs.client.aws.AWSGateway.client(AWSGateway.scala:39)
	at com.johnsnowlabs.client.aws.AWSGateway.getObjectFromS3(AWSGateway.scala:84)
	at com.johnsnowlabs.client.aws.AWSGateway.getMetadata(AWSGateway.scala:77)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:62)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:68)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:145)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:445)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:584)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
```

### Environment details:
os windows 11 Version 21H2 (OS Build 22000.493)
spark version : version 3.2.1
sparknlp version: 3.4.1
python 3.9.10
Java version: 
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

**Comment by maziyarpanahi** [comment]
Hi,

Please copy/paste both the code snippet and error in a formatted blocks, screenshots are hard to read and not searchable for others.

**Comment by Bassie1** [comment]
Thank you @maziyarpanahi for your prompt response. 
I have been working on this issue with my team for some time.
I pasted the code snippets in the post above and added the spark NLP version (3.4.1) in Environment details.
As for installing pyspark, I followed a tutorial for the installations and setting up environments, very similar to the instructions in issue #1022; I went through the instructions there and filled in what I was missing, but still have the error. 
On the emr, I am using spark NLP version 3.4.2, emr version 6.3.1, Hadoop distribution:Amazon 3.2.1.

**Comment by maziyarpanahi** [comment]
Thanks @Bassie1 

I usually see `java.lang.NoSuchMethodError` error trying to use `.pretrained()` on Windows when one or more of the followings are not correctly setup:

- missing C:\tmp and C:\tmp\hive
- permissions these directories via winutils.exe 
- a correct version of winutils.exe 
- and last the Microsoft Visual C++ 2010 Redistributed Package

The issue is, that post was tested and made on PySpark 2.4, and 3.x is a whole different setup. (I am gonna find someone with Windows on our team to update that post to 3.x so you can also check again, I've experienced this issue myself on Windows before and it only happens on `.pretrained()` due to something missing)

**Comment by Bassie1** [comment]
I am running the code in visual studio code.
code to start the sparksession: 

```
spark = SparkSession.builder \
    .appName("sparknlp") \
    .config("spark.jars.packages","com.johnsnowlabs.nlp:spark-nlp_2.12:3.4.0")\
    .config("spark.pyspark.python","python3")\
    .getOrCreate()
```

**Comment by Bassie1** [comment]
I switched my spark version to spark-3.1.3-bin-hadoop3.2 and now the download is working, but I am getting a memory error: 
```
Py4JJavaError: An error occurred while calling o301.fit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 23.0 failed 1 times, most recent failure: Lost task 3.0 in stage 23.0 (TID 903) (10.0.0.4 executor driver): java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.spark.io.ReadAheadInputStream.<init>(ReadAheadInputStream.java:106)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillReader.<init>(UnsafeSorterSpillReader.java:74)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillWriter.getReader(UnsafeSorterSpillWriter.java:159)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.getSortedIterator(UnsafeExternalSorter.java:523)
	at org.apache.spark.sql.execution.UnsafeKVExternalSorter.sortedIterator(UnsafeKVExternalSorter.java:206)
	at org.apache.spark.sql.execution.aggregate.SortBasedAggregator$$anon$1.<init>(ObjectAggregationIterator.scala:239)
	at org.apache.spark.sql.execution.aggregate.SortBasedAggregator.destructiveIterator(ObjectAggregationIterator.scala:238)
	at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.processInputs(ObjectAggregationIterator.scala:197)
	at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.<init>(ObjectAggregationIterator.scala:77)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2(ObjectHashAggregateExec.scala:107)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2$adapted(ObjectHashAggregateExec.scala:85)
	at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec$$Lambda$4786/2067718547.apply(Unknown Source)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:885)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:885)
	at org.apache.spark.rdd.RDD$$Lambda$2820/1107857682.apply(Unknown Source)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$2554/2114319237.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```
I have 16 GB of RAM and processor core is 2.30 GHz.
Does this make sense?
