### ISSUE TITLE
Unable to use pretrained pipelines/models on EMR cluster

### ISSUE THREAD

**Issue by ppangsf** [JohnSnowLabs/spark-nlp#742]
Using offline pretrained pipelines or models on EMR cluster results in Wrong FS error. 

## Description
Offline pretrained pipeline doesn't get loaded successfully. The pretrained pipeline was manually downloaded and then uploaded to a s3 bucket (xxx). Here's a code that was tested: 
```
import org.apache.spark.SparkConf
import org.apache.spark.ml.{PipelineModel}
import org.apache.spark.sql.SparkSession

object SimpleApp {
  def main(args: Array[String]) = {

    // initialise spark context
    val conf = new SparkConf().setAppName(SimpleApp.getClass.getName)
    val spark: SparkSession = SparkSession.builder.config(conf).getOrCreate()


    println("loading pretrained pipeline offline from s3")
    PipelineModel.load(
      "s3a://xxx/pipelines/onto_recognize_entities_sm_en_2.1.0_2.4_1564330931782/"
    )
    println("loaded pretrained pipeline offline from s3")

    spark.stop()
  }
}
```

## Expected Behavior
The pipeline should be loaded successfully

## Current Behavior
An exception is thrown:
```
Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: hdfs://ip-xx-xx-xx-xx.us-west-2.compute.internal:8020/user/hadoop/cache_pretrained/embeddings_tmp, expected: file:///
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:669)
	at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:86)
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:635)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:866)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:630)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:452)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1440)
	at org.apache.hadoop.fs.FileUtil.checkDest(FileUtil.java:500)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:351)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:341)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:292)
	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2114)
	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2083)
	at org.apache.hadoop.fs.FileSystem.copyToLocalFile(FileSystem.java:2059)
	at com.johnsnowlabs.nlp.embeddings.EmbeddingsHelper$.load(EmbeddingsHelper.scala:70)
```

## Possible Solution
If embeddings are on S3, they are currently copied to the local file system, even when code is running on an EMR cluster. The code should be modified to handle copying to HDFS. 

## Steps to Reproduce

1. Create an EMR cluster (version 5.28.0)
2. Run SimpleApp (see above) using client mode on the EMR cluster

## Context
Load pretrained pipelines and models to perform NER and sentiment analysis for huge volume of data on a distributed cluster (EMR)

## Your Environment

* EMR version: 5.28.0 (Spark version: 2.4.4)
* Spark NLP version: 2.3.5

**Comment by rohit-nlp** [comment]
`PipelineModel.load` is a function from Spark MLlib and not Spark NLP. It can not be fixed in Spark NLP library. This is a question for Spark MLLib.
