### ISSUE TITLE
pipeline error 

### ISSUE THREAD

**Issue by sultan-sheriff** [JohnSnowLabs/spark-nlp#749]
Traceback (most recent call last):
  File "onto_entity.py", line 15, in <module>
    pipeline = PretrainedPipeline('onto_recognize_entities_sm', 'en')
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/sparknlp/pretrained.py", line 91, in __init__
    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/sparknlp/pretrained.py", line 61, in downloadPipeline
    j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/sparknlp/internal.py", line 63, in __init__
    super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/sparknlp/internal.py", line 11, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/sparknlp/internal.py", line 21, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/pyspark/ml/wrapper.py", line 67, in _new_java_obj
    return java_obj(*java_args)
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/sultan/Desktop/sparknlp/venv/lib/python3.7/site-packages/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: 'Unsupported class file major version 55

## Your Environment

* Spark NLP version:2.4.4
* Apache NLP version:
* Setup and installation (Pypi, Conda, Maven, etc.):pypi
* Operating System and version:ubuntu 18

**Comment by sultan-sheriff** [comment]
@showy @kolia1985 @adolgarev @drbonis   could you please help me solving this problem

**Comment by maziyarpanahi** [comment]
Please update the specs correctly, we don’t have 2.4.4 version. 
Also, your error is about the Java version and it is Apache Spark who is complaining. You must have Java 8 and make sure that is the default JAVA_HOME.
If you search the error you get some easy steps to resolve this: Unsupported class file major version 55

**Comment by sultan-sheriff** [comment]
thank you i have used JAVA 8 and the problem has been solved
