### ISSUE TITLE
Problem using SentenceDetector

### ISSUE THREAD

**Issue by cigarsOfThePharaoh** [JohnSnowLabs/spark-nlp#751]
Hi, I'm very new to Spark NLP, so I might be guessing at the wrong problem. My goal is to turn a set of documents into word frequencies for each document, and I'm using Spark NLP to convert documents into a list of words. When I run this pipeline, some documents finished successfully, but others fail with this error: 

```---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<timed eval> in <module>
/usr/lib/spark/python/pyspark/sql/readwriter.py in parquet(self, path, mode, partitionBy, compression)
    841             self.partitionBy(partitionBy)
    842         self._set_opts(compression=compression)
--> 843         self._jwrite.parquet(path)
    844 
    845     @since(1.6)
/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:
/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()
/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(
Py4JJavaError: An error occurred while calling o967.parquet.
: org.apache.spark.SparkException: Job aborted.
at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:198)
at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:159)
at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:156)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:83)
at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:84)
at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:165)
at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:566)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 24 in stage 5.0 failed 4 times, most recent failure: Lost task 24.3 in stage 5.0 (TID 13059, ip-10-160-49-118.acadian-asset.com, executor 2): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
at scala.collection.Iterator$JoinIterator.hasNext(Iterator.scala:212)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.processInputs(ObjectAggregationIterator.scala:155)
at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.<init>(ObjectAggregationIterator.scala:78)
at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec$$anonfun$doExecute$1$$anonfun$2.apply(ObjectHashAggregateExec.scala:114)
at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec$$anonfun$doExecute$1$$anonfun$2.apply(ObjectHashAggregateExec.scala:105)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndexInternal$1$$anonfun$12.apply(RDD.scala:823)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndexInternal$1$$anonfun$12.apply(RDD.scala:823)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
at org.apache.spark.scheduler.Task.run(Task.scala:123)
at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Illegal group reference
at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
at scala.util.matching.Regex$Replacement$class.replace(Regex.scala:804)
at scala.util.matching.Regex$MatchIterator$$anon$1.replace(Regex.scala:782)
at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
at scala.collection.Iterator$class.foreach(Iterator.scala:891)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
at scala.util.matching.Regex.replaceAllIn(Regex.scala:473)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$2.apply(RuleFactory.scala:64)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$2.apply(RuleFactory.scala:63)
at com.johnsnowlabs.nlp.util.regex.RuleFactory.com$johnsnowlabs$nlp$util$regex$RuleFactory$$transformMatch(RuleFactory.scala:143)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4$$anonfun$apply$25.apply(RuleFactory.scala:95)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4$$anonfun$apply$25.apply(RuleFactory.scala:95)
at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
at scala.collection.immutable.List.foldLeft(List.scala:84)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4.apply(RuleFactory.scala:95)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4.apply(RuleFactory.scala:87)
at com.johnsnowlabs.nlp.util.regex.RuleFactory.transformWithSymbolicRules(RuleFactory.scala:162)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.PragmaticContentFormatter.formatBetweenPunctuations(PragmaticContentFormatter.scala:147)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.DefaultPragmaticMethod.extractBounds(PragmaticMethod.scala:50)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.tag(SentenceDetector.scala:33)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector$$anonfun$2.apply(SentenceDetector.scala:62)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector$$anonfun$2.apply(SentenceDetector.scala:62)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.annotate(SentenceDetector.scala:62)
at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
... 30 more
Driver stacktrace:
at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2041)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2029)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2028)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2028)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:966)
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:966)
at scala.Option.foreach(Option.scala:257)
at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:966)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2262)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2211)
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2200)
at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:777)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:167)
... 33 more

Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
at scala.collection.Iterator$JoinIterator.hasNext(Iterator.scala:212)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.processInputs(ObjectAggregationIterator.scala:155)
at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.<init>(ObjectAggregationIterator.scala:78)
at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec$$anonfun$doExecute$1$$anonfun$2.apply(ObjectHashAggregateExec.scala:114)
at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec$$anonfun$doExecute$1$$anonfun$2.apply(ObjectHashAggregateExec.scala:105)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndexInternal$1$$anonfun$12.apply(RDD.scala:823)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndexInternal$1$$anonfun$12.apply(RDD.scala:823)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
at org.apache.spark.scheduler.Task.run(Task.scala:123)
at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 1 more
Caused by: java.lang.IllegalArgumentException: Illegal group reference
at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
at scala.util.matching.Regex$Replacement$class.replace(Regex.scala:804)
at scala.util.matching.Regex$MatchIterator$$anon$1.replace(Regex.scala:782)
at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
at scala.util.matching.Regex$$anonfun$replaceAllIn$1.apply(Regex.scala:473)
at scala.collection.Iterator$class.foreach(Iterator.scala:891)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
at scala.util.matching.Regex.replaceAllIn(Regex.scala:473)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$2.apply(RuleFactory.scala:64)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$2.apply(RuleFactory.scala:63)
at com.johnsnowlabs.nlp.util.regex.RuleFactory.com$johnsnowlabs$nlp$util$regex$RuleFactory$$transformMatch(RuleFactory.scala:143)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4$$anonfun$apply$25.apply(RuleFactory.scala:95)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4$$anonfun$apply$25.apply(RuleFactory.scala:95)
at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
at scala.collection.immutable.List.foldLeft(List.scala:84)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4.apply(RuleFactory.scala:95)
at com.johnsnowlabs.nlp.util.regex.RuleFactory$$anonfun$4.apply(RuleFactory.scala:87)
at com.johnsnowlabs.nlp.util.regex.RuleFactory.transformWithSymbolicRules(RuleFactory.scala:162)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.PragmaticContentFormatter.formatBetweenPunctuations(PragmaticContentFormatter.scala:147)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.DefaultPragmaticMethod.extractBounds(PragmaticMethod.scala:50)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.tag(SentenceDetector.scala:33)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector$$anonfun$2.apply(SentenceDetector.scala:62)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector$$anonfun$2.apply(SentenceDetector.scala:62)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
at com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector.annotate(SentenceDetector.scala:62)
at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
... 30 more
```

Here's the pipeline that I used:
```
def get_tokens(df):
    document_assembler = (DocumentAssembler()
        .setInputCol('text')
        .setOutputCol('document')
        .setCleanupMode('inplace_full'))
    sentence_detector = (SentenceDetector()
        .setInputCols(['document'])
        .setOutputCol('sentence'))
    tokenizer = (Tokenizer()
        .setInputCols(['sentence'])
        .setOutputCol('token'))
    normalizer = (Normalizer()
        .setInputCols(['token'])
        .setOutputCol('normalized')
        .setLowercase(True))
    stemmer = (Stemmer()
        .setInputCols(['normalized'])
        .setOutputCol('stem'))
    finisher = (Finisher()
        .setInputCols(['stem']))
    pipeline = Pipeline(stages=[
        document_assembler,
        sentence_detector,
        tokenizer,
        normalizer,
        stemmer,
        finisher,
    ])
    return pipeline.fit(df).transform(df)
```

I haven't managed to find any Spark NLP errors similar to this on Google, and searching for the error alone points to escape characters in the regex patterns in SentenceDetector. I'm not sure this is the problem given that no one seemed to have complained about it, and also the fact that some documents finished successfully while others fail. I'd appreciate it if someone could point me to a solution.

**Comment by maziyarpanahi** [comment]
Hi,
Could you please complete the the specs part in our template?

**Comment by cigarsOfThePharaoh** [comment]
Thanks for the quick reply! Here are the specs:

## Your Environment

* Spark NLP version: 2.3.4
* Apache NLP version: not sure if I have this
* Setup and installation (Pypi, Conda, Maven, etc.): Conda for most packages, I used the `--packages JohnSnowLab:spark-nlp:2.3.4` argument when calling pyspark
* Operating System and version: Amazon Linux OS, emr-5.29.0

Thanks!

**Comment by maziyarpanahi** [comment]
I am not sure but you might be hitting a bug in 2.3.4 where it couldn't handle the `$` in the text for SentenceDetector. It was fixed in 2.3.5: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.3.5

Could you please test with the latest version 2.3.6 and do not use `JohnSnowLab:spark-nlp`, it is Spark Packages and we dropped them. (They were slow, unpredictable, and never published our release on time)

Use the maven as follow: `--packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.3.6`

**Comment by cigarsOfThePharaoh** [comment]
I see, thanks so much for the help. I'll report back after testing with the 2.3.6 package from maven.

**Comment by cigarsOfThePharaoh** [comment]
Confirming that using 2.3.6 solves my problem. Thank you very much!

**Comment by maziyarpanahi** [comment]
You are welcome and Thank you for confirming.
