### ISSUE TITLE
Errors loading pretrained pipeline from local filesystem (Spark NLP 2.4.0)

### ISSUE THREAD

**Issue by willprice76** [JohnSnowLabs/spark-nlp#777]
## Description
Since version 2.4.0, when I use Java to load a pre-trained pipeline from local filesystem (for example **analyze_sentiment_en**) I get an error.

## Expected Behavior
The pipeline should load without errors, as it did with previous versions (2.1.0-2.3.6)

## Current Behavior
An error is given:
```
[ERROR] Exception in task 1.0 in stage 9.0 (TID 13)
java.io.InvalidClassException: com.johnsnowlabs.nlp.util.regex.RuleFactory; local class incompatible: stream classdesc serialVersionUID = -6864579835492559496, local class serialVersionUID = 3504449169794985547
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1707)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.util.Utils$.deserialize(Utils.scala:169)
	at org.apache.spark.SparkContext$$anonfun$objectFile$1$$anonfun$apply$16.apply(SparkContext.scala:1305)
	at org.apache.spark.SparkContext$$anonfun$objectFile$1$$anonfun$apply$16.apply(SparkContext.scala:1305)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:390)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1334)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1364)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1364)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Possible Solution
It looks to be some kind of object deserialization compatibility issue, perhaps pretrained pipelines need to be generated again with the 2.4.0 version of the API.

## Steps to Reproduce
1. Create a Java project (based on [pom.xml example](https://gist.github.com/willprice76/2a7906031ee7cfde9e38b02fd5746c19))
1. Download and unzip pipeline files into folder under project root: https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/analyze_sentiment_en_2.1.0_2.4_1563204637489.zip
1. Add test class: [LoadPipelineTest.java](https://gist.github.com/willprice76/ceec2026c0935d90967d0be80205c4ed)
1. Execute the test - it should run without error.
1. Change the version of Spark NLP from 2.3.6 to 2.4.0 in pom.xml to see the error 

## Context
I want to use the latest version of Spark NLP, but this is blocking.

## Your Environment
* Spark NLP version: 2.4.0
* Apache Spark version: 2.11
* Setup and installation (Pypi, Conda, Maven, etc.): Maven, Java 1.8
* Operating System and version: Mac OS Mojave

**Comment by maziyarpanahi** [comment]
Hi @willprice76 

With every major release, we update all our pre-trained models and pipelines to be compatible with the new changes in the core library. (I haven't updated the spark-nlp-models with new offline links)

This is the pipeline compatible with 2.4.0: https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/analyze_sentiment_en_2.4.0_2.4_1580483464667.zip

`analyze_sentiment_en_2.4.0_2.4` the 2.4.0 indicates it's for Spark NLP 2.4.0 and the 2.4 is for Apache Spark.

I suggest if it's possible to use auto-download to get the right version (goes to cached_pretrained in your home directory)

```scala
val pipeline = PretrainedPipeline("analyze_sentiment", "en")
```

Please let me know if the new pipeline works for you (haven't tested yet in Java)

**Comment by willprice76** [comment]
Thanks @maziyarpanahi  - that works perfectly. Good tip to auto-download to get the latest...

**Comment by maziyarpanahi** [comment]
You are welcome. I’ll update the repo with some notes and tips regarding models and pipelines.

**Comment by ramanan-subramanian** [comment]
I just encountered the same exception, after upgrading Spark NLP to 3.0.0 and Apache Spark to 3.0.1:

```python
In [8]: import sparknlp 
   ...: from sparknlp.pretrained import PretrainedPipeline 
   ...:  
   ...: #create or get Spark Session 
   ...:  
   ...: spark = sparknlp.start() 
   ...:  
   ...: sparknlp.version() 
   ...: spark.version 
   ...:  
   ...: #download, load and annotate a text by pre-trained pipeline 
   ...:  
   ...: pipeline = PretrainedPipeline('recognize_entities_dl', 'en') 
   ...: result = pipeline.annotate('The Mona Lisa is a 16th century oil painting created by Leonardo') 
```

**Comment by C-K-Loan** [comment]
Hi @ramanan-subramanian  the `recognize_entities_dl` pipeline will be available later today in Spark 3.

You can try  `onto_recognize_entities_bert_small` which should be working fine right now :)

**Comment by ramanan-subramanian** [comment]
Thanks @C-K-Loan . Is there a page where I can check the progress of the release for the pre-trained pipelines?

**Comment by C-K-Loan** [comment]
Yes @ramanan-subramanian , you can check https://nlp.johnsnowlabs.com/models anything listed with `edition Spark NLP 3.0.0` is ready.  
Also check https://github.com/JohnSnowLabs/spark-nlp/pulls?q=is%3Apr+is%3Aclosed for merged PR's
Everything will be available within a few hours today.

**Comment by ramanan-subramanian** [comment]
Thanks. Tried `explain_document_dl` just now, it didn't work. I will check again in a couple of days.

**Comment by maziyarpanahi** [comment]
@ramanan-subramanian 
The new pipelines have been added. If you try `explain_document_dl` in Spark NLP 3.0.0 over Apache Spark 3.x it will download the new pipelines which are compatible.
