### ISSUE TITLE
Python API for DeBertaForSequenceClassification broken - `Unsupported Model`

### ISSUE THREAD

**Issue by C-K-Loan** [JohnSnowLabs/spark-nlp#8042]
## Description
Loading Deberta Seq classifier in Python causes exception in JVM `Unsupported Model` 

Use [this notebook](https://colab.research.google.com/drive/1FvYtWCRMx4uuWDBADtaZDDAaAl4XOX8V?usp=sharing) or this snippet to reproduce 

```python
import sparknlp
from sparknlp.annotator import DeBertaForSequenceClassification
sparknlp.start()

models = [('mdeberta_v3_base_sequence_classifier_imdb'	,'ur'),
('mdeberta_v3_base_sequence_classifier_allocine'	,'fr'),
('deberta_v3_xsmall_sequence_classifier_imdb'	,'en'),
('deberta_v3_small_sequence_classifier_imdb'	,'en'),
('deberta_v3_base_sequence_classifier_imdb'	,'en'),
('deberta_v3_large_sequence_classifier_imdb'	,'en'),
('deberta_v3_xsmall_sequence_classifier_ag_news'	,'en'),
('deberta_v3_small_sequence_classifier_ag_news'	,'en'),]

for model in models:
  try: 
    DeBertaForSequenceClassification.pretrained(*model)
  except Exception as err: 
    print(f'Failure for model = {model} and err = {err}')
```

Full Trace : 
```
 An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.RuntimeException: Unsupported Model: DeBertaForSequenceClassification
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.$anonfun$downloadModel$1(ResourceDownloader.scala:647)
	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
	at scala.collection.AbstractMap.getOrElse(Map.scala:63)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:647)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by C-K-Loan** [comment]
Most likely fixed with https://github.com/JohnSnowLabs/spark-nlp/commit/cc9e8a61205a902ce5165bcef75c62b1fb399cfe

**Comment by C-K-Loan** [comment]
Sure I added one.
I could not 100% validate this fixes the bug because I could not manage to compile a new jar and properly test it because sbt caused some troubles.
Ideally please test this before and see if there are other issues before making next release

https://github.com/JohnSnowLabs/spark-nlp/pull/8060

**Comment by maziyarpanahi** [comment]
Thanks @C-K-Loan - the error is exactly what you found when we forget to add the AnnotatorModel to the Python resource downloader.
