### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize. : com.amazonaws.services.s3.model.AmazonS3Exception: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken; Request ID: K1XC8BNMBEVVD5WH; S3 Extended Request ID:

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#8081]
### Discussed in https://github.com/JohnSnowLabs/spark-nlp/discussions/8080

<div type='discussions-op-text'>

<sup>Originally posted by **mshemko** April 24, 2022</sup>
Hello - getting strange error when trying to use my trial license on a windows machine in python jupyter notebook, trying to replicate the google colab code from here https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/healthcare/DEID_PHI_TEXT.ipynb#scrollTo=yo6nVQ99gt73

**_the code that causes the errror is:_**

documentAssembler = DocumentAssembler()\
  .setInputCol("text")\
  .setOutputCol("document")

sentenceDetector = SentenceDetector()\
  .setInputCols(["document"])\
  .setOutputCol("sentence")

tokenizer = Tokenizer()\
  .setInputCols(["sentence"])\
  .setOutputCol("token")

# Clinical word embeddings trained on PubMED dataset
word_embeddings = WordEmbeddingsModel.pretrained("embeddings_clinical", "en", "clinical/models")\
  .setInputCols(["sentence", "token"])\
  .setOutputCol("embeddings")

# NER model trained on n2c2 datasets)
clinical_ner = MedicalNerModel.pretrained(MODEL_NAME, "en", "clinical/models") \
    .setInputCols(["sentence", "token", "embeddings"])\
    .setOutputCol("ner")

ner_converter = NerConverterInternal()\
  .setInputCols(["sentence", "token", "ner"])\
  .setOutputCol("ner_chunk")

nlp_pipeline = Pipeline(stages=[
    documentAssembler, 
    sentenceDetector,
    tokenizer,
    word_embeddings,
    clinical_ner,
    ner_converter])

empty_df = spark.createDataFrame([['']]).toDF('text')
pipeline_model = nlp_pipeline.fit(empty_df)
light_pipeline = LightPipeline(pipeline_model)

and the error traceback is below - please help!:

Traceback (most recent call last):
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\ms234\AppData\Local\Temp\ipykernel_29212\1266134098.py", line 16, in <cell line: 16>
    word_embeddings = WordEmbeddingsModel.pretrained("embeddings_clinical", "en", "clinical/models")\
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\sparknlp\annotator.py", line 6353, in pretrained
    --------
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\sparknlp\pretrained.py", line 50, in downloadModel
    file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\sparknlp\internal.py", line 231, in __init__
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\sparknlp\internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\sparknlp\internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\pyspark\ml\wrapper.py", line 66, in _new_java_obj
    return java_obj(*java_args)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\py4j\java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\pyspark\sql\utils.py", line 111, in deco
    return f(*a, **kw)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\py4j\protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: com.amazonaws.services.s3.model.AmazonS3Exception: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken; Request ID: K1XC8BNMBEVVD5WH; S3 Extended Request ID: IDePEnCJbE+lvPo3DhNB1omQvvM1XeLDs1AFiP/N+BLMwItiXSN6tawrS96Lib1VLEx8kvyKe00=), S3 Extended Request ID: IDePEnCJbE+lvPo3DhNB1omQvvM1XeLDs1AFiP/N+BLMwItiXSN6tawrS96Lib1VLEx8kvyKe00=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1467)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1326)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:84)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:96)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:174)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:423)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:521)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\IPython\core\ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "C:\Users\ms234\Miniconda3\envs\sparknlp2\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0</div>

**Comment by maziyarpanahi** [comment]
We don’t have access to licensed products. You can wither use the Slack channels or directly email the team behind Healthcare.
