### ISSUE TITLE
BertEmbeddings download error

### ISSUE THREAD

**Issue by victorconan** [JohnSnowLabs/spark-nlp#830]
I try to load pretrained Bert embeddings but got error. 

## Description
I try to load pretrained Bert embeddings in databricks. I am using Databricks Runtime 5.5 LTS ML, python 3, and tensorflow 1.15.0. Cluster mode is `Standard`. Spark version is 2.4.3, and spark-nlp version is 2.4.0. 

## Expected Behavior
Load correctly. I can successfully load Glove but just got error for Bert. 

## Current Behavior
I got the error as :
```
java.lang.IllegalArgumentException: NodeDef mentions attr &#39;batch_dims&#39; not in Op&lt;name=ResourceGather; signature=resource:resource, indices:Tindices -&gt; output:dtype; attr=validate_indices:bool,default=true; attr=dtype:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; is_stateful=true&gt;; NodeDef: {{node module/bert/embeddings/embedding_lookup}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.IllegalArgumentException: NodeDef mentions attr 'batch_dims' not in Op<name=ResourceGather; signature=resource:resource, indices:Tindices -> output:dtype; attr=validate_indices:bool,default=true; attr=dtype:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; is_stateful=true>; NodeDef: {{node module/bert/embeddings/embedding_lookup}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	at org.tensorflow.Graph.importGraphDef(Native Method)
	at org.tensorflow.Graph.importGraphDef(Graph.java:130)
	at org.tensorflow.Graph.importGraphDef(Graph.java:114)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(TensorflowWrapper.scala:206)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:249)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:97)
	at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.readTensorflowModel(BertEmbeddings.scala:226)
	at com.johnsnowlabs.nlp.embeddings.ReadBertTensorflowModel$class.readTensorflow(BertEmbeddings.scala:188)
	at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.readTensorflow(BertEmbeddings.scala:226)
	at com.johnsnowlabs.nlp.embeddings.ReadBertTensorflowModel$$anonfun$2.apply(BertEmbeddings.scala:192)
	at com.johnsnowlabs.nlp.embeddings.ReadBertTensorflowModel$$anonfun$2.apply(BertEmbeddings.scala:192)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:356)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:350)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:452)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
<command-22681> in <module>()
     19 #                   .setInputCols(["document","normal"])
     20 #                   .setOutputCol("embeddings"))
---> 21 word_embeddings = (BertEmbeddings.pretrained()
     22                    .setInputCols(["document","token"])
     23                    .setOutputCol("embeddings"))

/local_disk0/spark-702f75d0-60e2-40ff-b56b-14a0431468a1/userFiles-f73671a2-0972-4962-b7f0-d1a3a5b6b0bb/addedFile2058022218141489189spark_nlp_2_4_0-e619c.jar/sparknlp/annotator.py in pretrained(name, lang, remote_loc)
   1684     def pretrained(name="bert_base_cased", lang="en", remote_loc=None):
   1685         from sparknlp.pretrained import ResourceDownloader
-> 1686         return ResourceDownloader.downloadModel(BertEmbeddings, name, lang, remote_loc)
   1687 
   1688 

/local_disk0/spark-702f75d0-60e2-40ff-b56b-14a0431468a1/userFiles-f73671a2-0972-4962-b7f0-d1a3a5b6b0bb/addedFile2058022218141489189spark_nlp_2_4_0-e619c.jar/sparknlp/pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     39             t1.start()
     40             try:
---> 41                 j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     42             finally:
     43                 stop_threads = True

/local_disk0/spark-702f75d0-60e2-40ff-b56b-14a0431468a1/userFiles-f73671a2-0972-4962-b7f0-d1a3a5b6b0bb/addedFile2058022218141489189spark_nlp_2_4_0-e619c.jar/sparknlp/internal.py in __init__(self, reader, name, language, remote_loc, validator)
    174 class _DownloadModel(ExtendedJavaWrapper):
    175     def __init__(self, reader, name, language, remote_loc, validator):
--> 176         super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
    177 
    178 

/local_disk0/spark-702f75d0-60e2-40ff-b56b-14a0431468a1/userFiles-f73671a2-0972-4962-b7f0-d1a3a5b6b0bb/addedFile2058022218141489189spark_nlp_2_4_0-e619c.jar/sparknlp/internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

/local_disk0/spark-702f75d0-60e2-40ff-b56b-14a0431468a1/userFiles-f73671a2-0972-4962-b7f0-d1a3a5b6b0bb/addedFile2058022218141489189spark_nlp_2_4_0-e619c.jar/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

/databricks/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: "NodeDef mentions attr 'batch_dims' not in Op<name=ResourceGather; signature=resource:resource, indices:Tindices -> output:dtype; attr=validate_indices:bool,default=true; attr=dtype:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; is_stateful=true>; NodeDef: {{node module/bert/embeddings/embedding_lookup}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.)."
```

## Possible Solution
N/A

## Steps to Reproduce
The code for reproduction is:
```
from pyspark.sql.functions import *
import sparknlp
from sparknlp.pretrained import PretrainedPipeline
from pyspark.ml import Pipeline
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.sql.types import *

sparknlp.start()

documentAssembler = (DocumentAssembler()
                     .setInputCol("grand_content")
                     .setOutputCol("document")
                     .setCleanupMode("shrink"))

tokenizer = (Tokenizer()
             .setInputCols(["document"])
             .setOutputCol("token"))

word_embeddings = (BertEmbeddings.pretrained()
                   .setInputCols(["document","token"])
                   .setOutputCol("embeddings"))

nlpPipeline = Pipeline(stages=[
 documentAssembler, 
 sentenceDetector,
 tokenizer,
 word_embeddings,
 ])
```

## Context
Just trying to load Bert embeddings...

## Your Environment
* Spark NLP version: 2.4.3
* Apache NLP version: 2.4.0
* Tensorflow version: 1.15.0
* Setup and installation (Pypi, Conda, Maven, etc.): JohnSnowLabs:spark-nlp:2.4.0
* Operating System and version: Databricks Runtime 5.5 LTS ML

**Comment by maziyarpanahi** [comment]
Hi
Thanks for reporting. At then moment the compatible Databricks versions are 6.2 and 6.3 not the ML editions. (It fails with serialization error in ML for some reason even though this error is complaining about not finding the right graph)

My best guess is some incompatibility between what is already on the machine(s). For Spark NLP you don’t need to install TensorFlow as it comes packaged inside the pypi and maven. Could it be possible to remove TF if you have and try again? 
And also try 6.2 or 6.3 none ML?

https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/databricks

**Comment by victorconan** [comment]
> Hi
> Thanks for reporting. At then moment the compatible Databricks versions are 6.2 and 6.3 not the ML editions. (It fails with serialization error in ML for some reason even though this error is complaining about not finding the right graph)
> 
> My best guess is some incompatibility between what is already on the machine(s). For Spark NLP you don’t need to install TensorFlow as it comes packaged inside the pypi and maven. Could it be possible to remove TF if you have and try again?
> And also try 6.2 or 6.3 none ML?
> 
> https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/databricks

It worked with 6.3 none ML! Thanks!
