### ISSUE TITLE
Unable to load Explain Document ML in python

### ISSUE THREAD

**Issue by mostaghimi** [JohnSnowLabs/spark-nlp#842]
## Description

While trying to load explain_document_ml which I have downloaded into HDFS by executing the load method as below:

advancedPipeline = PipelineModel.load("/tmp/SparknlpPretrainedModels/explain_document_ml_en_2.4.0_2.4_1580252705962")

I get the following Java Exception

## Current Behavior

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/util.py", line 311, in load
    return cls.read().load(path)
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/pipeline.py", line 242, in load
    return JavaMLReader(self.cls).load(path)
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/util.py", line 249, in load
    java_obj = self._jread.load(path)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py", line 320, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o88.load.
: java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.DocumentAssembler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:235)
        at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:452)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)
## Possible Solution

Looking forward to your assistance.
## Steps to Reproduce

1.
2.
3.
4.

## Context

I was trying to test loading one of the pipelines.
## Your Environment

* Spark NLP version: 2.4.4
* Apache Spark version:  2.3.0.2.6.5.0-292
* Java version (java -version): 1.8.0_112-b15
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version:  Red Hat Enterprise Linux Server release 6.10

**Comment by maziyarpanahi** [comment]
Spark NLP supports Apache Spark 2.4.x, we don’t support Apache Spark 2.3.x.

But the error is not clear to me, could you please provide the steps to reproduce? How did you install the maven and pypi? And the full code you are running.

**Comment by saz2nitk** [comment]
I am getting the same error. My spark version is 2.4.6 and sparknlp version is 2.5.2. This issue occurs when I try to load the model offline. My 'SPARK_HOME' is set correctly and I am not getting any issues while using pyspark. Can you please help. Here is the full code:
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp

# Start Spark Session with Spark NLP
spark = sparknlp.start()

# Download a pre-trained pipeline
pipeline = PretrainedPipeline.from_disk('/work/data/explain_document_dl_en')

$ls /work/data/explain_document_dl_en
metadata  stages

Can you please help?

**Comment by maziyarpanahi** [comment]
@saz2nitk Could you please open a new issue and complete the template. We need the extra information in that template and this thread didn't move one, unfortunately.

The important parts are how you install Spark NLP PyPI package, where are you running your code. (you said PySpark, is this a pyspark shell? Because in that case once you are in the shell you already have a Spark Session and sparknlp.start() won't be taking into account so you need to launch the pyspark with --packages)
