### ISSUE TITLE
Cannot Load Pretrained Models: local class incompatible: stream classdesc serialVersionUID

### ISSUE THREAD

**Issue by peili-uzh** [JohnSnowLabs/spark-nlp#8448]
## Description

I failed to load pre-trained models after upgrading spark nlp version from 3.1.0 to 3.1.1

## Expected Behavior

pre-trained models should work as in version 3.1.0

## Current Behavior

`explain_document_ml download started this may take some time.
Approximate size to download 9.1 MB
Download done! Loading the resource.
10:23:39.783 ERROR spark.internal.Logging:94 [Executor task launch worker for task 10] {}: Exception in task 2.0 in stage 8.0 (TID 10)
java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 1028182004549731694, local class serialVersionUID = 3456489343829468865
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:527)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2093)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1655)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.util.Utils$.deserialize(Utils.scala:132)
	at org.apache.spark.SparkContext.$anonfun$objectFile$2(SparkContext.scala:1365)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:268)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
	at org.apache.spark.rdd.RDD.$anonfun$take$2(RDD.scala:1423)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2139)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

## Steps to Reproduce

1. `PretrainedPipeline(downloadName = "explain_document_ml", lang = "en").model`
2.
3.
4.

## Context

I need to use bert models from spark nlp, and therefore have to upgrade to a higher version from 3.1.0 due to this issue: https://github.com/JohnSnowLabs/spark-nlp/issues/5690. however, several other pre-trained models failed to load after upgrading, 

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.1
* Apache NLP version `spark.version`: 3.0.1
* Java version `java -version`: 1.8.0_312
* Setup and installation (Pypi, Conda, Maven, etc.): sbt
* Operating System and version: 5.15.0-10025-tuxedo x86_64 GNU/Linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi @peili-uzh 

Could you please update to the latest Spark NLP 3.4.4` before we start investigating this? (even if there is an issue with those pipelines/models we would probably fix them for spark-nlp==3.4.x rather than going that many major releases back)

Demo: https://colab.research.google.com/drive/13tR2EsgxwVzBM9O8Jh7lgPzK1y_wopKh?usp=sharing
PS: Keep in mind, in terms of your environment (apache spark 3.0.1, Scala version, Python version, etc.), there is no difference between spark-nlp==3.1.x and spark-nlp==3.4.x. So you can seamlessly just move to the latest instead of staying in an inactive release

**Comment by peili-uzh** [comment]
@maziyarpanahi  thx for your comment. I've upgraded to 3.4.4 but got some new error:
`java.lang.NoClassDefFoundError: com/amazonaws/services/pi/model/InvalidArgumentException
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.awsGateway$lzycompute(S3ResourceDownloader.scala:47)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.awsGateway(S3ResourceDownloader.scala:47)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:65)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:70)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.download(S3ResourceDownloader.scala:82)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.$anonfun$downloadResource$1(ResourceDownloader.scala:423)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.pi.model.InvalidArgumentException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 18 more


A needed class was not found. This could be due to an error in your runpath. Missing class: com/amazonaws/services/pi/model/InvalidArgumentException
java.lang.NoClassDefFoundError: com/amazonaws/services/pi/model/InvalidArgumentException
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.awsGateway$lzycompute(S3ResourceDownloader.scala:47)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.awsGateway(S3ResourceDownloader.scala:47)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:65)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:70)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:204)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:544)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:440)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:517)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:512)
	at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline.<init>(PretrainedPipeline.scala:84)
	at one.engine.schema.SchemaMappingInstructionTest.$anonfun$new$67(SchemaMappingInstructionTest.scala:1227)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:405)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FreeSpec.withFixture(FreeSpec.scala:1739)
	at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:403)
	at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:415)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:415)
	at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:397)
	at one.engine.schema.SchemaMappingTestBase.org$scalatest$BeforeAndAfterEach$$super$runTest(SchemaMappingTestBase.scala:20)
	at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)
	at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
	at one.engine.schema.SchemaMappingTestBase.runTest(SchemaMappingTestBase.scala:20)
	at org.scalatest.FreeSpecLike.$anonfun$runTests$1(FreeSpecLike.scala:474)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FreeSpecLike.runTests(FreeSpecLike.scala:474)
	at org.scalatest.FreeSpecLike.runTests$(FreeSpecLike.scala:473)
	at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
	at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:518)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:518)
	at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:517)
	at one.engine.schema.SchemaMappingTestBase.org$scalatest$BeforeAndAfterAll$$super$run(SchemaMappingTestBase.scala:20)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at one.engine.schema.SchemaMappingTestBase.run(SchemaMappingTestBase.scala:20)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.pi.model.InvalidArgumentException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 63 more`

btw, I excluded a few dependencies due to conflicts:
`  val sparkNLP                    = "com.johnsnowlabs.nlp"          %% "spark-nlp"                      % "3.4.4"      excludeAll(
    ExclusionRule("org.apache.hadoop", "*"),
    ExclusionRule("com.amazonaws", "*"),                            // conflicts with com.amazonaws:aws-java-sdk-translate
    ExclusionRule("com.google.code.findbugs", "annotations"),       // conflicts with com.google.code.findbugs:jsr305:3.0.2
    ExclusionRule("org.projectlombok", "lombok")
  )`

I use aws-sdk version 1.11.800.

**Comment by maziyarpanahi** [comment]
Conflict with `aws-sdk` could be the reason (although we have been using the same aws-sdk version for a long time).

Could you please elaborate more on where you test (it says sbt), what other technologies/dependencies you have, and what is the final target (Intellij test, spark-shell/spark-submit, EMR, etc.)

Just in case here is a sbt project as a demo that I think uses the same pretrained pipelines: https://github.com/maziyarpanahi/spark-nlp-starter

**Comment by peili-uzh** [comment]
@maziyarpanahi  I use scala version 2.12.13, and the mentioned test failed in IDEA. 

It turned out there is a conflict with  `com.amazonaws:aws-java-sdk-translate`, so I managed to get rid of above error `java.lang.ClassNotFoundException: com.amazonaws.services.pi.model.InvalidArgumentException` by adding `ExclusionRule("com.amazonaws", "*")` and added missing dependency `com.amazonaws.aws-java-sdk-pi`. so till now, i have the following setting:

- Spark NLP version: 3.4.4
- Apache NLP version: 3.1.2
- aws-java-sdk version: 1.12.31
- Java version: 1.8.0_312
- Setup and installation: sbt, Scala version 2.12.13
- Operating System and version: 5.15.0-10025-tuxedo x86_64 GNU/Linux

the test failed with error:
```
Caused by: java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 1028182004549731694, local class serialVersionUID = 3456489343829468865
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:527)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2296)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2093)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1655)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.util.Utils$.deserialize(Utils.scala:133)
	at org.apache.spark.SparkContext.$anonfun$objectFile$2(SparkContext.scala:1395)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:268)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
	at org.apache.spark.rdd.RDD.$anonfun$take$2(RDD.scala:1449)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I also cloned your demo project https://github.com/maziyarpanahi/spark-nlp-starter, the test went through smoothly. But once changed Scala version to `2.12.13`, it threw the same error as above. 

Looks like my Scala version caused the serialiazed error. Is there any workaround except for down grading Scala version to 2.12.10? thx!

**Comment by maziyarpanahi** [comment]
@peili-uzh that's a very good question! Looking at the two releases I don't see any changes to the build.sbt nor any other dependency. Looking at that specific pipelines, if you were on 3.1.0 then you used the pipeline that was made for 3.0.0 and if you are on 3.1.1 and above it will use the 3.1.1 pipeline (spark 3.0):

![image](https://user-images.githubusercontent.com/5762953/168756294-6d643cd8-41a1-4846-97a0-1911ab41a69e.png)

So I am gonna look to see which Scala version was used to make 3.0.0_3.0 and what was used to make 3.1.3_3.0 (which I am sure it's what you are downloading/loading). There must be a difference here I am guessing.

One thing I have noticed is that `serialVersionUID` error is usually happening for major Scala version changes like if there is a Scala/Java object saved by Scala 2.11.9 will crash when it's loaded on 2.12, but not with minor releases like 2.11.11. (same for Scala 2.12) 

So if you go ahead and change the Scala version from 2.12.10 to 2.12.15 in `Dependencies.scala` and compile/assemble it, you will have a Fat Jar that supports Scala 2.12.15 without any issues for all the models/pipelines. (in the next major release we will use 2.12.15)

I am gonna test more to see if Spark NLP is being used as a dependency in an SBT project with a different minor Scala version like 2.12.13, does it crash on models/pipelines (made for 2.12.10) because of the Scala version mismatch or does this only happens with a handful of pretrained pipelines like `explain_document_ml`.
