### ISSUE TITLE
Could not initialize class com.johnsnowlabs.nlp.util.io.ResourceHelper$ error with EntityExtractor().setEntitiesPath

### ISSUE THREAD

**Issue by sofianeh** [JohnSnowLabs/spark-nlp#85]
I receive this error when I try to use EntityExtractor() in a transformer in Python:

```
java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.util.io.ResourceHelper$
	at com.johnsnowlabs.nlp.annotators.EntityExtractor$.retrieveEntityExtractorPhrases(EntityExtractor.scala:148)
	at com.johnsnowlabs.nlp.annotators.EntityExtractor.loadEntities(EntityExtractor.scala:80)
	at com.johnsnowlabs.nlp.annotators.EntityExtractor.getSearchTrie(EntityExtractor.scala:67)
	at com.johnsnowlabs.nlp.annotators.EntityExtractor.com$johnsnowlabs$nlp$annotators$EntityExtractor$$search(EntityExtractor.scala:106)
	at com.johnsnowlabs.nlp.annotators.EntityExtractor$$anonfun$annotate$1.apply(EntityExtractor.scala:133)
	at com.johnsnowlabs.nlp.annotators.EntityExtractor$$anonfun$annotate$1.apply(EntityExtractor.scala:133)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.johnsnowlabs.nlp.annotators.EntityExtractor.annotate(EntityExtractor.scala:133)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:42)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:41)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:423)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:49)
	at org.apache.spark.sql.execution.collect.Collector$$anonfun$2.apply(Collector.scala:126)
	at org.apache.spark.sql.execution.collect.Collector$$anonfun$2.apply(Collector.scala:125)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:349)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I tested with v1.2.6

**Comment by aleksei-ai** [comment]
@sofianeh May I ask you:
1. Sample of code that reproduces that error?
2. What spark-nlp library version do you use? Do you use spark+yarn?

**Comment by sofianeh** [comment]
It is the same [code example](https://github.com/sofianeh/databricks-examples/blob/master/python/SparkNLP-entityExtractor-example.py) I've mentionned in [Issue 57](https://github.com/JohnSnowLabs/spark-nlp/issues/57). The error occurs when I use a Databricks multi-node spark cluster. I've already contacted them and it looks like the spark-nlp library is trying to create another spark context within the [ResourceHelper.scala](https://github.com/JohnSnowLabs/spark-nlp/blob/2b3f340e6e14b70e8e71fdd9a9387ef8ea134591/src/main/scala/com/johnsnowlabs/nlp/util/io/ResourceHelper.scala#L31) code

**Comment by aleksei-ai** [comment]
@saifjsl Is it solved by 1.4? Can you help with it?

**Comment by albertoandreottiATgmail** [comment]
Hi @aleksei-ai, @sofianeh,

I was able to reproduce this problem too. It seems that as @sofianeh mentioned, a spark context is being created in one of the executors, and as a result the class that contains the context cannot be instantiated.
I can fix this with a reorg of the code, as the code we need to run on the executors doesn't actually need the initialized spark context.
I can have a PR for today with this, but you will need to re-build in order to get the fix.

Alberto.

**Comment by aleksei-ai** [comment]
@albertoandreottiATgmail Hi Alberto,

> I can have a PR for today with this, but you will need to re-build in order to get the fix.
Yes, it will be great.

**Comment by albertoandreottiATgmail** [comment]
Hi guys,

after reviewing the new code and testing, I can confirm that this is no longer a bug in the current code base. So no PR from my side, although @sofianeh  you will need to change the way you instantiate the EntityExtractor, like this,

extractor = EntityExtractor()\
  .setEntities("/dbfs/myentities.txt")\
  .setInputCols(["normal", "sentence"])\
  .setOutputCol("entities")

Only thing you will need is a fresh .jar. I compiled one updated to the latest code,

https://drive.google.com/file/d/1zlSP4aVn5Uj1dB_ub37QuMlnaxcY9ucw/view?usp=sharing

Let me know how it goes.

Alberto.

**Comment by sofianeh** [comment]
@albertoandreottiATgmail I loaded your JAR and I now receive the following error:
`java.io.FileNotFoundException: File/XXXXXXXXXXXXXXX/dbfs/myentities.txt does not exist.
`

When I try to use setEntitiesFormat('TXTDS') instead, I receive this error:
`AttributeError: 'EntityExtractor' object has no attribute 'setEntitiesFormat'`

**Comment by albertoandreottiATgmail** [comment]
hi @sofianeh, the API has changed a bit, the setEntitiesFormat() method is gone, now you specify the format as a parameter to setEntities() method, example,

setEntities(self, path, read_as="LINE_BY_LINE", options={"format": "text"})

documentation is indeed outdated, and there's already a PR for it that should be merged in the following days.

**Comment by sofianeh** [comment]
@albertoandreottiATgmail Are the changes in your JAR (from google drive) now included in the master branch?

**Comment by albertoandreottiATgmail** [comment]
HI @sofianeh, yes, it should work now with the jar coming from the new release. Please take a look and let me know if anything does not work as expected.

**Comment by aleksei-ai** [comment]
@sofianeh I'm closing this issue. Please reopen if there is still a problem here.
