### ISSUE TITLE
the java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by dshan0411** [JohnSnowLabs/spark-nlp#853]
when I use 

val typed_english_dependency = TypedDependencyParserModel.pretrained("dependency_typed_conllu")
      .setInputCols("token", "pos", "dependency")
      .setOutputCol("typed_dependency")

then it always report the error
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.johnsnowlabs.nlp.annotators.parser.typdep.Parameters.<init>(Parameters.java:129)
	at com.johnsnowlabs.nlp.annotators.parser.typdep.TypedDependencyParserModel.parameters$lzycompute(TypedDependencyParserModel.scala:31)
	at com.johnsnowlabs.nlp.annotators.parser.typdep.TypedDependencyParserModel.parameters(TypedDependencyParserModel.scala:31)
	at com.johnsnowlabs.nlp.annotators.parser.typdep.TypedDependencyParserModel.annotate(TypedDependencyParserModel.scala:49)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:108)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:107)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1063)
	at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:151)
	at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:50)
	at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:32)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$24.applyOrElse(Optimizer.scala:1364)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$24.applyOrElse(Optimizer.scala:1359)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:256)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:256)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:255)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.transformDown(AnalysisHelper.scala:149)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:261)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:261)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)

Process finished with exit code 1

**Comment by maziyarpanahi** [comment]
Please complete the template in order for us to help. The more detailed you are the faster and better it is for us to help.
Specially the versions, environment, how are you starting SparkSession and the full code to reproduce.

**Comment by dshan0411** [comment]
I used  

        <dependency>
            <groupId>com.johnsnowlabs.nlp</groupId>
            <artifactId>spark-nlp_2.11</artifactId>
            <version>2.4.5</version>
        </dependency>


all code in here:

import com.johnsnowlabs.nlp.annotator._
import com.johnsnowlabs.nlp.base._
import com.johnsnowlabs.nlp.training.POS
import com.johnsnowlabs.util.Benchmark
import org.apache.spark.ml.Pipeline
import org.apache.spark.ml.feature.NGram
import org.apache.spark.sql.{Dataset, SparkSession}

object ratingLableMine {

  def main(args: Array[String]): Unit = {

    val spark: SparkSession = SparkSession
      .builder()
      .appName("test")
      .master("local[*]")
      .config("spark.driver.memory", "12G")
      .config("spark.executor.memory","6g")
      .config("spark.kryoserializer.buffer.max", "400M")
      .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      .getOrCreate()

    import spark.implicits._
    spark.sparkContext.setLogLevel("WARN")


    val testing = Seq(
      ("Google is a famous company"),
      ("Peter Parker is a super hero"),
      ("I love you"),
      ("This product is bad quality"),
      ("bad quality")
    ).toDS.toDF("text")

    val english_pos = PerceptronModel.pretrained("pos_anc")
      .setInputCols("sentence", "token")
      .setOutputCol("pos")

    val english_dependency = DependencyParserModel.pretrained("dependency_conllu")
      .setInputCols("sentence", "token", "pos")
      .setOutputCol("dependency")

    val typed_english_dependency = TypedDependencyParserModel.pretrained("dependency_typed_conllu")
      .setInputCols("token", "pos", "dependency")
      .setOutputCol("typed_dependency")

    testing.show(truncate = false)

    val document = new DocumentAssembler()
      .setInputCol("text")
      .setOutputCol("document")

    val token = new Tokenizer()
      .setInputCols("document")
      .setOutputCol("token")

    val sentence: SentenceDetector = new SentenceDetector()
      .setInputCols("document")
      .setOutputCol("sentence")

    val pipeline = new Pipeline().setStages(Array(document, token, sentence, english_pos,english_dependency))

    val sparkPipeline = pipeline.fit(testing)
    val result = sparkPipeline.transform(testing)

    result.show(truncate = false)


    typed_english_dependency.transform(result).show(truncate = false)
  }
}

**Comment by dshan0411** [comment]
> Please complete the template in order for us to help. The more detailed you are the faster and better it is for us to help.
> Specially the versions, environment, how are you starting SparkSession and the full code to reproduce.

**Comment by dshan0411** [comment]
I used

    <dependency>
        <groupId>com.johnsnowlabs.nlp</groupId>
        <artifactId>spark-nlp_2.11</artifactId>
        <version>2.4.5</version>
    </dependency>


all code in here:

import com.johnsnowlabs.nlp.annotator._
import com.johnsnowlabs.nlp.base._
import com.johnsnowlabs.nlp.training.POS
import com.johnsnowlabs.util.Benchmark
import org.apache.spark.ml.Pipeline
import org.apache.spark.ml.feature.NGram
import org.apache.spark.sql.{Dataset, SparkSession}

object ratingLableMine {

def main(args: Array[String]): Unit = {

val spark: SparkSession = SparkSession
  .builder()
  .appName("test")
  .master("local[*]")
  .config("spark.driver.memory", "12G")
  .config("spark.executor.memory","6g")
  .config("spark.kryoserializer.buffer.max", "400M")
  .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
  .getOrCreate()

import spark.implicits._
spark.sparkContext.setLogLevel("WARN")


val testing = Seq(
  ("Google is a famous company"),
  ("Peter Parker is a super hero"),
  ("I love you"),
  ("This product is bad quality"),
  ("bad quality")
).toDS.toDF("text")

val english_pos = PerceptronModel.pretrained("pos_anc")
  .setInputCols("sentence", "token")
  .setOutputCol("pos")

val english_dependency = DependencyParserModel.pretrained("dependency_conllu")
  .setInputCols("sentence", "token", "pos")
  .setOutputCol("dependency")

val typed_english_dependency = TypedDependencyParserModel.pretrained("dependency_typed_conllu")
  .setInputCols("token", "pos", "dependency")
  .setOutputCol("typed_dependency")

testing.show(truncate = false)

val document = new DocumentAssembler()
  .setInputCol("text")
  .setOutputCol("document")

val token = new Tokenizer()
  .setInputCols("document")
  .setOutputCol("token")

val sentence: SentenceDetector = new SentenceDetector()
  .setInputCols("document")
  .setOutputCol("sentence")

val pipeline = new Pipeline().setStages(Array(document, token, sentence, english_pos,english_dependency))

val sparkPipeline = pipeline.fit(testing)
val result = sparkPipeline.transform(testing)

result.show(truncate = false)


typed_english_dependency.transform(result).show(truncate = false)
}
}
