### ISSUE TITLE
Loading pre-trained pipeline from diskfile is not working with error Param cleanupMode does not exist

### ISSUE THREAD

**Issue by JuanCarlosCamara** [JohnSnowLabs/spark-nlp#854]
Loading pre-trained pipeline from diskfile is not working with error Param cleanupMode does not exist

### Description
I´m trying to load a pre-trained pipeline for [spanish language](https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/explain_document_lg_es_2.4.0_2.4_1581975536033.zip) via offline mode. 

### Expected behavior
Pretrained pipeline is loaded and possible functions like annotate are able to be executed

### Current behavior

However, and error is given:

`
: java.util.NoSuchElementException: Param cleanupMode does not exist.
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getParam(params.scala:728)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:42)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata$$anonfun$setParams$1.apply(ReadWrite.scala:591)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata$$anonfun$setParams$1.apply(ReadWrite.scala:589)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.setParams(ReadWrite.scala:589)
	at org.apache.spark.ml.util.DefaultParamsReader$Metadata.getAndSetParams(ReadWrite.scala:577)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:497)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:652)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
`

### Possible solution
After reading similar other issues, I´m wondering if maybe link for offline use is not correctly updated as per SparkNLP 2.4.5 version

### Context
I want to use the latest version of Spark NLP, but this is blocking

### Your Environment

- Spark NLP Version: 2.4.5
- Apache Spark Version(pyspark): 2.4.4
- Operating System and version: Mac OS Mojave

**Comment by maziyarpanahi** [comment]
Thanks for reporting this. The link suggests the pipeline should be compatible with the `2.4.x` releases. Could you please provide the code snippet for reproducibility?

**Comment by maziyarpanahi** [comment]
I just tried it on 2.4.5 and it was fine. I am suspecting you are either not on `2.4.x` version, so you need to be absolutely sure both PyPI and --packages are in the same versions (2.4.5). 
Also, try the `pretrained()` function first like my screenshot just to be sure you didn't use an older pipeline by mistake:

![image](https://user-images.githubusercontent.com/5762953/79594343-22e85280-80dd-11ea-91c6-ef1af4641924.png)


If the result is the same, please provide full snippet code and full details as how you installed the library in PyPI, and most importantly how are you starting your SparkSession (manually or sparknlp.start)

**Comment by maziyarpanahi** [comment]
It also works in Python:
![image](https://user-images.githubusercontent.com/5762953/79643040-4a085800-81a1-11ea-9674-488e855430aa.png)


This must be either old pipeline saved and being loaded in a newer version, or a new pipeline being loaded on an old version (both PyPI and --packages/--jars must be the same versions)

Please provide information as to how you start your SparkSession, how you installed the library with full code if the error still persists.
