### ISSUE TITLE
UniversalSentenceEncoder: org.apache.spark.SparkException: Failed to execute user defined function

### ISSUE THREAD

**Issue by mendansandesh** [JohnSnowLabs/spark-nlp#863]
Trying to perform text classification using ClassifierDL with USE in Spark structured streaming project

Encountered with error on running spark code:
```
Apr 21 2020 01:11:27.380 PM [Executor task launch worker for task 218] ERROR org.apache.spark.executor.Executor:91 - Exception in task 3.0 in stage 6.0 (TID 218)
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source) ~[na:na]
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43) ~[spark-sql_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636) ~[spark-sql_2.11-2.4.4.jar:2.4.4]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409) ~[scala-library-2.11.12.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409) ~[scala-library-2.11.12.jar:na]
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409) ~[scala-library-2.11.12.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[scala-library-2.11.12.jar:na]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104) ~[scala-library-2.11.12.jar:na]
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310) ~[scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.to(Iterator.scala:1334) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302) ~[scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1334) ~[scala-library-2.11.12.jar:na]
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289) ~[scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1334) ~[scala-library-2.11.12.jar:na]
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:945) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:945) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.scheduler.Task.run(Task.scala:123) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414) ~[spark-core_2.11-2.4.4.jar:2.4.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347) ~[scala-library-2.11.12.jar:na]
	at scala.None$.get(Option.scala:345) ~[scala-library-2.11.12.jar:na]
	at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder.getModelIfNotSet(UniversalSentenceEncoder.scala:45) ~[spark-nlp_2.11-2.4.5.jar:2.4.5]
	at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder.annotate(UniversalSentenceEncoder.scala:75) ~[spark-nlp_2.11-2.4.5.jar:2.4.5]
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35) ~[spark-nlp_2.11-2.4.5.jar:2.4.5]
	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34) ~[spark-nlp_2.11-2.4.5.jar:2.4.5]
	... 29 common frames omitted
```

below are the dependencies i used:
```
    compile 'org.apache.spark:spark-core_2.11:2.4.0'
    compile group: 'org.apache.spark', name: 'spark-sql_2.11', version: '2.4.0'
    compile group: 'org.apache.spark', name: 'spark-sql-kafka-0-10_2.11', version: '2.4.4'
    compile group: 'org.apache.spark', name: 'spark-mllib_2.11', version: '2.4.4'
    compile group: 'com.johnsnowlabs.nlp', name: 'spark-nlp_2.11', version: '2.4.5'`
```
Full code:
`    
    public class ModelTrainer {
        public static void main(String[] args) {

        final SparkSession spark = SparkNLP.start(true);

        Dataset<Row> trainData = spark.read()
                .option("inferSchema", "true")
                .option("header", "true")
                .csv("/home/inct-sandeshmendan/sandesh/ML/sparkNLP/news_category_train.csv");
        Dataset<Row> testData = spark.read()
                .option("inferSchema", "true")
                .option("header", "true")
                .csv("/home/inct-sandeshmendan/sandesh/ML/sparkNLP/news_category_test.csv");

        //ClassifierDL with USE
        DocumentAssembler document = new DocumentAssembler();
        document.setInputCol("description")
                .setOutputCol("document");

        UniversalSentenceEncoder use = new UniversalSentenceEncoder();
        use.setInputCols(new String[]{document.getOutputCol()});
        use.setOutputCol("sentence_embeddings");

        ClassifierDLApproach classifierDL = new ClassifierDLApproach();
        classifierDL.setInputCols(new String[]{use.getOutputCol()});
        classifierDL.setOutputCol("class");
        classifierDL.setLabelColumn("category");
        classifierDL.setMaxEpochs(5);
        classifierDL.setEnableOutputLogs(true);

        Pipeline pipeline = new Pipeline().setStages(new PipelineStage[]{document, use, classifierDL});
        PipelineModel pipelineModel = pipeline.fit(trainData);

        LightPipeline lightPipeline = new LightPipeline(pipelineModel, true);
        testData.select("description").take(2);
        String text = "In the year 2020, due to corona virus people are dying as there are no enough beds and equipment to treat patient in hospital";
        Map<String, List<String>> result = lightPipeline.annotateJava(text);
        //Map<String, Seq<String>> result = lightPipeline.annotate(text);
        System.out.println(result.get("class")); //token

        spark.close();
    }
}
`
* Spark NLP version: 2.4.5
* Apache Spark version: 2.4.4
* Java version (java -version): 1.8
* Setup and installation (Pypi, Conda, Maven, etc.): java gradle project
* Operating System and version: ubuntu 18.04
* Link to your project (if any):
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/5.Text_Classification_with_ClassifierDL.ipynb
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/english/classification/ClassifierDL_Train_multi_class_news_category_classifier.ipynb

**Comment by maziyarpanahi** [comment]
I have noticed you are using this line:

```
        UniversalSentenceEncoder use = new UniversalSentenceEncoder();
```
Nowhere in our examples, we mentioned you can do that. This annotator is a Model, every example has a `.pretrained()` or `.load()` without the `new` part.

Please look at the examples: 

https://github.com/JohnSnowLabs/spark-nlp-workshop/search?q=universalsentenceencoder&unscoped_q=universalsentenceencoder
