### ISSUE TITLE
Py4jJavaError

### ISSUE THREAD

**Issue by jamshaidsohail5** [JohnSnowLabs/spark-nlp#869]
Trying to run the example on [Light Pipelines](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/jupyter/1-%20How%20to%20use%20Light%20Pipelines.ipynb).  An error is thrown.  "Py4JJavaError:".

## Description
Running the example provided at https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/jupyter/1-%20How%20to%20use%20Light%20Pipelines.ipynb crashes at pipeline = PretrainedPipeline('explain_document_ml', lang='en') with the exception

========================================================
explain_document_ml download started this may take some time.

Approx size to download 9.4 MB
[OK!]

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-4-0896d6b45bb3> in <module>
----> 1 pipeline = PretrainedPipeline('explain_document_ml', lang='en')

~\.conda\envs\sparknlp\lib\site-packages\sparknlp\pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     89     def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     90         if not disk_location:
---> 91             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         else:
     93             self.model = PipelineModel.load(disk_location)

~\.conda\envs\sparknlp\lib\site-packages\sparknlp\pretrained.py in downloadPipeline(name, language, remote_loc)
     58             t1.start()
     59             try:
---> 60                 j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     61                 jmodel = PipelineModel._from_java(j_obj)
     62             finally:

~\.conda\envs\sparknlp\lib\site-packages\sparknlp\internal.py in __init__(self, name, language, remote_loc)
    179 class _DownloadPipeline(ExtendedJavaWrapper):
    180     def __init__(self, name, language, remote_loc):
--> 181         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
    182 
    183 

~\.conda\envs\sparknlp\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

~\.conda\envs\sparknlp\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

~\.conda\envs\sparknlp\lib\site-packages\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

~\.conda\envs\sparknlp\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~\.conda\envs\sparknlp\lib\site-packages\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~\.conda\envs\sparknlp\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/C:/Users/jamshaid.sohail/cache_pretrained/explain_document_ml_en_2.4.0_2.4_1580252705962/metadata
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:287)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1343)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1337)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1378)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1377)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:615)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:267)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:373)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:367)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:461)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)`

================================================
## Expected Behavior

All necessary resources should be downloaded without running into an exception.

## Current Behavior

Downloader crashes when attempting to download resources for pretrained pipeline. This happens for "explain_document_ml".

## Possible Solution

No idea, I followed the steps as below to set up sparkNLP.

$ java -version
# should be Java 8 (Oracle or OpenJDK)
$ conda create -n sparknlp python=3.6 -y
$ conda activate sparknlp
$ pip install spark-nlp==2.4.5 pyspark==2.4.4

After this i launched the notebook in this respective environment and started running the code as above.I have alreay installed spark with hadoop on my system.

## Steps to Reproduce

1. Install pyspark along with spark NLP as indicated above and activated the sparknlp virtual environment and launched the notebook in it.
2. Create a spark session from spark NLP (Although I have installed Spark with Hadoop on my system.)
3. Run code at https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/jupyter/1-%20How%20to%20use%20Light%20Pipelines.ipynb

 
## Context

Goal: Run this example without crashing. And then I will be using BioBert as [here ](https://github.com/JohnSnowLabs/spark-nlp-models/releases/tag/2.3.4-biobert-embeddings)to generate embeddings of a medical dataset.

## Your Environment

* Spark NLP version: 2.4.5
* Apache Spark version:  2.4.4
* Java version (java -version): java version "1.8.0_251"
* Setup and installation (Pypi, Conda, Maven, etc.): Installation using pip as above.
* Operating System and version: Windows 10

**Comment by maziyarpanahi** [comment]
It downloaded the pipeline correctly, however, it has a problem either writing or accessing it:
```
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/C:/Users/jamshaid.sohail/cache_pretrained/explain_document_ml_en_2.4.0_2.4_1580252705962/metadata
```
This happens when the home directory in Windows doesn't have required permissions to read/write. In cases like this:

- You can download the pipeline from `spark-nlp-models` manually, **extract** it, and use it as follow:

```
pipeline = PipelineModel.load("/tmp/explain_document_ml_en_2.4.0_2.4_1580252705962/")
```

NOTE: Beware, BioBERT models are not public nor supported in 2.4.x releases.

**Comment by maziyarpanahi** [comment]
BioBERT and ClinicalBERT models (6) are now available on 2.5.x releases!
https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.5.1

**Comment by arianpasquali** [comment]
Same error with Bert models. Trying to load Bert Portuguese as described [here ](https://github.com/JohnSnowLabs/spark-nlp-models#portuguese---models)

`bert = BertEmbeddings.pretrained('bert_portuguese_large_cased', 'pt')`

I wonder if the model is public or licensed

**Comment by maziyarpanahi** [comment]
> Same error with Bert models. Trying to load Bert Portuguese as described [here ](https://github.com/JohnSnowLabs/spark-nlp-models#portuguese---models)
> 
> 
> 
> `bert = BertEmbeddings.pretrained('bert_portuguese_large_cased', 'pt')`
> 
> 
> 
> I wonder if the model is public or licensed 

The model is public. The error can be caused by a number of things. Please create a new issue with a full template so we can reproduce and help.
