### ISSUE TITLE
PySpark 2.3: Constructor com.johnsnowlabs.nlp.training.CoNLLU does not exist

### ISSUE THREAD

**Issue by NorDar** [JohnSnowLabs/spark-nlp#9001]
## Description

Hi, 
We are currently trying to use spark-nlp on an older Spark stack and are running into compatibility issues from time to time. 

At the moment we want to use CoNLLU to read a text file into a Spark Dataframe. I can load the CoNLLU class but as soon as I try to create the spark dataframe there are java gateway exceptions. 

## Expected Behavior
I expect to be able to have a `.conllu` file in HDFS and read it into a Spark dataframe.

## Current Behavior
As soon as I want to instantiate the CoNLLU class I get an error. It does not matter if I provide any existing or nonexisting `path` parameter to `.readDataset(spark=spark, path=conlluFile)`. 

With the following lines:
```python
import sparknlp
from sparknlp.training import CoNLLU
conlluFile = "/user/username/en_atis-ud-train.conllu"
#conlluFile = "/tmp/conllu-data/en_atis-ud-train.conllu"
conllDataSet = CoNLLU().readDataset(spark=spark, path=conlluFile) # TrainingSet POS Tagger
```

I get the follwing output:
```
Fail to execute line 5: conllDataSet = CoNLLU().readDataset(spark=spark, path=conlluFile) # TrainingSet POS Tagger
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-5607070394230017834.py", line 380, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 5, in <module>
  File "/app/miniconda3/envs/lab_legal343_env/lib/python3.7/site-packages/sparknlp/training.py", line 208, in __init__
    explodeSentences)
  File "/app/miniconda3/envs/lab_legal343_env/lib/python3.7/site-packages/sparknlp/internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/app/miniconda3/envs/lab_legal343_env/lib/python3.7/site-packages/sparknlp/internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling None.com.johnsnowlabs.nlp.training.CoNLLU. Trace:
py4j.Py4JException: Constructor com.johnsnowlabs.nlp.training.CoNLLU([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.Boolean]) does not exist
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:179)
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:196)
	at py4j.Gateway.invoke(Gateway.java:237)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

## Possible Solution

Might it be possible that this specific release with combination (spark 2.3.2, python 3.7.9, sparknlp 3.4.3) is buggy? There were also issues while installing the library from conda as described at the bottom of the post.
It seems that the dependency from within the `.jar` can't be found.

## Steps to Reproduce

`start-sparknlp-pyspark.sh`
```sh
export PYSPARK_DRIVER_PYTHON=/app/miniconda3/envs/lab_legal343_env/bin/python
export PYSPARK_PYTHON=/app/miniconda3/envs/lab_legal343_env/bin/python


pyspark \
  --master local[*] \
  --jars /usr/hdp/current/spark2-client/jars/spark-nlp-spark23_2.11-3.4.3.jar
```

Run the following lines:
```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.3.2.3.1.0.0-78
      /_/

Using Python version 3.7.9 (default, Feb 13 2021 20:03:11)
SparkSession available as 'spark'.
>>> import sparknlp
>>> from sparknlp.training import CoNLLU
>>> conlluFile = "/user/user/en_atis-ud-train.conllu"
>>> conllDataSet = CoNLLU().readDataset(spark=spark, path=conlluFile) # TrainingSet POS Tagger
```

## Your Environment

* Spark NLP version `sparknlp.version()`: `3.4.3`
* Apache NLP version `spark.version`: `2.3.2.3.1.0.0-78` 
* Java version `java -version`: `1.8.0_262`
* Setup and installation (Pypi, Conda, Maven, etc.): The spark-nlp jars are directly deployed on all worker nodes due to a bug in the `legacy Zeppelin`. The bug was reproduced directly in the pyspark console.
* Operating System and version: CentOS Linux release 7.8.2003 (Core)
* Link to your project (if any): -

### Additional Environment Information
We use Apache Zeppelin and provide a specific Interpreter for specific use cases. The specific python environments are deployed on every worker node via miniconda. The python environment for this interpreter was configured with the following libraries:
```yaml
miniconda_env_vars:
  - python=3.7.9
  - pyspark=2.3.2
  - spark-nlp=3.4.3=py37_0
  - numpy
  - pandas
  - nltk
```
Please note that we had to explicitly define the python version for spark-nlp. Otherwise, conda was not correctly resolving the python dependency and installing spark-nlp=3.4.3=**py38_0**

We don't initiate Spark from within the script since we have configured our Zeppelin interpreter according to [sparknlp.start()](https://github.com/JohnSnowLabs/spark-nlp/blob/master/python/sparknlp/__init__.py#L61)
We are linking to the spark-nlp jar `/usr/hdp/current/spark2-client/jars/spark-nlp-spark23_2.11-3.4.3.jar` from https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp-spark23_2.11/3.4.3/spark-nlp-spark23_2.11-3.4.3.jar

Thanks a lot for your help :)

**Comment by maziyarpanahi** [comment]
Those jars on Maven are shallow/light with no dependencies and they cannot be used for offline use cases via --jars. 

Please use the actual Fat JARs we provide and host on S3. You can see the list of them with each release note (at the end): https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.4.4

**Comment by NorDar** [comment]
Hi Maziyar,

Thanks a lot for your prompt reply :) 

I have deployed the fat jar linked from the release note: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.4.3
directly to the cluster via Ansible.  
```yaml
- hosts: relevant-hosts
  gather_facts: no
  become: yes

  tasks:
   - name: Install NLP Artifact for Spark
     shell: |
       cd /.../jars
       wget https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/jars/spark-nlp-spark23-assembly-3.4.3.jar
```

I then modify the `spark.jars` argument to `	/.../jars/spark-nlp-spark23-assembly-3.4.3.jar` and restart the Zeppelin interpreter.  
I check the available jars in Zeppelin. `print(spark.sparkContext._jsc.sc().listJars())`  
```
ArrayBuffer(spark://zeppelin-host:42744/jars/spark-nlp-spark23-assembly-3.4.3.jar, spark://zeppelin-host:42744/jars/spark-xml_2.11-0.11.0.jar)
```
As far as I understand it the correct fat-jar should be available and loaded.  

When I run the example cell in the same Zeppelin interpreter:
```py
import sparknlp
from sparknlp.training import CoNLLU
print(spark.sparkContext._jsc.sc().listJars())
conlluFile = "/user/user/en_atis-ud-train.conllu"
conllDataSet = CoNLLU().readDataset(spark=spark, path=conlluFile) # TrainingSet POS Tagger
```

I still get the output:
```
ArrayBuffer(spark://hdp-edge-02.corp.itsroot.biz:39254/jars/spark-xml_2.11-0.11.0.jar, spark://hdp-edge-02.corp.itsroot.biz:39254/jars/spark-nlp-spark23-assembly-3.4.3.jar)
Fail to execute line 5: conllDataSet = CoNLLU().readDataset(spark=spark, path=conlluFile) # TrainingSet POS Tagger
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-3887932545663434071.py", line 380, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 5, in <module>
  File "/app/miniconda3/envs/lab_legal343_env/lib/python3.7/site-packages/sparknlp/training.py", line 208, in __init__
    explodeSentences)
  File "/app/miniconda3/envs/lab_legal343_env/lib/python3.7/site-packages/sparknlp/internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/app/miniconda3/envs/lab_legal343_env/lib/python3.7/site-packages/sparknlp/internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling None.com.johnsnowlabs.nlp.training.CoNLLU. Trace:
py4j.Py4JException: Constructor com.johnsnowlabs.nlp.training.CoNLLU([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.Boolean]) does not exist
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:179)
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:196)
	at py4j.Gateway.invoke(Gateway.java:237)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

```

I inspected the jar with WinRAR and was able to find the file `com/johnsnowlabs/nlp/training/CoNLLU.class` that also contains the string "readDataset" and a lot of other jumbled Information. Unfortunately, my Java debugging skills end here.

I am not sure what to make out of this.

Thanks again.
