### ISSUE TITLE
java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods

### ISSUE THREAD

**Issue by kwongm** [JohnSnowLabs/spark-nlp#928]
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;

## Description

I am trying to use the NorvigSweetingModel pretrained model, but I am getting an error when trying to load this in. Can anyone help me with this issue?

## Code

import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *

spark = sparknlp.start()
data = spark.createDataFrame([['Peter is a godo person living in Germny. Paula is also a good person. She lives in London.']]).toDF('text')
document = DocumentAssembler().setInputCol('text').setOutputCol('document')
sentence = SentenceDetector().setInputCols('document').setOutputCol('sentence')
sentence.setExplodeSentences(True)
tokenizer = Tokenizer().setInputCols('sentence').setOutputCol('token')
tokenizer.setExceptions(['e-mail'])
checker = NorvigSweetingModel.pretrained().setInputCols(['token']).setOutputCol('checked')

## Your Environment

* Spark NLP version: 2.5.1
* Apache Spark version: 2.4.4 
* Java version (java -version): java 1.8.0_251
* Setup and installation (Pypi, Conda, Maven, etc.): Conda , running on Jupyter Notebook
* Operating System and version: Windows 10
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,
Thanks for reporting this. Could you please provide the following:

- Spark NLP version printed from inside the app: `sparknlp.version()`
- Apache Spark version printed from inside the app (very important as. the error looks like you are using Apache Spark 2.3.x): `spark.version`
- The full-stack of error

**Comment by kwongm** [comment]
sparknlp.version() 2.5.1

spark.version 2.4.5

**Comment by kwongm** [comment]
spellcheck_norvig download started this may take some time.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-10-4330c634e817> in <module>
----> 1 checker = NorvigSweetingModel.pretrained().setInputCols(['token']).setOutputCol('checked')

~\miniconda3\lib\site-packages\sparknlp\annotator.py in pretrained(name, lang, remote_loc)
   1142     def pretrained(name="spellcheck_norvig", lang="en", remote_loc=None):
   1143         from sparknlp.pretrained import ResourceDownloader
-> 1144         return ResourceDownloader.downloadModel(NorvigSweetingModel, name, lang, remote_loc)
   1145 
   1146 

~\miniconda3\lib\site-packages\sparknlp\pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     30     def downloadModel(reader, name, language, remote_loc=None, j_dwn='PythonResourceDownloader'):
     31         print(name + " download started this may take some time.")
---> 32         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     33         if file_size == "-1":
     34             print("Can not find the model to download please check the name!")

~\miniconda3\lib\site-packages\sparknlp\internal.py in __init__(self, name, language, remote_loc)
    190     def __init__(self, name, language, remote_loc):
    191         super(_GetResourceSize, self).__init__(
--> 192             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
    193 
    194 

~\miniconda3\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

~\miniconda3\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

C:\spark-2.4.5-bin-hadoop2.7\python\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

C:\spark-2.4.5-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

C:\spark-2.4.5-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

C:\spark-2.4.5-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
	at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.parseJson(ResourceMetadata.scala:61)
	at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$$anonfun$readResources$1.applyOrElse(ResourceMetadata.scala:90)
	at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$$anonfun$readResources$1.applyOrElse(ResourceMetadata.scala:89)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.collection.Iterator$$anon$14.next(Iterator.scala:542)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1334)
	at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.readResources(ResourceMetadata.scala:92)
	at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.readResources(ResourceMetadata.scala:84)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:70)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:81)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:159)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:394)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:479)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)

**Comment by maziyarpanahi** [comment]
This is strange, I just ran your code and it works:

```python

import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *

spark = sparknlp.start()
data = spark.createDataFrame([['Peter is a godo person living in Germny. Paula is also a good person. She lives in London.']]).toDF('text')
document = DocumentAssembler().setInputCol('text').setOutputCol('document')
sentence = SentenceDetector().setInputCols('document').setOutputCol('sentence')
sentence.setExplodeSentences(True)
tokenizer = Tokenizer().setInputCols('sentence').setOutputCol('token')
tokenizer.setExceptions(['e-mail'])
checker = NorvigSweetingModel.pretrained().setInputCols(['token']).setOutputCol('checked')

sparknlp.version()
# 2.5.2
spark.version
# 2.4.5

nlpPipeline = Pipeline(stages=[
document,
sentence,
tokenizer,
checker
... ])

nlpPipeline.fit(data).transform(data).show()

+--------------------+--------------------+--------------------+--------------------+--------------------+
|                text|            document|            sentence|               token|             checked|
+--------------------+--------------------+--------------------+--------------------+--------------------+
|Peter is a godo p...|[[document, 0, 89...|[[document, 0, 39...|[[token, 0, 4, Pe...|[[token, 0, 4, Pe...|
|Peter is a godo p...|[[document, 0, 89...|[[document, 41, 6...|[[token, 41, 45, ...|[[token, 41, 45, ...|
|Peter is a godo p...|[[document, 0, 89...|[[document, 70, 8...|[[token, 70, 72, ...|[[token, 70, 72, ...|
+--------------------+--------------------+--------------------+--------------------+--------------------+

I can think of one thing, I see `C:\spark-2.4.5-bin-hadoop2.7\` why aren't you using a `pip install pyspark`? 

One more thing to debug would be in the same cond environment instead of launching Jupyter, please run the code inside Python console to be sure there is no wrong config set for Jupyter. (sometimes people follow tutorials on the internet where you launch Juoyter specifically for Apache Spark with extra configs and special Kernel)

**Comment by kwongm** [comment]
Okay I was able to remove the conflicts with the Apache Spark I had on my machine. However I am now receiving a new error regarding the annotator:

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/C:/Users/MKwon/cache_pretrained/spellcheck_norvig_en_2.1.0_2.4_1563017660080/metadata

Again, my environment setup:
Spark NLP version: 2.5.2
Apache Spark version: 2.4.4
Java version (java -version): java 1.8.0_251

Here is the full stack error:
spellcheck_norvig download started this may take some time.
Approximate size to download 4.2 MB
[OK!]
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-12-4330c634e817> in <module>
----> 1 checker = NorvigSweetingModel.pretrained().setInputCols(['token']).setOutputCol('checked')

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\annotator.py in pretrained(name, lang, remote_loc)
   1160     def pretrained(name="spellcheck_norvig", lang="en", remote_loc=None):
   1161         from sparknlp.pretrained import ResourceDownloader
-> 1162         return ResourceDownloader.downloadModel(NorvigSweetingModel, name, lang, remote_loc)
   1163 
   1164 

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     39             t1.start()
     40             try:
---> 41                 j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     42             finally:
     43                 stop_threads = True

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in __init__(self, reader, name, language, remote_loc, validator)
    174 class _DownloadModel(ExtendedJavaWrapper):
    175     def __init__(self, reader, name, language, remote_loc, validator):
--> 176         super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
    177 
    178 

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

c:\users\mkwon\anaconda3\envs\sparknlp\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/C:/Users/MKwon/cache_pretrained/spellcheck_norvig_en_2.1.0_2.4_1563017660080/metadata
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:287)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1388)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1382)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1423)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1422)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:615)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:493)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:12)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:359)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:353)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:463)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)

Thanks for the advice!

**Comment by maziyarpanahi** [comment]
OK, it's good that you found the conflict. Regarding your second error, depending on the environment and how Apache Spark' setup, sometimes Spark NLP cannot find the appropriate HOME_DIR of the user. 
As you can see, it downloads, extracts, and load any pretrained models/pipelines inside `file:/C:/Users/MKwon/cache_pretrained/` which is `HOME_DIR/cache_pretrained`. A couple of things that can be done:

* Check if this directory exists
* If yes, check the permissions to see if it can read/write
* If no, you may want to manually create it and see what happens
* If all fails, then you can always download anything you need and use `.load(PATH)` instead of `pretrained()` from here which is called `offline`: https://github.com/JohnSnowLabs/spark-nlp-models

**Comment by kwongm** [comment]
Yes manually creating the folder seems to have solved the issue. My program is running smoothly now. Thank you very much!

**Comment by maziyarpanahi** [comment]
Great to hear that, it was probably not having enough permission to create that folder at first. 
Best of luck and thanks for updating us.
