### ISSUE TITLE
AWS 403 Access denied error in getting download size for glove_100d pretrained Spark nlp model

### ISSUE THREAD

**Issue by preetbawa** [JohnSnowLabs/spark-nlp#9314]
On databricks job cluster, we are trying to generate embeddings for some Recommendations content using Spark NLP like this 
  glove = (
        WordEmbeddingsModel.pretrained()
        .setInputCols(["document", "clean_normal"])
        .setOutputCol("embeddings")
    )

    glovePipeline = Pipeline(
        stages=[
            documentAssembler,
            sentenceDetector,
            tokenizer,
            normalizer,
            stopword_cleaner,
            glove,
        ]
    )

After  glove100d download is initiated, you see the following stack trace: 
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: RXYGFG87QQZ9JJQS; S3 Extended Request ID: s+wD6a1Ud4HEgT7yjDkdyGdz/5X1XRBeuaPY7Lk84I0M8sQOvEvSOH+jKaNVBaj5zZh4kkk/hSk=), S3 Extended Request ID: s+wD6a1Ud4HEgT7yjDkdyGdz/5X1XRBeuaPY7Lk84I0M8sQOvEvSOH+jKaNVBaj5zZh4kkk/hSk=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4926)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4872)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1472)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1327)
	at com.johnsnowlabs.client.aws.AWSGateway.getObjectFromS3(AWSGateway.scala:108)
	at com.johnsnowlabs.client.aws.AWSGateway.getMetadata(AWSGateway.scala:93)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:65)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:70)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:204)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:544)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:714)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

## Description
This works fine when running in a databricks notebook using personal databricks cluster but it doesn't work using Airflow Databricks job clusters as part of production job. 

## Expected Behavior
Glove100d pretrained model for WordEmbeddings should download and be able to build embeddings
## Current Behavior
403 access denied when it initiates the download and tries to get download size. 
## Possible Solution
i am thinking to offline download the model and put it on databricks file system and read from path instead of downloading it. 
## Steps to Reproduce
1.  glove = (
        WordEmbeddingsModel.pretrained()
        .setInputCols(["document", "clean_normal"])
        .setOutputCol("embeddings")
    )

    glovePipeline = Pipeline(
        stages=[
            documentAssembler,
            sentenceDetector,
            tokenizer,
            normalizer,
            stopword_cleaner,
            glove,
        ]
    )

## Context

Trying to build embeddings for Recommendations as part of running as a job (using Databricks job cluster)
## Your Environment

* Spark NLP version `sparknlp.version()`: 3.4.4
* Apache NLP version `spark.version`: 3.1.2
* Java version `java -version`: 
* Setup and installation (Pypi, Conda, Maven, etc.): Maven
* Operating System and version: Databricks spark cluster
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
The public models/pipelines are on an S3 bucket with public access. There is nothing Spark NLP nor the S3 can do here, your environment either has some AWS settings/confs already that conflict or date/time not correct (usual suspects as to why a public folder gives 403 error).

I'll ask around, but if you can have a clean airflow without anything else and just Spark NLP it would be helpful. (we use airflow, but not on Databricks)

**Comment by preetbawa** [comment]
can i just download the glove_100d model offline and have it read from path

**Comment by maziyarpanahi** [comment]
Absolutely! 100% offline is supported: 
https://github.com/JohnSnowLabs/spark-nlp#offline

In your case will be `WordEmbeddingsModel.load("dbfs:/PATH_TO_EXTRACTED_MODEL")`

**Comment by preetbawa** [comment]
thanks Maziyar, really appreciate your fast response.
