### ISSUE TITLE
nullpointerexception using BERT NER pretrained pipeline

### ISSUE THREAD

**Issue by clabornd** [JohnSnowLabs/spark-nlp#938]
## Description

I am running into this error when trying to write out or print the munged/finished output of the bert pretrained ner pipeline.  Before applying a finisher, I extract the results of entities.metadata and embeddings.embeddings into a new columns and then run a UDF on the new column containing entities.metadata to rearrange the output.  There is one final UDF run on the finished_entities to produce several struct columns.  

I then attempt to drop the columns containing entities.metadata and either display/save the table.  Apologies I do not have a mwe, I cannot reproduce this locally or on a toy dataset.

The general code is:

```
bert_pipeline = PretrainedPipeline("recognize_entities_bert", lang="en")
ner_pipeline_df = bert_pipeline.transform(textdf)

ner_finisher = (
  Finisher()
  .setInputCols(["document", "ner", "entities"])
)

meta_df = ner_finisher.transform(
    ner_pipeline_df
    .withColumn('entities_meta', sf.col('entities.metadata'))
    .withColumn('bert_embeddings', sf.col('embeddings.embeddings'))
  )

from pyspark.sql.functions import udf
from pyspark.sql.types import StructType, StructField, ArrayType, StringType

def array_to_struct(reslist):
  # 
  out_dict = {}

  for key in reslist[0].keys():
    if isinstance(reslist[0][key], dict):
       for sub_key in reslist[0][key].keys():
          out_dict[sub_key] = [el[key][sub_key] for el in reslist]
    else:
      out_dict[key] = [el[key] for el in reslist]

  return out_dict

schema = StructType(
  [
    StructField("sentence", ArrayType(StringType()), True),
    StructField("chunk", ArrayType(StringType()), True),
    StructField("entity", ArrayType(StringType()), True)
  ]
)

array_to_struct_udf = udf(array_to_struct, schema)

named_ent_df = meta_df.withColumn('extracted_terms', array_to_struct_udf("entities_meta"))
```

At this point I have a dataframe with structure:

|-- date_str: string (nullable = true)
 |-- DocumentId: string (nullable = true)
 |-- themes: string (nullable = true)
 |-- text: string (nullable = true)
 |-- entities_meta: array (nullable = true)
 |    |-- element: map (containsNull = true)
 |    |    |-- key: string
 |    |    |-- value: string (valueContainsNull = true)
 |-- bert_embeddings: array (nullable = true)
 |    |-- element: array (containsNull = true)
 |    |    |-- element: float (containsNull = false)
 |-- finished_document: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- finished_ner: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- finished_entities: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- extracted_terms: struct (nullable = true)
 |    |-- sentence: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- chunk: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- entity: array (nullable = true)
 |    |    |-- element: string (containsNull = true)

then (sorry for the pseudo-code) I apply a udf and drop the metadata columns.  _Everything seems to work if I do not drop extracted_terms or entities_meta._

```
## apply another udf that munges "extracted" terms.

###
named_ent_df = named_ent_df.select(*['GKGRecordID',
 'date_str',
 'DocumentId',
'bert_embeddings,
 'themes',
 'text',
 'matches',
....])

display(named_ent_df) # or
named_ent_df.write....
```

which results in:

```
An error occurred while calling o5092.getResult.
: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:358)
	at org.apache.spark.security.SocketAuthServer.getResult(SocketAuthServer.scala:67)
	at org.apache.spark.security.SocketAuthServer.getResult(SocketAuthServer.scala:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 64.0 failed 4 times, most recent failure: Lost task 6.3 in stage 64.0 (TID 291, 10.139.64.4, executor 7): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAssembleNoExtras$1: (string) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_ScalaUDF_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doAggregateWithKeysOutput_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anonfun$3$$anon$1.next(InMemoryRelation.scala:104)
	at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anonfun$3$$anon$1.next(InMemoryRelation.scala:96)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1235)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:366)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:364)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1235)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.johnsnowlabs.nlp.DocumentAssembler.assemble(DocumentAssembler.scala:98)
	at com.johnsnowlabs.nlp.DocumentAssembler$$anonfun$dfAssembleNoExtras$1.apply(DocumentAssembler.scala:124)
	at com.johnsnowlabs.nlp.DocumentAssembler$$anonfun$dfAssembleNoExtras$1.apply(DocumentAssembler.scala:123)
	... 67 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2362)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2350)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2349)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2349)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2582)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2529)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2517)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:897)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2280)
	at org.apache.spark.sql.Dataset$$anonfun$collectAsArrowToPython$1$$anonfun$apply$20.apply(Dataset.scala:3440)
	at org.apache.spark.sql.Dataset$$anonfun$collectAsArrowToPython$1$$anonfun$apply$20.apply(Dataset.scala:3409)
	at org.apache.spark.api.python.PythonRDD$$anonfun$6$$anonfun$apply$7.apply$mcV$sp(PythonRDD.scala:627)
	at org.apache.spark.api.python.PythonRDD$$anonfun$6$$anonfun$apply$7.apply(PythonRDD.scala:627)
	at org.apache.spark.api.python.PythonRDD$$anonfun$6$$anonfun$apply$7.apply(PythonRDD.scala:627)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.api.python.PythonRDD$$anonfun$6.apply(PythonRDD.scala:628)
	at org.apache.spark.api.python.PythonRDD$$anonfun$6.apply(PythonRDD.scala:624)
	at org.apache.spark.api.python.SocketFuncServer.handleConnection(PythonRDD.scala:1172)
	at org.apache.spark.api.python.SocketFuncServer.handleConnection(PythonRDD.scala:1166)
	at org.apache.spark.security.SocketAuthServer$$anonfun$1$$anonfun$apply$1.apply(SocketAuthServer.scala:48)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.security.SocketAuthServer$$anonfun$1.apply(SocketAuthServer.scala:48)
	at org.apache.spark.security.SocketAuthServer$$anonfun$1.apply(SocketAuthServer.scala:47)
	at org.apache.spark.security.SocketAuthServer$$anon$1.run(SocketAuthServer.scala:102)
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAssembleNoExtras$1: (string) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_ScalaUDF_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doAggregateWithKeysOutput_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anonfun$3$$anon$1.next(InMemoryRelation.scala:104)
	at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anonfun$3$$anon$1.next(InMemoryRelation.scala:96)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1235)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:366)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:364)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1235)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1161)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1226)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1045)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:315)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.johnsnowlabs.nlp.DocumentAssembler.assemble(DocumentAssembler.scala:98)
	at com.johnsnowlabs.nlp.DocumentAssembler$$anonfun$dfAssembleNoExtras$1.apply(DocumentAssembler.scala:124)
	at com.johnsnowlabs.nlp.DocumentAssembler$$anonfun$dfAssembleNoExtras$1.apply(DocumentAssembler.scala:123)
	... 67 more
```

## Your Environment
* Spark NLP version: 2.5.2
* Databricks runtime 6.4 (includes Apache Spark 2.4.5, Scala 2.11)
* Java version (java -version): 1.8.0_232
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi/Maven

**Comment by maziyarpanahi** [comment]
Hi,
I dont see anything related to BertEmbeddings in the trace, all I see is DocumentAssembler. Do you have an empty input?
I see why and where it fails in DocumentAssembler but it would be helpful to filter out any empty and null input for test on your side.

**Comment by clabornd** [comment]
Yea I had some null values, removing them seems to work.  Running into unrelated issues but pretty sure this part of my problems are resolved.  Thanks.

**Comment by maziyarpanahi** [comment]
Thanks for the updates. None the less we shouldn’t crash on empty strings so I’ll create a new issue for that to be fixed next release.
Thanks again for reporting this.
