### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder.read. : java.lang.NoClassDefFoundError: com/amazonaws/AmazonClientException

### ISSUE THREAD

**Issue by tooobsias** [JohnSnowLabs/spark-nlp#965]
Im getting this error message and don't really know why.
Cant explain why amazonaws is needed when loading offline model 

**Settings:** Spark 2.4.5, sparknlp 2.5.3, scala 2.11
**Submit via:** spark-submit --jars spark-nlp_2.11-2.5.3.jar,<ANOTHER_ONE>.jar main.py
**Code:**
```
spark = SparkSession.builder \
            .appName("Spark NLP") \
            .master("spark://dear-bengal.maas:7077") \
            .config(*config1) \
            .config(*config2) \
            .config("spark.kryoserializer.buffer.max", "1000M") \
            .getOrCreate()
```

```
def sentiment_pipeline() -> Pipeline:
    document = DocumentAssembler() \
        .setInputCol("text") \
        .setOutputCol("document")

    use = UniversalSentenceEncoder.load("/home/ubuntu/pretrained_models/tfhub_use_en_2.4.0_2.4_1587136330099") \
        .setInputCols(["document"]) \
        .setOutputCol("sentence_embeddings")

    sentimentdl = SentimentDLModel.load("/home/ubuntu/pretrained_models/tmp_sentimentdl_model") \
        .setInputCols(["sentence_embeddings"]) \
        .setOutputCol("class")

    pipeline = Pipeline(
        stages=[
            document,
            use,
            sentimentdl
        ])

    return pipeline
```
**Error:**
Traceback (most recent call last):
  File "/home/ubuntu/forschungsmodul_db_gruppe6/project/main.py", line 213, in <module>
    run()
  File "/home/ubuntu/forschungsmodul_db_gruppe6/project/main.py", line 207, in run
    main(True, DataSet.small_loc, "Test")
  File "/home/ubuntu/forschungsmodul_db_gruppe6/project/main.py", line 190, in main
    pipeline = sentiment_pipeline()
  File "/home/ubuntu/forschungsmodul_db_gruppe6/project/main.py", line 78, in sentiment_pipeline
    use = UniversalSentenceEncoder.load("/home/ubuntu/pretrained_models/tfhub_use_en_2.4.0_2.4_1587136330099") \
  File "/opt/spark-2.4.5-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/ml/util.py", line 362, in load
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sparknlp/internal.py", line 51, in read
    return AnnotatorJavaMLReader(cls())
  File "/opt/spark-2.4.5-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/ml/util.py", line 294, in __init__
  File "/opt/spark-2.4.5-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark-2.4.5-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/opt/spark-2.4.5-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder.read.
: java.lang.NoClassDefFoundError: com/amazonaws/AmazonClientException
        at com.johnsnowlabs.nlp.HasPretrained$class.$init$(HasPretrained.scala:16)
        at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder$.<init>(UniversalSentenceEncoder.scala:193)
        at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder$.<clinit>(UniversalSentenceEncoder.scala)
        at com.johnsnowlabs.nlp.embeddings.UniversalSentenceEncoder.read(UniversalSentenceEncoder.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.AmazonClientException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 15 more

**Comment by maziyarpanahi** [comment]
Hi,

How did you make this `spark-nlp_2.11-2.5.3.jar` JAR?

**Comment by tooobsias** [comment]
I have downloaded it from Maeven

More info:
The same code works when executed on the same virtual env via jupyter notebook 
This error gets just thrown when submitting directly via spark-submit

And thanks for your fast reply !

**Comment by maziyarpanahi** [comment]
The JARs on Maven are not Fat JARs, they don't have all the dependencies even if they are not being used like in your case AWS which you don't need now but needs to be loaded. 

I normally put the links to Fat JARs in the release notes but for 2.5.3 I will tomorrow. For now, you have to choices, either use the Fat JAR for 2.5.2: 

https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/spark-nlp-assembly-2.5.2.jar

Or you can clone the repo and make the Fat JAR yourself from the `master` which is the latest release:
https://github.com/JohnSnowLabs/spark-nlp#compiled-jars

You need to load that JAR instead in `spark.jars` in SparkSession and `--jars` in spark-submit which is around 220-230MB compare to the one on Maven which is around 22-26MB.

**Comment by tooobsias** [comment]
> The JARs on Maven are not Fat JARs, they don't have all the dependencies even if they are not being used like in your case AWS which you don't need now but needs to be loaded.

Well that was it ! 
Got the Fat Jar and its working as it should.
Thank you very much !

**Comment by maziyarpanahi** [comment]
Fantastic! Thanks for the update and the JARs are available now just in case: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.5.3

**Comment by elmondhir** [comment]
Hi @maziyarpanahi, please help i am encountering an issue with serving the spark-nlp to my worker nodes. i am running spark using standalone mode to 3 workers.

I am using the command spark-submit --master spark://127.0.0.1:7077 --driver-memory 8g --executor-memory 2g --jars spark-nlp-assembly-5.1.1.jar main.py

but i get the error:
ModuleNotFoundError: No module named 'sparknlp'

I think it means they are not installed inside spark and inside the worker. i have done nothing so far except download the jar and then add it as --jars argument, do i have to install anything ??

Thanks in advance

**Comment by maziyarpanahi** [comment]
Hi,

As you have guessed correctly, besides the JAR (or the Maven package), you also need the PyPi package installed on all the machines (same exact Python env being used by your PySpark/Spark):

this on all the executors including the Driver:

pip install spark-nlp==5.1.1


If you still encounter issues you can open a new bug report and provide more details so we can debug and help you.
