### ISSUE TITLE
Unable to download pre-trained WordEmbeddingsModel

### ISSUE THREAD

**Issue by asuag** [JohnSnowLabs/spark-nlp#966]
## Description
Experimenting with a WordEmbeddingsModel/BERT pre-trained model, spark-shell hangs at downloading pre-trained model with error. 
Here's my code I am trying in 2.4.5 Spark, 2.11 Scala on spark-shell loaded with fat JAR of spark-nlp 2.5.2
`./bin/spark-shell --jars spark-nlp-assembly-2.5.2.jar `

The code is simple and works fine until WordEmbeddingsModel

```import com.johnsnowlabs.nlp._
import com.johnsnowlabs.nlp.annotators._
import org.apache.spark.ml.Pipeline

val documentAssembler = new DocumentAssembler().setInputCol("title").setOutputCol("document").setCleanupMode("shrink_full")

val tokenizer = new Tokenizer().setInputCols("document").setOutputCol("token").setContextChars(Array("(", ")", "?", "!")).setSplitChars(Array("-"))

val normalizer = new Normalizer().setInputCols(Array("token")).setOutputCol("normalized")

val stopWordsCleaner = new StopWordsCleaner().setInputCols("normalized").setOutputCol("cleanTokens").setCaseSensitive(false)

val stemmer = new Stemmer().setInputCols("cleanTokens").setOutputCol("stem")

import com.johnsnowlabs.nlp.embeddings._
val word_embeddings =  WordEmbeddingsModel.pretrained("glove_100d", "en").setInputCols(Array("document", "stem")).setOutputCol("embeddings")
```

Fails and hangs with: 
```
glove_100d download started this may take some time.
Approximate size to download 145.3 MB
java.lang.NoSuchMethodError: com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(Ljava/lang/String;Ljava/lang/String;)Z
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$download$1.apply(S3ResourceDownloader.scala:99)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader$$anonfun$download$1.apply(S3ResourceDownloader.scala:95)
	at scala.Option.flatMap(Option.scala:171)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.download(S3ResourceDownloader.scala:94)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$$anonfun$9.apply(ResourceDownloader.scala:310)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$$anonfun$9.apply(ResourceDownloader.scala:309)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```
## Expected Behavior
Should be able to download the pre-trained model.

## Current Behavior
Fails and hangs with error.

## Steps to Reproduce
Code to reproduce
`val word_embeddings =  WordEmbeddingsModel.pretrained("glove_100d", "en").setInputCols(Array("document", "stem")).setOutputCol("embeddings")`

## Context
Trying to implement semantic similarity for work.
## Your Environment
* Spark NLP version: 2.5.2 (Tried 2.5.3, 2.5.0, 2.4.0 with same issue)
* Spark Version: 2.4.5
* Scala Version: 2.11.12
* Java version (java -version): Java 1.8.0_60
* Setup and installation (Pypi, Conda, Maven, etc.): Using fat JAR with spark-shell

**Comment by asuag** [comment]
I have also tried `BertEmbeddings` which also fails with the same error. Code for it :
```val word_embeddings =  BertEmbeddings.pretrained("bert_base_uncased","en").setInputCols(Array("document", "stem")).setOutputCol("embeddings").setPoolingLayer(0)```

Also tried to download the BertModel and put it on HDFS but it gives a different error.
```val word_embeddings =  BertEmbeddings.load("/home/datascience/tmp/bert").setInputCols(Array("document", "stem")).setOutputCol("embeddings").setPoolingLayer(0)```

Error:
```20/07/12 00:45:25 ERROR lzo.GPLNativeCodeLoader: Could not load native gpl library
java.lang.UnsatisfiedLinkError: no gplcompression in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.hadoop.compression.lzo.GPLNativeCodeLoader.<clinit>(GPLNativeCodeLoader.java:32)
	at com.hadoop.compression.lzo.LzoCodec.<clinit>(LzoCodec.java:71)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:132)
	at org.apache.hadoop.io.compress.CompressionCodecFactory.<init>(CompressionCodecFactory.java:180)
	at org.apache.hadoop.mapred.TextInputFormat.configure(TextInputFormat.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)
	at org.apache.spark.rdd.HadoopRDD.getInputFormat(HadoopRDD.scala:190)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1388)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1382)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1423)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1422)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadMetadata(ReadWrite.scala:615)
	at org.apache.spark.ml.util.DefaultParamsReader.load(ReadWrite.scala:493)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:12)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:380)
	at com.johnsnowlabs.nlp.embeddings.BertEmbeddings$.load(BertEmbeddings.scala:333)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:39)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:44)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:46)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:48)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:50)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:52)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:54)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:56)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:58)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:60)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:62)
	at $line30.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:64)
	at $line30.$read$$iw$$iw$$iw$$iw.<init>(<console>:66)
	at $line30.$read$$iw$$iw$$iw.<init>(<console>:68)
	at $line30.$read$$iw$$iw.<init>(<console>:70)
	at $line30.$read$$iw.<init>(<console>:72)
	at $line30.$read.<init>(<console>:74)
	at $line30.$read$.<init>(<console>:78)
	at $line30.$read$.<clinit>(<console>)
	at $line30.$eval$.$print$lzycompute(<console>:7)
	at $line30.$eval$.$print(<console>:6)
	at $line30.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
	at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply$mcZ$sp(SparkILoop.scala:285)
	at org.apache.spark.repl.SparkILoop.runClosure(SparkILoop.scala:159)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:182)
	at org.apache.spark.repl.Main$.doMain(Main.scala:78)
	at org.apache.spark.repl.Main$.main(Main.scala:58)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/07/12 00:45:25 ERROR lzo.LzoCodec: Cannot load native-lzo without native-hadoop
```

I guess, I will first focus on fixing why I am unable to download it. Thanks for your help.

**Comment by maziyarpanahi** [comment]
Thanks @asuag 

@rohit-nlp Could this be related to network connectivity, proxy, or firewall?

**Comment by kmillanrfractal** [comment]
Trying something similar in 2.4.5 Spark, 2.11 Scala on spark-shell loaded with fat JAR of spark-nlp 2.5.3 getting same error

**Comment by rohit-nlp** [comment]
This issue is due to the messy conflict in hadoop-aws and aws-java sdk incompatibilities.. Can you check which versions of jar you have. It should work for "org.apache.hadoop" % "hadoop-aws" %  "3.2.0" and  "com.amazonaws" % "aws-java-sdk-core" % "1.11.603" and "com.amazonaws" % "aws-java-sdk-s3" % "1.11.603".

com.amazonaws.services.s3.AmazonS3Client.doesObjectExist is a function which was removed at some point from Hadoop aws and is used to check and download the pretrained models from s3.

**Comment by asuag** [comment]
@maziyarpanahi It's a yarn cluster.

@rohit-nlp Yeah, I was able to identify this issue and yes it relates to what you mentioned. I switched to using a HDFS hosted pre-trained model and I am good for now. Harder for me to switch those dependencies due to complicated nature of project. 

Thanks for the help guys
