### ISSUE TITLE
Out of Memory error, for using pretrained model explain_document_ml over more than 5000 records

### ISSUE THREAD

**Issue by sahilsingh1123** [JohnSnowLabs/spark-nlp#977]
i was trying to use one of the explain_document_ml pretrained model for text analytics, it was working fine on smaller dataset but when i tried using it on large dataset, out of memory error started throwing.

`java.lang.OutOfMemoryError: GC overhead limit exceeded
    at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:554)
    at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:543)
    at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:543)
    at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:543)
    at scala.collection.immutable.HashSet.$plus(HashSet.scala:84)
    at scala.collection.immutable.HashSet.$plus(HashSet.scala:35)
    at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:22)
    at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:20)
    at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
    at scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1.apply(Growable.scala:59)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
    at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
    at scala.collection.generic.GenericCompanion.apply(GenericCompanion.scala:49)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel.allWords$lzycompute(NorvigSweetingModel.scala:32)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel.allWords(NorvigSweetingModel.scala:31)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel.getSuggestion(NorvigSweetingModel.scala:93)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel.getBestSpellingSuggestion(NorvigSweetingModel.scala:74)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel.checkSpellWord(NorvigSweetingModel.scala:58)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel$$anonfun$annotate$1.apply(NorvigSweetingModel.scala:44)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel$$anonfun$annotate$1.apply(NorvigSweetingModel.scala:43)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel.annotate(NorvigSweetingModel.scala:43)
    at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
    at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)`

**Comment by maziyarpanahi** [comment]
Hi,

Could you please provide the information required in the issue's template?
In addition, how long is each text? (It maybe 5000 but each record can be the entire page of Wikipedia). Also, how did you start the SparkSession and what are the config especially the memory for Driver/executors.

**Comment by sahilsingh1123** [comment]
sparknlp version - 2.4.3
spark version - 2.4.5
java - 8
python - 3.6

every row/record has around 100- 200 words.

about spark configuration.
```
import pyspark
from pyspark.sql import SparkSession


config = pyspark.SparkConf().setAll([('spark.executor.memory', '2g'), ('spark.executor.cores', '5'), ('spark.cores.max', '5'),
                                     ('spark.driver.memory','2g'), ('spark.memory.storageFraction','0.35')])

spark = \
    SparkSession.builder.appName('DMXPredictiveAnalytics')\
        .config("spark.jars", "/home/fidel/cache_pretrained/sparknlpFATjar.jar")\
        .config(conf=config)\
        .master('local[*]').getOrCreate()
spark.sparkContext.setLogLevel('ERROR')
```

**Comment by maziyarpanahi** [comment]
2G is very low for both executor and the driver. Could you please increase them to 8G for start?

**Comment by sahilsingh1123** [comment]
yes i had already experimented with increasing the memory with 6G, 8G, but still got the same error.
and always the flow breaks at the row 5096.

**Comment by maziyarpanahi** [comment]
Interesting, if there is enough memory the. This shouldn't happen. How so you know at which row it crashes? Could you please share your full code from the beginning all the way to the end?

**Comment by sahilsingh1123** [comment]
i uses one of your explain_document_dl pretrained model for text processing.
below is the code snippet.
`documentPipeline = infoData.get(pc.DOCUMENTPRETRAINEDPIPELINE)
        dataset = dataset.withColumnRenamed(sentimentCol, "text")
        # explainDocument = PretrainedPipeline("explain_document_dl", "en") #only need to download it once.

        '''
        documentPipeline is the explain_document_dl pretrained pipeline model.
        '''
        loadedDocumentPipeline = PipelineModel.load(documentPipeline)
        dataset = loadedDocumentPipeline.transform(dataset)`

So once i get the transformed dataset, i tried to write it back to the hdfs.
there it throws error of OOM.
to confirm this, i tried to use the localIterator and loop the whole dataset
in that looping i found that it is looping till 5096 records and after that it throws OOM error.

**Comment by maziyarpanahi** [comment]
Thanks, one more question regarding your setup. Where do you run this code? I see you assigned memory to executors but manually creating a SparkSession with no info whether this is a Master/Slave or local or YARN cluster. 

I would like to know the setup to be sure the memory is actually being set right in the config an don't before. Also, the title says `explain_document_ml` but your example says `explain_document_dl` are they both having the same issue? Have you tried to just locally run the code on the same dataset in Python console by using `sparknlp.start()`?

**Comment by sahilsingh1123** [comment]
1st- I run this code locally.
2nd- i had tried to run both explain_document_dl and _ml to see if any one of them runs. but for both i've got the same issue.
And i didn't try running the code on console with sparknlp.start().

**Comment by maziyarpanahi** [comment]
Great thanks. By locally you mean in Jupyter or an IDE? 

- Could you please try that coed in your Python console in the same environment that has `pip install spark-nlp pyspark`? (if it's locally then you don't need executor, it's all on the driver and the memory on driver is the main memory being used.)
