### ISSUE TITLE
NerDLModel:  Could not initialize class org.tensorflow.Graph Error

### ISSUE THREAD

**Issue by SreeDeviKutty** [JohnSnowLabs/spark-nlp#982]
**Description**
I encountered an error when running the jupyter notebook.
Here are the scripts in my notebook cell:

ner = NerDLModel.pretrained().setInputCols(['sentence','checked']).setOutputCol('ner')

```
when running through the above line , it gives the **NoClassDefFoundError: Could not initialize class org.tensorflow.Graph**


---------------------------------------------------------------------------
ner_dl download started this may take some time.
Approximate size to download 13.6 MB
[OK!]
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-14-29351ff529fc> in <module>
----> 1 ner = NerDLModel.pretrained().setInputCols(['sentence','checked']).setOutputCol('ner')

~\anaconda3\lib\site-packages\sparknlp\annotator.py in pretrained(name, lang, remote_loc)
   1501     def pretrained(name="ner_dl", lang="en", remote_loc=None):
   1502         from sparknlp.pretrained import ResourceDownloader
-> 1503         return ResourceDownloader.downloadModel(NerDLModel, name, lang, remote_loc)
   1504 
   1505 

~\anaconda3\lib\site-packages\sparknlp\pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     39             t1.start()
     40             try:
---> 41                 j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     42             finally:
     43                 stop_threads = True

~\anaconda3\lib\site-packages\sparknlp\internal.py in __init__(self, reader, name, language, remote_loc, validator)
    174 class _DownloadModel(ExtendedJavaWrapper):
    175     def __init__(self, reader, name, language, remote_loc, validator):
--> 176         super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
    177 
    178 

~\anaconda3\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

~\anaconda3\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.Graph
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(TensorflowWrapper.scala:207)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:252)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:97)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowModel(NerDLModel.scala:227)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$class.readNerGraph(NerDLModel.scala:207)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readNerGraph(NerDLModel.scala:227)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:211)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:211)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:360)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadModel(ResourceDownloader.scala:354)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadModel(ResourceDownloader.scala:465)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)
```

Spark-NLP version: 2.5.3
Apache Spark version: 2.4.6
Operating System and version: Windows 10
Python: 3.6

**Comment by maziyarpanahi** [comment]
Could you please also provide how you installed the spark-nlp package, is the kernel in Jupyter Python3, and lastly how are you starting your SparkSession?

**Comment by SreeDeviKutty** [comment]
I have installed the spark-nlp package using the command:
conda install -c johnsnowlabs spark-nlp
 and loaded  Spark NLP with PySpark using the command:
pyspark --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.4

Kernel : jupyter python 3

I have started SparkSession using the following command
import sparknlp
spark = sparknlp.start()

**Comment by maziyarpanahi** [comment]
Thanks, just for the test, could you please download this model, extract it, and load it offline:

ner_dl = https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/ner_dl_en_2.4.3_2.4_1584624950746.zip

```python
ner = NerDLModel.load("./tmp/ner_dl_en_2.4.3_2.4_1584624950746/").setInputCols(['sentence','checked']).setOutputCol('ner')
```

**Comment by SreeDeviKutty** [comment]
ok I will download and try with that

**Comment by SreeDeviKutty** [comment]
I have downloaded the model and loaded through offline  but same error occurred 

Py4JJavaError                             Traceback (most recent call last)
<ipython-input-21-53cdaa603d10> in <module>
----> 1 ner = NerDLModel.load("./tmp/ner_dl_en_2.4.3_2.4_1584624950746/").setInputCols(['sentence','checked']).setOutputCol('ner')

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\ml\util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\ml\util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o435.load.
: java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.Graph
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(TensorflowWrapper.scala:207)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(TensorflowWrapper.scala:252)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:97)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowModel(NerDLModel.scala:227)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$class.readNerGraph(NerDLModel.scala:207)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readNerGraph(NerDLModel.scala:227)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:211)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:211)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)

**Comment by maziyarpanahi** [comment]
The ./tmp/ was an example, if you are on Windows you cannot access path like linux. Is this a linux environment that actually has access to ./tmp/?
Also, could you please do java --version to see your Java version?

**Comment by SreeDeviKutty** [comment]
Java Version : 1.8.0_261
OS : Windows

At first I have tried the following command:
ner = NerDLModel.load("G:/Work/ner_dl_en_2.4.3_2.4_1584624950746/").setInputCols(['sentence','checked']).setOutputCol('ner')

then I got the following error:

Py4JJavaError                             Traceback (most recent call last)
<ipython-input-15-4287eb381809> in <module>
----> 1 ner = NerDLModel.load("G:/Work/ner_dl_en_2.4.3_2.4_1584624950746/").setInputCols(['sentence','checked']).setOutputCol('ner')

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\ml\util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\ml\util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

G:\Work\spark\spark-2.4.6-bin-hadoop2.7\python\lib\py4j-0.10.7-src.zip\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o138.load.
: java.io.IOException: No FileSystem for scheme: G
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at com.johnsnowlabs.nlp.serialization.StructFeature.deserializeObject(Feature.scala:116)
	at com.johnsnowlabs.nlp.serialization.Feature.deserialize(Feature.scala:46)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:15)
	at com.johnsnowlabs.nlp.FeaturesReader$$anonfun$load$1.apply(ParamsAndFeaturesReadable.scala:14)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:14)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)



After that I have created a tmp folder inside C:/Users/Usernam/tmp
and placed nermodel there 
then I got the error:  java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.Graph

**Comment by maziyarpanahi** [comment]
OK so this has something to do with your OS. May I know the exact details of your Windows 10 so we can reproduce it ourselves?

**Comment by SreeDeviKutty** [comment]
Windows 8.1 Pro

**Comment by maziyarpanahi** [comment]
So it's not Windows 10 as initially mentioned? No worries, I'll find a Windows 8 and try it. (you just normally installed Anaconda and use the default CMD for the rest?)

**Comment by maziyarpanahi** [comment]
Last very important question, have you installed any `tensorflow` in the same Python/Conda environment that you have installed `spark-nlp` and `pyspark` and run Juypter? (you can check with pip freeze or conda list)

**Comment by SreeDeviKutty** [comment]
Really sorry I got a mistake in the above comment...
I am using Windows 8.1 pro
First I have installed Spark on Windows with PySpark using pre built version for Apache Hadoop 2.7
After that i dropped the plan and installed pysaprk through conda
and also installed sparknlp through conda

pipeline = PretrainedPipeline('recognize_entities_dl_noncontrib', lang='en')
while running this command I got tenserflow graph error so that I have downloaded a jar file 'libtensorflow_jni-1.15.0' and placed it in the path 'C:\Users\username\.ivy2\jars\'
I didn't install tensorflow using conda
I have listed the conda packages - no tenserflow package found

**Comment by maziyarpanahi** [comment]
Thanks, Spark NLP doesn't need TensorFlow being installed via pip/conda or its Jar. They all come together so you can remove whatever you added already regarding that JAR.

The error is related to TensorFlow that sometimes on some OSes it cannot find some files it needs in the /tmp do to versioning.

I am going to test on Windows 8.1 and come back to you.

**Comment by SreeDeviKutty** [comment]
@maziyarpanahi Thank You

**Comment by maziyarpanahi** [comment]
Hi @SreeDeviKutty 

I can see that the first error is about `: java.io.IOException: No FileSystem for scheme: G` which says there is no fileSystem path with `G:\` which is correct. The second error regarding `org.tensorflow.Graph`, could you please provide the full error stack for this error as well?

**Comment by maziyarpanahi** [comment]
Hi @SreeDeviKutty 

I have tested this on a fresh Windows 8 Pro and I cannot reproduce this issue. It seems you might not have some of the requirements for Apache Spark/Hadoop or they are not correctly setup.

![image](https://user-images.githubusercontent.com/5762953/89555294-27fa1a80-d810-11ea-8b62-b75441a1a414.png)

The most important parts are:

- JAVA_HOME 
- SPARK_HOME
- HADOOP_HOME pointing to C:\hadoop 
- %HADOOP_HOME%\bin and %SPARK_HOME%\bin in your PATH
- Having the right `winutils` in C:\hadoop\bin directory
- Install Microsoft Visual C++ 2010 Redistributed Package (x64)
- Anaconda3 with Python 3.6 env for Apache Spark and Spark NLP

For Jupyter, you just need to run `jupyter notebook` in the same conda environment you have with spark-nlp and pyspark==2.4.4 and open a Python3 kernel. (I saw somewhere you mentioned `pyspark --packages ...` you don't need that if you are in Jupyter and are suing sparknlp.start())

`explain_document_dl` has NerDLModel inside as well:

![image](https://user-images.githubusercontent.com/5762953/89556748-23366600-d812-11ea-98ef-bfc6173acdbf.png)

**Comment by maziyarpanahi** [comment]
Since it works as expected in Windows 8, please feel free to reopen this issue if the problem exists after following those steps.

**Comment by TiGaI** [comment]
Hey Maziyarpanahi,

I am not sure about window 8 PRO, but I follow your step one by one in window 10.
![image](https://user-images.githubusercontent.com/22779825/90053405-7132ea00-dca8-11ea-86bb-148a1ea717d7.png)
![image](https://user-images.githubusercontent.com/22779825/90053558-accdb400-dca8-11ea-9ed9-e6ff390b5a5a.png)
![image](https://user-images.githubusercontent.com/22779825/90053595-b9eaa300-dca8-11ea-810d-b6a34ef98ba2.png)
![image](https://user-images.githubusercontent.com/22779825/90053629-c3740b00-dca8-11ea-9f32-7a2595c19566.png)
![image](https://user-images.githubusercontent.com/22779825/90053754-eacad800-dca8-11ea-866b-6d54c62a923a.png)
![image](https://user-images.githubusercontent.com/22779825/90053883-15b52c00-dca9-11ea-9fc9-48b9fb4af913.png)


But when I load this it gives me the same exact error. Now it is saying a little more.
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.UnsupportedOperationException: Spark NLP tried to load a TensorFlow Graph using Contrib module, but failed to load it on this system. If you are on Windows, this operation is not supported. Please try a noncontrib model. If not the case, please report this issue. Original error message:

![image](https://user-images.githubusercontent.com/22779825/90053330-506a9480-dca8-11ea-9a00-cde09bf2ee52.png)

![image](https://user-images.githubusercontent.com/22779825/90053286-4052b500-dca8-11ea-9835-8906eca91e09.png)
